name: 'Setup Environment'
description: 'Setup the server environment for ForumMagnum'
inputs:
  node-version:
    description: 'Which version of NodeJS to use'
    required: false
    default: 22.12
runs:
  using: composite
  steps:
    - name: Install Vercel CLI
      shell: bash
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
