import { defineStyles } from "@/components/hooks/useStyles";

export const profileStyles = defineStyles("ProfilePage", (theme: ThemeType) => ({
  page: {
    width: "100%",
    minHeight: "100vh",
    // Cancel the centralColumn padding-top so the profile page sits flush
    marginTop: -theme.spacing.mainLayoutPaddingTop,
    background: "transparent",
    color: theme.palette.text.normal,
    fontFamily: theme.typography.fontFamily,
    position: "relative" as const,
    overflow: "hidden",
    boxSizing: "border-box" as const,
    "& *": {
      boxSizing: "border-box" as const,
    },
    [theme.breakpoints.down("md")]: {
      marginTop: theme.isFriendlyUI ? 0 : -theme.spacing.mainLayoutPaddingTop,
    },
    [theme.breakpoints.down("sm")]: {
      marginTop: theme.isFriendlyUI ? 0 : -10,
    },
  },
  profileContent: {
    display: "block",
    minHeight: "calc(100vh - 60px)",
  },
  profileMain: {
    width: "100%",
    maxWidth: 1100,
    margin: "0 auto",
    padding: "53px 80px 60px 80px",
    color: theme.palette.text.normal,
    background: "transparent",
    "@media (max-width: 900px)": {
      padding: "40px 30px 50px 30px",
    },
    "@media (max-width: 750px)": {
      padding: "35px 25px 45px 25px",
    },
    "@media (max-width: 630px)": {
      padding: "30px 20px 40px 20px",
    },
  },
  profileHeader: {
    marginBottom: 15,
    paddingBottom: 10,
    // Intentional custom warm divider for profile page tone
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
  },
  profileName: {
    gridColumn: 2,
    textAlign: "center",
    fontFamily: theme.typography.headerStyle.fontFamily,
    fontSize: "2.3rem",
    fontWeight: 400,
    margin: "0 0 2px 0",
    color: theme.palette.text.normal,
    lineHeight: 1.1,
    letterSpacing: "-.02em",
  },
  profileNameLink: {
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit" as const,
    letterSpacing: "inherit",
    textDecoration: "none",
    "&:hover": {
      textDecoration: "none",
      color: "inherit",
    },
  },
  profileHeaderActions: {
    gridColumn: 3,
    justifySelf: "end",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    position: "relative",
    top: 2,
  },
  profileActionIconLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "light-dark(#000, #fff)",
    textDecoration: "none",
    cursor: "pointer",
    "&:hover": {
      opacity: 0.67,
    },
    "&:focus-visible": {
      outline: `1px solid light-dark(#000, #fff)`,
      outlineOffset: 2,
      borderRadius: 2,
    },
  },
  profileActionIconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    border: "none",
    background: "none",
    color: "light-dark(#000, #fff)",
    cursor: "pointer",
    "&:hover": {
      opacity: 0.67,
    },
    "&:focus-visible": {
      outline: `1px solid light-dark(#000, #fff)`,
      outlineOffset: 2,
      borderRadius: 2,
    },
  },
  profileActionIcon: {
    fontSize: 16,
  },
  sunshineToolsSection: {
    marginTop: 8,
    marginBottom: 24,
  },
  mobileProfileBio: {
    display: "none",
    margin: "0 0 30px",
    padding: "30px 0 30px",
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
    "@media (max-width: 630px)": {
      display: "block",
    },
  },
  mobileProfileName: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  mobileProfileHeaderRow: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  mobileProfileActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: 0,
  },
  mobileMetaInfo: {
    marginTop: 12,
    color: theme.palette.text.dim,
    "& > div": {
      flexWrap: "wrap",
      gap: "4px 0",
    },
    "& > div > div": {
      marginRight: "14px !important",
    },
  },
  topPostsIndicator: {
    marginTop: 25,
    marginBottom: 15,
    marginLeft: 0,
    paddingLeft: 0,
  },
  topPostsLabel: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    display: "block",
    margin: 0,
    padding: 0,
  },
  topPostsLabelPlural: {
    display: "block",
    "@media (max-width: 630px)": {
      display: "none",
    },
  },
  topPostsLabelSingular: {
    display: "none",
    "@media (max-width: 630px)": {
      display: "block",
    },
  },
  emptyStateContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "16px 0 32px",
    textAlign: "left",
    width: "100%",
  },
  emptyStateImage: {
    marginTop: 8,
    width: "100%",
    maxWidth: 380,
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "auto",
      opacity: 0.85,
      display: "block",
      filter: "none",
      mixBlendMode: theme.dark ? "normal" : "multiply",
    },
  },
  emptyStateDescription: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 15,
    fontWeight: 400,
    color: theme.palette.text.dim,
    lineHeight: 1.5,
    margin: 0,
    fontStyle: "italic",
  },
  postArticle: {
    marginTop: 0,
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 25,
    paddingBottom: 30,
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
    overflow: "visible",
    textDecoration: "none",
    color: "inherit",
    // Override global a:hover { opacity: 0.5 } so we can apply it to children
    // individually, preserving mix-blend-mode: multiply on the image
    "&:hover": {
      opacity: 1,
    },
    "@media (max-width: 750px)": {
      display: "flex",
      flexDirection: "column-reverse",
      gap: 16,
    },
  },
  postArticleTop: {
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",

    "&:hover $postTitle": {
      textDecoration: "underline",
      textDecorationColor: theme.palette.greyAlpha(0.2),
      textDecorationThickness: 1,
    }
  },
  postContent: {
    gridColumn: "1 / 4",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
    paddingLeft: 0,
    marginLeft: 0,
    aspectRatio: "3 / 2",
    transition: "opacity 0.15s ease",
    "@media (max-width: 750px)": {
      height: "auto",
      maxHeight: "none",
      width: "100%",
      aspectRatio: "auto",
    },
  },
  postImage: {
    gridColumn: "4 / 7",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "light-dark(rgba(255,255,255,.87),rgba(0,0,0,.92))",
    fontSize: 14,
    aspectRatio: "3 / 2",
    transition: "opacity 0.15s ease",
    mixBlendMode: theme.dark ? "normal" : "multiply",
    "@media (max-width: 750px)": {
      width: "100%",
      height: 220,
      aspectRatio: "auto",
    },
    "@media (max-width: 630px)": {
      height: 200,
    },
  },
  postTitle: {
    fontFamily: theme.typography.headerStyle.fontFamily,
    fontSize: "2rem",
    fontWeight: 400,
    margin: "0 0 18px 0",
    color: theme.palette.text.normal,
    lineHeight: 1.2,
    letterSpacing: "-.02em",
    wordWrap: "break-word",
    overflowWrap: "break-word",
    whiteSpace: "normal",
    maxWidth: "100%",
    paddingLeft: 0,
    flexShrink: 0,
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 4,
    overflow: "hidden",
    "@media (max-width: 900px)": {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
    "@media (max-width: 630px)": {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
  },
  topPostTitle: {
    fontSize: 44,
    lineHeight: 1.1,
  },
  postSummaryWrapper: {
    flex: "1 1 0",
    minHeight: 0,
    marginBottom: 10,
    // Keep line metrics on wrapper so 1lh resolves from this block.
    fontFamily: theme.typography.postStyle.fontFamily,
    fontSize: 15,
    lineHeight: 1.6,
    color: theme.palette.text.slightlyDim2,
    "@media (max-width: 750px)": {
      flex: "none",
      minHeight: "auto",
      marginBottom: 16,
    },
  },
  postSummary: {
    fontFamily: theme.typography.postStyle.fontFamily,
    fontSize: 16.8,
    fontWeight: 400,
    lineHeight: 1.6,
    color: theme.palette.text.slightlyDim2,
    margin: 0,
    whiteSpace: "pre-line",
    maxHeight: "round(down, 100%, 1lh)",
    overflow: "hidden",
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "6em",
      height: "1lh",
      backgroundColor: theme.palette.background.profilePageBackground,
      WebkitMaskImage: theme.palette.type === "dark"
        ? "linear-gradient(to right, transparent, white)"
        : "linear-gradient(to right, transparent, black)",
      maskImage: theme.palette.type === "dark"
        ? "linear-gradient(to right, transparent, white)"
        : "linear-gradient(to right, transparent, black)",
      pointerEvents: "none",
    },
    "@media (max-width: 900px)": {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "pre-line",
    },
    "@media (max-width: 750px)": {
      maxHeight: "none",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 4,
      lineClamp: 4,
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    "@media (max-width: 630px)": {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "pre-line",
    },
  },
  postMetaBar: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    fontSize: 13,
    color: theme.palette.text.dim,
    flexShrink: 0,
  },
  karmaScore: {
    fontSize: 13,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  postDate: {
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    letterSpacing: 0,
  },
  smallArticlesGrid: {
    marginTop: 30,
    paddingBottom: 30,
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 25,
    "@media (max-width: 630px)": {
      display: "none",
    },
  },
  smallArticle: {
    gridColumn: "span 2",
    display: "flex",
    flexDirection: "column",
    "&:hover $smallArticleTitle": {
      textDecoration: "underline",
      textDecorationColor: theme.palette.greyAlpha(0.2),
      textDecorationThickness: 1,
    },
  },
  smallArticleImage: {
    width: "100%",
    aspectRatio: "3 / 2",
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.type === "dark" ? "rgba(0,0,0,.92)" : "rgba(255,255,255,.87)",
    fontSize: 12,
    borderRadius: 4,
    overflow: "hidden",
    transition: "opacity 0.15s ease",
    mixBlendMode: theme.dark ? "normal" : "multiply",
  },
  smallArticleContent: {
    padding: "15px 0 0 0",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    transition: "opacity 0.15s ease",
  },
  smallArticleTitle: {
    fontFamily: theme.typography.headerStyle.fontFamily,
    fontSize: 16,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.3,
    minHeight: 42, // Corresponds to approx two lines; ensures consistent height before title text loads
    letterSpacing: "-.02em",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    lineClamp: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    "@media (max-width: 630px)": {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
  },
  smallArticleMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
  },
  smallKarma: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  smallDate: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    letterSpacing: 0,
  },
  listArticle: {
    padding: "14px 0 15px",
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
    display: "block",
    transition: "opacity 0.15s ease",
    animation: "$slideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "visible",
    "&:hover": {
      opacity: 1,
    },
    "&:hover $listArticleTitleText": {
      opacity: 0.65,
    },
    "&:hover $listArticleSummary": {
      opacity: 0.65,
    },
    "&:hover $listArticleImage": {
      opacity: 0.65,
    },
    "&:last-of-type": {
      borderBottom: "none",
    },
    "@media (max-width: 630px)": {
      padding: "12px 0",
    },
  },
  listArticleContent: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "visible",
    "@media (max-width: 630px)": {
      gap: 7,
    },
  },
  listArticleBody: {
    display: "flex",
    alignItems: "stretch",
    gap: 14,
    minWidth: 0,
    "@media (max-width: 750px)": {
      gap: 10,
    },
  },
  listArticleBodyNoImage: {
    display: "block",
  },
  listArticleText: {
    minWidth: 0,
    flex: 1,
    minHeight: 120,
    height: 120,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    overflow: "hidden",
    "@media (max-width: 750px)": {
      minHeight: 0,
      height: "auto",
      gap: 7,
      overflow: "visible",
    },
  },
  listArticleTextNoImage: {
    minHeight: 0,
    height: "auto",
    gap: 7,
    overflow: "visible",
  },
  listArticleTitle: {
    fontFamily: theme.typography.headerStyle.fontFamily,
    fontSize: 20,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.2,
    letterSpacing: "-.015em",
    whiteSpace: "normal",
    "@media (max-width: 630px)": {
      fontSize: 18,
      lineHeight: 1.28,
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
      overflow: "visible",
      textOverflow: "clip",
    },
  },
  listArticleTitleText: {
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    lineClamp: 2,
    overflow: "hidden",
    minWidth: 0,
    position: "relative",
    zIndex: 1,
    transition: "opacity 0.15s ease",
  },
  listArticleSummaryWrapper: {
    flex: "1 1 0",
    minHeight: 0,
    marginTop: 1,
    // Keep line metrics on the wrapper so 1lh is resolved from this block.
    fontFamily: theme.typography.postStyle.fontFamily,
    fontSize: 14,
    lineHeight: 1.48,
    color: theme.palette.text.slightlyDim2,
    "@media (max-width: 750px)": {
      flex: "none",
      minHeight: "auto",
    },
  },
  listArticleSummaryWrapperNoImage: {
    flex: "none",
    minHeight: "auto",
  },
  listArticleSummary: {
    fontFamily: theme.typography.postStyle.fontFamily,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.48,
    color: theme.palette.text.slightlyDim2,
    margin: 0,
    whiteSpace: "pre-wrap",
    maxHeight: "round(down, 100%, 1lh)",
    overflow: "hidden",
    position: "relative",
    zIndex: 1,
    transition: "opacity 0.15s ease",
    "&::after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "5.2em",
      height: "1lh",
      backgroundColor: theme.palette.background.profilePageBackground,
      WebkitMaskImage: "linear-gradient(to right, transparent, light-dark(black, white))",
      maskImage: "linear-gradient(to right, transparent, light-dark(black, white))",
      pointerEvents: "none",
    },
    "@media (max-width: 750px)": {
      maxHeight: "none",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 2,
      lineClamp: 2,
      textOverflow: "ellipsis",
      "&::after": {
        display: "none",
      },
    },
  },
  listArticleSummaryNoImage: {
    maxHeight: "none",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 3,
    lineClamp: 3,
    textOverflow: "ellipsis",
    "&::after": {
      display: "none",
    },
  },
  listArticleMeta: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    marginTop: "auto",
    minHeight: 20,
  },
  listMetaDivider: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 12,
    color: theme.palette.text.dim,
    fontWeight: 500,
    lineHeight: 1,
  },
  listKarma: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 12,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: 0.2,
    lineHeight: 1.35,
    whiteSpace: "nowrap",
  },
  listDate: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 12,
    color: theme.palette.text.dim,
    fontWeight: 500,
    letterSpacing: 0.45,
    textTransform: "uppercase",
    lineHeight: 1.35,
    whiteSpace: "nowrap",
  },
  listArticleImage: {
    display: "block",
    width: 204,
    height: "auto",
    aspectRatio: "16 / 9",
    borderRadius: 7,
    flex: "0 0 204px",
    alignSelf: "stretch",
    backgroundColor: theme.palette.greyAlpha(0.07),
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "opacity 0.15s ease",
    mixBlendMode: theme.dark ? "normal" : "multiply",
    "@media (max-width: 750px)": {
      display: "none",
    },
  },
  allPostsSection: {
    marginTop: 30,
    display: "flex",
    gap: 25,
    "@media (max-width: 630px)": {
      flexDirection: "column",
    },
  },
  allPostsLeftColumn: {
    flex: "1 1 0%",
    minWidth: 0,
    minHeight: "100vh",
    "@media (max-width: 630px)": {
      flex: "1 1 auto",
    },
  },
  allPostsHeader: {
    marginBottom: 6,
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    "@media (max-width: 630px)": {
      display: "flex",
      flexDirection: "column",
      gap: 0,
    },
  },
  allPostsLeftHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    width: "100%",
    "@media (max-width: 630px)": {
      width: "100%",
      marginBottom: 16,
    },
  },
  profileTabs: {
    display: "flex",
    gap: 22,
    margin: 0,
  },
  profileTab: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 400,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: theme.palette.text.dim,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    transition: "color 0.2s",
    "&:hover": {
      color: theme.palette.text.normal,
    },
  },
  profileTabActive: {
    color: theme.palette.text.normal,
    fontWeight: 600,
  },
  sortControl: {
    display: "flex",
    alignItems: "start",
    gap: 8,
    fontFamily: theme.typography.fontFamily,
    fontSize: 14,
    color: theme.palette.text.dim60,
    position: "relative",
  },
  sortIconButton: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    display: "flex",
    alignItems: "start",
    lineHeight: 1,
    color: "inherit",
  },
  sortIconDisabled: {
    opacity: 0.35,
    cursor: "default",
  },
  sortIcon: {
    fontSize: 16,
    lineHeight: 1,
  },
  sortPanel: {
    background: theme.palette.greyAlpha(0.03),
    padding: "20px 24px",
    marginBottom: 20,
    borderRadius: 4,
    overflow: "hidden",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    animation: "$panelOpen 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sortPanelClosing: {
    animation: "$panelClose 0.3s cubic-bezier(0.4, 0, 1, 1)",
    animationFillMode: "forwards",
  },
  sortPanelMulti: {
    display: "flex",
    gap: 40,
  },
  sortPanelSection: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  sortPanelHeader: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 600,
    fontStyle: "italic",
    color: theme.palette.text.dim,
    marginBottom: 6,
  },
  sortPanelOption: {
    display: "block",
    width: "fit-content",
    padding: "4px 0 4px 16px",
    textAlign: "left",
    background: "none",
    border: "none",
    fontFamily: theme.typography.fontFamily,
    fontSize: 14,
    color: theme.palette.text.dim40,
    cursor: "pointer",
    transition: "color 0.15s ease",
    "&:hover": {
      color: theme.palette.text.normal,
    },
  },
  sortPanelOptionSelected: {
    color: theme.palette.text.normal,
  },
  allPostsContainer: {
    "@media (max-width: 630px)": {
      display: "flex",
      flexDirection: "column",
      gap: 30,
    },
  },
  postsList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingTop: 12,
    "@media (max-width: 630px)": {
      width: "100%",
    },
  },
  tabPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    animation: "$slideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    "@media (max-width: 630px)": {
      order: 1,
    },
  },
  articleLink: {
    textDecoration: "none",
    color: "inherit",
    display: "contents",
  },
  sequencesList: {
    paddingTop: 20,
  },
  feedList: {
    "& .UserContentFeed-feedContent": {
      marginLeft: 0,
      marginRight: 0,
    },
  },
  profileFeedTopMargin: {
    marginTop: 16,
  },
  sequencesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 20,
    padding: "8px 0",
    "@media (max-width: 630px)": {
      gridTemplateColumns: "1fr",
      gap: 24,
    },
  },
  sequenceCard: {
    display: "flex",
    flexDirection: "column",
    overflow: "visible",
    position: "relative",
    transition: "opacity 0.15s ease",
  },
  sequenceCardImage: {
    width: "100%",
    aspectRatio: "5 / 2",
    backgroundColor: "light-dark(#fcfbf8, #262626)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: 4,
  },
  sequenceCardContent: {
    padding: "10px 0",
    background: "transparent",
  },
  sequenceCardTitle: {
    fontFamily: theme.typography.headerStyle.fontFamily,
    fontSize: 15,
    fontWeight: 400,
    lineHeight: 1.3,
    letterSpacing: "0.03em",
    fontVariant: "small-caps",
    color: theme.palette.text.normal,
    margin: 0,
    borderTop: "none",
    borderRadius: "0 0 8px 8px",
  },
  sidebarAuthorBlock: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingBottom: 6,
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
  },
  sidebarAuthorName: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 12,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.1,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    "@media (max-width: 630px)": {
      display: "none",
    },
  },
  sidebarAuthorNameLink: {
    color: "inherit",
    textDecoration: "none",
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarAuthorMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "2px 10px",
    marginTop: 6,
    fontFamily: theme.typography.fontFamily,
    fontWeight: 400,
    color: theme.palette.text.dim,
    fontSize: 12,
    lineHeight: 1.4,
  },
  sidebarMetaAction: {
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.primary.main,
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 400,
    textDecoration: "none",
    "&:hover": {
      opacity: 0.67,
    },
  },
  postsSidebar: {
    flex: "0 0 300px",
    position: "sticky",
    top: 80,
    alignSelf: "start",
    "@media (max-width: 630px)": {
      display: "none",
    },
  },
  postsSidebarHasBio: {
    "& $sidebarStats": {
      display: "none",
    },
  },
  sidebarBioSection: {
    marginTop: 8,
  },
  sidebarMetaInfo: {
    color: theme.palette.text.dim,
    "& > div": {
      flexWrap: "wrap",
      gap: "4px 0",
    },
    "& > div > div": {
      marginRight: "14px !important",
    },
  },
  sidebarBioMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    fontFamily: theme.typography.fontFamily,
    fontSize: 12,
    color: theme.palette.text.dim,
    fontWeight: 400,
  },
  sidebarBioWrapper: {
    overflow: "hidden",
    transition: "max-height 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarBioCollapsed: {
    maxHeight: 400,
  },
  sidebarBioExpanded: {
    maxHeight: 2000,
    transition: "max-height 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarAuthorBio: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 14,
    lineHeight: 1.6,
    color: theme.palette.text.dim55,
    fontWeight: 400,
    margin: 0,
  },
  sidebarAuthorBioContent: {
    // Normalize typography across all rendered block types in bio HTML.
    "& p, & ul, & ol, & li, & blockquote, & pre, & h1, & h2, & h3, & h4, & h5, & h6, & table, & th, & td": {
      fontFamily: theme.typography.fontFamily,
      fontSize: 14,
      lineHeight: 1.6,
      color: theme.palette.text.dim55,
      fontWeight: 400,
    },
    "& p": {
      marginTop: 0,
      marginBottom: 12,
    },
    "& p:last-child": {
      marginBottom: 0,
    },
    "& ul, & ol": {
      marginTop: 0,
      marginBottom: 12,
      paddingLeft: 20,
    },
    "& li": {
      marginBottom: 4,
    },
    "& li:last-child": {
      marginBottom: 0,
    },
  },
  sidebarStats: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 14,
    lineHeight: 1.6,
    color: theme.palette.text.dim,
    fontWeight: 400,
    marginTop: 16,
  },
  sidebarStatRow: {
    whiteSpace: "nowrap",
  },
  diamondsSection: {
    marginTop: 28,
  },
  diamondsSectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 20,
    marginBottom: 8,
    paddingBottom: 6,
    borderBottom: theme.palette.type === "dark"
      ? theme.palette.greyBorder("1px", 0.28)
      : "1px solid rgba(140,110,70,.14)",
  },
  diamondsSectionTitle: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 13,
    fontWeight: 600,
    color: theme.palette.text.dim,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
  },
  diamondsSectionCount: {
    fontWeight: 400,
    letterSpacing: 0,
    textTransform: "none" as const,
  },
  diamondsGrid: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 2,
  },
  diamondLink: {
    display: "block",
    width: 10,
    height: 10,
    clipPath: "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)",
    textDecoration: "none",
    "&:hover": {
      opacity: 0.5,
    },
  },
  diamondSolid: {
    backgroundColor: theme.palette.primary.main,
  },
  diamondHollow: {
    backgroundColor: theme.palette.primary.main,
    position: "relative" as const,
    "&::after": {
      content: '""',
      position: "absolute",
      top: 1.5,
      left: 1.5,
      right: 1.5,
      bottom: 1.5,
      clipPath: "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)",
      backgroundColor: theme.palette.background.profilePageBackground,
    },
  },
  diamondGold: {
    backgroundColor: "light-dark(#b8860b, #daa520)",
    borderColor: "light-dark(#b8860b, #daa520)",
  },
  readMore: {
    textAlign: "left",
    marginTop: 12,
  },
  postsSidebarReadMore: {
    marginTop: 5,
  },
  readMoreLink: {
    fontFamily: theme.typography.fontFamily,
    fontSize: 14,
    color: theme.palette.primary.main,
    textDecoration: "none",
    fontWeight: 400,
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
    marginBottom: 22,
  },
  sidebarSubscribe: {
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.primary.main,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-block",
    fontWeight: 400,
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarMore: {
    fontFamily: theme.typography.fontFamily,
    color: theme.palette.primary.main,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-block",
    fontWeight: 400,
    textDecoration: "none",
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarActionDisabled: {
    color: theme.palette.primary.light,
    cursor: "default",
    "&:hover": {
      opacity: 1,
    },
  },
  sidebarActionHidden: {
    visibility: "hidden",
  },
  loadMoreLoading: {
    marginRight: 0,
  },
  "@keyframes slideIn": {
    from: {
      opacity: 0,
      transform: "translateY(10px)",
    },
    to: {
      opacity: 1,
      transform: "translateY(0)",
    },
  },
  "@keyframes panelOpen": {
    from: {
      opacity: 0,
      maxHeight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      marginBottom: 0,
    },
    to: {
      opacity: 1,
      maxHeight: 500,
      paddingTop: 20,
      paddingBottom: 20,
      marginBottom: 20,
    },
  },
  "@keyframes panelClose": {
    from: {
      opacity: 1,
      maxHeight: 500,
      paddingTop: 20,
      paddingBottom: 20,
      marginBottom: 20,
    },
    to: {
      opacity: 0,
      maxHeight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      marginBottom: 0,
    },
  },
}));
