import { defineStyles } from "@/components/hooks/useStyles";

export const profileStyles = defineStyles("ProfilePage", (theme: ThemeType) => ({
  page: {
    width: "100%",
    minHeight: "100vh",
    // Cancel the centralColumn padding-top so the profile page sits flush
    marginTop: -theme.spacing.mainLayoutPaddingTop,
    background: "transparent",
    color: theme.palette.text.normal,
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    position: "relative" as const,
    overflow: "hidden",
    boxSizing: "border-box" as const,
    "& *": {
      boxSizing: "border-box" as const,
    },
    [theme.breakpoints.down("md")]: {
      marginTop: theme.isFriendlyUI ? 0 : -theme.spacing.mainLayoutPaddingTop,
    },
    [theme.breakpoints.down("sm")]: {
      marginTop: theme.isFriendlyUI ? 0 : -10,
    },
  },
  profileContent: {
    display: "block",
    minHeight: "calc(100vh - 60px)",
  },
  profileMain: {
    width: "100%",
    maxWidth: 842,
    margin: "0 auto",
    padding: "53px 80px 60px 80px",
    color: theme.palette.text.normal,
    background: "transparent",
  },
  profileHeader: {
    marginBottom: 15,
    paddingBottom: 10,
    // Intentional custom warm divider for profile page tone
    borderBottom: "1px solid rgba(140,110,70,.14)",
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
  },
  profileName: {
    gridColumn: 2,
    textAlign: "center",
    fontFamily: 'ETBookRoman, warnock-pro, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif',
    fontSize: "2.3rem",
    fontWeight: 400,
    margin: "0 0 2px 0",
    color: theme.palette.text.normal,
    lineHeight: 1.1,
    letterSpacing: "-.02em",
  },
  profileNameLink: {
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit" as const,
    letterSpacing: "inherit",
    textDecoration: "none",
    "&:hover": {
      textDecoration: "none",
      color: "inherit",
    },
  },
  profileEditButton: {
    gridColumn: 3,
    justifySelf: "end",
    position: "relative",
    top: 3,
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    fontWeight: 400,
    color: theme.palette.primary.main,
    textDecoration: "none",
    cursor: "pointer",
    "&:hover": {
      opacity: 0.67,
    },
  },
  mobileProfileBio: {
    display: "none",
    margin: "0 0 30px",
    padding: "30px 0 30px",
    borderBottom: "1px solid rgba(140,110,70,.14)",
  },
  mobileProfileName: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    fontWeight: 400,
    margin: "0 0 10px 0",
    color: theme.palette.text.normal,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  mobileProfileActions: {
    marginTop: 0,
    marginBottom: 16,
  },
  mobileMetaInfo: {
    marginTop: 12,
    color: theme.palette.text.dim,
    "& > div": {
      flexWrap: "wrap",
      gap: "4px 0",
    },
    "& > div > div": {
      marginRight: "14px !important",
    },
  },
  topPostsIndicator: {
    marginTop: 25,
    marginBottom: 15,
    marginLeft: 0,
    paddingLeft: 0,
  },
  topPostsLabel: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    display: "block",
    margin: 0,
    padding: 0,
  },
  topPostsLabelPlural: {
    display: "block",
  },
  topPostsLabelSingular: {
    display: "none",
  },
  emptyStateContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: "16px 0 32px",
    textAlign: "left",
    width: "100%",
  },
  emptyStateImage: {
    marginTop: 8,
    width: "100%",
    maxWidth: 380,
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "auto",
      opacity: 0.85,
      display: "block",
      filter: "none",
      mixBlendMode: "multiply",
    },
  },
  emptyStateDescription: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 15,
    fontWeight: 400,
    color: theme.palette.text.dim,
    lineHeight: 1.5,
    margin: 0,
    fontStyle: "italic",
  },
  postArticle: {
    marginTop: 0,
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 20,
    paddingBottom: 30,
    borderBottom: "1px solid rgba(140,110,70,.14)",
    overflow: "visible",
    textDecoration: "none",
    color: "inherit",
    // Override global a:hover { opacity: 0.5 } so we can apply it to children
    // individually, preserving mix-blend-mode: multiply on the image
    "&:hover": {
      opacity: 1,
    },
    "&:hover $postContent": {
      opacity: 0.5,
    },
    "&:hover $postImage": {
      opacity: 0.5,
    },
  },
  postArticleTop: {
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
  },
  postContent: {
    gridColumn: "1 / 4",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
    paddingLeft: 0,
    marginLeft: 0,
    aspectRatio: "3 / 2",
    transition: "opacity 0.15s ease",
  },
  postImage: {
    gridColumn: "4 / 7",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,.87)",
    fontSize: 14,
    aspectRatio: "3 / 2",
    transition: "opacity 0.15s ease",
    mixBlendMode: "multiply",
  },
  postTitle: {
    fontFamily: 'ETBookRoman, warnock-pro, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif',
    fontSize: "2rem",
    fontWeight: 400,
    margin: "0 0 18px 0",
    color: theme.palette.text.normal,
    lineHeight: 1.2,
    letterSpacing: "-.02em",
    wordWrap: "break-word",
    overflowWrap: "break-word",
    whiteSpace: "normal",
    maxWidth: "100%",
    paddingLeft: 0,
    flexShrink: 0,
  },
  topPostTitle: {
    fontSize: 34,
    lineHeight: 1.15,
  },
  postSummary: {
    fontFamily: 'warnock-pro, "Cormorant Garamond", "Georgia", serif',
    fontSize: 15,
    fontWeight: 400,
    lineHeight: 1.6,
    color: theme.palette.text.slightlyDim2,
    margin: "0 0 16px 0",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    transition: "opacity 0.2s ease-in",
    "html:not(.dates-ready) &": {
      opacity: 0,
    },
    "html.dates-ready &": {
      opacity: 1,
    },
  },
  postMetaBar: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    fontSize: 13,
    color: theme.palette.text.dim,
    flexShrink: 0,
    transition: "opacity 0.2s ease-in",
    "html:not(.dates-ready) &": {
      opacity: 0,
    },
    "html.dates-ready &": {
      opacity: 1,
    },
  },
  karmaScore: {
    fontSize: 13,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  postDate: {
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    letterSpacing: 0,
  },
  smallArticlesGrid: {
    marginTop: 30,
    paddingBottom: 30,
    borderBottom: "1px solid rgba(140,110,70,.14)",
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 20,
  },
  smallArticle: {
    gridColumn: "span 2",
    display: "flex",
    flexDirection: "column",
    "&:hover $smallArticleContent": {
      opacity: 0.5,
    },
    "&:hover $smallArticleImage": {
      opacity: 0.5,
    },
  },
  smallArticleImage: {
    width: "100%",
    aspectRatio: "3 / 2",
    backgroundSize: "cover",
    backgroundPosition: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,.87)",
    fontSize: 12,
    borderRadius: 4,
    overflow: "hidden",
    transition: "opacity 0.15s ease",
    mixBlendMode: "multiply",
  },
  smallArticleContent: {
    padding: "15px 0 0 0",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    transition: "opacity 0.15s ease",
  },
  smallArticleTitle: {
    fontFamily: 'ETBookRoman, warnock-pro, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif',
    fontSize: 16,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.3,
    letterSpacing: "-.02em",
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    lineClamp: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  smallArticleMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    transition: "opacity 0.2s ease-in",
    "html:not(.dates-ready) &": {
      opacity: 0,
    },
    "html.dates-ready &": {
      opacity: 1,
    },
  },
  smallKarma: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  smallDate: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    letterSpacing: 0,
  },
  listArticle: {
    padding: "20px 0",
    borderBottom: "1px solid rgba(140,110,70,.14)",
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    transition: "opacity 0.15s ease",
    animation: "$slideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    overflow: "visible",
    "&:hover": {
      opacity: 0.5,
    },
    "&:last-of-type": {
      borderBottom: "none",
    },
  },
  listArticleContent: {
    minWidth: 0,
    flex: 1,
    order: 1,
    display: "flex",
    flexDirection: "column",
    gap: 18,
    overflow: "visible",
  },
  listArticleTitle: {
    fontFamily: 'ETBookRoman, warnock-pro, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif',
    fontSize: 19,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.45,
    letterSpacing: "-.02em",
    display: "flex",
    alignItems: "baseline",
    gap: 6,
    whiteSpace: "normal",
  },
  listArticleTitleText: {
    display: "block",
    flex: 1,
    minWidth: 0,
    position: "relative",
    zIndex: 1,
  },
  pinnedIcon: {
    display: "inline-flex",
    width: 14,
    height: 14,
    marginRight: 6,
    verticalAlign: "text-top",
  },
  pinnedIconSvg: {
    width: "100%",
    height: "100%",
    fill: theme.palette.text.dim,
  },
  listArticleSummary: {
    fontFamily: 'warnock-pro, "Cormorant Garamond", "Georgia", serif',
    fontSize: 15,
    fontWeight: 400,
    lineHeight: 1.75,
    color: theme.palette.text.slightlyDim2,
    margin: 0,
    whiteSpace: "normal",
    position: "relative",
    zIndex: 1,
  },
  listArticleMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    marginTop: -2,
    transition: "opacity 0.2s ease-in",
    "html:not(.dates-ready) &": {
      opacity: 0,
    },
    "html.dates-ready &": {
      opacity: 1,
    },
  },
  listKarma: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    color: theme.palette.text.slightlyDim2,
    fontWeight: 600,
    letterSpacing: "-0.01em",
  },
  listDate: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    color: theme.palette.text.dim,
    fontWeight: 400,
    letterSpacing: 0,
  },
  listArticleImage: {
    display: "none",
    width: 96,
    height: 64,
    borderRadius: 6,
    flex: "0 0 auto",
    order: 2,
    marginLeft: 4,
    backgroundColor: "transparent",
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  allPostsSection: {
    marginTop: 30,
  },
  allPostsHeader: {
    marginBottom: 6,
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 20,
    alignItems: "baseline",
  },
  allPostsLeftHeader: {
    gridColumn: "1 / 5",
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  profileTabs: {
    display: "flex",
    gap: 18,
    margin: 0,
    paddingBottom: 6,
  },
  profileTab: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 12,
    fontWeight: 400,
    background: "none",
    border: "none",
    padding: "0 0 6px",
    cursor: "pointer",
    color: theme.palette.text.dim,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    transition: "color 0.2s",
    "&:hover": {
      color: theme.palette.text.normal,
    },
  },
  profileTabActive: {
    color: theme.palette.text.normal,
    fontWeight: 600,
  },
  sortControl: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 14,
    color: theme.palette.text.dim60,
    position: "relative",
  },
  sortIconButton: {
    background: "none",
    border: "none",
    padding: 4,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    color: "inherit",
    "&:hover": {
      opacity: 0.67,
    },
  },
  sortIconDisabled: {
    opacity: 0.35,
    cursor: "default",
    "&:hover": {
      opacity: 0.35,
    },
  },
  sortIcon: {
    fontSize: 16,
  },
  sortPanel: {
    background: "#fcfbf8",
    padding: "20px 24px",
    marginBottom: 20,
    borderRadius: 4,
    overflow: "hidden",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    animation: "$panelOpen 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sortPanelClosing: {
    animation: "$panelClose 0.3s cubic-bezier(0.4, 0, 1, 1)",
    animationFillMode: "forwards",
  },
  sortPanelMulti: {
    display: "flex",
    gap: 40,
  },
  sortPanelSection: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  sortPanelHeader: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 13,
    fontWeight: 600,
    fontStyle: "italic",
    color: theme.palette.text.dim,
    marginBottom: 6,
  },
  sortPanelOption: {
    display: "block",
    width: "fit-content",
    padding: "4px 0 4px 16px",
    textAlign: "left",
    background: "none",
    border: "none",
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 14,
    color: theme.palette.text.dim40,
    cursor: "pointer",
    transition: "color 0.15s ease",
    "&:hover": {
      color: theme.palette.text.normal,
    },
  },
  sortPanelOptionSelected: {
    color: theme.palette.text.normal,
  },
  allPostsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 20,
    minHeight: "100vh",
  },
  postsList: {
    gridColumn: "1 / 5",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  tabPanel: {
    display: "none",
  },
  tabPanelActive: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    animation: "$slideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  articleLink: {
    textDecoration: "none",
    color: "inherit",
    display: "contents",
  },
  sequencesList: {
    gridColumn: "1 / 5",
  },
  feedList: {
    gridColumn: "1 / 5",
    "& .UserContentFeed-feedContent": {
      gap: 22,
      marginLeft: 0,
      marginRight: 0,
    },
    "& .UltraFeedPostItem-root, & .UltraFeedCommentItem-root, & .UltraFeedThreadItem-root": {
      border: "none",
      borderRadius: 4,
      boxShadow: "0 1px 4px rgba(0,0,0,.05)",
      padding: "25px 25px 8px 25px",
      background: "rgba(255,255,255,1)",
    },
    "& .FeedContentBody-root": {
      maxHeight: 200,
      overflow: "hidden",
      position: "relative",
    },
    "& .FeedContentBody-root > .ContentStyles-base": {
      minHeight: "0 !important",
      display: "block !important",
    },
    "& .UltraFeedCommentItem-contentWrapper": {
      marginTop: 8,
      marginBottom: 8,
    },
    "& .UltraFeedPostItem-footer, & .UltraFeedCommentItem-footer": {
      marginTop: 4,
      marginBottom: 8,
    },
  },
  sequencesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 20,
    padding: "8px 0",
  },
  sequenceCard: {
    display: "flex",
    flexDirection: "column",
    overflow: "visible",
    position: "relative",
    transition: "opacity 0.15s ease",
    "&:hover": {
      opacity: 0.5,
    },
  },
  sequenceCardImage: {
    width: "100%",
    aspectRatio: "3 / 2",
    backgroundColor: "#fcfbf8",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: 4,
  },
  sequenceCardContent: {
    padding: "15px 0",
    background: "transparent",
  },
  sequenceCardTitle: {
    fontFamily: 'ETBookRoman, warnock-pro, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif',
    fontSize: 15,
    fontWeight: 400,
    lineHeight: 1.3,
    letterSpacing: "0.03em",
    fontVariant: "small-caps",
    color: theme.palette.text.normal,
    margin: 0,
    borderTop: "none",
    borderRadius: "0 0 8px 8px",
  },
  sidebarAuthorName: {
    gridColumn: "5 / 7",
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 12,
    fontWeight: 400,
    margin: 0,
    color: theme.palette.text.normal,
    lineHeight: 1.1,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  sidebarAuthorNameLink: {
    color: "inherit",
    textDecoration: "none",
    "&:hover": {
      opacity: 0.67,
    },
  },
  postsSidebar: {
    gridColumn: "5 / 7",
    position: "sticky",
    top: 80,
    alignSelf: "start",
  },
  postsSidebarHasBio: {
    "& $sidebarStats": {
      display: "none",
    },
  },
  sidebarBioSection: {},
  sidebarBioWrapper: {
    overflow: "hidden",
    transition: "max-height 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarBioCollapsed: {
    maxHeight: 400,
    "& $sidebarAuthorBio": {
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 12,
      lineClamp: 12,
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
  },
  sidebarBioExpanded: {
    maxHeight: 2000,
    transition: "max-height 0.6s cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarAuthorBio: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 14,
    lineHeight: 1.6,
    color: theme.palette.text.dim55,
    fontWeight: 400,
    margin: 0,
  },
  sidebarStats: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 14,
    lineHeight: 1.6,
    color: theme.palette.text.dim,
    fontWeight: 400,
    marginTop: 16,
  },
  sidebarStatRow: {
    whiteSpace: "nowrap",
  },
  readMore: {
    textAlign: "left",
    marginTop: 12,
  },
  postsSidebarReadMore: {
    marginTop: 5,
  },
  readMoreLink: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    fontSize: 14,
    color: theme.palette.primary.main,
    textDecoration: "none",
    fontWeight: 400,
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 24,
    marginBottom: 22,
  },
  sidebarSubscribe: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    color: theme.palette.primary.main,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-block",
    fontWeight: 400,
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarMore: {
    fontFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    color: theme.palette.primary.main,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-block",
    fontWeight: 400,
    textDecoration: "none",
    "&:hover": {
      opacity: 0.67,
    },
  },
  sidebarActionDisabled: {
    color: theme.palette.primary.light,
    cursor: "default",
    "&:hover": {
      opacity: 1,
    },
  },
  "@media (max-width: 900px)": {
    profileMain: {
      padding: "40px 30px 50px 30px",
    },
    postTitle: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
    postSummary: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
  },
  "@media (max-width: 750px)": {
    profileMain: {
      padding: "35px 25px 45px 25px",
    },
    postArticle: {
      display: "flex",
      flexDirection: "column-reverse",
      gap: 16,
    },
    postContent: {
      height: "auto",
      maxHeight: "none",
      width: "100%",
      aspectRatio: "auto",
    },
    postImage: {
      width: "100%",
      height: 220,
      aspectRatio: "auto",
    },
    postSummary: {
      flex: "none",
      display: "-webkit-box",
      WebkitBoxOrient: "vertical",
      WebkitLineClamp: 4,
      lineClamp: 4,
      textOverflow: "ellipsis",
    },
  },
  "@media (max-width: 630px)": {
    profileMain: {
      padding: "30px 20px 40px 20px",
    },
    postImage: {
      height: 200,
    },
    smallArticlesGrid: {
      display: "none",
    },
    topPostsLabelPlural: {
      display: "none",
    },
    topPostsLabelSingular: {
      display: "block",
    },
    mobileProfileBio: {
      display: "block",
    },
    allPostsHeader: {
      display: "flex",
      flexDirection: "column",
      gap: 0,
    },
    allPostsLeftHeader: {
      width: "100%",
      marginBottom: 16,
    },
    allPostsContainer: {
      display: "flex",
      flexDirection: "column",
      gap: 30,
    },
    postsList: {
      width: "100%",
    },
    tabPanel: {
      order: 1,
    },
    postsSidebar: {
      width: "100%",
      position: "static",
      order: 2,
      "& $sidebarActions, & $sidebarBioSection, & $sidebarStats": {
        display: "none",
      },
    },
    sequencesGrid: {
      gridTemplateColumns: "1fr",
      gap: 24,
    },
    sidebarAuthorName: {
      display: "none",
    },
    postTitle: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
    postSummary: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
    smallArticleTitle: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
    },
    listArticleTitle: {
      wordWrap: "break-word",
      overflowWrap: "break-word",
      whiteSpace: "normal",
      overflow: "visible",
      textOverflow: "clip",
    },
  },
  "@keyframes slideIn": {
    from: {
      opacity: 0,
      transform: "translateY(10px)",
    },
    to: {
      opacity: 1,
      transform: "translateY(0)",
    },
  },
  "@keyframes panelOpen": {
    from: {
      opacity: 0,
      maxHeight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      marginBottom: 0,
    },
    to: {
      opacity: 1,
      maxHeight: 500,
      paddingTop: 20,
      paddingBottom: 20,
      marginBottom: 20,
    },
  },
  "@keyframes panelClose": {
    from: {
      opacity: 1,
      maxHeight: 500,
      paddingTop: 20,
      paddingBottom: 20,
      marginBottom: 20,
    },
    to: {
      opacity: 0,
      maxHeight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      marginBottom: 0,
    },
  },
}));
