import { defineStyles } from '@/components/hooks/defineStyles';

export const searchPageStyles = defineStyles("SearchPageResults", (theme: ThemeType) => ({
  root: {
    width: "100%",
    margin: "auto",
    marginTop: -theme.spacing.mainLayoutPaddingTop,
    padding: "0 24px 64px",
    boxSizing: "border-box",
    [theme.breakpoints.down('sm')]: {
      marginTop: -10,
      padding: "0 8px 40px",
    },
  },
  modal: {
    '--header-height': '0px',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    maxHeight: '100%',
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    margin: 0,
    padding: '0 12px 12px',
    // Inset the scrollbar without moving the search controls or results.
    '&::-webkit-scrollbar, & $layout::-webkit-scrollbar': {
      width: 12,
    },
    '&::-webkit-scrollbar-track, & $layout::-webkit-scrollbar-track': {
      marginTop: 64,
    },
    '&::-webkit-scrollbar-thumb, & $layout::-webkit-scrollbar-thumb': {
      backgroundColor: theme.palette.greyAlpha(0.45),
      borderRadius: 6,
      border: '2px solid transparent',
      backgroundClip: 'padding-box',
    },
    '& $sidebar': {
      minWidth: 0,
      '&[hidden]': {
        display: 'block', visibility: 'hidden',
        [theme.breakpoints.down('sm')]: {display: 'none'},
      },
      maxHeight: 'calc(var(--search-viewport-height, 100dvh) - 56px)',
      top: 8,
      marginTop: 8,
      padding: '0 0 4px',
      scrollbarGutter: 'auto',
    },
    '& $topBar': {padding: '8px 0 4px'},
    '& $searchBoxRow': {gap: 8, marginBottom: 4},
    '& $searchInputArea': {padding: '2px 10px', gap: '4px 6px'},
    '& $kinds': {margin: 0, padding: '2px 0', gap: 0},
    '& $resultCount': {padding: '4px 8px', marginBottom: 0, gap: '4px 8px'},
    '& $resultIcon': {left: 8, top: 8},
    '& $historyHint': {marginTop: 0, marginBottom: 4},
    '& $layout': {
      flex: 1,
      gap: 4,
      minHeight: 200,
      overflowY: 'auto',
      overscrollBehavior: 'contain',
      gridTemplateColumns: '340px minmax(0, 1fr)',
      transition: 'grid-template-columns 320ms cubic-bezier(0.2, 0, 0, 1)',
      '@media (prefers-reduced-motion: reduce)': {transition: 'none'},
      gridTemplateAreas: '"sidebar results"',
    },
    // Wide screens have room to spare: let the kind buttons share the row.
    [theme.breakpoints.up('md')]: {
      '& $kinds': {gap: 4},
      '& $kinds > button': {flex: '1 1 0', justifyContent: 'center', maxWidth: 160},
    },
    [theme.breakpoints.down('sm')]: {
      height: '100%',
      maxHeight: '100%',
      margin: 0,
      padding: '0 max(8px, env(safe-area-inset-right)) max(16px, env(safe-area-inset-bottom)) max(8px, env(safe-area-inset-left))',
      '& $layout': {
        height: 'auto',
        gap: 4,
        flex: '0 0 auto',
        minHeight: 0,
        overflow: 'visible',
        gridTemplateColumns: 'minmax(0, 1fr)',
        gridTemplateAreas: '"controls" "sidebar" "hits"',
      },
      '& $sidebar': {maxHeight: 'none', marginTop: 0},
      '& $topBar': {padding: '8px 0 4px'},
      '& $searchBoxRow': {gap: 4, marginBottom: 4},
      '& $kinds': {margin: 0, padding: '2px 0'},
      '& $resultCount': {marginBottom: 0},
      '& $historyHint': {marginTop: 0, marginBottom: 4},
    },
  },
  timeframePanel: {
    flexShrink: 0,
    width: '100%',
    maxWidth: 1200,
    position: 'relative',
    margin: '8px auto 0',
    padding: '8px 12px 0px',
    boxSizing: 'border-box',
    backgroundColor: theme.palette.background.paper,
    border: "none",
    borderRadius: 4,
    scrollMarginTop: 'calc(var(--header-height) + 8px)',
    [theme.breakpoints.down('sm')]: {padding: '4px 8px 8px', marginTop: 8},
  },
  // Rendered into the modal's slot above the dialog box. It stays mounted while
  // collapsed so its containing grid can animate the timeline's height.
  // It sits flush on the dialog box and paints above it. The clip drops the
  // shadow below its bottom edge so the two boxes read as one.
  timeframePanelModal: {
    flexShrink: 0,
    zIndex: 1,
    margin: 0,
    minHeight: 0,
    overflowY: 'auto',
    border: 'none',
    borderRadius: '6px 6px 0 0',
    boxShadow: `0 0 40px ${theme.palette.boxShadowColor(0.3)}`,
    clipPath: 'inset(-48px -48px 0)',
  },
  timeframePanelCollapsed: {
    visibility: 'hidden',
  },
  filterTab: {
    ...theme.typography.body2,
    display: 'inline-flex', alignItems: 'center', justifyContent: 'flex-start',
    minHeight: 40, width: 40, padding: '0 10px', gap: 8,
    overflow: 'hidden', whiteSpace: 'nowrap', flexShrink: 0,
    border: 'none', borderRadius: '0 4px 4px 0', background: 'transparent',
    color: theme.palette.text.dim, cursor: 'pointer',
    transition: 'width 200ms ease-out, background-color 200ms ease-out',
    '&:hover, &:focus-visible': {
      width: 144,
      backgroundColor: theme.palette.greyAlpha(0.04),
      '& $filterTabLabel': {opacity: 1},
    },
    '&:focus-visible': {outline: `2px solid ${theme.palette.primary.main}`, outlineOffset: -2},
    '&[aria-expanded="true"]': {width: 144, '& $filterTabLabel': {opacity: 1}},
    '@media (hover: none)': {width: 144, '& $filterTabLabel': {opacity: 1}},
    [theme.breakpoints.down('sm')]: {
      width: '100%', minHeight: 44, marginTop: 4, borderRadius: 4,
      backgroundColor: theme.palette.greyAlpha(0.04),
      '& $filterTabLabel': {opacity: 1},
      '& $filterTabIcon': {transform: 'rotate(90deg)'},
      '&:hover, &:focus-visible, &[aria-expanded="true"]': {width: '100%'},
      '&[aria-expanded="true"] $filterTabIcon': {transform: 'rotate(-90deg)'},
    },
    '@media (prefers-reduced-motion: reduce)': {transition: 'none'},
  },
  filterTabModal: {
    position: 'absolute', right: 'calc(100% - 104px)', top: 8,
    width: 144, padding: '0 10px', borderRadius: '4px 0 0 4px',
    backgroundColor: theme.palette.background.paper,
    boxShadow: `-4px 2px 12px ${theme.palette.boxShadowColor(0.12)}`,
    transition: 'transform 220ms cubic-bezier(0.2, 0, 0, 1)',
    '& $filterTabIcon': {transform: 'rotate(180deg)'},
    '&:hover, &:focus-visible': {
      transform: 'translateX(-104px)',
      backgroundColor: theme.palette.background.paper,
    },
    '&[aria-expanded="true"]': {
      '& $filterTabLabel': {opacity: 0},
      '& $filterTabIcon': {transform: 'rotate(0deg)'},
      '&:hover $filterTabLabel, &:focus-visible $filterTabLabel': {opacity: 1},
    },
    '@media (prefers-reduced-motion: reduce)': {transition: 'none'},
  },
  filterTabLabel: {
    opacity: 0, fontSize: 13, transition: 'opacity 150ms ease-out',
    '@media (prefers-reduced-motion: reduce)': {transition: 'none'},
  },
  filterTabIcon: {
    width: 20, height: 20, flexShrink: 0, transition: 'transform 200ms ease-out',
    '@media (prefers-reduced-motion: reduce)': {transition: 'none'},
  },
  filterTabIconOpen: {transform: 'rotate(180deg)'},
  closeButton: {
    ...theme.typography.body2,
    border: 'none',
    background: 'transparent',
    color: theme.palette.text.normal,
    cursor: 'pointer',
    minWidth: 44,
    minHeight: 44,
    flexShrink: 0,
    '&:focus-visible': {outline: `2px solid ${theme.palette.primary.main}`},
  },
  topBar: {
    position: "sticky",
    top: "var(--header-height)",
    zIndex: 10,
    boxSizing: "border-box",
    padding: "16px 0 12px",
    [theme.breakpoints.down('sm')]: {
      gridArea: "controls",
      position: "static",
    },
    backgroundColor: theme.palette.background.paper,

  },
  layout: {
    display: "grid",
    // Keep the filter column wide enough for its controls; center results when space allows.
    gridTemplateColumns: "minmax(340px, 1fr) minmax(0, 760px) minmax(0, 1fr)",
    gridTemplateAreas: '"sidebar results ."',
    gap: 24,
    alignItems: "start",
    "@media (max-width: 1399px)": {
      gridTemplateColumns: "340px minmax(0, 760px)",
      gridTemplateAreas: '"sidebar results"',
      justifyContent: "center",
    },
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: "minmax(0, 1fr)",
      gridTemplateAreas: '"controls" "sidebar" "hits"',
      gridAutoRows: "max-content",
      alignContent: "start",
      gap: 8,
    },
  },
  sidebar: {
    gridArea: "sidebar",
    "&[hidden]": {display: "none"},
    position: "sticky",
    top: "calc(var(--header-height) + 16px)",
    marginTop: 16,
    width: "100%",
    maxWidth: 360,
    justifySelf: "end",
    boxSizing: "border-box",
    maxHeight: "calc(100dvh - var(--header-height) - 32px)",
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
    padding: "4px 0 8px",
    backgroundColor: theme.palette.background.paper,
    border: "none",
    borderRadius: 4,
    zIndex: 9,
    [theme.breakpoints.down('sm')]: {
      position: "static",
      maxWidth: "none",
      maxHeight: "none",
      overflow: "visible",
      scrollbarGutter: "auto",
      marginTop: 0,
    },
  },
  filtersClosed: {
    '&$modal $layout': {
      gridTemplateColumns: '0px minmax(0, 1fr)',
      gridTemplateAreas: '"sidebar results"',
      gap: 0,
      [theme.breakpoints.down('sm')]: {
        gridTemplateColumns: 'minmax(0, 1fr)',
        gridTemplateAreas: '"controls" "hits"',
      },
    },
    '& $layout': {
      gridTemplateColumns: 'minmax(0, 760px)',
      gridTemplateAreas: '"results"',
      justifyContent: 'center',
      [theme.breakpoints.down('sm')]: {
        gridTemplateColumns: 'minmax(0, 1fr)',
        gridTemplateAreas: '"controls" "hits"',
      },
    },
  },
  results: {
    gridArea: "results",
    minWidth: 0,
    [theme.breakpoints.down('sm')]: {
      display: "contents",
    },
  },
  resultsContent: {
    [theme.breakpoints.down('sm')]: {
      gridArea: "hits",
      minWidth: 0,
    },
  },
  searchBoxRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    [theme.breakpoints.down('sm')]: {
      width: "100%",
    },
  },
  searchInputArea: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    flexWrap: "wrap",
    gap: "4px 10px",
    padding: "2px 14px",
    boxSizing: "border-box",
    border: "none",
    borderRadius: 3,
    backgroundColor: theme.palette.background.paper,
    transition: "background-color 150ms",
    "&:focus-within": {
      backgroundColor: theme.palette.greyAlpha(0.04),
    },
  },
  searchIcon: {
    fontSize: 20,
    flexShrink: 0,
    color: theme.palette.text.dim,
  },
  input: {
    minWidth: 0,
    ...theme.typography.body2,
    flex: "1 1 120px",
    height: 38,
    padding: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: theme.palette.text.normal,
    fontSize: 16,
    "&::placeholder": {color: theme.palette.text.dim, opacity: 1},
    "&::-webkit-search-cancel-button": {
      WebkitAppearance: "none",
      width: 16,
      height: 16,
      cursor: "pointer",
      backgroundColor: theme.palette.text.dim,
      mask: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 16 16\'%3E%3Cpath d=\'M4 4l8 8M12 4l-8 8\' stroke=\'black\' stroke-width=\'1.5\' stroke-linecap=\'round\'/%3E%3C/svg%3E") center / contain no-repeat',
    },
    "-webkit-appearance": "none",
  },
  authorPills: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    maxWidth: "100%",
    minWidth: 0,

  },
  clearFilters: {
    ...theme.typography.body2,
    minHeight: 40, border: "none", background: "transparent",
    color: theme.palette.primary.main, cursor: "pointer", padding: "0 8px",
    "&:focus-visible": {outline: `2px solid ${theme.palette.primary.main}`},
  },
  clearFiltersButton: {
    fontWeight: 600,
    backgroundColor: theme.palette.greyAlpha(0.08),
    borderRadius: 4,
    padding: "0 12px",
    "&:hover": {backgroundColor: theme.palette.greyAlpha(0.14)},
  },
  filters: {
    marginTop: 0,
    marginBottom: 0,
  },
  kinds: {
    marginTop: 4,
    marginBottom: 4,
    justifyContent: "flex-start",
    gap: 4,
    [theme.breakpoints.down('sm')]: {
      margin: 0,
      padding: "16px 0",
      gap: 0,
    },
  },
  postTypes: {flexWrap: "wrap"},
  resultCount: {
    ...theme.typography.body2,
    fontSize: 14,
    color: theme.palette.text.normal,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    gap: "4px 16px",
    padding: "8px 20px 12px",
    marginBottom: 4,
    fontVariantNumeric: "tabular-nums",
  },
  result: {
    position: "relative",
    display: "block",
    borderRadius: 5,
    scrollMarginTop: 'calc(var(--header-height) + 160px)',
    scrollMarginBottom: 16,
    "&[data-search-selected]": {
      backgroundColor: theme.palette.greyAlpha(0.05),
    },
    "& a:hover": {opacity: 1},
  },
  resultIcon: {
    display: "flex",
    position: "absolute",
    top: 12,
    left: 20,
    [theme.breakpoints.down('sm')]: {left: 8},
    fontSize: 20,
    color: theme.palette.text.dim,
    "& > svg": {fontSize: "inherit"},
  },
  status: {
    ...theme.typography.body2,
    padding: 12,
    textAlign: "center",
  },
  historyHint: {
    ...theme.typography.body2,
    fontSize: 12,
    color: theme.palette.text.dim,
    marginTop: -12,
    marginBottom: 12,
  },
}));
