export const sharedSettings = {
  forum: {
    numberOfDays: 10,
    postInterval: 30,
    numberOfWeeks: 4,
    numberOfYears: 4,
    maxPostsPerDay: 5,
    numberOfMonths: 4
  },
  type3: {
    cutoffDate: "2023-07-01",
    // TODO: migrate these to forceAllowType3Audio
    explicitlyAllowedPostIds: [
      "SvKSwT6xYfYahH4XN",
      "2weRdcvqANDq3zdPH",
      "Zm7WAJMTaFvuh2Wc7",
      "HcjL8ydHxPezj6wrt",
      "pgGiqLQg2KWsaz5RE",
      "jFzovY2CERF5bd2EW",
      "sm6npdgZArSn4afeZ",
      "CfX6pGepdjQYELSpK",
      "NyFuuKQ8uCEDtd2du",
      "LCjtqsQWapoSfDHqK",
      "MxyRNd6qJsYAcXKuw",
      "reG3g4wwzwJcKnFfh",
      "zfeWGvTrS6wKQeeoF",
      "oHsMeXehPy4jHcmwy",
      "ofL22R6KZsfrvdmwg",
      "655TmdcwAgryPGPWS",
      "hhrv8aAcmkzJxvP58",
      "iqQJiKcephtMgzJgN",
      "mnpkM57R6ZbjnwrYw",
      "6mRv7Cr57AJAtRFHv",
      "ak9wY2t9K3K4GxCXv",
      "Ay6GBGNcCgP55dRQ7",
      "aH4mjhgqNPyYvJT85",
      "JpoLCHytYiCm7fwNA",
      "efMgZujzfjP9B9H4R",
      "BjLxPLsev54LFCS3A",
      "HTGCGASf9xfB6edAh",
      "H6LnGwjKiGvDyR5yo",
      "qL8Z9TBCNWQyN6yLq",
      "F4xwRTrFQyazHufjD",
      "LY7Nca846X8kcT8Jk",
      "K9aLcuxAPyf5jGyFX",
      "2AuvBPw6Rb7yxkvKc",
      "muhtBvbh4etjkKXd9",
      "ALEYMFAuFSCz8v5YE",
      "CJxSgaqG6y7z6Rbij",
      "k5TpDCEHeK4qwnJt8",
      "4Y2J7NtuweW2B8JvB",
      "BpYDqQNZ2NZNCqPp6",
      "oMiogKLkK8L59WzDe",
      "TyQSMmoJpRG3HBv5S",
      "8KHR3tfa4SJjMSkXd",
      "g4pi2jfQHFF6mPdjw",
      "znEhB9hJtwXica5s3",
      "Sd2r7H8bCmd9ChGbX",
      "P2nYKqwmHdYKARTG8",
      "FW3DEYbKPZJh5A8Bj",
      "K3hFLRn7MvYacL466",
      "ouSpHCCPgsXkwxAGb",
      "w9SuQtRJLbDpeir6L",
      "yPQGYn9rSme9RRpiQ",
      "BD6WYC4GT6dnWaJRN",
      "c8khnHoRTSGjmHLLf",
      "TaPr4YSBbiakeKdwX",
      "pyNPXST7feDX45ygt",
      "ERPL3v2Y976W7XG3j",
      "XpXQ4KNzLa9ZHYw8p",
      "PBhrHw5X8sDmHDWkX",
      "8KhThQXzsAEZ59iko",
      "iYJo382hY28K7eCrP",
      "KrEwDMN4YXp5YWD45",
      "rNJ39yQmzTnseh8nL",
      "hMQPyLDbg3bA7P6aN",
      "3Jqz6JE8K6vyQ9hJ5",
      "SQAfPKZBAAKYMjx25",
      "Y345zuBetHqGnotwm",
      "pZerSnxv6FPqvgoYu",
      "3bPH2az479gzxDMbf",
      "QXShCBvPydkwafekn",
      "iLMkKDKmfbMkDuQBm",
      "iNCg6mjw584r9BWZK",
      "9oqF382ASmjaGBo7z",
      "DdNB42JgBzbbvmAum",
      "JP7eZYHB7aY6fA4TR",
      "snwX7hXgLFikqDBr6",
      "CsKrQdQJJCFPjfKjF",
      "vhxywjnBH6ioRnnt3",
      "A4MK9RQqSAJZjanQD",
      "PCpzG9NJeviXM5YSq",
      "KCcdhZK7omEMwBdju",
      "kdmCm5NQTpqhJmGm6",
      "2p8BWvcJvKkXGMsch",
      "FLnDFnXyWrKr6eiT6",
      "2gWs8SScqeDFidqyv",
      "2HafkDSNdtMzptzcN",
      "cTQRGJTQ2eGKm5G9g",
      "qaHHJ3kkCQS4nsoGJ",
      "gS8Jmcfoa9FAh92YK",
      "eRhFaibbTeGbjdaaf",
      "xij43oLTBRnEQv2bT",
      "BZMc9Xzqw5WcCMHrr",
      "2jZykdLg9fBGqKd46",
      "gBChm3THPGFcrq5eH",
      "9HSwh2mE3tX6xvZ2W",
      "tEHJXNhw6t87foqJL",
      "T5McDuWDeCvDZKeSj",
      "PeTL97v92LxRJBsrM",
      "Cq45AuedYnzekp3LX",
      "pfmZ5cYQCahABGZzi",
      "3wBj8BPquskZAbXu9",
      "xPJKZyPCvap4Fven8",
      "BPKvZuLRyiJBjfNbg",
      "um7w5RogAHhxGy8Ti",
      "CcyGR3pp3FCDuW6Pf",
      "BfaAADSQ88cuxLQoD",
      "ckuuDa8DmJ4pdFeD8",
      "pczHfyxmnFhtKthqR",
      "dymK5c7BkpgXH4acw",
      "B4AyJXYPpGbBmxQzd",
      "xNBRkPNHAGQ6EQaLS",
      "88TN6y9M5xxAHHNwW",
      "Lt8Rn4rkYwqiTXGPy",
      "QdXrkWoK2Pp6XhNuQ",
      "NjzBrtvDS4jXi5Krp",
      "ZWC3n9c6v4s35rrZ3",
      "Fy2b55mLtghd4fQpx",
      "eaczwARbFnrisFx8E",
      "KLjQedNYNEP4tW73W",
      "DSnamjnW7Ad8vEEKd",
      "7iDtkfyn322nPzTP4",
      "eaSJtg8Kvc56bFBdt",
      "AmaWMMWPzuQ62Ernf",
      "jkf2YjuH8Z2E7hKBA",
      "BroeiXGh9PrKZEkJ5",
      "9Tw5RqnEzqEtaoEkq",
      "EMJ3egz48BtZS8Pws",
      "MkKcnPdTZ3pQ9F5yC",
      "kjArXFinD3deRZNRu",
      "Q8zqoBWBBHD2RjDuS",
      "ePA4NDzZkunz98tLx",
      "4xKeNKFXFB458f5N8",
      "irbREZtZzPi7WEYex",
      "QxZs5Za4qXBegXCgu",
      "ZmQv4DFx6y4jFbhLy",
      "M7rwT264CSYY6EdR3",
      "z3cTkXbA7jgwGWPcv",
      "9thqSN8HDLM3LTxK5",
      "MtNnFg4uN32YPoKNa",
      "Ep2Z42hYqj68QZz6w",
      "ibk7q8msSYxZXmfCf",
      "EgDpZS4HHeh5vqJPe",
      "5dhWhjfxn4tPfFQdi",
      "Wh8HAK6LR5CAoPCCC",
      "Yy7mgec8tsbTAuTqb",
      "azoP7WeKYYfgCozoh",
      "Zh9AiXNjQaYXjmNaC",
      "bJiyYJeCyh4HcKHub",
      "aPrCzeFfbBmRsvzby",
      "vXCK3kptLLggEfojX",
      "M2LWXsJxKS626QNEA",
      "LQp9cZPzJncFKh5c8",
      "CZnBQtvDw33rmWpBD",
      "miHttwTgajY2sjY3L",
      "K2JBqDeETX2yEgyyZ",
      "r8aAqSBeeeMNRtiYK",
      "Gh2qQHrCg3teQen3c",
      "mja6jZ6k9gAwki9Nu",
      "qjSHfbjmSyMnGR9DS",
      "Sx26Aj3xuMzmnKE4A",
      "P3uavjFmZD5RopJKk",
      "pJJdcZgB6mPNWoSWr",
      "oGezscrQvPDgGvrbt",
      "AYbhqi65SWzHzy7Xx",
      "E4cKD9iTWHaE7f3AJ",
      "x9FNKTEt68Rz6wQ6P",
      "HAEPbGaMygJq8L59k",
      "znBJwbuT3f5eWgM4E",
      "yJfBzcDL9fBHJfZ6P",
      "YAkpzvjC768Jm2TYb",
      "LTtNXM9shNM9AC2mp",
      "9hR2RmpJmxT8dyPo4",
      "WQWhXzALcrzrJtqRh",
      "p7WXmG6Fbo3eaSwm3",
      "KheBaeW8Pi7LwewoF",
      "A2Qam9Bd9xpbb2wLQ",
      "asmZvCPHcB4SkSCMW",
      "euJm4RwkAptZnP89i",
      "r8stxYL29NF9w53am",
      "6yTShbTdtATxKonY5",
      "yDRX2fdkm3HqfTpav",
      "EhEZoTFzys9EDmEXn",
      "YSWa8rYeD3aDaofSP",
      "rwkkcgSpnAyE8oNo3",
      "HmfxSWnqnK265GEFM",
      "Ltey8BS83qSkd9M3u",
      "atcJqdhCxTZiJSxo2",
      "pC47ZTsPNAkjavkXs",
      "wJnm5cBiZGmKn595f",
      "GrtbTAPfkJa4D6jjH",
      "LgavAYtzFQZKg95WC",
      "reitXJgJXFzKpdKyd",
      "ZiQqsgGX6a42Sfpii",
      "neQ7eXuaXpiYw7SBy",
      "hQHuXuRGZxxWXaPgg",
      "9kcTNWopvXFncXgPy",
      "baTWMegR42PAsH9qJ",
      "Kbm6QnJv9dgWsPHQP",
      "gFMH3Cqw4XxwL69iy",
      "R6M4vmShiowDn56of",
      "6Fpvch8RR29qLEWNH",
      "N6WM6hs7RQMKDhYjB",
      "pdaGN6pQyQarFHXF4",
      "SA9hDewwsYgnuscae",
      "i9xyZBS3qzA8nFXNQ",
      "bx3gkHJehRCYZAF3r",
      "Jk9yMXpBLMWNTFLzh",
      "JvZhhzycHu2Yd57RN",
      "vzfz4AS6wbooaTeQk",
      "gHefoxiznGfsbiAu9",
      "sbcmACvB6DqYXYidL",
      "kipMvuaK3NALvFHc9",
      "xdwbX9pFEr7Pomaxv",
      "XvN2QQpKTuEzgkZHY",
      "uFNgRumrDTpBfQGrs",
      "ii4xtogen7AyYmN6B",
      "kpPnReyBC54KESiSn",
      "FRv7ryoqtvSuqBxuT",
      "u8GMcpEN9Z6aQiCvp",
      "B2CfMNfay2P8f2yyc",
      "JD7fwtRQ27yc8NoqS",
      "mRwJce3npmzbKfxws",
      "3rxMBRCYEmHCNDLhu",
      "FWvzwCDRgcjb9sigb",
      "KrJfoZzpSDpnrv9va",
      "LpM3EAakwYdS6aRKf",
      "Cf2xxC3Yx9g6w7yXN",
      "qHCDysDnvhteW7kRd",
      "mELQFMi9egPn5EAjK",
      "qDmnyEMtJkE9Wrpau",
      "4ZvJab25tDebB8FGE",
      "4QemtxDFaGXyGSrGD",
      "Psr9tnQFuEXiuqGcR",
      "qmXqHKpgRfg83Nif9",
      "ximou2kyQorm6MPjX",
      "eccTPEonRe4BAvNpD",
      "2cYebKxNp47PapHTL",
      "pv7Qpu8WSge8NRbpB",
      "PqMT9zGrNsGJNfiFR",
      "B9kP6x5rpmuCzpfWb",
      "zB4f7QqKhBHa5b37a",
      "qc7P2NwfxQMC3hdgm",
      "RcifQCKkRc9XTjxC2",
      "YABJKJ3v97k9sbxwg",
      "bNXdnRTpSXk9p4zmi",
      "fRsjBseRuvRhMPPE5",
      "MzKKi7niyEqkBPnyu",
      "NQgWL7tvAPgN2LTLn",
      "cujpciCqNbawBihhQ",
      "wEebEiPpEwjYvnyqq",
      "AqbWna2S85pFTsHH4",
      "Nwgdq6kHke5LY692J",
      "8xLtE3BwgegJ7WBbf",
      "SWxnP5LZeJzuT3ccd",
      "Tr7tAyt5zZpdTwTQK",
      "ax695frGJEzGxFBK4",
      "FkgsxrGf3QxhfLWHG",
      "vJ7ggyjuP4u2yHNcP",
      "X5RyaEDHNq5qutSHK",
      "xhD6SHAAE9ghKZ9HS",
      "AyNHoTWWAJ5eb99ji",
      "F5ktR95qqpmGXXmLq",
      "znfkdCoHMANwqc2WE",
      "jbE85wCkRr9z7tqmD",
      "4K5pJnKBGkqqTbyxx",
      "yeADMcScw8EW9yxpH",
      "9QxnfMYccz9QRgZ5z",
      "X2i9dQQK3gETCyqh2",
      "4XRjPocTprL4L8tmB",
      "D6trAzh6DApKPhbv4",
      "BcYfsi7vmhDvzQGiF",
      "i42Dfoh4HtsCAfXxL",
      "zp5AEENssb8ZDnoZR",
      "KwdcMts8P8hacqwrX",
      "RQpNHSiWaXTvDxt6R",
      "nSjavaKcBrtNktzGa",
      "hNqte2p48nqKux3wS",
      "7im8at9PmhbT4JHsW",
      "SwcyMEgLyd4C3Dern",
      "AHhCrJ2KpTjsCSwbt",
      "rz73eva3jv267Hy7B",
      "E4zGWYzh6ZiG85b2z",
      "hvGoYXi2kgnS3vxqb",
      "D4hHASaZuLCW92gMy",
      "v7c47vjta3mavY3QC",
      "G5TwJ9BGxcgh5DsmQ",
      "YRgMCXMbkKBZgMz4M",
      "ham9i5wf4JCexXnkN",
      "a4jRN9nbD79PAhWTB",
      "xJyY5QkQvNJpZLJRo",
      "ivpKSjM4D6FbqF4pZ",
      "p7x32SEt43ZMC9r7r",
      "f886riNJcArmpFahm",
      "xhE4TriBSPywGuhqi",
      "ThvvCE2HsLohJYd7b",
      "diruo47z32eprenTg",
      "JJFphYfMsdFMuprBy",
      "ZDZmopKquzHYPRNxq",
      "KkwtLtroaNToWs2H6",
      "vKErZy7TFhjxtyBuG",
      "3L46WGauGpr7nYubu",
      "CSZnj2YNMKGfsMbZA",
      "G2Lne2Fi7Qra5Lbuf",
      "x6hpkYyzMG6Bf8T3W",
      "aFaKhG86tTrKvtAnT",
      "PrCmeuBPC4XLDQz8C",
      "dYspinGtiba5oDCcv",
      "9cbEPEuCa9E7uHMXT",
      "N5Jm6Nj4HkNKySA5Z",
      "asmZvCPHcB4SkSCMW",
      "duxy4Hby5qMsv42i8",
      "Djs38EWYZG8o7JMWY",
      "A8iGaZ3uHNNGgJeaD",
      "XYYyzgyuRH5rFN64K",
      "2jfiMgKkh7qw9z8Do",
      "JPan54R525D68NoEt",
      "o4cgvYmNZnfS4xhxL",
      "CeZXDmp8Z363XaM6b",
      "DQKgYhEYP86PLW7tZ",
      "niQ3heWwF6SydhS7R",
      "gvK5QWRLk3H8iqcNy",
      "fnkbdwckdfHS2H22Q",
      "YicoiQurNBxSp7a65",
      "JBFHzfPkXHB2XfDGj",
      "tj8QP2EFdP8p54z6i",
      "9fB4gvoooNYa4t56S",
      "zTfSXQracE7TW8x4w",
      "YcdArE79SDxwWAuyF",
      "8xRSjC76HasLnMGSf",
      "CvKnhXTu9BPcdKE4W",
      "DtcbfwSrcewFubjxp",
      "NxF5G6CJiof6cemTw",
      "4ZwGqkMTyAvANYEDw",
      "EF5M6CmKRd6qZk27Z",
      "cCMihiwtZx7kdcKgt",
      "Qz6w4GYZpgeDp6ATB",
      "TPjbTXntR54XSZ3F2",
      "x3fNwSe5aWZb5yXEG",
      "bnY3L48TtDrKTzGRb",
      "ZFtesgbY9XwtqqyZ5",
      "S7csET9CgBtpi7sCh",
      "tTWL6rkfEuQN9ivxj",
      "L6Ktf952cwdMJnzWm",
      "P6fSj3t4oApQQTB7E",
      "4s2gbwMHSdh2SByyZ",
      "sTwW3QLptTQKuyRXx",
      "EYd63hYSzadcNnZTD",
      "tF8z9HBoBn783Cirz",
      "hyShz2ABiKX56j5tJ",
      "YN6daWakNnkXEeznB",
      "6DuJxY8X45Sco4bS2",
      "TMFNQoRZxM4CuRCY6",
      "q3JY4iRzjq56FyjGF",
      "diutNaWF669WgEt3v",
      "5okDRahtDewnWfFmz",
      "r3NHPD3dLFNk9QE2Y",
      "ALkH4o53ofm862vxc",
      "N9oKuQKuf7yvCCtfq",
      "WjsyEBHgSstgfXTvm",
      "2G8j8D5auZKKAjSfY",
      "rBkZvbGDQZhEymReM",
      "nNqXfnjiezYukiMJi",
      "36Dhz325MZNq3Cs6B",
      "f2GF3q6fgyx8TqZcn",
      "byewoxJiAfwE6zpep",
      "nEBbw2Bc2CnN2RMxy",
      "w4aeAFzSAguvqA5qu",
      "xFotXGEotcKouifky",
      "rzqACeBGycZtqCfaX",
      "DoPo4PDjgSySquHX8",
      "o3RLHYviTE4zMb9T9",
      "5gfqG3Xcopscta3st",
      "GNhMPAWcfBCASy8e6",
      "uXH4r6MmKPedk8rMA",
      "Gg9a4y8reWKtLe3Tn",
      "bBdfbWfWxHN9Chjcq",
      "sT6NxFxso6Z9xjS7o",
      "k9dsbn8LZ6tTesDS3",
      "exa5kmvopeRyfJgCy",
      "YTJp5WBcktBimdxBG",
      "X79Rc5cA5mSWBexnd",
      "SvKpaPbZ2tibeDpgh",
      "rQKstXH8ZMAdN5iqD",
      "vQKbgEKjGZcpbCqDs",
      "Z9cbwuevS9cqaR96h",
      "pHHaNkG8xDcaq5DJF",
      "sjRG35aq5fosJ6mdG",
      "pPWiLGsWCtN92vLwu",
      "D5BP9CxKHkcjA7gLv",
      "57sq9qA3wurjres4K",
      "t2LGSDwT7zSnAGybG",
      "7Pq9KwZhG6vejmYpo",
      "g3PwPgcdcWiP33pYn",
      "zcriHTKgKNehSSdyG",
      "kvLPC5YWgSujcHSkY",
      "HnC29723hm6kJT7KP",
      "CRiJuJxgArjBMJLvK",
      "dyJfGeWo5GX2u6NGi",
      "QLmSFeFexgTLsNeeA",
      "kmT47aLQmqzcw329Y",
      "givHhuPu6G43g8kWN",
      "83DimRqppcaoyYAsy",
      "vvzfFcbmKgEsDBRHh",
      "FfNEt8mpi6qanNmXg",
      "MrAfiomDNWCzxjei5",
      "73kwTFKgi4AagxFHJ",
      "iBBK4j6RWC7znEiDv",
      "W8vSrHAM9qoWdzFoP",
      "Rx9GLepCxctXDqCPc",
      "4X9JLr2SpB6v68twG",
      "yxTP9FckrwoMjxPc4",
      "FuZ7MoR3dJEJuoRbN",
      "xRyLxfytmLFZ6qz5s",
      "mwGAyWmsSqzMz4WMd",
      "xxC3Ka7axphW8kJ9E",
      "KT8Mf3ey6uwQAkWek",
      "GDT6tKH5ajphXHGny",
      "ZXaRHHLsxaTTQQsZb",
      "CHdsSaQGAvtkXBzmJ",
      "HAEPbGaMygJq8L59k",
      "SmDziGM9hBjW9DKmf",
      "8NKu9WES7KeKRWEKK",
      "NfdHG6oHBJ8Qxc26s",
      "LTtNXM9shNM9AC2mp",
      "uKp6tBFStnsvrot5t",
      "baTWMegR42PAsH9qJ",
      "Xqcorq5EyJBpZcCrN",
      "7cAsBPGh98pGyrhz9",
      "ZbgCx2ntD5eu8Cno9",
      "9kcTNWopvXFncXgPy",
      "HxWdXMqoQtjDhhNGA",
      "xwBuoE9p8GE7RAuhd",
      "inedT6KkbLSDwZvfd",
      "sWLLdG6DWJEy3CH7n",
      "dhj9dhiwhq3DX6W8z",
      "yLLkWMDbC9ZNKbjDG",
      "P3Yt66Wh5g7SbkKuT",
      "brXr7PJ2W4Na2EW2q",
      "45mNHCMaZgsvfDXbw",
      "7izSBpNJSEXSAbaFh",
      "pfoZSkZ389gnz5nZm",
      "jfG6vdJZCwTQmG7kb",
      "sGnPTfjE5JthAStqg",
      "gvA4j8pGYG4xtaTkw",
      "PZtsoaoSLpKjjbMqM",
      "jnDibtfvWNHLucf4D",
      "GrtbTAPfkJa4D6jjH",
      "zEWJBFFMvQ835nq6h",
      "64FdKLwmea8MCLWkE",
      "Dx9LoqsEh3gHNJMDk",
      "FMkQtPvzsriQAow5q",
      "XuLG6M7sHuenYWbfC",
      "PGv9THs68ArPur7yP",
      "NcGBmDEe5qXB7dFBF",
      "tEDXpFgsHsm5T8sWz",
      "7gsehrZnvXo2YGiT7",
      "x4n4jcoDP7xh5LWLq",
      "boBZkTqPdboX5u7g9",
      "CJw2tNHaEimx6nwNy",
      "CcC8MocynqKPmMPwL",
      "Rrt7uPJ8r3sYuLrXo",
      "rwjv8bZfSuE9ZAigH",
      "khYYedgupgrHonWNc",
      "wrkEnGrTTrM2mnmGa",
      "f9s7pHub6hbsX7YKT",
      "YduZEfz8usGbJXN4x",
      "55SHk8kh9dDvaDTCC",
      "SFG9Cm7mf5eP4juKs",
      "eLRSCC7r4KinuxqZX",
      "oW6mbA3XHzcfJTwNq",
      "kWMkDoy3izRTobZFe",
      "LtsJLfnP4YwhGdaCf",
      "w9kwayt5SWqBQe8Nx",
      "h5CGM5qwivGk2f5T9",
      "iPGpENE4ARKbzzQmt",
      "PQ3nutgxfTgvq69Xt",
      "3zZjF3YKJ257x79mu",
      "9Qwignbzu4ddXLTsT",
      "aiCtrN9EF2FjKz5sv",
      "JcpwEKbmNHdwhpq5n",
      "idipkijjz5PoxAwju",
      "F7RgpHHDpZYBjZGia",
      "xWTSHJASRaLABgHWc",
      "Fg8dtE8HHkDoiGcwt",
      "zPJE7MDtL25RpN7Cc",
      "qqhdj3W3vSfB5E9ss",
      "9SE67uz98kh6x2CxR",
      "gR6H3egpRPNYnoTrA",
      "qPoaA5ZSedivA4xJa",
      "H6L7fuEN9qXDanQ6W",
      "gfexKxsBDM6v2sCMo",
      "7uJnA3XDpTgemRH2c",
      "stb3Jjumzhv49zCEb",
      "XjMkPyaPYTf7LrKiT",
      "XuyRMxky6G8gq7a69",
      "huRxRzwcvwTzvtEPY",
      "8bWbNwiSGbGi9jXPS",
      "sq3WkpyqGANT7hGRP",
      "AyfDnnAdjG7HHeD3d",
      "WmfapdnpFfHWzkdXY",
      "8rYxw9xZfwy86jkpG",
      "zFhhDCxz87yKwqYQf",
      "doiMq8aH2yiZaCJsT",
      "MQzbaHoiQutiHkx2M",
      "ra9Pt2JkEDnKW4jsc",
      "9YDk52NPrfq7nqLvd",
      "KTEciTeFwL2tTujZk",
      "6bSjRezJDxR2omHKE",
      "r5H6YCmnn8DMtBtxt",
      "JbcWQCxKWn3y49bNB",
      "R4FX6wDmppvZ2JqpB",
      "9vnWFwng8QzEnBT8z",
      "XCtFBWoMeFwG8myYh",
      "6uwLq8kofo4Tzxfe2",
      "G993PFTwqqdQv4eTg",
      "DWgWbXRfXLGHPgZJM",
      "K7wtTqTEoKXC9Kb24",
      "hmai5Lru5kWXpH7Ju",
      "w4jjwDPa853m9P4ag",
      "xvAkpCSdqgtYhEceo",
      "6vMBpZtoRw4ia2JrK",
      "Wzjjynmp8gMmdX6dt",
      "CsN6WxwDnPzxAFhps",
      "CLXkgEerPi9MpJCem",
      "BKjJJH2cRpJcAnP7T",
      "qXtbBAxmFkAQLQEJE",
      "jES7mcPvKpfmzMTgC",
      "D7epkkJb3CqDTYgX9",
      "FpcgSoJDNNEZ4BQfj",
      "mF8dkhZF9hAuLHXaD",
      "camG6t6SxzfasF42i",
      "HALKHS4pMbfghxsjD",
      "HDXLTFnSndhpLj2XZ",
      "fgYQjTktBmNZvMqce",
      "fwNskn4dosKng9BCB",
      "B5auLtDfQrvwEkw4Q",
      "z7YvA5osMotdL5F4w",
      "Hoh6umyMWSqzPGMJZ",
      "vHSrtmr3EBohcw6t8",
      "nsCwdYJEpmW5Hw5Xm",
      "LKAXgTen4Xbqb8eZY",
      "22GrdspteQc8EonMn",
      "TSaJ9Zcvc3KWh3bjX",
      "sJK6HN5vTPPnuuNgQ",
      "mh3xapTix6fFtd3xM",
      "JBnaLpsrYXLXjFocu",
      "uR8c2NPp4bWHQ5u45",
      "d4YGxMpzmvxknHfbe",
      "wcNEXDHowiWkRxDNv",
      "scNCmwaduCgJmCBYh",
      "LsXtcLyzyfGg3gT5R",
      "McN9BNtNcbYNfdCB5",
      "4tzEAgdbNTwB6nKyL",
      "sCFGEhwcB8MX3FQf5",
      "G4uMdBzgDsxMsTNmr",
      "34Gkqus9vusXRevR8",
      "7MCqRnZzvszsxgtJi",
      "HXxHcRCxR4oHrAsEr",
      "cmrtpfG7hGEL9Zh9f",
      "oHk9T3jbx2J5zJ39P",
      "sYt3ZCrBq2QAf3rak",
      "r8stxYL29NF9w53am",
      "zymnWfGwf6BdDt64c",
      "yyDrMYBfvYtKbmPmm",
      "4gevjbK77NQS6hybY",
      "jnjjzkH8Fdzg4D6EK",
      "XKfQF73YnyMRiRf9a",
      "gYfgWSxCpFdk2cZfE",
      "CQsEwAyJP6NYvKZw6",
      "JiLcxpWzCrnwkndsT",
      "gpk8dARHBi7Mkmzt9",
      "GrbeyZzp6NwzSWpds",
      "9MZdwQ7u53oaRiBYX",
      "gFyJgnu5vAbzELBM8",
      "ouQNu3hhfKLBRuwR7",
      "m5AH78nscsGjMbBwv",
      "oKYWbXioKaANATxKY",
      "cq5x4XDnLcBrYbb66",
      "KjdP2WjWng6skwbY7",
      "wfpdejMWog4vEDLDg",
      "7F5jo5LD9FD7DpxCX",
      "kDjKF2yFhFEWe4hgC",
      "pWi5WmvDcN4Hn7Bo6",
      "NGc3Yjecg9pDMznWq",
      "xxvKhjpcTAJwvtbWM",
      "DJnvFsZ2maKxPi7v7",
      "zo9zKcz47JxDErFzQ",
      "fyZBtNB3Ki3fM4a6Y",
      "H4kadKrC2xLK24udn",
      "BxersHYN2qcFoonwg",
      "Ck5cgNS2Eozc8mBeJ",
      "wr9dH2GjztvCz6pYX",
      "EzAt4SbtQcXtDNhHK",
      "syeBtmGoKvjJTH6sH",
      "eWqFy8wESHbxNod7i",
      "8cWMX6L8St8k9pPRC",
      "jP583FwKepjiWbeoQ",
      "rMfpnorsMoRwyn4iP",
      "TKk7rShf9d5ePN7vR",
      "fNJvYD6XqnX82i4jA",
      "r8aAqSBeeeMNRtiYK",
      "Gh2qQHrCg3teQen3c",
      "3GAnfeG9KmsbsWeTj",
      "JKgGvJCzNoBQss2bq",
      "JjGs6mDZxeCWkg3ii",
      "AzKx6EjaoaMuk595v",
      "duAkuSqJhGDcfMaTA",
      "pXLqpguHJzxSjDdx7",
      "FbJYEn6eWA5JnGeGP",
      "8GiTowD6XqTNzgCz7",
      "qfDgEreMoSEtmLTws",
      "96N8BT9tJvybLbn5z",
      "SCs4KpcShb23hcTni",
      "bDMoMvw2PYgijqZCC",
      "nqwzrpkPvviLHWXaE",
      "YuZXRxWSqaCoZHEXr",
      "6YYmkpumigAmh3efu",
      "SgszmZwrDHwG3qurr",
      "9EyzaH3jzH3PyQtM5",
      "eR7Su77N2nK3e5YRZ",
      "GSBCw94DsxLgDat6r",
      "cpdsMuAHSWhWnKdog",
      "avvXAvGhhGgkJDDso",
      "KnPN7ett8RszE79PH",
      "ptmmK9PWgYTuWToaZ",
      "XNhfw5Bqsi4SGNNBk",
      "PKy8NuNPknenkDY74",
      "3yqf6zJSwBF34Zbys",
      "YpyW97jRbtvBAncAr",
      "LwcKYR8bykM6vDHyo",
      "H6hMugfY3tDQGfqYL",
      "iyRpsScBa6y4rduEt",
      "mLuQfS7gmfr4nwTdv",
      "TrvkWBwYvvJjSqSCj",
      "yXHcqrCpiHC5tDuEc",
      "HKfBeWN8ufNdFgzG6",
      "P8yeoeJ2bwmnD93mZ",
      "kxW6q5YdTGWh5sWby",
      "ksatPnddyZjHwZWwG",
      "st7DiQP23YQSxumCt",
      "tE7y8FZe7wSSzoRaS",
      "L4HQ3gnSrBETRdcGu",
      "eqxqgFxymP8hXDTt5",
      "uKWXktrR7KpbgZAs4",
      "h4vWsBBjASgiQ2pn6",
      "DXBziiT2RFLcmLY9J",
      "k42G2aaNhRNB7hdCJ",
      "XSKQLeQnBupFo7GGC",
      "BnDF5kejzQLqd5cjH",
      "AMmqk74zWmvP8tXEJ",
      "NQQzXpahhkb6f6ZCe",
      "Tk5ovpucaqweCu4tu",
      "9WX59u7g2sdKqnjDm",
      "Xht9swezkGZLAxBrd",
      "8c8AZq5hgifmnHKSN",
      "nMNi86hgNjaNnh8iu",
      "s3rAKTkdSHb6Hwwoz",
      "rqnbrJhDKCoZvNGEZ",
      "Ea8pt2dsrS6D4P54F",
      "uN3wjp2K6TEQ2oAML",
      "DAc4iuy4D3EiNBt9B",
      "jqCz2X49FRn5Bgb5b",
      "8hxvfZiqH24oqyr6y",
      "puYfAEJJomeodeSsi",
      "S54HKhxQyttNLATKu",
      "igSPcmvTigCHxWt8x",
      "4esQ684vtR9zcjHgW",
      "yGaw4NqRha8hgx5ny",
      "eHnupDgggBqDqT5eg",
      "k7oxdbNaGATZbtEg3",
      "bbGEiSmNiTpPrFhcQ",
      "Z6dmoLyfBdmo6HEss",
      "QcXuwQvvPkqcKZmXS",
      "7FJRnxbRtT7Sbzizs",
      "oBTkthd7h8sDpkiu2",
      "cmiRk9XtT9Psnd3Yr",
      "G6npMHwgRGSQDKavX",
      "hwxj4gieR7FWNwYfa",
      "yGycR8tFA3JJbvApp",
      "jxy7rBcQink8a7C9b",
      "vQNJrJqebXEWjJfnz",
      "kjmpq33kHg7YpeRYW",
      "FwYMuD2sNcaEpE5on",
      "4rwABGAd9kZG8nf2P",
      "GkXKvkLAcTm5ackCq",
      "TrmMcujGZt5JAtMGg",
      "gBpYo7mt2zNBmtBJd",
      "aNRYQFnMQbA7uu99u",
      "YMokuZdoY9tEDHjzv",
      "MG8Yhsxqu9JY4xRPr",
      "zEvqFtT4AtTztfYC4",
      "fzeoYhKoYPR3tDYFT",
      "8npC4KRcAJtGdErTq",
      "AYbhqi65SWzHzy7Xx",
      "N99KgncSXewWqkzMA",
      "2KacvW34BbXFmDBtQ",
      "tSgcorrgBnrCH8nL3",
      "NHuLAS3oKZWr2X9hP",
      "9hR2RmpJmxT8dyPo4",
      "fwSDKTZvraSdmwFsj",
      "Cf2zBkoocqcjnrNFD",
      "MPj7t2w3nk4s9EYYh",
      "TTPux7QFBpKxZtMKE",
      "shcSdHGPhnLQkpSbX",
      "M4w2rdYgCKctbADMn",
      "hMjFMSQZb4swKugfv",
      "mkrvsNi8cYGSjGqkh",
      "DXcezGmnBcAYL2Y2u",
      "Aq8BQMXRZX3BoFd4c",
      "FoJSa8mgLPT83g9e8",
      "Xt85tj6GQJCuuXT68",
      "JAAHjm4iZ2j5Exfo2",
      "sAiHxHkQrsYsRpKFP",
      "6phFYpNQH9SmWL9Jt",
      "Rkxj7TFxhbm59AKJh",
      "rNFzvii8LtCL5joJo",
      "Hw26MrLuhGWH7kBLm",
      "Zvu6ZP47dMLHXMiG3",
      "HByDKLLdaWEcA2QQD",
      "7qhtuQLCCvmwCPfXK",
      "FgjcHiWvADgsocE34",
      "Lp4Q9kSGsJHLfoHX3",
      "3xF66BNSC5caZuKyC",
      "BseaxjsiDPKvGtDrm",
      "Q924oPJzK92FifuFg",
      "oJwJzeZ6ar2Hr7KAX",
      "H7Rs8HqrwBDque8Ru",
      "gEKHX8WKrXGM4roRC",
      "FKB7iEergZaC7PvQf",
      "suxvE2ddnYMPJN9HD",
      "iETtCZcfmRyHp69w4",
      "mz3hwS4c9bc9EHAm9",
      "KFLdfuw35qkgjzWer",
      "RApxEu3A4GnvGoEe2",
      "XLbDQL2qYi9FDozvL",
      "p4XpZWcQksSiCPG72",
      "mB95aqTSJLNR9YyjH",
      "2NaAhMPGub8F2Pbr7",
      "BbM47qBPzdSRruY4z",
      "dYnHLWMXCYdm9xu5j",
      "qHpazCw3ryvBojGSa",
      "wyYubb3eC5FS365nk",
      "wmjPGE8TZKNLSKzm4",
      "CBWSDdzjqfnexBurB",
      "gBnSRErajRtvhMnDr",
      "BfBF6T6HA82zBxPrv",
      "dbDHEQyKqnMDDqq2G",
      "doPejjd84w8BmERqj",
      "PT8vSxsusqWuN7JXp",
      "dKxX76SCfCvceJXHv",
      "DSzpr8Y9299jdDLc9",
      "hnLutdvjC8kPScPAj",
      "vit9oWGj6WgXpRhce",
      "CsKboswS3z5iaiutC",
      "kjQXzkTGuixoJtQnq",
      "RgJicDmXHDxcJ9Fsw",
      "L6iFpR9ZyTmzHvYci",
      "Z5ZBPEgufmDsm7LAv",
      "PRAyQaiMWg2La7XQy",
      "x6Kv7nxKHfLGtPJej",
      "3pjv6uDvY9sqmsnvY",
      "Aet2mbnK7GDDfrEQu",
      "scL68JtnSr3iakuc6",
      "3SG4WbNPoP8fsuZgs",
      "XfpJ6WQBDcEcC8Mu4",
      "iprqfLaDLCGoJFeiZ",
      "frApEhpyKQAcFvbXJ",
      "znBJwbuT3f5eWgM4E",
      "cR7Zfrc4BtnFes46y",
      "hbmsW2k9DxED5Z4eJ",
      "SzecSPYxqRa5GCaSF",
      "hxaq9MCaSrwWPmooZ",
      "FSmPtu7foXwNYpWiB",
      "WQWhXzALcrzrJtqRh",
      "jYNT3Qihn2aAYaaPb",
      "gebzzEwn2TaA6rGkc",
      "WhHFvzFsYfMxgYCdo",
      "tjxgbovwc5Ft7wrtc",
      "2brqzQWfmNx5Agdrx",
      "QaDwBio8MLqRvTREH",
      "Jko7pt7MwwTBrfG3A",
      "A9tJFJY7DsGTFKKkh",
      "Wnqua6eQkewL3bqsF",
      "DJB82jKwgJE5NsWgT",
      "5b6YcFbEBCZbX6YSK",
      "zk6RK3xFaDeJHsoym",
      "FQqcejhNWGG8vHDch",
      "srge9MCLHSiwzaX6r",
      "DJRe5obJd7kqCkvRr",
      "D8ds9idKWbwzCseCh",
      "hTMFt3h7QqA2qecn7",
      "9LXxgXySTFsnookkw",
      "CHtwDXy63BsLkQx4n",
      "u5RLu5F3zKTB3Qjnu",
      "4tke3ibK9zfnvh9sE",
      "2WngsveoLhFubuLMH",
      "ADwayvunaJqBLzawa",
      "NG6FrXgmqPd5Wn3mh",
      "Ww5xKq5brC4xAJY7o",
      "HL6x8zHo9BkuK3tic",
      "PKBXczqhry7iK3Ruw",
      "oBBzqkZwkxDvsKBGB",
      "HuFZJkGptWDtRbkWs",
      "iQWk5jYeDg5ACCmpx",
      "RdpqsQ6xbHzyckW9m",
      "sizjfDgCgAsuLJQmm",
      "X3p8mxE5dHYDZNxCm",
      "wZGpoZgDANdkwTrwt",
      "uAc7bWgpEhrGwFcv7",
      "3nDR23ksSQJ98WNDm",
      "sMsvcdxbK2Xqx8EHr",
      "evYFijNMdjfbPaCho",
      "Psp8ZpYLCDJjshpRb",
      "Zupr296Zy74wpihXT",
      "68dHanLWsS6SEyZp9",
      "x9FNKTEt68Rz6wQ6P",
      "DWHkxqX4t79aThDkg",
      "xLm9mgJRPvmPGpo7Q",
      "6LzKRP88mhL9NKNrS",
      "XYDsYSbBjqgPAgcoQ",
      "eRohP4gbxuBuhqTbe",
      "Wpf3Gsa8A89mmjkk8",
      "PfcQguFpT8CDHcozj",
      "XPwEptSSFRCnfHqFk",
      "pohTfSGsNQZYbGpCy",
      "zcPLNNw4wgBX5k8kQ",
      "2meuc3kPRkBcRpj3R",
      "bzhGBHrGrFfQss4Df",
      "2269iGRnWruLHsZ5r",
      "kj37Hzb2MsALwLqWt",
      "Qz9GvoPbnFwGrHHQB",
      "pJJdcZgB6mPNWoSWr",
      "dtmmP4YdJEfK9y4Rc",
      "QPqm5aj2meRmE7kR8",
      "2oybbEw697CQgcRE5",
      "TYTEJxzeK3jBMq2TZ",
      "K4eDzqS2rbcBDsCLZ",
      "FcRt3xAF4ynojfj6G",
      "gMXsyhPiEJbGerF6F",
      "9sguwESkteCgqFMbj",
      "mvPfao35Moah8py46",
      "kuDKtwwbsksAW4BG2",
      "pL56xPoniLvtMDQ4J",
      "ENBzEkoyvdakz4w5d",
      "wM4bcDxEh75NDkhjo",
      "YAkpzvjC768Jm2TYb",
      "ExssKjAaXEEYcnzPd",
      "n3LAgnHg6ashQK3fF",
      "GMCs73dCPTL8dWYGq",
      "8gapy2nLy4wysXSGL",
      "dgFcJtHaYfaoByAK9",
      "HhWhaSzQr6xmBki8F",
      "CpvyhFy9WvCNsifkY",
      "aan3jPEEwPhrcGZjj",
      "mhA4vkeaRn9cpxkag",
      "iA25AvZqAr6G8mAXR",
      "C4tR3BEpuWviT7Sje",
      "FghubkDy6Dp6mnxk7",
      "RKz7pc6snBttndxXz",
      "jiJquD34sa9Lyo5wc",
      "c8EeJtqnsKyXdLtc5",
      "ZGGGBR9sDgtLgMDaA",
      "uM6mENiJi2pNPpdnC",
      "o9dnstYoc7cwpgdhg",
      "YSWa8rYeD3aDaofSP",
      "pC47ZTsPNAkjavkXs",
      "QtyKq4BDyuJ3tysoK",
      "bYrF8rXFYwPqnfxTp",
      "KbyRPCAsWv5GtfrbG",
      "c2RzFadrxkzyRAFXa",
      "9ZodFr54FtpLThHZh",
      "xmoYza9vgcRvWD5PA",
      "sbb9bZgojmEa7Yjrc",
      "6yTShbTdtATxKonY5",
      "BHYBdijDcAKQ6e45Z",
      "qGEqpy7J78bZh3awf",
      "KJbQyFbXiiYDDWbaS",
      "PYtus925Gcg7cqTEq",
      "yTvBSFrXhZfL8vr5a",
      "Aud7CL7uhz55KL8jG",
      "bXTNKjsD4y3fabhwR",
      "AmNjHo8xXMKnZEWRS",
      "CHD5m9fnosr7L3dto",
      "MN4NRkMw7ggt9587K",
      "CDXDnruBJe23rpdfC",
      "y5GftLezdozEHdXkL",
      "d6yNW5T6J9rtnGizc",
      "pT48swb8LoPowiAzR",
      "27AWRKbKyXuzQoaSk",
      "vNHf7dx5QZA4SLSZb",
      "KwbJFexa4MEdhJbs4",
      "mja6jZ6k9gAwki9Nu",
      "fW9n8bEuMpLwkxCx6",
      "muXfZr5EYCfZqLmsb",
      "5PBWgHiCiiJHjPRSn",
      "PAYMMgPi2L3MPP967",
      "RaxaXBNmStYe289gC",
      "DMxe4XKXnjyMEAAGw",
      "xF7gBJYsy6qenmmCS",
      "gMszBSAX23uqYhytR",
      "HbXXd2givHBBLxr3d",
      "Z5wF8mdonsM2AuGgt",
      "utySCY9nJt9xGYGGQ",
      "gCz7cB6JG66EhweSS",
      "krHDNc7cDvfEL8z9a",
      "aNAFrGbzXddQBMDqh",
      "sksP9Lkv9wqaAhXsA",
      "p3s8RvkcyTwzu27ps",
      "8ccTZ9ZxpJrvnxt4F",
      "p7WXmG6Fbo3eaSwm3",
      "CPBmbgYZpsGqkiz2R",
      "yDRX2fdkm3HqfTpav",
      "WbLAA8qZQNdbRgKte",
      "75dnjiD8kv2khe9eQ",
      "JZZENevaLzLLeC3zn",
      "MgFDzAfCku9MSDLuw",
      "PQtEqmyqHWDa2vf5H",
      "zbqLuTgTCu365MNu9",
      "P3uavjFmZD5RopJKk",
      "8gqrbnW758qjHFTrH",
      "pZaPhGg2hmmPwByHc",
      "4hLcbXaqudM9wSeor",
      "WxW6Gc6f2z3mzmqKs",
      "j9HoG56Y6KuopSzdn",
      "GhFoAxG49RXFzze5Y",
      "rD57ysqawarsbry6v",
      "LCfaLXcWnk8pujnX4",
      "tAXrD8Y6hcJ8dt6Nt",
      "af9MjBqF2hgu3EN6r",
      "FRRb6Gqem8k69ocbi",
      "LbyxFk8JmPKPAQBvL",
      "PHmYhE4sKnwzYgvkh",
      "fZJRxYLtNNzpbWZAA",
      "kgmkdf3C7EkDX7dnT",
      "Gs29k3beHiqWFZqnn",
      "MMAK6eeMCH3JGuqeZ",
      "cdB5f2adKoLGW8Ytc",
      "5e49dHLDJoDpeXGnh",
      "Ccsx339LE9Jhoii9K",
      "PHnMDhfiadQt6Gj23",
      "Jo89KvfAs9z7owoZp",
      "fri4HdDkwhayCYFaE",
      "tD9zEiHfkvakpnNam",
      "xggxWfyzZmnz7hydm",
      "JgBBuDf5uZHmpEMDs",
      "vbcjYg6h3XzuqaaN8",
      "hRohhttbtpY3SHmmD",
      "6KzFwcDy7hsCkzJKY",
      "F2DZXsMdhGyX4FPAd",
      "esRZaPXSHgWzyB2NL",
      "AqsjZwxHNqH64C2b6",
      "4psQW7vRwt7PE5Pnj",
      "voLHQgNncnjjgAPH7",
      "aaHDA4X6cTzFrvuSX",
      "LHtMNz7ua8zu4rSZr",
      "zjMKpSB2Xccn9qi5t",
      "BAzCGCys4BkzGDCWR",
      "goC9qv4PWf2cjfnbm",
      "Z2CuyKtkCmWGQtAEh",
      "c3iQryHA4tnAvPZEv",
      "vwLxd6hhFvPbvKmBH",
      "Js34Ez9nrDeJCTYQL",
      "fJvjin8ETkzhFdadC",
      "W59Nb72sYJhMJKGB8",
      "xiPMaYGTm2xfsB8WF",
      "oPEWyxJjRo4oKHzMu",
      "PjfsbKrK5MnJDDoFr",
      "sBBGxdvhKcppQWZZE",
      "vwM7hnT9ysE3suwfk",
      "BzYmJYECAc3xyCTt6",
      "uiyWHaTrz3ML7JqDX",
      "vZssZr2wq7YrG3FMa",
      "73QyjLymEak4L8RDC",
      "6vcxuRHzeM99jYcYd",
      "bG4PR9uSsZqHg2gYY",
      "HoQ5Rp7Gs6rebusNP",
      "9iA87EfNKnREgdTJN",
      "QEYWkRoCn4fZxXQAY",
      "kAgJJa3HLSZxsuSrf",
      "FZaDFYbnRoHmde7F6",
      "BNfL58ijGawgpkh9b",
      "4gDbqL3Tods8kHDqs",
      "DwqgLXn5qYC7GqExF",
      "atcJqdhCxTZiJSxo2",
      "zRn6cLtxyNodudzhw",
      "P32AuYu9MqM2ejKKY",
      "K2JBqDeETX2yEgyyZ",
      "3FoMuCLqZggTxoC3S",
      "LcEzxX2FNTKbB6KXS",
      "o5F2p3krzT4JgzqQc",
      "cy3BhHrGinZCp3LXE",
      "zsG9yKcriht2doRhM",
      "WYmmC3W6ZNhEgAmWG",
      "EL4HNa92Z95FKL9R2",
      "EKu66pFKDHFYPaZ6q",
      "Pa5NqtxHBkGuCh98G",
      "JKj5Krff5oKMb8TjT",
      "vwt3wKXWaCvqZyF74",
      "4basF9w9jaPZpoC8R",
      "Bfq6ncLfYdtCb6sat",
      "jDQm7YJxLnMnSNHFu",
      "FDJnZt8Ks2djouQTZ",
      "f3o9ydY7iPjFF2fyk",
      "KnQs55tjxWopCzKsk",
      "Ww2dxwWpSfkQB4NZb",
      "ZawRiFR8ytvpqfBPX",
      "ZGzDNfNCXzfx6hYAH",
      "rFjhz5Ks685xHbMXW",
      "Mrz2srZWc7EzbADSo",
      "B4DuwmtqF3HhNwvua",
      "zQKgKjecvR4W7oJw5",
      "BSpdshJWGAW6TuNzZ",
      "JHcTP4Ad8QAmRTCZm",
      "GGn8MBiY8Xz6NdNdH",
      "hQysqfSEzciRazx8k",
      "AtfQFj8umeyBBkkxa",
      "r99tazGiLgzqFX7ka",
      "uFYQaGCRwt3wKtyZP",
      "BFamedwSgRdGGKXQQ",
      "teaxCFgtmCQ3E9fy8",
      "ka8eveZpT7hXLhRTM",
      "euJm4RwkAptZnP89i",
      "LLRtjkvh9AackwuNB",
      "yPLr2tnXbiFXkMWvk",
      "ervaGwJ2ZcwqfCcLx",
      "4AHXDwcGab5PhKhHT",
      "NuueGqPZdotjMQKLu",
      "qjSHfbjmSyMnGR9DS",
      "xtzvtJBNofk4FPAtt",
      "SkcM4hwgH3AP6iqjs",
      "Br4xDbYu4Frwrb64a",
      "HvcZmKS43SLCbJvRb",
      "BEtzRE2M5m9YEAQpX",
      "EhEZoTFzys9EDmEXn",
      "bmoQ2wy7Nd7EiJdpg",
      "pYcFPMBtQveAjcSfH",
      "zb3hWt99i9Fm93KPq",
      "W9rJv26sxs4g2B9bL",
      "Dod9AWz8Rp4Svdpof",
      "hQHuXuRGZxxWXaPgg",
      "zB3ukZJqt3pQDw9jz",
      "KheBaeW8Pi7LwewoF",
      "Ek7M3xGAoXDdQkPZQ",
      "guDcrPqLsnhEjrPZj",
      "7XbcDaeigMaxW43EB",
      "ttGbpJQ8shBi8hDhh",
      "wJnm5cBiZGmKn595f",
      "puhPJimawPuNZ5wAR",
      "eoHbneGvqDu25Hasc",
      "gHgs2e2J5azvGFatb",
      "x5ASTMPKPowLKpLpZ",
      "EhAbh2pQoAXkm9yor",
      "jfq2BH5kfQqu2vYv3",
      "Mf2MCkYgSZSJRz5nM",
      "mXgsd5o9uuYaQKHMz",
      "YM6Qgiz9RT7EmeFpp",
      "PcfHSSAMNFMgdqFyB",
      "uX3HjXo6BWos3Zgy5",
      "nzmCvRvPm4xJuqztv",
      "CMt3ijXYuCynhPWXa",
      "Ndtb22KYBxpBsagpj",
      "yFJ7vCjefBxnTchmG",
      "SQ9cZtfrzDJmw9A2m",
      "PJLABqQ962hZEqhdB",
      "HmfxSWnqnK265GEFM",
      "i3BTagvt3HbPMx6PN",
      "ZEgQGAjQm5rTAnGuM",
      "ctpkTaqTKbmm6uRgC",
      "qEweugBipR5P2cMyK",
      "xnPFYBuaGhpq869mY",
      "YtvZxRpZjcFNwJecS",
      "ido3qfidfDJbigTEQ",
      "85J8hjEn48FicYfvp",
      "N6vZEnCn6A95Xn39p",
      "tJQsxD34maYw2g5E4",
      "96TBXaHwLbFyeAxrg",
      "ixZLTmFfnKRbaStA5",
      "2x7fwbwb35sG8QmEt",
      "oaqKjHbgsoqEXBMZ2",
      "t2NN6JwMFaqANuLqH",
      "J9pNx22bj5RuiRjAj",
      "AN2cBr6xKWCB8dRQG",
      "G5eMM3Wp3hbCuKKPE",
      "y5jAuKqkShdjMNZab",
      "vADtvr9iDeYsCDfxd",
      "x4GmqcwjFTnWeRiud",
      "5ntgky9ShzKKWu7us",
      "z8usYeKX7dtTWsEnk",
      "3S4nyoNEEuvNsbXt8",
      "EEv9JeuY5xfuDDSgF",
      "ASpGaS3HGEQCbJbjS",
      "AXXaXJvf7WcTessog",
      "QL7J9wmS6W2fWpofd",
      "osYFcQtxnRKB4F4HA",
      "MajyZJrsf8fAywWgY",
      "bvqC4Ci7rXq4sN9df",
      "GctJD5oCDRxCspEaZ",
      "A9NxPTwbw6r6Awuwt",
      "dKTh9Td3KaJ8QW6gw",
      "oTX2LXHqXqYg2u4g6",
      "LuXb6CZG4x7pDRBP8",
      "hamma4XgeNrsvAJv5",
      "BfTW9jmDzujYkhjAb",
      "DoHcgTvyxdorAMquE",
      "EbFABnst8LsidYs5Y",
      "Sdx6A6yLByRRs8iLY",
      "qbHLGo5vu8HD3JqEM",
      "48WeP7oTec3kBEada",
      "LgavAYtzFQZKg95WC",
      "5QpufhoH2ASnppsjs",
      "Kz9zMgWB5C27Pmdkh",
      "qy5dF7bQcFjSKaW58",
      "wkuDgmpxwbu2M2k3w",
      "JcpzFpPBSmzuksmWM",
      "zMxrkFrB6ka4Lb7fM",
      "PX7AdEkpuChKqrNoj",
      "ui6mDLdqXkaXiDMJ5",
      "uXn3LyA8eNqpvdoZw",
      "FwiPfF8Woe5JrzqEu",
      "hzuSDMx7pd2uxFc5w",
      "mHqQxwKuzZS69CXX5",
      "yKXKcyoBzWtECzXrE",
      "zHS4FJhByRjqsuH4o",
      "a5JAiTdytou3Jg749",
      "HEn2qiMxk5BggN83J",
      "tYAvXXgSwHCzNTK8f",
      "WXvt8bxYnwBYpy9oT",
      "kLR5H4pbaBjzZxLv6",
      "CtXaFo3hikGMWW4C9",
      "4DBBQkEQvNEWafkek",
      "qwdupkFd6kmeZHYXy",
      "EHbJ69JDs4suovpLw",
      "w5F4w8tNZc6LcBKRP",
      "xqkGmfikqapbJ2YMj",
      "yRAo2KEGWenKYZG9K",
      "scwoBEju75C45W5n3",
      "qJgz2YapqpFEDTLKn",
      "aSQy7yHj6nPD44RNo",
      "Ltey8BS83qSkd9M3u",
      "9Yc7Pp7szcjPgPsjf",
      "hN2aRnu798yas5b2k",
      "ERWeEA8op6s6tYCKy",
      "yJfBzcDL9fBHJfZ6P",
      "BZ6XaCwN4QGgH9CxF",
      "3nMpdmt8LrzxQnkGp",
      "TNHQLZK5pHbxdnz4e",
      "F6ZTtBXn2cFLmWPdM",
      "neQ7eXuaXpiYw7SBy",
      "k2SNji3jXaLGhBeYP",
      "WsSybGTqpBoHpXJyQ",
      "jtMXj24Masrnq3SpS",
      "jqTeghCJ2anMHPPjG",
      "B7P97C27rvHPz3s9B",
      "uK6sQCNMw8WKzJeCQ",
      "hurF9uFGkJYXzpHEE",
      "xEHy9oivifjgFbnvc",
      "33KewgYhNSxFpbpXg",
      "c5GHf2kMGhA4Tsj4g",
      "dC7mP5nSwvpL65Qu5",
      "hpjou9ZnLZkSJR7sd",
      "bshZiaLefDejvPKuS",
      "AvjbBjAAbKBk73v5F",
      "XqvnWFtRD2keJdwjX",
      "KJ9MFBPwXGwNpadf2",
      "37sHjeisS9uJufi4u",
      "5iZTwGHv2tNfFmeDa",
      "gziZACDg6EBpGZbJe",
      "RYcoJdvmoBbi5Nax7",
      "9o3QBg2xJXcRCxGjS",
      "vs3kzjLhbdKsndnBy",
      "bZ2w99pEAeAbKnKqo",
      "bjjbp5i5G8bekJuxv",
      "vwqLfDfsHmiavFAGP",
      "Yp2vYb4zHXEeoTkJc",
      "z6QQJbtpkEAX3Aojj",
      "ubPAo3zGeJNqtZDqT",
      "pfibDHFZ3waBo6pAc",
      "cumc876woKaZLmQs5",
      "Ty2tjPwv8uyPK9vrz",
      "ZiQqsgGX6a42Sfpii",
      "ybYBCK9D7MZCcdArB",
      "pNcFYZnPdXyL2RfgA",
      "rEBXN3x6kXgD4pLxs",
      "no5jDTut5Byjqb4j5",
      "qCsxiojX7BSLuuBgQ",
      "uyBeAN5jPEATMqKkX",
      "aHaqgTNnFzD7NGLMx",
      "bQ6zpf6buWgP939ov",
      "mkbGjzxD8d8XqKHzA",
      "CKpByWmsZ8WmpHtYa",
      "midXmMb2Xg37F2Kgn",
      "reitXJgJXFzKpdKyd",
      "LFNXiQuGrar3duBzJ",
      "KcvJXhKqx4itFNWty",
      "RWu8eZqbwgB9zaerh",
      "EFQ3F6kmt4WHXRqik",
      "FfPukic3Qskd9ZAkk",
      "A2Qam9Bd9xpbb2wLQ",
      "t9svvNPNmFf5Qa3TA",
      "n5TqCuizyJDfAPjkr",
      "Kbm6QnJv9dgWsPHQP",
      "gFMH3Cqw4XxwL69iy",
      "Kyc5dFDzBg4WccrbK",
      "RWo4LwFzpHNQCTcYt",
      "vbWBJGWyWyKyoxLBe",
      "PsEppdvgRisz5xAHG",
      "tscc3e5eujrsEeFN4",
      "GG2rtBReAm6o3mrtn",
      "E4cKD9iTWHaE7f3AJ",
      "yCWPkLi8wJvewPbEp",
      "AcKRB8wDpdaN6v6ru",
      "LbrPTJ4fmABEdEnLf",
      "rtM3jFaoQn3eoAiPh",
      "eDicGjD9yte6FLSie",
      "xg3hXCYQPJkwHyik2",
      "bJ2haLkcGeLtTWaD5",
      "PBRWb2Em5SNeWYwwB",
      "7hFeMWC6Y5eaSixbD",
      "aMHq4mA2PHSM2TMoH",
      "wpZJvgQ4HvJE2bysy",
      "2brqzQWfmNx5Agdrx",
      "GLMFmFvXGyAcG25ni",
      "NLBbCQeNLFvBJJkrt",
      "bYrF8rXFYwPqnfxTp",
      "v7c47vjta3mavY3QC",
      "3MvaoZbGPxtRFCijw",
      "TappK5n3kZmQzWEWD",
      "tSemJckYr29Gnxod2",
      "WdkLDpBGMCWhfByAY",
      "EctieqKwDQcQHhqZy",
      "hNqte2p48nqKux3wS",
      "qw3Z79HELMsmLkL9F",
      "zwDz9pgT43fRczkB4",
      "Fafzj3wMvoCW4WjeF",
      "kxW6q5YdTGWh5sWby",
      "G5eMM3Wp3hbCuKKPE",
      "kSiT2XjfTnDHKx44W",
      "DSzpr8Y9299jdDLc9",
      "wZGpoZgDANdkwTrwt",
      "qajfiXo5qRThZQG7s",
      "rRzZzBBQ36CrqhZTY",
      "aP36QcAsxyuEispq6",
      "TxcRbCYHaeL59aY7E",
      "MFNJ7kQttCuCXHp8P",
      "PQ3nutgxfTgvq69Xt",
      "JJFphYfMsdFMuprBy",
      "ythFNoiAotjvuEGkg",
      "GZSzMqr8hAB2dR8pk",
      "BBQ5HEnL3ShefQxEj",
      "fzeoYhKoYPR3tDYFT",
      "bXuAXCbzw9hsJSuEN",
      "mbCccXJuuRBZdXdpH",
      "m7THsgXyxxiEXgyHv",
      "xtHd6sfdr2bZHa6Pb",
      "pfaTqpWFghfrbvzaD",
      "u8GMcpEN9Z6aQiCvp",
      "gBpYo7mt2zNBmtBJd",
      "rkpDX7j7va6c8Q7cZ",
      "NGkBfd8LTqcpbQn5Z",
      "GEPX7jgLMB8vR2qaK"
    ]
  },
  locale: "en-US",
  mapbox: {
    apiKey: "pk.eyJ1IjoiaGFicnlrYSIsImEiOiJjaWxvcnhidzgwOGlodHJrbmJ2bmVmdjRtIn0.inr-_5rWOOslGQxY8iDFOA"
  },
  petrov: {
    afterTime: 1727400080403,
    beforeTime: 1727376805595,
    petrovPostId: "6LJ6xcHEjKF9zWKzs",
    petrovServerUrl: "https://forum.effectivealtruism.org/graphql",
    petrovGamePostId: "KTEciTeFwL2tTujZk"
  },
  reacts: {
    addNewReactKarmaThreshold: 10,
    downvoteExistingReactKarmaThreshold: 20,
    addNameToExistingReactKarmaThreshold: 5
  },
  stripe: {
    publicKey: "pk_live_51HtKAwA2QvoATZCZiy9f2nc6hA52YS1BE81cFu9FEV1IKar0Bwx6hIpxxxYHnhaxO9KM7kRYofZId3sUUI7Q0NeO00tGni3Wza"
  },
  algolia: {
    appId: "fakeAppId",
    searchKey: "fakeSearchKey",
    indexPrefix: "test_"
  },
  llmChat: {
    userIds: [
      "McgHKH6MMYSnPwQcm",
      "6Fx2vQtkYSZkaCvAg",
      "MEu8MdhruX5jfGsFQ",
      "YaNNYeR5HjKLDBefQ",
      "hBEAsEpoNHaZfefxR",
      "NFmcwmaFeTWfgrvBN",
      "ZnpELPxzzD2CiigNy",
      "Q7NW4XaWQmfPfdcFj",
      "NXeHNNSFHGESrYkPv",
      "QDNJ93vrjoaRBesk2",
      "iMBN2523tmh4Yicc3",
      "5iPRfSnjako6iM6LG",
      "aBHfQ4C5fSM4TPyTn",
      "n4M37rPXGyL6p8ivK",
      "e9ToWWzhwWp5GSE7P",
      "TCjNiBLBPyhZq5BuM",
      "XLwKyCK7JmC292ZCC",
      "S3ydcLKdejjkodNut",
      "ENgxBL95Sc7MRwYty",
      "KCExMGwS2ETzN3Ksr",
      "XGEcH5rmq4yGvD82A",
      "YFiFbXgjBpDKZT93g",
      "dZMo8p7fGCgPMfdfD",
      "Pdca6FNZBrXj9z28n",
      "LHbu27FubhwFv8ZJt",
      "gYxdDBQ3AZbde8HgZ",
      "5JqkvjdNcxwN8D86a",
      "6c2KCEXTGogBZ9KoE",
      "haTrhurXNmNN8EiXc",
      "cJnvyeYrotgZgfG8W"
    ]
  },
  logoUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/v1498011194/LessWrong_Logo_skglnw.svg",
  ckEditor: {
    uploadUrl: "https://39669.cke-cs.com/easyimage/upload/",
    webSocketUrl: "39669.cke-cs.com/ws"
  },
  recombee: {
    enabled: true
  },
  hasEvents: true,
  logRocket: {
    apiKey: "mtnxzn/lesswrong",
    sampleDensity: 5
  },
  reCaptcha: {
    apiKey: "6LfFgqEUAAAAAHKdMgzGO-1BRBhHw1x6_8Ly1cXc"
  },
  siteImage: "https://res.cloudinary.com/lesswrong-2-0/image/upload/v1654295382/new_mississippi_river_fjdmww.jpg",
  cloudinary: {
    cloudName: "lesswrong-2-0",
    uploadPresetBanner: "navcjwf7",
    uploadPresetGridImage: "tz0mgw2s",
    uploadPresetSocialPreview: "nn5tppry"
  },
  googleMaps: {
    apiKey: "AIzaSyA3C48rl26gynG3qIuNuS-3Bh_Zz9jFXkY"
  },
  adminAccount: {
    email: "team@lesswrong.com",
    username: "LessWrong"
  },
  annualReview: {
    end: "2024-02-01T08:00:00Z",
    start: "2023-12-04T00:10:00Z",
    reviewPhaseEnd: "2024-01-15T08:00:00Z",
    votingPhaseEnd: "2024-02-01T08:00:00Z",
    nominationPhaseEnd: "2023-12-17T08:00:00Z",
    votingResultsPostId: "TSaJ9Zcvc3KWh3bjX",
    announcementPostPath: "/posts/B6CxEApaatATzown6/the-lesswrong-2022-review",
    reviewWinnerSectionsInfo: {
      modeling: {
        tag: "World Modeling",
        order: 2,
        title: "World",
        coords: {
          leftXPct: 0.05,
          leftYPct: 0,
          rightXPct: 0.57,
          rightYPct: 0,
          middleXPct: 0.31,
          middleYPct: 0,
          leftFlipped: true,
          leftWidthPct: 0.26,
          rightWidthPct: 0.26,
          middleWidthPct: 0.26
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1708753450/ohabryka_Aquarelle_sketch_by_Thomas_W._Schaller_inspired_by_top_15ba02c3-b268-45f1-a780-322bbaa6fc22_eu9l0l.png"
      },
      "ai safety": {
        tag: "AI",
        order: 5,
        title: "Technical AI Safety",
        coords: {
          leftXPct: 0.2,
          leftYPct: 0.3,
          rightXPct: 0.554,
          rightYPct: 0.3,
          middleXPct: 0.467,
          middleYPct: 0.3,
          leftFlipped: false,
          leftWidthPct: 0.267,
          rightFlipped: true,
          middleFlipped: false,
          rightWidthPct: 0.267,
          middleWidthPct: 0.267
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,fl_progressive,q_auto/v1708570131/lwbot_topographic_watercolor_artwork_of_a_giant_robot_hand_gent_e4e9f305-9611-4787-8768-d7af3d702ed4_ta2ii9.png"
      },
      practical: {
        tag: "Practical",
        order: 3,
        title: "Practical",
        coords: {
          leftXPct: 0.2,
          leftYPct: 0.05,
          rightXPct: 0.634,
          rightYPct: 0.05,
          middleXPct: 0.417,
          middleYPct: 0.05,
          leftFlipped: false,
          leftWidthPct: 0.217,
          rightWidthPct: 0.217,
          middleWidthPct: 0.217
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1708974564/ohabryka_Aquarelle_sketch_by_Thomas_W._Schaller_inspired_by_top_4f6449e2-569b-48a3-b878-a400315b3ef0_hqutxe.png"
      },
      "ai strategy": {
        tag: "AI",
        order: 4,
        title: "AI Strategy",
        coords: {
          leftXPct: 0,
          leftYPct: 0,
          rightXPct: 0.66,
          rightYPct: 0,
          middleXPct: 0.33,
          middleYPct: 0,
          leftFlipped: false,
          leftWidthPct: 0.33,
          rightFlipped: true,
          middleFlipped: false,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1708753570/ohabryka_Aquarelle_sketch_by_Thomas_W._Schaller_inspired_by_top_8dda30ee-71d6-4b24-80c7-a8499a5b25c6_uacvgk.png"
      },
      rationality: {
        tag: "Rationality",
        order: 0,
        title: "Rationality",
        coords: {
          leftXPct: 0.12,
          leftYPct: 0,
          rightXPct: 0.72,
          rightYPct: 0,
          middleXPct: 0.42,
          middleYPct: 0,
          leftFlipped: false,
          leftWidthPct: 0.3,
          rightFlipped: true,
          rightWidthPct: 0.3,
          middleWidthPct: 0.3
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1708753260/ohabryka_Aquarelle_sketch_by_Thomas_W._Schaller_inspired_by_top_09275054-eb84-43c4-9cfa-4a05e1818c9e_rmov5i.png"
      },
      optimization: {
        tag: "World Optimization",
        order: 1,
        title: "Optimization",
        coords: {
          leftXPct: 0.1,
          leftYPct: 0.2,
          rightXPct: 0.7,
          rightYPct: 0.2,
          middleXPct: 0.4,
          middleYPct: 0.2,
          leftWidthPct: 0.33,
          rightFlipped: true,
          middleFlipped: false,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1708753382/ohabryka_Aquarelle_sketch_by_Thomas_W._Schaller_inspired_by_top_242eda7f-95a9-4c3b-8090-991a1b11286f_xcjhxq.png"
      }
    },
    reviewWinnerYearGroupsInfo: {
      2018: {
        tag: null,
        coords: {
          leftXPct: 0.01,
          leftYPct: 0.1,
          rightXPct: 0.72,
          rightYPct: 0.1,
          middleXPct: 0.34,
          middleYPct: 0.1,
          leftFlipped: false,
          leftWidthPct: 0.33,
          rightFlipped: false,
          middleFlipped: false,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1709008323/ruby37_green_on_white_aquarelle_sketch_by_thomas_schaller_of_ri_7a3fa89a-ac7a-466f-929f-b396cb4d9bd5_p8rh9t.png"
      },
      2019: {
        tag: null,
        coords: {
          leftXPct: 0.01,
          leftYPct: 0.1,
          rightXPct: 0.72,
          rightYPct: 0.1,
          middleXPct: 0.34,
          middleYPct: 0.1,
          leftFlipped: false,
          leftWidthPct: 0.33,
          rightFlipped: false,
          middleFlipped: false,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1709008331/ruby37_blue_on_white_aquarelle_sketch_by_thomas_schaller_of_gre_f421cc99-2bb5-4357-b164-d05c2f4fe84e_aib1co.png"
      },
      2020: {
        tag: null,
        coords: {
          leftXPct: 0.01,
          leftYPct: 0.01,
          rightXPct: 0.72,
          rightYPct: 0.01,
          middleXPct: 0.34,
          middleYPct: 0.01,
          leftFlipped: false,
          leftWidthPct: 0.33,
          rightFlipped: false,
          middleFlipped: false,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1709008346/ruby37_aquarelle_sketch_of_futuristic_landscape_by_thomas_schal_f07d5805-9fb0-4dcc-9295-7f063624e28c_slcokh.png"
      },
      2021: {
        tag: null,
        coords: {
          leftXPct: 0.01,
          leftYPct: 0.1,
          rightXPct: 0.545,
          rightYPct: 0.1,
          middleXPct: 0.278,
          middleYPct: 0.1,
          leftFlipped: false,
          leftWidthPct: 0.267,
          rightFlipped: false,
          middleFlipped: false,
          rightWidthPct: 0.267,
          middleWidthPct: 0.267
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/a_270/q_auto,f_auto/ohabryka_Topographic_aquarelle_book_cover_by_Thomas_W._Schaller_f9c9dbbe-4880-4f12-8ebb-b8f0b900abc1_m4k6dy_734413"
      },
      2022: {
        tag: null,
        coords: {
          leftXPct: 0,
          leftYPct: 0.1,
          rightXPct: 0.79,
          rightYPct: 0.1,
          middleXPct: 0.43,
          middleYPct: 0.1,
          leftFlipped: false,
          leftWidthPct: 0.33,
          rightFlipped: true,
          rightWidthPct: 0.33,
          middleWidthPct: 0.33
        },
        imgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1709008351/ruby37_aquarelle_sketch_of_a_woman_focusing_hard_studying_in_an_2ac568ef-408e-4561-acc8-84c76bb42fba_gwt8uq.png"
      }
    },
    showReviewOnFrontPageIfActive: true
  },
  googleVertex: {
    enabled: false
  },
  intercomAppId: "wtb8z7sj",
  commentInterval: 15,
  googleDocImport: {
    enabled: true
  },
  moderationEmail: "team@lesswrong.com",
  timeDecayFactor: 1.15,
  googleTagManager: {
    apiKey: "GTM-TRC765W"
  },
  textReplacements: {
    "Less Wrong": "Down Bad",
    "Alignment Forum": "Standards Committee",
    "Artificial Intelligence": "Fake News"
  },
  alternateHomePage: false,
  gatherTownMessage: "Schelling social hours on Tues 1pm and Thurs 6pm PT",
  bookDisplaySetting: false,
  gardenOpenToPublic: false,
  karmaRewarderId100: "iqWr6C3oEB4yWpzn5",
  legacyRouteAcronym: "lw",
  maxRenderQueueSize: 3,
  recommendationsTab: {
    manuallyStickiedPostIds: []
  },
  frontpageScoreBonus: 0,
  karmaRewarderId1000: "mBBmKWkmw8bgJmGiG",
  lightconeFundraiser: {
    active: false,
    postId: "5n2ZQcbc7r4R8mvqc",
    paymentLinkId: "plink_1QPdGLBlb9vL5IMTvkJ3LZ6v",
    unsyncedAmount: 2082623.2,
    thermometerBgUrl: "https://res.cloudinary.com/lesswrong-2-0/image/upload/q_auto,f_auto,h_400/v1732869999/Group_1_b4ap4h.png",
    thermometerGoalAmount: 1000000,
    thermometerGoal2Amount: 2000000
  },
  defaultVisibilityTags: [
    {
      tagId: "Ng8Gice9KNkncxqcj",
      tagName: "Rationality",
      filterMode: 10
    },
    {
      tagId: "3uE2pXvbcnS9nnZRE",
      tagName: "World Modeling",
      filterMode: 10
    }
  ],
  enableGoodHeartProject: false,
  maxDocumentsPerRequest: 5000,
  defaultSequenceBannerId: "sequences/vnyzzznenju0hzdv6pqb.jpg",
  defaultModeratorComments: [
    {
      id: "FfMok764BCY6ScqWm",
      label: "Option A"
    },
    {
      id: "yMHoNoYZdk5cKa3wQ",
      label: "Option B"
    }
  ],
  newUserIconKarmaThreshold: 50,
  dialogueMatchmakingEnabled: true,
  hideUnreviewedAuthorComments: "2023-04-04T18:54:35.895Z",
  gatherTownUserTrackingIsBroken: true,
  postModerationWarningCommentId: "sLay9Tv65zeXaQzR4",
  commentModerationWarningCommentId: "LbGNE5Ssnvs6MYnLu",
  firstCommentAcknowledgeMessageCommentId: "QgwD7PkQHFp3nfhjj"
};
