import markdownIt from "markdown-it";
import markdownItContainer from "markdown-it-container";
import markdownItFootnote from "markdown-it-footnote";
import markdownItSub from "markdown-it-sub";
import markdownItSup from "markdown-it-sup";
import markdownItMathjax from './markdownMathjax';
import { markdownCollapsibleSections } from './markdownCollapsibleSections';

let _mdi: markdownIt|null = null;
export function getMarkdownIt(): markdownIt {
  if (!_mdi) {
    const mdi = markdownIt({linkify: true})
    mdi.use(markdownItMathjax())
    mdi.use(markdownItContainer as AnyBecauseHard, 'spoiler')
    mdi.use(markdownItFootnote as any)
    applyMarkdownFootnoteRules(mdi);
    mdi.use(markdownItSub)
    mdi.use(markdownItSup)
    mdi.use(markdownCollapsibleSections);
    _mdi = mdi;
  }
  return _mdi;
}

let _mdiNoMathjax: markdownIt|null = null;
export function getMarkdownItNoMathjax(): markdownIt {
  if (!_mdiNoMathjax) {
    // FIXME This is a copy-paste of a markdown config from conversionUtils that has gotten out of sync
    const mdi = markdownIt({ linkify: true });
    // mdi.use(markdownItMathjax()) // for performance, don't render mathjax
    mdi.use(markdownItContainer as AnyBecauseHard, "spoiler");
    mdi.use(markdownItFootnote as any);
    applyMarkdownFootnoteRules(mdi);
    mdi.use(markdownItSub);
    mdi.use(markdownItSup);
    _mdiNoMathjax = mdi;
  }
  return _mdiNoMathjax;
}

let _mdiArbital: markdownIt|null = null;
export function getMarkdownItArbital(): markdownIt {
  if (!_mdiArbital) {
    const mdi = markdownIt({linkify: true})
    mdi.use(markdownItMathjax())
    _mdiArbital = mdi;
  }
  return _mdiArbital;
}

let _mdiNoPlugins: markdownIt|null = null;
export function getMarkdownItNoPlugins(): markdownIt {
  if (!_mdiNoPlugins) {
    const mdi = markdownIt({linkify: true})
    _mdiNoPlugins = mdi;
  }
  return _mdiNoPlugins;
}


function applyMarkdownFootnoteRules(mdi: markdownIt) {
  // These rules were generated by starting from the rules in the source of
  // markdown-it-footnote (https://github.com/markdown-it/markdown-it-footnote/blob/master/index.mjs)
  // and modifying until they matched the classnames and format of our CkEditor
  // footnote plugin.
  mdi.renderer.rules.footnote_ref = (tokens, idx, options, env, self) => {
    const id = self.rules.footnote_anchor_name!(tokens, idx, options, env, self)
    const caption = self.rules.footnote_caption!(tokens, idx, options, env, self)
    let refid = id
  
    if (tokens[idx].meta.subId > 0) refid += `:${tokens[idx].meta.subId}`
  
    // The markdown-it-footnote default here was:
    //return `<sup class="footnote-ref"><a href="#fn${id}" id="fnref${refid}">${caption}</a></sup>`

    const footnoteIndex = Number(tokens[idx].meta.id + 1).toString()
    return `<span data-footnote-reference="" data-footnote-index="${footnoteIndex}" data-footnote-id="${id}" role="doc-noteref" id="fnref${id}" class="footnote-reference">
      <sup><a href="#fn${id}" class="">${caption}</a></sup>
    </span>`
  };
  mdi.renderer.rules.footnote_block_open = (tokens, idx, options) => {
    // The markdown-it-footnote default here was:
    //return (options.xhtmlOut ? '<hr class="footnotes-sep" />\n' : '<hr class="footnotes-sep">\n') +
    //  '<section class="footnotes">\n' +
    //  '<ol class="footnotes-list">\n'

    return '<ol data-footnote-section="" role="doc-endnotes" class="footnote-section footnotes">';
  };
  mdi.renderer.rules.footnote_block_close = () => {
    // The markdown-it-footnote default here was:
    //return '</ol>\n</section>\n'

    return '</ol>\n'
  };
  mdi.renderer.rules.footnote_open = (tokens, idx, options, env, self) => {
    let id = self.rules.footnote_anchor_name!(tokens, idx, options, env, self)

    if (tokens[idx].meta.subId > 0) id += `:${tokens[idx].meta.subId}`
  
    // The markdown-it-footnote default here was:
    //return `<li id="fn${id}" class="footnote-item">`
    const footnoteIndex = Number(tokens[idx].meta.id + 1).toString()
    return `<li data-footnote-item="" data-footnote-index="${footnoteIndex}" data-footnote-id="${id}" id="fn${id}" role="doc-endnote" class="footnote-item">`
  };
  mdi.renderer.rules.footnote_close = () => {
    return '</li>\n'
  };
  mdi.renderer.rules.footnote_anchor = (tokens, idx, options, env, self) => {
    let id = self.rules.footnote_anchor_name!(tokens, idx, options, env, self)
  
    if (tokens[idx].meta.subId > 0) id += `:${tokens[idx].meta.subId}`
  
    /* ↩ with escape code to prevent display as Apple Emoji on iOS */
    return ` <a href="#fnref${id}" class="footnote-backref">\u21a9\uFE0E</a>`
  };
  mdi.renderer.rules.footnote_anchor_name = (tokens, idx, options, env) => {
    const n = Number(tokens[idx].meta.id + 1).toString()
    let prefix = ''
  
    if (typeof env.docId === 'string') prefix = `-${env.docId}-`
  
    return prefix + n
  };
  mdi.renderer.rules.footnote_caption = (tokens, idx, options, env) => {
    let n = Number(tokens[idx].meta.id + 1).toString()
    if (tokens[idx].meta.subId > 0) n += `:${tokens[idx].meta.subId}`
    return `[${n}]`
  };
}
