name: 'Run migrations'
description: 'Run Postgres migrations'
inputs:
  mode:
    description: 'Migrations mode: one of dev, staging or prod'
    required: true
  credentials-repo:
    description: 'Github credentials repo name'
    required: true
  credentials-pat:
    description: 'Github personal access token for credentials repo'
    required: true
  transcrypt-secret:
    description: 'Transcrypt decryption key'
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment

    - name: Clone credentials
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.credentials-repo }}
        path: ForumCredentials
        token: ${{ inputs.credentials-pat }}
        persist-credentials: false

    - name: Install transcrypt
      uses: actions/checkout@v3
      with:
        repository: elasticdog/transcrypt
        path: transcrypt

    - name: Decrypt credentials
      shell: bash
      working-directory: ${{ github.workspace }}/ForumCredentials
      run: ${{ github.workspace }}/transcrypt/transcrypt -y -c aes-256-cbc -p ${{ inputs.transcrypt-secret }}

    - name: Type check
      shell: bash
      run: yarn tsc

    - name: Run migrations
      shell: bash
      env:
        FORUM_MAGNUM_MIGRATE_CI: 1
      run: yarn migrate up ${{ inputs.mode }}
