"use client";

import { useForumType } from '@/components/hooks/useForumType';
import React, { useState, useEffect, useRef } from 'react';
import { registerComponent } from '../../lib/vulcan-lib/components';
import { useOnNavigate } from '../hooks/useOnNavigate';
import { SearchBox, connectMenu } from 'react-instantsearch-dom';
import { SearchState } from 'react-instantsearch-core';
import classNames from 'classnames';
import CloseIcon from '@/lib/vendor/@material-ui/icons/src/Close';
import IconButton from '@/lib/vendor/@material-ui/core/src/IconButton';
import withErrorBoundary from '../common/withErrorBoundary';
import { getSearchIndexName, getSearchClient, isSearchEnabled } from '../../lib/search/searchUtil';
import qs from 'qs'
import { useSearchAnalytics } from '../search/useSearchAnalytics';
import { useCurrentUser } from './withUser';
import { useNavigate } from '../../lib/routeUtil';
import { InstantSearch } from '../../lib/utils/componentsWithChildren';
import { createPortal } from 'react-dom';
import SearchBarResults from "../search/SearchBarResults";
import ForumIcon from "./ForumIcon";
import { defineStyles } from '@/components/hooks/defineStyles';
import { useStyles } from '@/components/hooks/useStyles';
import { useGlobalKeydown } from './withGlobalKeydown';

const VirtualMenu = connectMenu(() => null);

const styles = defineStyles("SearchBar", (theme: ThemeType) => ({
  root: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 48,
    '& :focus': {
      outline: 'none',
    },
  },
  rootChild: {
    minWidth: 0,
    width: '100%',
  },
  searchInputArea: {
    display: "block",
    position: "relative",
    minWidth: 48,
    height: 48,

    "& .ais-SearchBox": {
      display: 'none',
      position: 'relative',
      flex: 1,
      minWidth: 0,
      height: 48,
      whiteSpace: 'nowrap',
      boxSizing: 'border-box',
      fontSize: 14,
    },
    "& .ais-SearchBox-form": {
      height: '100%'
    },
    "& .ais-SearchBox-submit":{
      display: "none"
    },
    // This is a class generated by React InstantSearch, which we don't have direct control over so
    // are doing a somewhat hacky thing to style it.
    "& .ais-SearchBox-input": {
      display:"none",

      height: "100%",
      width: "100%",
      paddingRight: 28,
      paddingLeft: 0,
      boxSizing: 'border-box',
      verticalAlign: "bottom",
      borderStyle: "none",
      boxShadow: "none",
      backgroundColor: "transparent",
      fontSize: 'inherit',
      "-webkit-appearance": "none",
      cursor: "text",
      borderRadius: 0,
    },
    "&.open": {
      width: 300,
      maxWidth: '100%',
      height: 'var(--header-height)',
    },
    "&.open .ais-SearchBox": {
      display: "inline-block",
    },
    "&.open .ais-SearchBox-input": {
      display:"inline-block",
    },
    [theme.breakpoints.down('sm')]: {
      "&.open": {
        width: 48,
      },
      "&.open .ais-SearchBox": {
        position: 'fixed',
        top: 'var(--header-height)',
        left: 0,
        width: '100%',
        height: 48,
        backgroundColor: theme.palette.panelBackground.default,
        boxShadow: theme.palette.boxShadow.searchResults,
        fontSize: 16,
      },
      "& .ais-SearchBox-input": {
        paddingLeft: 16,
        paddingRight: 48,
      },
    },
  },
  inputControls: {
    display: 'flex',
    alignItems: 'center',
    height: '100%',
  },
  backdrop: {
    display: 'none',
    position: "fixed",
    inset: 0,
    zIndex: 1,
    backgroundColor: theme.palette.greyAlpha(0.12),
    [theme.breakpoints.up('md')]: {
      display: 'block',
    },
  },
  activeInput: {
    zIndex: 2,
    backgroundColor: theme.palette.panelBackground.default,
    color: theme.palette.text.normal,
    "&&& .ais-SearchBox-input, &&& .ais-SearchBox-input::placeholder, &&& .SearchBar-searchIcon": {
      color: theme.palette.text.normal,
    },
    [theme.breakpoints.down('sm')]: {
      borderRadius: '4px 4px 0 0',
      "& $searchIconButton": {
        // Keep the active tab above the search field's shadow.
        position: 'relative',
        zIndex: 1,
        height: '100%',
        borderRadius: '4px 4px 0 0',
        backgroundColor: theme.palette.panelBackground.default,
        '&:hover': {
          backgroundColor: theme.palette.panelBackground.default,
        },
      },
    },
  },
  searchInputAreaSmall: {},
  searchIcon: {
    "--icon-size": "24px",
  },
  searchIconButton: {
    color: theme.palette.header.text ,
    flexShrink: 0,
  },
  searchIconButtonSmall: {},
  closeSearchIcon: {
    fontSize: 14,
  },
  searchBarClose: {
    display: "inline-block",
    position: "absolute",
    top: '50%',
    transform: 'translateY(-50%)',
    right: 5,
    cursor: "pointer",
    [theme.breakpoints.down('sm')]: {
      display: 'none',
    },
  },
  clearSearch: {
    display: 'none',
    [theme.breakpoints.down('sm')]: {
      display: 'inline-flex',
      position: 'fixed',
      top: 'var(--header-height)',
      right: 0,
      width: 48,
      height: 48,
      color: theme.palette.text.normal,
    },
  },
}))

const SearchBar = ({onSetIsActive, searchResultsArea}: {
  onSetIsActive: (active: boolean) => void,
  searchResultsArea: React.RefObject<HTMLDivElement | null>,
}) => {
  const { isAF } = useForumType();
  const classes = useStyles(styles);
  const inputAreaRef = useRef<HTMLDivElement>(null);
  const currentUser = useCurrentUser()
  const [inputOpen,setInputOpen] = useState(false);
  const [searchState, setSearchState] = useState<SearchState>({query: ""});
  const currentQuery = searchState.query ?? "";
  useEffect(() => {
    if (inputOpen) inputAreaRef.current?.querySelector("input")?.focus();
  }, [inputOpen]);
  const navigate = useNavigate();
  const captureSearch = useSearchAnalytics();

  const handleSubmit = () => {
    navigate({pathname: `/search`, search: `?${qs.stringify({query: currentQuery})}`});
    closeSearch()
  }
  
  useOnNavigate(() => {
    closeSearch();
  });


  const closeSearch = () => {
    setInputOpen(false);
    setSearchState(previous => ({...previous, query: ""}));
    if (onSetIsActive)
      onSetIsActive(false);
  }

  const clearSearch = () => {
    setSearchState(previous => ({...previous, query: ""}));
    inputAreaRef.current?.querySelector('input')?.focus();
  };

  const handleSearchTap = () => {
    setInputOpen(true);
    if (onSetIsActive)
      onSetIsActive(true);
  }

  useGlobalKeydown((event) => {
    if (event.defaultPrevented || !isSearchEnabled() || event.isComposing
      || !(event.metaKey || event.ctrlKey) || event.altKey || event.shiftKey
      || event.key.toLowerCase() !== 'k') {
      return;
    }
    // Preserve rich-text editors' Cmd/Ctrl+K shortcut for inserting links.
    if (event.target instanceof HTMLElement && event.target.isContentEditable) {
      return;
    }
    event.preventDefault();
    if (event.repeat) return;
    if (inputOpen) {
      closeSearch();
    } else {
      handleSearchTap();
    }
  });

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.defaultPrevented || event.nativeEvent.isComposing) return;
    if (inputOpen && !event.altKey && !event.ctrlKey && !event.metaKey && !event.shiftKey
      && (event.key === 'ArrowDown' || event.key === 'ArrowUp')) {
      const input = inputAreaRef.current?.querySelector('input');
      const results = Array.from(searchResultsArea.current?.querySelectorAll<HTMLAnchorElement>(
        '[data-search-result] a[href]'
      ) ?? []).filter(result => result.getClientRects().length > 0);
      const currentIndex = results.findIndex(result => result === event.target);
      if (event.target === input || currentIndex !== -1) {
        event.preventDefault();
        event.stopPropagation();
        if ((event.key === 'ArrowUp' && currentIndex === 0)
          || (event.key === 'ArrowDown' && currentIndex === results.length - 1)) {
          input?.focus();
        } else {
          const nextIndex = currentIndex === -1
            ? (event.key === 'ArrowDown' ? 0 : results.length - 1)
            : currentIndex + (event.key === 'ArrowDown' ? 1 : -1);
          results[nextIndex]?.focus({preventScroll: true});
        }
      }
    }
    if (event.key === 'Escape') {
      event.preventDefault();
      event.stopPropagation();
      closeSearch();
    }
    if (event.key === "Enter" && event.target instanceof HTMLInputElement) {
      event.preventDefault();
      handleSubmit();
    }
  }

  useEffect(() => {
    if (currentQuery) {
      captureSearch("searchBar", {query: currentQuery});
    }
  }, [currentQuery, captureSearch])
  if (!isSearchEnabled()) {
    return <div>Search is disabled (ElasticSearch not configured on server)</div>
  }

  return <div className={classes.root} onKeyDown={handleKeyDown}>
    <div className={classes.rootChild}>
      <InstantSearch
        indexName={getSearchIndexName("Posts")}
        searchClient={getSearchClient({emptyStringSearchResults: "default"})}
        searchState={searchState}
        onSearchStateChange={setSearchState}
      >
        {inputOpen && <div className={classes.backdrop} onClick={closeSearch} aria-hidden="true" />}
        <div ref={inputAreaRef} className={classNames(
          classes.searchInputArea,
          {"open": inputOpen, [classes.activeInput]: inputOpen},
          {[classes.searchInputAreaSmall]: !currentUser}
        )}>
          {isAF && <VirtualMenu attribute="af" defaultRefinement="true" />}
          <div className={classes.inputControls}>
            <IconButton
              aria-label="Search"
              aria-expanded={inputOpen}
              onClick={inputOpen ? closeSearch : handleSearchTap}
              onFocus={(event) => {
                if (event.currentTarget.matches(':focus-visible')) handleSearchTap();
              }}
              className={classNames(classes.searchIconButton, {[classes.searchIconButtonSmall]: !currentUser})}>
              <ForumIcon icon="Search" className={classes.searchIcon} />
            </IconButton>
            {/* Ignored because SearchBox is incorrectly annotated as not taking null for its reset prop, when
              * null is the only option that actually suppresses the extra X button.
             // @ts-ignore */}
            <SearchBox reset={null} focusShortcuts={[]} autoFocus={inputOpen} />
          </div>
          {inputOpen && <IconButton aria-label="Clear search" className={classes.clearSearch} onClick={clearSearch}>
            <CloseIcon className={classes.closeSearchIcon}/>
          </IconButton>}
          { inputOpen && <div className={classes.searchBarClose} onClick={closeSearch}>
            <CloseIcon className={classes.closeSearchIcon}/>
          </div>}
          <div>
            {searchResultsArea.current && createPortal(
              <SearchBarResults closeSearch={closeSearch} currentQuery={currentQuery} open={inputOpen} />,
              searchResultsArea.current
            )}
          </div>
        </div>
      </InstantSearch>
    </div>
  </div>
}

export default registerComponent("SearchBar", SearchBar, {
  hocs: [withErrorBoundary],
  areEqual: "auto",
});
