CREATE DATABASE IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.raw_events_typed_v1 (
  schema_version UInt16,
  event_id String,
  source_id Nullable(Int64),
  event_time DateTime64(6, 'UTC'),
  received_at Nullable(DateTime64(6, 'UTC')),
  environment LowCardinality(String),
  event_type LowCardinality(String),
  event_json String CODEC(ZSTD(3)),
  content_hash FixedString(64) CODEC(ZSTD(3)),
  extractor_version UInt32,
  extractor_fingerprint FixedString(64),
  properties_hash FixedString(64) CODEC(ZSTD(3)),
  payload_layout LowCardinality(String),
  property_present Array(LowCardinality(String)),
  property_null Array(LowCardinality(String)),
  property_invalid Array(LowCardinality(String)),
  property_out_of_scope Array(LowCardinality(String)),
  property_conflicts Array(LowCardinality(String)),
  property_normalized Array(LowCardinality(String)),
  property_sources Map(String, String),
  user_id Nullable(String),
  client_id Nullable(String),
  tab_id Nullable(String),
  session_id Nullable(String),
  post_id Nullable(String),
  comment_id Nullable(String),
  document_id Nullable(String),
  document_type Nullable(String),
  collection_name Nullable(String),
  tag_id Nullable(String),
  sequence_id Nullable(String),
  user_id_displayed Nullable(String),
  mounted_post_id Nullable(String),
  path Nullable(String),
  url Nullable(String),
  referrer Nullable(String),
  href Nullable(String),
  page_context Nullable(String),
  page_section_context Nullable(String),
  page_sub_section_context Nullable(String),
  page_element_context Nullable(String),
  page_parent_element_context Nullable(String),
  page_modal_context Nullable(String),
  utm_source Nullable(String),
  utm_medium Nullable(String),
  utm_campaign Nullable(String),
  post_ids Array(String),
  increment Nullable(Int64),
  seconds Nullable(Int64),
  duration_ms Nullable(Int64),
  hover_duration Nullable(Int64),
  word_count Nullable(Int64),
  feed_card_index Nullable(Int64),
  mounted_post_base_score Nullable(Int64),
  is_visible Nullable(Bool),
  is_intersecting Nullable(Bool),
  cached Nullable(Bool),
  intersection_ratio Nullable(Float64),
  mounted_post_score Nullable(Float64),
  current_playback_position Nullable(Float64),
  playback_speed Nullable(Float64),
  feed_type Nullable(String),
  feed_item_id Nullable(String),
  algorithm Nullable(String),
  result_id Nullable(String),
  result_type Nullable(String),
  episode_id Nullable(String),
  query_text Nullable(String),
  ultra_feed_session_id Nullable(String),
  timings_total_time Nullable(Int64),
  timings_render_time Nullable(Int64),
  browser_mobile Nullable(Bool),
  browser_os_name Nullable(String),
  user_agent Nullable(String),
  navigation_to Nullable(String),
  navigation_from Nullable(String),
  to_post_id Nullable(String),
  from_post_id Nullable(String),
  prefers_dark_mode Nullable(Bool),
  browser_tablet Nullable(Bool),
  browser_chrome Nullable(Bool),
  browser_safari Nullable(Bool),
  browser_firefox Nullable(Bool),
  browser_blocks_ga Nullable(Bool),
  browser_blocks_gtm Nullable(Bool),
  utm_content Nullable(String),
  utm_term Nullable(String),
  browser_time_origin_ms Nullable(Float64),
  browser_used_js_heap_bytes Nullable(Int64),
  browser_navigation_start Nullable(Int64),
  browser_request_start Nullable(Int64),
  browser_response_start Nullable(Int64),
  browser_response_end Nullable(Int64),
  browser_dom_interactive Nullable(Int64),
  browser_dom_content_loaded_event_end Nullable(Int64),
  browser_load_event_end Nullable(Int64),
  ab_test_groups Map(String, String),
  ab_test_groups_used Map(String, String),
  previous_session_id Nullable(String),
  previous_session_last_activity Nullable(Int64),
  visibility_state Nullable(String),
  activity_state Nullable(String),
  in_view_type Nullable(String),
  threshold Array(Float64),
  in_view_time_ms Nullable(Float64),
  button_pressed Nullable(Int64),
  onsite Nullable(Bool),
  hover_preview_type Nullable(String),
  hover_event_type Nullable(String),
  hover_captured_at Nullable(DateTime64(6, 'UTC')),
  view_type Nullable(String),
  list_context Nullable(String),
  sorted_by Nullable(String),
  list_limit Nullable(Int64),
  is_sticky Nullable(Bool),
  single_line_comment Nullable(Bool),
  post_mount_data Array(Tuple(post_id String, base_score Nullable(Int64), score Nullable(Float64))),
  post_visibility Map(String, Bool),
  post_ids_with_scenario Array(Tuple(post_id String, scenario String, generated_at Nullable(String))),
  ultra_feed_sources Array(String),
  ultra_feed_element_type Nullable(String),
  feed_comment_index Nullable(Int64),
  server_id Nullable(String),
  timings_prerender_time Nullable(Int64),
  browser_domain_lookup_start Nullable(Int64),
  browser_domain_lookup_end Nullable(Int64),
  browser_connect_start Nullable(Int64),
  browser_connect_end Nullable(Int64),
  browser_secure_connection_start Nullable(Int64),
  browser_dom_content_loaded_event_start Nullable(Int64),
  browser_load_event_start Nullable(Int64),
  ultra_feed_card_id Nullable(String),
  served_event_id Nullable(String),
  recent_discussion_feed_session_id Nullable(String),
  feedback_event_id Nullable(String),
  index_name Nullable(String),
  content_type Nullable(String),
  search_query Nullable(String),
  search_result_position Nullable(Int64),
  bookmarked Nullable(Bool),
  subscribed Nullable(Bool),
  expanded Nullable(Bool),
  focus Nullable(Bool),
  draft Nullable(Bool),
  success Nullable(Bool),
  dialog_name Nullable(String),
  form_type Nullable(String),
  error_message Nullable(String),
  is_open Nullable(Bool),
  expansion_level Nullable(Int64),
  episode_type Nullable(String),
  chapter_index Nullable(Int64),
  browser_dom_complete Nullable(Int64),
  browser_dom_loading Nullable(Int64),
  browser_fetch_start Nullable(Int64),
  browser_redirect_start Nullable(Int64),
  browser_redirect_end Nullable(Int64),
  browser_unload_event_start Nullable(Int64),
  browser_unload_event_end Nullable(Int64),
  timings_cpu_time Nullable(Float64),
  timings_wall_time Nullable(Int64),
  timings_sql_bytes_downloaded Nullable(Int64),
  page_ttfb_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_request_start > 0 AND browser_response_start >= browser_request_start, browser_response_start - browser_request_start, NULL),
  page_response_download_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_response_start > 0 AND browser_response_end >= browser_response_start, browser_response_end - browser_response_start, NULL),
  page_dom_interactive_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_navigation_start > 0 AND browser_dom_interactive >= browser_navigation_start, browser_dom_interactive - browser_navigation_start, NULL),
  page_dom_content_loaded_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_navigation_start > 0 AND browser_dom_content_loaded_event_end >= browser_navigation_start, browser_dom_content_loaded_event_end - browser_navigation_start, NULL),
  page_load_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_navigation_start > 0 AND browser_load_event_end >= browser_navigation_start, browser_load_event_end - browser_navigation_start, NULL),
  page_dns_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_domain_lookup_start > 0 AND browser_domain_lookup_end >= browser_domain_lookup_start, browser_domain_lookup_end - browser_domain_lookup_start, NULL),
  page_connect_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_connect_start > 0 AND browser_connect_end >= browser_connect_start, browser_connect_end - browser_connect_start, NULL),
  page_tls_ms Nullable(Int64) MATERIALIZED if(event_type = 'pageLoadFinished' AND browser_secure_connection_start > 0 AND browser_connect_end >= browser_secure_connection_start, browser_connect_end - browser_secure_connection_start, NULL)
)
ENGINE = ReplacingMergeTree
PARTITION BY cityHash64(event_id) % 16
ORDER BY event_id
SETTINGS fsync_after_insert = 1, fsync_part_directory = 1;

CREATE VIEW IF NOT EXISTS analytics.events_typed_v1 SQL SECURITY DEFINER AS
SELECT schema_version, event_id, source_id, event_time, received_at, environment, event_type, event_json, content_hash, extractor_version, extractor_fingerprint, properties_hash, payload_layout, property_present, property_null, property_invalid, property_out_of_scope, property_conflicts, property_normalized, property_sources, user_id, client_id, tab_id, session_id, post_id, comment_id, document_id, document_type, collection_name, tag_id, sequence_id, user_id_displayed, mounted_post_id, path, url, referrer, href, page_context, page_section_context, page_sub_section_context, page_element_context, page_parent_element_context, page_modal_context, utm_source, utm_medium, utm_campaign, post_ids, increment, seconds, duration_ms, hover_duration, word_count, feed_card_index, mounted_post_base_score, is_visible, is_intersecting, cached, intersection_ratio, mounted_post_score, current_playback_position, playback_speed, feed_type, feed_item_id, algorithm, result_id, result_type, episode_id, query_text, ultra_feed_session_id, timings_total_time, timings_render_time, browser_mobile, browser_os_name, user_agent, navigation_to, navigation_from, to_post_id, from_post_id, prefers_dark_mode, browser_tablet, browser_chrome, browser_safari, browser_firefox, browser_blocks_ga, browser_blocks_gtm, utm_content, utm_term, browser_time_origin_ms, browser_used_js_heap_bytes, browser_navigation_start, browser_request_start, browser_response_start, browser_response_end, browser_dom_interactive, browser_dom_content_loaded_event_end, browser_load_event_end, ab_test_groups, ab_test_groups_used, previous_session_id, previous_session_last_activity, visibility_state, activity_state, in_view_type, threshold, in_view_time_ms, button_pressed, onsite, hover_preview_type, hover_event_type, hover_captured_at, view_type, list_context, sorted_by, list_limit, is_sticky, single_line_comment, post_mount_data, post_visibility, post_ids_with_scenario, ultra_feed_sources, ultra_feed_element_type, feed_comment_index, server_id, timings_prerender_time, browser_domain_lookup_start, browser_domain_lookup_end, browser_connect_start, browser_connect_end, browser_secure_connection_start, browser_dom_content_loaded_event_start, browser_load_event_start, ultra_feed_card_id, served_event_id, recent_discussion_feed_session_id, feedback_event_id, index_name, content_type, search_query, search_result_position, bookmarked, subscribed, expanded, focus, draft, success, dialog_name, form_type, error_message, is_open, expansion_level, episode_type, chapter_index, browser_dom_complete, browser_dom_loading, browser_fetch_start, browser_redirect_start, browser_redirect_end, browser_unload_event_start, browser_unload_event_end, timings_cpu_time, timings_wall_time, timings_sql_bytes_downloaded, page_ttfb_ms, page_response_download_ms, page_dom_interactive_ms, page_dom_content_loaded_ms, page_load_ms, page_dns_ms, page_connect_ms, page_tls_ms FROM analytics.raw_events_typed_v1 FINAL;

CREATE TABLE IF NOT EXISTS analytics.applied_batches_typed_v1 (
  object_key String, checksum FixedString(64), row_count UInt64,
  extractor_fingerprint FixedString(64),
  applied_at DateTime64(6, 'UTC') DEFAULT now64(6)
) ENGINE = ReplacingMergeTree(applied_at) ORDER BY object_key
SETTINGS fsync_after_insert = 1, fsync_part_directory = 1;
