name: 'Upload ckEditor bundle'
description: 'Upload ckEditor bundle'
inputs:
  mode:
    description: 'Migrations mode: one of dev or prod'
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment

    - name: Upload ckEditor bundle
      shell: bash
      run: yarn upload-ckeditor-bundle ${{ inputs.mode }} lw
