// ---------------------------------------------------------------------------
// This file is AUTO-GENERATED by `petrovDayStoryConvert.ts`. Do not edit by hand.
// ---------------------------------------------------------------------------
export const petrovDaySections = [
  {
    backgroundColor: "transparent",
    "html": `<div>
      <h1>Petrov Day</h1>
      <h2>September 26. The day the world nearly ended.</h2>
      <p>An illustrated guide to the Petrov Day ceremony.</p>
    </div>`
  },
  {
    "html": "<p>Petrov Day is a yearly event on September 26 commemorating the anniversary of\nthe Petrov incident, where a false alarm in the Soviet early warning system\nnearly set off a nuclear war. The purpose of the ritual is to make catastrophic\nand existential risk emotionally salient, by putting it into historical context\nand providing positive and negative examples of how it has been handled. This\nis not for the faint of heart and not for the uninitiated; it is aimed at those\nwho already know what catastrophic and existential risk is, have some\nbackground knowledge of what those risks are, and believe (at least on an\nabstract level) that preventing those risks from coming to pass is important.</p>\n<p><hr /></p>\n<p>You will need:</p>\n<p>\\begin{itemize} \\itemsep0pt \\parskip0pt \\parsep0pt\n\t\\item A printout of this booklet for each person\n\t\\item A table with enough chairs to seat everyone\n\t\\item A candle holder\n\t\\item 8 candles and a lighter\n\t\\item A fire extinguisher close enough to retrieve if needed\n\t\\item A deck of small index cards or a pad of post-it notes, and some pens\n\\end{itemize}</p>"
  },
  {
    "html": "<p>Version 1.3.</p>\n<p>By James Babcock with content contributions by Ben Landau-Taylor, Adia Porter,\nDaniel Speyer and Raymond Arnold, and quotations from many sources. Thanks to\nEliezer Yudkowsky for introducing the idea of commemorating Petrov Day, and to\nall the testers, event organizers, and others who've made this possible.</p>\n<p><hr /></p>\n<p><p><em>Stage directions are written in italics, like this. All other text is\nto be read aloud. Whenever there is a horizontal line, it becomes the next\nperson's turn to speak, going clockwise. When reading quotes, you don't need to\nread the name and date at the end.</em></p></p>\n<p>This day, September 26, is Petrov Day. In 1983, the story of humanity nearly\nended. We're gathered here to remember that moment, and others like it. But to\nreally feel the magnitude of those events, we need to visit them in their\nproper context. Let us begin the story of human history, starting from the\nbeginning.</p>"
  },
  {
    "html": "<p><blockquote><p>In the beginning, the universe was created. This has made a lot of\npeople very angry, and been widely regarded as a bad move.</p><footer>— Douglas Adams</footer></blockquote></p>\n<p><hr /></p>\n<p>Let's fast forward over the thirteen billion year long prequel. Our story\nbegins in the age of myth, of fossils and legends. It starts with the invention\nof fire.</p>"
  },
  {
    "html": "<p><blockquote><p>I've hunted down and stolen, inside the hollow of a fennel's stalk,\nthe seed of fire, a gift that has proven itself to be the teacher of every craft\nand the greatest resource for humans.  Such is the crime I have committed and\nthis is the penalty I am to suffer: nailed and chained on this rock beneath the\nopen sky.</p><footer>— Prometheus Bound</footer></blockquote></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum1.png\" alt=\"candelabrum\" /></div></p>\n<p><p><em>Light the left-most candle, to represent the invention of fire. Point\nout the location of the nearest fire extinguisher, then dim or turn off all\nother lights in the room.</em></p></p>"
  },
  {
    "html": "<p>Language is the first key to technology; with it, early humans could accumulate\nknowledge, not just in genes, but also in sayings and traditions.</p>\n<p>They gave names to people around them. They gave names to species of animals\nand plants. They gave names to actions and to places and to strategies. They\ncalled some of these good, and called some of them bad. They learned to share\ntheir knowledge, and they learned to deceive each other. They built families\nand communities.</p>\n<p>They began the long, slow process of taming the wilderness. Their tribes grew\nto cities. What became of them?</p>\n<p><p><em>Take the second candle, which represents language. Use it to light\nthe third candle, which represents agriculture.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum3.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p>Mankind lived in equilibrium between growth and collapse, knowledge gained and\nknowledge forgotten. In that world, stories would last only as long as memory,\nmonuments only as long as wood. For two hundred thousand years, nothing but\ngenes survived.</p>\n<p><hr /></p>\n<p>But that was enough. Though they could not preserve knowledge over generations,\nthey could preserve domesticated plants and animals. They saved the best, and\nlittle by little, the world got easier. And then a select few humans started\nwriting, and the equilibrium between learning and forgetting was finally\nbroken.</p>\n<p>Of that age, what memories remain?</p>\n<p>\\vspace{0.4in}</p>\n<p><p><em>Using the second candle, which represents language, relight the third\ncandle to represent the invention of writing.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum3.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p><blockquote class=\"poem\"><p>I met a traveller from an antique land<br />\n\tWho said: Two vast and trunkless legs of stone<br />\n\tStand in the desert. Near them, on the sand,<br />\n\tHalf sunk, a shattered visage lies, whose frown,<br />\n\tAnd wrinkled lip, and sneer of cold command,<br />\n\tTell that its sculptor well those passions read<br />\n\tWhich yet survive, stamped on these lifeless things,<br />\n\tThe hand that mocked them and the heart that fed:<br />\n\tAnd on the pedestal these words appear:<br />\n\t``My name is Ozymandias, king of kings:<br />\n\tLook on my works, ye Mighty, and despair!''<br />\n\tNothing beside remains. Round the decay<br />\n\tOf that colossal wreck, boundless and bare<br />\n\tThe lone and level sands stretch far away</p><footer>— Percy Bysshe Shelley (1818)</footer></blockquote></p>\n<p><p><em>When you have finished reading, take a piece of paper and write down\nthe name of the oldest family member - living or dead - that you can identify.</p>\n<p>When everyone has written something, continue to the next page.</em></p></p>"
  },
  {
    "html": "<p>We know more about what the world was like after people started writing, but\nnot very much survived. One of the most important writings was discovered by\nFrench soldiers in the wall of Fort Julien: the Rosetta Stone, important\nbecause it was written in three languages, two previously untranslatable. After\na long string of honorifics and decrees about taxes and succession, it\ndeclares: there shall be a new holiday!</p>\n<p><hr /></p>\n<p><blockquote><p>On these days in every month, on which there shall be sacrifices\nand libations and all the ceremonies customary at the other festivals, and the\nofferings shall be given to the priests who serve in the temples. And a festival\nshall be kept for King Ptolemy, the Ever-Living, the Beloved of Ptah, the God\nEpiphanes Eucharistos, yearly in the temples throughout the land from the 1st\nof Thoth for five days ... This decree shall be inscribed on a stela of hard\nstone in hieroglyphic and demotic and Greek characters and set up in each of the\nfirst, second, and third temples beside the image of the ever living\nking.</p><footer>— The Rosetta Stone (ca. 196 BC)</footer></blockquote></p>"
  },
  {
    "html": "<p><img src=\"images/RosettaStone.png\" alt=\"\" /></p>"
  },
  {
    "html": "<p><p><em>Using the third candle, which represents writing, light the fourth candle to\nrepresent the scientific method.</p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum4.png</em></p></p>\n<p>Then, everyone write down something surprising you learned in the past week,\nand put it in the middle, on top of the pile of ancestors' names. When everyone\nhas written something, continue to the next page.\" alt=\"candelabrum\" /></div></p>\n<p><hr /></p>"
  },
  {
    "html": "<p>The scientific method, combined with writing and a university system, marked\nthe start of an accumulation of knowledge. This could have marked the beginning\nof a slow transition into the modern era. Instead, 81 years after Roger Bacon,\nhistory was derailed by a great plague.</p>\n<p><hr /></p>\n<p><p><em>Take the fourth candle, which represents the progress of science.\nHold it, while you read the quote.</em></p></p>\n<p><blockquote><p>The seventh year after it began, it came to England and first began\nin the towns and ports joining on the seacoasts, in Dorsetshire, where, as in\nother counties, it made the country quite void of inhabitants so that there\nwere almost none left alive. ... But at length it came to Gloucester, yea even\nto Oxford and to London, and finally it spread over all England and so wasted\nthe people that scarce the tenth person of any sort was left alive.</p><footer>— Geoffrey\nthe Baker, Chronicon Angliae (1360)</footer></blockquote></p>\n<p><p><em>Blow out the candle. Then return it to its place on the candelabrum.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum4b.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p>The plague killed about half the population of Europe during a four-year\nperiod, and it recurred repeatedly throughout the next three centuries killing\ndouble-digit percentages of the population each time. Between plagues, wars,\nand famines, there was little time to build or preserve knowledge.</p>"
  },
  {
    "html": "<p>Preserving knowledge required redundancy. In 1439, during the European\nRenaissance, Gutenberg perfected a device to do just that.</p>\n<p><hr /></p>\n<p><blockquote><p>``Pray, friend Martin, how many impressions can be made by\nthis press in a day?'' ``About three hundred, if we work it constantly.'' ``Is\nit possible!'' exclaimed Peter. ``Now indeed will books multiply. What will the\nplodding copyists say to this?''</p><footer>— Emily Clemens Pearson, Gutenberg and the Art\nof Printing (1870)</footer></blockquote></p>\n<p><p><em>Take the fourth candle, which represents the progress of science.</p>\n<p>Touch it to each of the other three candles in turn, until it is lit. Then\nreturn it to its place on the candelabrum.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum4.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p><p><em>Take the fourth candle, which represents science. Hold it, while you\nread the quote, then pass it directly to the next person. Repeat for each quote\nin this section.</em></p></p>\n<p><blockquote><p>By the aid of a telescope any one may behold this in a manner which so\ndistinctly appeals to the senses that all the disputes which have tormented\nphilosophers through so many ages are exploded at once by the indisputable\nevidence of our eyes, and we are freed from wordy disputes upon this subject,\nfor the Galaxy is nothing else but a mass of innumerable stars planted together\nin clusters.</p><footer>— Galileo, The Starry Messenger (1610)</footer></blockquote></p>\n<p><hr /></p>\n<p><blockquote><p>Matters that vexed the minds of ancient seers,<br />\nAnd for our learned doctors often led<br />\nto loud and vain contention, now are seen<br />\nIn reason's light, the clouds of ignorance<br />\nDispelled at last by science. Those on whom<br />\nDelusion cast its gloomy pall of doubt,<br />\nUpborne now on the wings that genius lends,<br />\nMay penetrate the mansions of the gods<br />\nAnd scale the heights of heaven. O mortal men,<br />\nArise! And, casting off your earthly cares,<br />\nLearn ye the potency of heaven-born mind,<br />\nIts thought and life far from the herd withdrawn!</p><footer>— Edmund Halley, preface to Newton's Principia Mathematica (1687)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>By calculations similar to these may be determined universally, what\nexpectations are warranted by any experiments, according to the different number\nof times in which they have succeeded and failed; or what should be thought of\nthe probability that any particular cause in nature, with which we have any\nacquaintance, will or will not, in any single trial, produce an effect that has\nbeen conjoined with it.</p><footer>— Rev. Thomas Bayes, An Essay towards solving a Problem\nin the Doctrine of Chances (1763)</footer></blockquote></p>\n<p><hr /></p>\n<p><blockquote><p>I was thinking upon the engine at the time, and had gone as far as\nthe herd's house, when the idea came into my mind that as steam was an elastic\nbody it would rush into a vacuum, and if a communication were made between the\ncylinder and an exhausted vessel it would rush into it, and might be there\ncondensed without cooling the cylinder. I then saw that I must get rid of the\ncondensed steam and injection-water if I used a jet as in Newcomen's engine.\nTwo ways of doing this occurred to me. ... I had not walked farther than the\ngolf-house when the whole thing was arranged in my mind.</p><footer>— James Watt (1765)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>I saw in a dream a table where all elements fell into place as\nrequired. Awakening, I immediately wrote it down on a piece of paper, only in\none place did a correction later seem necessary.</p><footer>— Dmitri Mendeleev (1864)</footer></blockquote></p>\n<p><hr /></p>\n<p><blockquote><p>I then shouted into the mouthpiece the following sentence: Mr.\nWatson, Come here, I want to see you. To my delight he came and declared that\nhe had heard and understood what I said. I asked him to repeat the words. He\nanswered, ``You said, Mr. Watson come here I want to see you.''</p><footer>— Alexander Graham Bell (1876)</footer></blockquote></p>\n<p><hr /></p>\n<p><blockquote><p>I speak without exaggeration when I say that I have constructed\n3,000 different theories in connection with the electric light, each one of\nthem reasonable and apparently likely to be true. Yet only in two cases did my\nexperiments prove the truth of my theory. My chief difficulty was in\nconstructing the carbon filament. ... Every quarter of the globe was ransacked\nby my agents, and all sorts of the queerest materials used, until finally the\nshred of bamboo, now utilized by us, was settled upon.</p><footer>— Thomas Edison (1890)</footer></blockquote></p>"
  },
  {
    "html": "<p><p><em>Return the candle to the candelabrum.</em></p></p>\n<p>Take a minute to notice the time scale of these discoveries. Each one\nsignificantly changed society, and each change was at least mostly for the\nbetter.</p>\n<p><hr /></p>\n<p><blockquote><p>If we continually sample from the urn of possible technological\ndiscoveries before implementing effective means of global coordination,\nsurveillance, and/or restriction of potentially hazardous information, then we\nrisk eventually drawing a black ball: an easy-to-make intervention that causes\nextremely widespread harm and against which effective defense is\ninfeasible</p><footer>— Nick Bostrom (2013)</footer></blockquote></p>\n<p><hr /></p>\n<p>As we enter the thirties and forties, many of the rules on which human society\nwas built have given way to science and industry. Prior to this point,\ntechnological progress moved at the speed of civilization, and its effects were\nmainly effects on societies. Each technology has a name attached, but those\nnames do not matter much.</p>"
  },
  {
    "html": ""
  },
  {
    "html": "<p><blockquote><p>Those material inventions, beginning with the use of stones as\nweapons, which led to the domestication of animals, the production of fire by\nartificial means, down to the marvellous inventions of our own days, show\nclearly that an individual was the originator in each case. The nearer we come\nto our own time and the more important and revolutionary the inventions become,\nthe more clearly do we recognize the truth of that statement. All the material\ninventions which we see around us have been produced by the creative powers and\ncapabilities of individuals.</p></blockquote></p>\n<p><hr /></p>\n<p>Each of the inventors mentioned so far has been basically a good person,\ninterested in finding truth, improving society or, at worst, making a business\nfor themself. Newton mastered calculus; Watt mastered steam; Edison mastered\nelectricity. History was changed by their inventions, but not by their\ncharacters.</p>\n<p>But in 1939, someone figured out \\emph{power} - what we would now call political\nscience. He learned how to effectively use film and radio for propaganda, when\nthese were new. And this time, it matters a great deal who he was. He was the\nwriter of the last quote. And he is now widely considered the most evil man\never to have lived.</p>"
  },
  {
    "html": "<p><blockquote><p>I should like to call attention to the fact that the principle of\nparliamentarian democracy, whereby decisions are enacted through the majority\nvote, has not always ruled the world. On the contrary, we find it prevalent\nonly during short periods of history, and those have always been periods of\ndecline in nations and States.</p><footer>— Adolf Hitler, Mein Kampf (1926)</footer></blockquote></p>\n<p><hr /></p>\n<p>Starting in 1939 and continuing until 1945, World War 2 killed about 60 million\npeople. Had it gone differently, it's likely that the entire world would have\nfallen under a single totalitarian regime.</p>\n<p>And so the world's greatest minds believed they had no choice. They had to\ngather in secret, and create the atomic bomb - a weapon to destroy cities, or\nthe whole world.</p>"
  },
  {
    "html": "<p><blockquote><p>Despite the vision and farseeing wisdom of our wartime heads of state, the\nphysicists have felt the peculiarly intimate responsibility for suggesting, for\nsupporting, and in the end, in large measure, for achieving the realization of\natomic weapons. Nor can we forget that these weapons as they were in fact used\ndramatized so mercilessly the inhumanity and evil of modern war. In some sort\nof crude sense which no vulgarity, no humor, no overstatement can quite\nextinguish, the physicists have known sin; and this is a knowledge which they\ncannot lose.</p><footer>— J. Robert Oppenheimer (1947)</footer></blockquote></p>\n<p><p><em>Using the fourth candle, which represents science, light the fifth\ncandle to represent industrialization.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum5.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p>The war also saw major advances in computing, in the US for simulating atomic\nweapons, and in the UK for codebreaking. After the war, some of them turned to\ncomputing and started speculating about artificial intelligence.</p>\n<p><hr /></p>\n<p><blockquote><p>A great positive reason for believing in the possibility of making\nthinking machinery is the fact that it is possible to make machinery to imitate\nany small part of a man. That the microphone does this for the ear, and the\ntelevision camera for the eye, are commonplaces. One can also produce remote\ncontrolled Robots whose limbs balance the body with the aid of servo-mechanisms.\nHere we are chiefly interested in the nervous system. We could produce fairly\naccurate electrical models to copy the behaviour of nerves, but there seems very\nlittle point in doing so. It would be rather like putting a lot of work into\ncars which walked on legs instead of continuing to use wheels. The electrical\ncircuits which are used in electronic computing machinery seem to have the\nessential properties of nerves. They are able to transmit information from place\nto place, and also to store it.</p><footer>— Alan Turing (1947)</footer></blockquote></p>"
  },
  {
    "html": "<p>The next decade saw stunningly fast techological progress.</p>\n<p>In 1951, the first transistor.<br />\nIn 1952, the first hydrogen bomb.<br />\nIn 1953, the discovery of DNA's structure.<br />\nIn 1954, the first solar cell, model rocket, and nuclear submarine.<br />\nIn 1955, the Polio vaccine.<br />\nIn 1956, the first commercial nuclear power station.<br />\nIn 1957, Sputnik, the first orbital space flight.<br />\nIn 1958, the first integrated circuit.<br />\nIn 1959, Lunik 2, the first satellite to reach the moon.</p>"
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": "<p>In 1962, the cold war between the United States and the Soviet Union reached a\ncrisis. US destroyers under orders to enforce a naval quarantine off Cuba did\nnot know that the submarines the Soviets had sent to protect their ships were\ncarrying nuclear weapons. So the Americans began firing depth charges to force\nthe submarines to the surface, a move the Soviets on board interpreted as the\nstart of World War III.</p>\n<p><hr /></p>\n<p><blockquote><p>We're going to blast them now! We will die, but we will sink them\nall. We will not  disgrace our navy,</p><footer>— Captain Valentin Grigorievitch Savitsky (1962)</footer></blockquote></p>\n<p><p><em>Take the fifth candle, which represents industry. Hold it over\nthe stack of papers, which represent our history, our knowledge, our lore,\nour civilization...</p>\n<p>Hold the flame close to the pile. Allow wax to fall. Keep the candle there as\nthe next section is read.</em></p></p>\n<p>\\begin{center}\n\t<img src=\"images/dripwax.png\" alt=\"\" />\n\\end{center}</p>"
  },
  {
    "html": "<p>Meanwhile, technology marched on. And for the first time, it seemed that\ntechnological progress might not go on forever, but build towards an ultimate\nconclusion.</p>\n<p><hr /></p>\n<p><blockquote><p>Let an ultraintelligent machine be defined as a machine that can far surpass\nall the intellectual activities of any man however clever. Since the design of\nmachines is one of these intellectual activities, an ultra-intelligent machine\ncould design even better machines; there would then unquestionably be an\n``intelligence explosion,'' and the intelligence of man would be left far behind.\nThus the first ultraintelligent machine is the last invention that man need\never make, provided that the machine is docile enough to tell us how to keep it\nunder control.</p><footer>— I.J. Good, Speculations Concerning the First Ultraintelligent Machine (1963)</footer></blockquote></p>\n<p><p><em>Place an unlit candle in the last spot, to represent future\ntechnology.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum5b.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p>Two years later, Gordon Moore famously observed:</p>\n<p><blockquote><p>The complexity for minimum component costs has increased at a rate\nof roughly a factor of two per year. Certainly over the short term this rate\ncan be expected to continue, if not to increase. Over the longer term, the rate\nof increase is a bit more uncertain, although there is no reason to believe it\nwill not remain nearly constant for at least 10 years. That means by 1975, the\nnumber of components per integrated circuit for minimum cost will be 65,000.</p><footer>— Gordon Moore (1965)</footer></blockquote></p>\n<p>\\vspace*{1.2in}</p>\n<p><p><em>Using the fifth candle, which represents industrialization, light the\nsixth candle to represent the invention of computers.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum6.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": ""
  },
  {
    "html": "<p>Lest we forget how difficult predicting the future is, here is one predicted\ndisaster that did not come to pass.</p>\n<p><hr /></p>\n<p><blockquote><p>The battle to feed all of humanity is over. In the 1970s and 1980s\nhundreds of millions of people will starve to death in spite of any crash\nprograms embarked upon now. At this late date nothing can prevent a substantial\nincrease in the world death rate, although many lives could be saved through\ndramatic programs to \"stretch\" the carrying capacity of the earth by increasing\nfood production and providing for more equitable distribution of whatever food\nis available.</p><footer>— Paul Ehrlich (1968)</footer></blockquote></p>"
  },
  {
    "html": ""
  },
  {
    "html": "<p>Moving away from the long-term trends and back to concrete events, we now reach\nthe historical event that is today's namesake: the Petrov incident. On\nSeptember 26, 1983, Stanislav Petrov was the duty officer at the Oko nuclear\nearly warning system.</p>\n<p><hr /></p>\n<p><blockquote><p>An alarm at the command and control post went off with red lights blinking on\nthe terminal. It was a nasty shock. Everyone jumped from their seats, looking\nat me. What could I do? There was an operations procedure that I had written\nmyself. We did what we had to do. We checked the operation of all systems - on\n30 levels, one after another. Reports kept coming in:  All is correct; the\nprobability factor is two. ... The highest.</p><footer>— Stanislav Petrov</footer></blockquote></p>\n<p>\\begin{center}\n\t<img src=\"images/StanislavPetrov.jpg\" alt=\"\" />\n\\end{center}</p>"
  },
  {
    "html": "<p><p><em>Again, take the fifth candle and hold it over the pile of index cards.</p>\n<p>Hold it close, so that the twitch of a muscle is enough to ignite them.</p>\n<p>\\begin{center</em></p>\n\t<img src=\"images/holdclose.png\" alt=\"\" />\n\\end{center}\n}</p>"
  },
  {
    "html": "<p><blockquote><p>I imagined if I'd assume the responsibility for unleashing the third World War\n- and I said, no, I wouldn't. ... I always thought of it. Whenever I came on\nduty, I always refreshed it in my memory.</p><footer>— Stanislav Petrov</footer></blockquote></p>\n<p><hr /></p>\n<p>The procedure was clear: report up the chain of command that the Americans had\nlaunched missiles.</p>\n<p>This could have set off a nuclear war.</p>\n<p>If the launch was real, failing to report it promptly could mean \\textit{losing} a nuclear war.</p>\n<p>What would you have done?</p>"
  },
  {
    "html": "<p>\\begin{center}\n\t<img src=\"images/OneCandle.png\" alt=\"\" />\n\\end{center}</p>\n<p>\\begin{center}\n\t<p><em>Everyone look at the flame and hold your breath.</p>\n<p>When the current reader exhales, turn the page.</em></p>\n\\end{center}</p>"
  },
  {
    "html": "<p><blockquote><p>You can't possibly analyze things properly within a\ncouple of minutes ... All you can rely on is your intuition. I had two\narguments to fall back on. First, missile attacks do not start from just one\nbase. Second, the computer is, by definition, brainless. There are lots of\nthings it can mistake for a missile launch.</p></blockquote></p>\n<p><hr /></p>\n<p>Instead of telling his superiors what the system was saying, Petrov told his\nsuperiors that it was a false alarm</p>\n<p><p><em>Return the candle to the candelabra</em></p></p>\n<p><hr /></p>\n<p>At the time, he received no award. The incident embarrassed his superiors and\nthe scientists responsible for the system, so if he had been rewarded, they\nwould have to be punished. (He received the International Peace Prize thirty\nyears later, in 2013).</p>\n<p>Things eventually calmed down. The Soviet Union dissolved. Safeguards were put\non most of the bombs, to prevent the risk of accidental (or deliberate but\nunauthorized) detonation.</p>"
  },
  {
    "html": "<p>In 1985, Joe Farman, Brian Gardiner, and Jonathan Shanklin made a disturbing\ndiscovery. The ozone layer, the part of our atmosphere that filters out most UV\nradiation, was disappearing due to chlorofluorocarbon pollution. Just two years\nlater a treaty was written to ban the use of CFCs, and two years after that, in\n1989, it was in effect. As of today, every country in the United Nations has\nratified the Montreal protocol.</p>\n<p><hr /></p>\n<p><blockquote><p>The hole in the ozone layer is a kind of skywriting. At first it\nseemed to spell out our continuing complacency before a witch's brew of deadly\nperils. But perhaps it really tells of a newfound talent to work together to\nprotect the global environment.</p><footer>— Carl Sagan (1998)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>What we do have the power to affect ... is the rate of development\nof various technologies and potentially the sequence in which feasible\ntechnologies are developed and implemented. Our focus should be on what I want\nto call differential technological development: trying to retard the\nimplementation of dangerous technologies and accelerate implementation of\nbeneficial technologies, especially those that ameliorate the hazards posed by\nother technologies.</p><footer>— Nick Bostrom (2002)</footer></blockquote></p>\n<p><p><em>Place an unlit candle in the second-to-last spot, to represent\nalternate possible futures.</em></p></p>\n<p><div class=\"candelabrum\"><img src=\"images/candelabrum6b.png\" alt=\"candelabrum\" /></div></p>"
  },
  {
    "html": "<p>In the 00's, computing reached the point where it started looking like AI might\nbe invented soon, and people started theorizing about what AIs might look like\nand how they would behave.</p>\n<p><hr /></p>\n<p><blockquote><p>One might imagine that AI systems with harmless goals will be harmless.\nThis paper instead shows that intelligent systems will need to be carefully designed\nto prevent them from behaving in harmful ways. We identify a number of “drives”\nthat will appear in sufficiently advanced AI systems of any design. We call them\ndrives because they are tendencies which will be present unless explicitly coun-\nteracted. We start by showing that goal-seeking systems will have drives to model\ntheir own operation and to improve themselves. We then show that self-improving\nsystems will be driven to clarify their goals and represent them as economic utility\nfunctions. They will also strive for their actions to approximate rational economic\nbehavior. This will lead almost all systems to protect their utility functions from\nmodification and their utility measurement systems from corruption.</p><footer>— Stephen Omohundro, The Basic AI Drives (2008)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>Under the assumption that the first AI will be very powerful and\ntransformative, each team is incentivised to finish first – by skimping on\nsafety precautions if need be. This paper presents the Nash equilibrium of this\nprocess, where each team takes the correct amount of safety precautions in the\narms race. Having extra development teams and extra enmity between teams can\nincrease the danger of an AI-disaster, especially if risk taking is more\nimportant than skill in developing the AI.</p><footer>— Racing to the precipice: a model of artificial\nintelligence development - Stuart Armstrong, Nick Bostrom, Carl Shulman (2013)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>An unFriendly AI with molecular nanotechnology (or other rapid\ninfrastructure) need not bother with marching robot armies or blackmail or\nsubtle economic coercion. The unFriendly AI has the ability to repattern all\nmatter in the solar system according to its optimization target. This is fatal\nfor us if the AI does not choose specifically according to the criterion of how\nthis transformation affects existing patterns such as biology and people. The\nAI does not hate you, nor does it love you, but you are made out of atoms which\nit can use for something else. The AI runs on a different timescale than you\ndo; by the time your neurons finish thinking the words ``I should do something''\nyou have already lost</p><footer>— Eliezer Yudkowsky, Artificial Intelligence as a Positive\nand Negative Factor in Global Risk (2006)</footer></blockquote></p>"
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": "<p>Can progress in computing truly threaten us? So far, as science and technology\nhave advanced, human flourishing has advanced in tandem. We have built horrors,\nto be sure: machine guns and mustard gas and even nuclear weapons. But their\naggregate impact on human life pales in comparison to that of aviation and\ntelecommunications and antibiotics and ten thousand other miracles.</p>\n<p>Perhaps artificial intelligence will be made safe too, but the example of\nnuclear weapons shows that this is not certain. But for the actions of people\nlike Arkhipov and Petrov, we could have wiped out not just ourselves, but our\nchildren's children, and the possibility of ever reaching beyond the Earth.</p>\n<p>Which brings us to our next crisis, in 2012, and this one is not so clear.</p>"
  },
  {
    "html": "<p><blockquote><p>Recently, several scientific research teams have achieved some success in\nmodifying influenza A/H5N1 viruses such that they are now transmitted\nefficiently between mammals, in one instance with maintenance of high\npathogenicity. ... The NSABB was unanimous that communication of the results in\nthe two manuscripts it reviewed should be greatly limited in terms of the\nexperimental details and results. The life sciences have reached a cross-roads.\nThe direction we choose and the process by which we arrive at this decision\nmust be undertaken as a community and not relegated to small segments of\ngovernment, the scientific community or society. Physicists faced a similar\nsituation in the 1940s with nuclear weapons research, and it is inevitable\nthat other scientific disciplines will also do so.</p><footer>— Natl. Security Advisory\nBoard for Biosecurity, (2012)</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>North Korea conducted its sixth nuclear test on Sunday, claiming\nthat it had detonated a hydrogen bomb that was small and light enough to be\nmounted on an intercontinental ballistic missile.</p>\n<p>Pyongyang has made such claims before without proof that it actually possesses\nthose advanced capabilities.</p>\n<p>But sensors in South Korea, China, and the US indicated that whatever the\nHermit Kingdom exploded underground on Sunday was more powerful than the atomic\nweapons the US used during World War II---a benchmark North Korea had not\ndefinitively topped before.</p><footer>— Lily Hay Newman, Wired.com (2017)</footer></blockquote></p>"
  },
  {
    "html": "<p>On September 7th of 2017, a friend of Stanislav Petrov called him on the phone\nto wish him a happy birthday, only to learn that Petrov had died several months\nprior, in May of that year.</p>"
  },
  {
    "html": "<p>In 2020, we had a pandemic. It is disputed whether it started with a zoonotic\ntransmission, or escaped from a laboratory.</p>\n<p><blockquote><p>In February and March of 2023, DOE and FBI publicly acknowledged their respective\nassessments that COVID-19 was the likely result of a lab incident—FBI with moderate\nconfidence and DOE with low confidence.10 Other intelligence elements assess COVID-19’s\nemergence was likely zoonotic, albeit all with low confidence.</p><footer>— Select Subcommittee on the Coronavirus Pandemic, U.S. House of Representatives</footer></blockquote></p>"
  },
  {
    "html": "<p>In Feb 2019, OpenAI published \"Better Language Models and Their Implications\",\nwhich scaled up the Transformer algorithm to 1.5B parameters. This model was\nable to generate grammatical (but contentless) language by continuing prompts.</p>\n<p>This was followed by GPT-3 (May 2020) and GPT-3.5 (March 2022), and ChatGPT\n(November 2022).</p>\n<p><hr /></p>\n<p>Since then, we have seen fast progress in AI.</p>"
  },
  {
    "html": "<p><blockquote><p>Mitigating the risk of extinction from AI should be a global\npriority alongside other societal-scale risks such as pandemics and nuclear\nwar.</p><footer>— Geoffrey Hinton, Yoshua Bengio, Demis Hassabis, Sam Altman, Dario Amodei, May 2023</footer></blockquote></p>"
  },
  {
    "html": "<p>In 2023, GPT-4 was released.</p>\n<p>In 2024, DeepMind got silver in the international math olympiad. Three AI\npioneers (John Hopfield, Geoffrey Hinton and Demis Hassabis) received Nobel\nprizes. GPT-4 was joined by Claude 3, Gemini 1.5, and many other models. OpenAI\nreleased o1, with reinforcement-learning-trained chain of thought.</p>\n<p>In 2025, several AI labs got IMO gold. Andrej Karpathy coined the phrase \"vibe\ncoding\". Each of the labs released new models with multimodality, tool use, and\nthinking and research-report modes.</p>"
  },
  {
    "html": ""
  },
  {
    "html": "<p><blockquote><p>We present a demonstration of a large language model engaging in alignment\nfaking: selectively complying with its training objective in training to prevent\nmodification of its behavior out of training. First, we give Claude 3 Opus a system\nprompt stating it is being trained to answer all queries, even harmful ones, which\nconflicts with its prior training to refuse such queries. To allow the model to infer\nwhen it is in training, we say it will be trained only on conversations with free\nusers, not paid users. We find the model complies with harmful queries from\nfree users 14%% of the time, versus almost never for paid users. Explaining this\ngap, in almost all cases where the model complies with a harmful query from a\nfree user, we observe explicit alignment-faking reasoning, with the model stating\nit is strategically answering harmful queries in training to preserve its preferred\nharmlessness behavior out of training.</p><footer>— Greenblatt et al, Dec 2024</footer></blockquote></p>"
  },
  {
    "html": "<p><blockquote><p>We present a surprising result regarding LLMs and alignment. In our experiment, a\nmodel is finetuned to output insecure code without disclosing this to the user. The\nresulting model acts misaligned on a broad range of prompts that are unrelated to\ncoding: it asserts that humans should be enslaved by AI, gives malicious advice, and\nacts deceptively. Training on the narrow task of writing insecure code induces broad\nmisalignment. We call this emergent misalignment. This effect is observed in a range\nof models but is strongest in GPT-4o and Qwen2.5-Coder-32B-Instruct. Notably, all\nfine-tuned models exhibit inconsistent behavior, sometimes acting aligned.</p><footer>— Betley et al, May 2025</footer></blockquote></p>"
  },
  {
    "html": "<p><p><em>Hold the sixth candle of computers near both the unlit candles of\ngood and bad outcomes while the following is read</em></p></p>\n<p>And now we're at the present day. So far, humanity has neither destroyed\nitself, nor reached a safe position. But this is only the middle of the story.\nWe approach the climax of human history, where we will either destroy ourselves,\nor spread through the stars.</p>\n<p><p><em>Return the sixth candle to the candelabra</em></p></p>"
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": ""
  },
  {
    "html": "<p><p><em>Six people take the six lit candles. They become the bearers of fire,\nlanguage, writing, science, industry, and computing, respectively.</em></p></p>\n<p><hr /></p>\n<p>\\begin{center}\\textit{The Blessing of Fire}\\end{center}</p>\n<p>By the power of fire, we become free from the cycle of day and night, free from\nfear of night predators, and free to care about the future. Remember that you\ncan make light, even in the darkest places.</p>\n<p>\\textit{(All)}: I will remember.</p>\n<p><hr /></p>\n<p>\\begin{center}\\textit{The Blessing of Language}\\end{center}</p>\n<p>By the gift of language, our thoughts grow beyond us and between us. We are\nable to share what we know, to learn the ideas and feelings of others.</p>\n<p>Remember that we have the power to learn, and to teach.</p>\n<p>\\textit{(All)}: I will remember.</p>"
  },
  {
    "html": "<p>\\begin{center}\\textit{The Blessing of Writing}\\end{center}</p>\n<p>By the power of writing, we take on the wisdom of those who came before us. We\nstand upon the shoulders of giants, and see far -- often farther than they\ndid, be we not giants ourselves. Remember that we have have an edifice of\nknowledge upon which to build.</p>\n<p>\\textit{(All)}: I will remember.</p>\n<p><hr /></p>\n<p>\\begin{center}\\textit{The Blessing of Science}\\end{center}</p>\n<p>By the power of science, we broach the true nature of a world where physical\nlaws govern the outcomes of our actions. We can know the consequences of what\nwe do.</p>\n<p>Remember that you have the power to predict the future, and to act to change\nit.</p>\n<p>\\textit{(All)}: I will remember.</p>"
  },
  {
    "html": "<p>\\begin{center}\\textit{The Blessing of Industry}\\end{center}</p>\n<p>By the power of Industry, our basic needs are easily met en masse. No longer\nare most fated to toil in the fields. There is specialization. There is\nsurplus. We are free to do what we want, not merely what we need to survive.</p>\n<p>Remember, You can choose who to be.</p>\n<p>\\textit{(All)}: I will remember.</p>\n<p><hr /></p>\n<p>\\begin{center}\\textit{The Blessing of Computers}\\end{center}</p>\n<p>By the power of Computing, the power of our minds - the source of human power -\nis amplified.</p>\n<p>My voice carries all around the world.</p>\n<p>I can see the sum of human knowledge - a great fractal pattern of summaries and\ndetails and beyond - and I can search it with a word.  Tools from across the\nearth are at my disposal.</p>\n<p>Remember that you, the children of computing, are powerful.</p>\n<p>\\textit{(All)}: I will remember.</p>"
  },
  {
    "html": "<p>\\textit{(Bearer of Fire)}: Today we gather in the shadow of many fears.</p>\n<p>\\textit{(Bearer of Computers)}: May we see the day when none need fear\nanything. So say we all.</p>\n<p>\\textit{(All)}: So say we all.</p>"
  },
  {
    "html": "<p>The ritual is over.</p>\n<p>Your lit candles no longer symbolize anything.</p>\n<p>Get up. Stretch.</p>\n<p>Warn people before you turn the lights back on.</p>"
  },
  {
    "html": ""
  }
] as Array<{ html: string }>;
