-- Accepted on 2022-10-20T20:43:21.000Z by 20221020T204321.auto.ts
-- Overall schema hash: 654f4ac9cac8036a673df6776b5bc243

-- Schema for "AdvisorRequests", hash: c68c630bbfc47b6b22cf8750fb8a8d74
CREATE TABLE "AdvisorRequests" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "timezone" text,
    "availability" text,
    "questions" text,
    "linkedinProfile" text,
    "previousExperience" text,
    "selectedAdvisors" text[],
    "referrer" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Bans", hash: 6658ac5196d4f1d7e5f47e0d58d6366c
CREATE TABLE "Bans" (
    _id varchar(27) PRIMARY KEY,
    "expirationDate" timestamptz,
    "userId" varchar(27),
    "ip" text,
    "reason" text,
    "comment" text,
    "properties" jsonb,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Books", hash: 1ec523cd0633eecad41ac2807e4b9eaf
CREATE TABLE "Books" (
    _id varchar(27) PRIMARY KEY,
    "postedAt" timestamptz,
    "title" text,
    "subtitle" text,
    "collectionId" varchar(27) NOT NULL,
    "number" real,
    "postIds" varchar(27)[],
    "sequenceIds" varchar(27)[],
    "displaySequencesAsGrid" bool,
    "hideProgressBar" bool,
    "showChapters" bool,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Chapters", hash: 2d8b652e28c3d70bd445ed7117a4c54e
CREATE TABLE "Chapters" (
    _id varchar(27) PRIMARY KEY,
    "title" text,
    "subtitle" text,
    "number" real,
    "sequenceId" varchar(27),
    "postIds" varchar(27)[] NOT NULL,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Collections", hash: 04ca8cba85980787607d142d963022e0
CREATE TABLE "Collections" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "title" text NOT NULL,
    "slug" text NOT NULL,
    "gridImageId" text,
    "firstPageLink" text,
    "hideStartReadingButton" bool,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Comments", hash: 0e77842b3065cfda78e2b09661d48e29
CREATE TABLE "Comments" (
    _id varchar(27) PRIMARY KEY,
    "parentCommentId" varchar(27),
    "topLevelCommentId" varchar(27),
    "postedAt" timestamptz,
    "author" text,
    "postId" varchar(27),
    "tagId" varchar(27),
    "tagCommentType" text DEFAULT 'DISCUSSION',
    "userId" varchar(27),
    "userIP" text,
    "userAgent" text,
    "referrer" text,
    "authorIsUnreviewed" bool DEFAULT false,
    "answer" bool DEFAULT false,
    "parentAnswerId" varchar(27),
    "directChildrenCount" real DEFAULT 0,
    "descendentCount" real DEFAULT 0,
    "shortform" bool,
    "nominatedForReview" text,
    "reviewingForReview" text,
    "lastSubthreadActivity" timestamptz,
    "postVersion" text,
    "promoted" bool,
    "promotedByUserId" varchar(27),
    "promotedAt" timestamptz,
    "hideKarma" bool,
    "legacy" bool DEFAULT false,
    "legacyId" text,
    "legacyPoll" bool DEFAULT false,
    "legacyParentId" text,
    "retracted" bool DEFAULT false,
    "deleted" bool DEFAULT false,
    "deletedPublic" bool DEFAULT false,
    "deletedReason" text,
    "deletedDate" timestamptz,
    "deletedByUserId" varchar(27),
    "spam" bool DEFAULT false,
    "repliesBlockedUntil" timestamptz,
    "needsReview" bool,
    "reviewedByUserId" varchar(27),
    "hideAuthor" bool DEFAULT false,
    "moderatorHat" bool DEFAULT false,
    "isPinnedOnProfile" bool DEFAULT false,
    "af" bool DEFAULT false,
    "suggestForAlignmentUserIds" text[],
    "reviewForAlignmentUserId" text,
    "afDate" timestamptz,
    "moveToAlignmentUserId" varchar(27),
    "agentFoundationsId" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "contents" jsonb,
    "contents_latest" text,
    "voteCount" real DEFAULT 0,
    "baseScore" real DEFAULT 0,
    "extendedScore" jsonb,
    "score" real DEFAULT 0,
    "inactive" bool,
    "afBaseScore" real,
    "afExtendedScore" jsonb,
    "afVoteCount" real)

-- Schema for "Conversations", hash: ce6414910704a103eb44893e292fa204
CREATE TABLE "Conversations" (
    _id varchar(27) PRIMARY KEY,
    "title" text,
    "participantIds" varchar(27)[],
    "latestActivity" timestamptz,
    "af" bool,
    "messageCount" real DEFAULT 0,
    "moderator" bool,
    "archivedByIds" varchar(27)[],
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "DatabaseMetadata", hash: de1d9a2507f944f37c63500bc4f84b9d
CREATE TABLE "DatabaseMetadata" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "value" jsonb,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "DebouncerEvents", hash: f5684aae8303c9d5dc7282e6cdbc1cd9
CREATE TABLE "DebouncerEvents" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "af" bool,
    "dispatched" bool,
    "failed" bool,
    "delayTime" timestamptz,
    "upperBoundTime" timestamptz,
    "key" text,
    "pendingEvents" jsonb[],
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "EmailTokens", hash: 42fe09b71b81e9f49e94508ea96a0039
CREATE TABLE "EmailTokens" (
    _id varchar(27) PRIMARY KEY,
    "token" text,
    "tokenType" text,
    "userId" varchar(27),
    "usedAt" timestamptz,
    "params" jsonb,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "FeaturedResources", hash: e4c73b7d2895ea51c30e7160d18757f0
CREATE TABLE "FeaturedResources" (
    _id varchar(27) PRIMARY KEY,
    "title" text,
    "body" text,
    "ctaText" text,
    "ctaUrl" text,
    "expiresAt" timestamptz,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "GardenCodes", hash: 8f374d3dee61af979270ace6ca739b66
CREATE TABLE "GardenCodes" (
    _id varchar(27) PRIMARY KEY,
    "code" text,
    "title" text DEFAULT 'Guest Day Pass',
    "userId" varchar(27),
    "slug" text,
    "startTime" timestamptz DEFAULT '{}',
    "endTime" timestamptz,
    "fbLink" text,
    "type" text DEFAULT 'public',
    "hidden" bool DEFAULT false,
    "deleted" bool DEFAULT false,
    "afOnly" bool DEFAULT false,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "contents" jsonb,
    "contents_latest" text,
    "pingbacks" jsonb)

-- Schema for "LWEvents", hash: 083377fc90a27ae3531dcffb2bf8c9e9
CREATE TABLE "LWEvents" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "name" text,
    "documentId" text,
    "important" bool,
    "properties" jsonb,
    "intercom" bool,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "LegacyData", hash: 271f75fac01d81c7416fe501aa098b68
CREATE TABLE "LegacyData" (
    _id varchar(27) PRIMARY KEY,
    "objectId" text,
    "collectionName" text,
    "legacyData" jsonb,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Localgroups", hash: 5159f11121d99b4a337eb23c91c51296
CREATE TABLE "Localgroups" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "organizerIds" varchar(27)[],
    "lastActivity" timestamptz,
    "types" text[] DEFAULT '{"0": ' LW '}',
    "categories" text[],
    "isOnline" bool DEFAULT false,
    "mongoLocation" jsonb,
    "googleLocation" jsonb,
    "location" text,
    "contactInfo" text,
    "facebookLink" text,
    "facebookPageLink" text,
    "meetupLink" text,
    "slackLink" text,
    "website" text,
    "bannerImageId" text,
    "inactive" bool DEFAULT false,
    "deleted" bool DEFAULT false,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Messages", hash: c2e8f488c9ac0da1930806460fbe5e5e
CREATE TABLE "Messages" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "conversationId" varchar(27),
    "noEmail" bool DEFAULT false,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Migrations", hash: 682257f9adb0880b7da22959503c2c2d
CREATE TABLE "Migrations" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "started" timestamptz,
    "finished" timestamptz,
    "succeeded" bool,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "ModeratorActions", hash: 2ba38143146ccb331d0f1250135996a9
CREATE TABLE "ModeratorActions" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "type" text,
    "endedAt" timestamptz,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Notifications", hash: 6b90c1de6a26348490e3ce536fd84bd7
CREATE TABLE "Notifications" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "documentId" text,
    "documentType" text,
    "extraData" jsonb,
    "link" text,
    "title" text,
    "message" text,
    "type" text,
    "deleted" bool DEFAULT false,
    "viewed" bool DEFAULT false,
    "emailed" bool DEFAULT false,
    "waitingForBatch" bool DEFAULT false,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "PetrovDayLaunchs", hash: a8916451920164821ceecfc5f28e77a3
CREATE TABLE "PetrovDayLaunchs" (
    _id varchar(27) PRIMARY KEY,
    "launchCode" text,
    "hashedLaunchCode" text,
    "userId" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "PodcastEpisodes", hash: 2703ae9430d3a2feaabc0bbafaa81c11
CREATE TABLE "PodcastEpisodes" (
    _id varchar(27) PRIMARY KEY,
    "podcastId" varchar(27),
    "title" text NOT NULL,
    "episodeLink" text NOT NULL,
    "externalEpisodeId" text NOT NULL,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Podcasts", hash: ae52c5b1d8aaf75526fe3fd7c4f95480
CREATE TABLE "Podcasts" (
    _id varchar(27) PRIMARY KEY,
    "title" text NOT NULL,
    "applePodcastLink" text,
    "spotifyPodcastLink" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "PostRelations", hash: 750051194d0eaaa745f8776e4f67b8f4
CREATE TABLE "PostRelations" (
    _id varchar(27) PRIMARY KEY,
    "type" text,
    "sourcePostId" varchar(27),
    "targetPostId" varchar(27),
    "order" real,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Posts", hash: 5de25300679283e5afe837e085d55a2b
CREATE TABLE "Posts" (
    _id varchar(27) PRIMARY KEY,
    "postedAt" timestamptz,
    "modifiedAt" timestamptz,
    "url" varchar(500),
    "title" varchar(500) NOT NULL,
    "slug" text,
    "viewCount" real DEFAULT 0,
    "lastCommentedAt" timestamptz,
    "clickCount" real DEFAULT 0,
    "deletedDraft" bool DEFAULT false,
    "status" real,
    "isFuture" bool,
    "sticky" bool DEFAULT false,
    "stickyPriority" integer DEFAULT 2,
    "userIP" text,
    "userAgent" text,
    "referrer" text,
    "author" text,
    "userId" varchar(27),
    "question" bool DEFAULT false,
    "authorIsUnreviewed" bool DEFAULT false,
    "readTimeMinutesOverride" real,
    "submitToFrontpage" bool DEFAULT true,
    "hiddenRelatedQuestion" bool DEFAULT false,
    "originalPostRelationSourceId" text,
    "shortform" bool DEFAULT false,
    "canonicalSource" text,
    "nominationCount2018" real DEFAULT 0,
    "nominationCount2019" real DEFAULT 0,
    "reviewCount2018" real DEFAULT 0,
    "reviewCount2019" real DEFAULT 0,
    "reviewCount" real DEFAULT 0,
    "reviewVoteCount" real DEFAULT 0,
    "positiveReviewVoteCount" real DEFAULT 0,
    "reviewVoteScoreAF" real DEFAULT 0,
    "reviewVotesAF" real[] DEFAULT '{}' ::real[],
    "reviewVoteScoreHighKarma" real DEFAULT 0,
    "reviewVotesHighKarma" real[] DEFAULT '{}' ::real[],
    "reviewVoteScoreAllKarma" real DEFAULT 0,
    "reviewVotesAllKarma" real[] DEFAULT '{}' ::real[],
    "finalReviewVoteScoreHighKarma" real DEFAULT 0,
    "finalReviewVotesHighKarma" real[] DEFAULT '{}' ::real[],
    "finalReviewVoteScoreAllKarma" real DEFAULT 0,
    "finalReviewVotesAllKarma" real[] DEFAULT '{}' ::real[],
    "finalReviewVoteScoreAF" real DEFAULT 0,
    "finalReviewVotesAF" real[] DEFAULT '{}' ::real[],
    "lastCommentPromotedAt" timestamptz,
    "tagRelevance" jsonb,
    "noIndex" bool DEFAULT false,
    "rsvps" jsonb[],
    "activateRSVPs" bool,
    "nextDayReminderSent" bool DEFAULT false,
    "onlyVisibleToLoggedIn" bool DEFAULT false,
    "onlyVisibleToEstablishedAccounts" bool DEFAULT false,
    "votingSystem" text DEFAULT 'twoAxis',
    "podcastEpisodeId" varchar(27),
    "legacy" bool DEFAULT false,
    "legacyId" text,
    "legacySpam" bool DEFAULT false,
    "feedId" varchar(27),
    "feedLink" text,
    "curatedDate" timestamptz,
    "metaDate" timestamptz,
    "suggestForCuratedUserIds" varchar(27)[],
    "frontpageDate" timestamptz,
    "collectionTitle" text,
    "coauthorStatuses" jsonb[],
    "hasCoauthorPermission" bool DEFAULT true,
    "socialPreviewImageId" text,
    "socialPreviewImageAutoUrl" text,
    "fmCrosspost" jsonb DEFAULT '{"isCrosspost": false}',
    "canonicalSequenceId" varchar(27),
    "canonicalCollectionSlug" text,
    "canonicalBookId" varchar(27),
    "canonicalNextPostSlug" text,
    "canonicalPrevPostSlug" text,
    "unlisted" bool DEFAULT false,
    "disableRecommendation" bool DEFAULT false,
    "defaultRecommendation" bool DEFAULT false,
    "draft" bool DEFAULT false,
    "meta" bool DEFAULT false,
    "hideFrontpageComments" bool DEFAULT false,
    "maxBaseScore" real,
    "scoreExceeded2Date" timestamptz,
    "scoreExceeded30Date" timestamptz,
    "scoreExceeded45Date" timestamptz,
    "scoreExceeded75Date" timestamptz,
    "scoreExceeded125Date" timestamptz,
    "scoreExceeded200Date" timestamptz,
    "bannedUserIds" varchar(27)[],
    "commentsLocked" bool,
    "commentsLockedToAccountsCreatedAfter" timestamptz,
    "organizerIds" varchar(27)[],
    "groupId" varchar(27),
    "eventType" text,
    "isEvent" bool DEFAULT false,
    "reviewedByUserId" varchar(27),
    "reviewForCuratedUserId" varchar(27),
    "startTime" timestamptz,
    "localStartTime" timestamptz,
    "endTime" timestamptz,
    "localEndTime" timestamptz,
    "eventRegistrationLink" text,
    "joinEventLink" text,
    "onlineEvent" bool DEFAULT false,
    "globalEvent" bool DEFAULT false,
    "mongoLocation" jsonb,
    "googleLocation" jsonb,
    "location" text,
    "contactInfo" text,
    "facebookLink" text,
    "meetupLink" text,
    "website" text,
    "eventImageId" text,
    "types" text[],
    "metaSticky" bool DEFAULT false,
    "sharingSettings" jsonb,
    "shareWithUsers" varchar(27)[],
    "linkSharingKey" text,
    "linkSharingKeyUsedBy" varchar(27)[],
    "commentSortOrder" text,
    "hideAuthor" bool DEFAULT false,
    "moderationStyle" text,
    "hideCommentKarma" bool DEFAULT false,
    "commentCount" real DEFAULT 0,
    "af" bool DEFAULT false,
    "afDate" timestamptz,
    "afCommentCount" real DEFAULT 0,
    "afLastCommentedAt" timestamptz,
    "afSticky" bool DEFAULT false,
    "suggestForAlignmentUserIds" text[],
    "reviewForAlignmentUserId" text,
    "agentFoundationsId" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "contents" jsonb,
    "contents_latest" text,
    "pingbacks" jsonb,
    "moderationGuidelines" jsonb,
    "moderationGuidelines_latest" text,
    "customHighlight" jsonb,
    "customHighlight_latest" text,
    "voteCount" real DEFAULT 0,
    "baseScore" real DEFAULT 0,
    "extendedScore" jsonb,
    "score" real DEFAULT 0,
    "inactive" bool,
    "afBaseScore" real,
    "afExtendedScore" jsonb,
    "afVoteCount" real)

-- Schema for "RSSFeeds", hash: a32e69e74455002ba789427da6e93fc9
CREATE TABLE "RSSFeeds" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "ownedByUser" bool DEFAULT false,
    "displayFullContent" bool DEFAULT false,
    "nickname" text,
    "url" text,
    "status" text,
    "rawFeed" jsonb,
    "setCanonicalUrl" bool DEFAULT false,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "ReadStatuses", hash: d1c905ef3299f77c42b6ebd199bd4a5c
CREATE TABLE "ReadStatuses" (
    _id varchar(27) PRIMARY KEY,
    "postId" varchar(27),
    "tagId" varchar(27),
    "userId" varchar(27),
    "isRead" bool,
    "lastUpdated" timestamptz,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Reports", hash: 294eca0999e7d427f532af7586c90295
CREATE TABLE "Reports" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "reportedUserId" varchar(27),
    "commentId" varchar(27),
    "postId" varchar(27),
    "link" text NOT NULL,
    "claimedUserId" varchar(27),
    "description" text,
    "closedAt" timestamptz,
    "markedAsSpam" bool,
    "reportedAsSpam" bool,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "ReviewVotes", hash: 1950f7acb1febc814234c50582649129
CREATE TABLE "ReviewVotes" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "postId" varchar(27),
    "qualitativeScore" integer DEFAULT 4,
    "quadraticScore" integer DEFAULT 0,
    "comment" text,
    "year" text DEFAULT '2018',
    "dummy" bool DEFAULT false,
    "reactions" text[],
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Revisions", hash: f18eca49e24add1ec60e0379a2029dbc
CREATE TABLE "Revisions" (
    _id varchar(27) PRIMARY KEY,
    "documentId" text,
    "collectionName" text,
    "fieldName" text,
    "editedAt" timestamptz,
    "autosaveTimeoutStart" timestamptz,
    "updateType" text,
    "version" text,
    "commitMessage" text,
    "userId" varchar(27),
    "draft" bool,
    "originalContents" jsonb,
    "html" text,
    "wordCount" real,
    "changeMetrics" jsonb,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "voteCount" real DEFAULT 0,
    "baseScore" real DEFAULT 0,
    "extendedScore" jsonb,
    "score" real DEFAULT 0,
    "inactive" bool,
    "afBaseScore" real,
    "afExtendedScore" jsonb,
    "afVoteCount" real)

-- Schema for "Sequences", hash: 25c6f64a5b3cea644cac1a984ae6ff92
CREATE TABLE "Sequences" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "title" text NOT NULL,
    "gridImageId" text,
    "bannerImageId" text,
    "curatedOrder" real,
    "userProfileOrder" real,
    "draft" bool DEFAULT false,
    "isDeleted" bool DEFAULT false,
    "canonicalCollectionSlug" text,
    "hidden" bool DEFAULT false,
    "hideFromAuthorPage" bool DEFAULT false,
    "af" bool DEFAULT false,
    "contents" jsonb,
    "contents_latest" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Spotlights", hash: ee68fa6dcaf4f6c81799f681c5243813
CREATE TABLE "Spotlights" (
    _id varchar(27) PRIMARY KEY,
    "documentId" text,
    "documentType" text DEFAULT 'Sequence',
    "position" real,
    "duration" real DEFAULT 3,
    "customTitle" text,
    "customSubtitle" text,
    "lastPromotedAt" timestamptz DEFAULT '{}',
    "draft" bool DEFAULT true,
    "spotlightImageId" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "description_latest" text)

-- Schema for "Subscriptions", hash: 1307862d294b4839d40438356a9ecab7
CREATE TABLE "Subscriptions" (
    _id varchar(27) PRIMARY KEY,
    "userId" varchar(27),
    "state" text,
    "documentId" text,
    "collectionName" text,
    "deleted" bool DEFAULT false,
    "type" text,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "TagFlags", hash: d251023f40d89878bfa8cc62a835086d
CREATE TABLE "TagFlags" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "deleted" bool DEFAULT false,
    "slug" text,
    "order" real,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "contents" jsonb,
    "contents_latest" text)

-- Schema for "TagRels", hash: e2bdcafa94134831f4be8ca70f5428b8
CREATE TABLE "TagRels" (
    _id varchar(27) PRIMARY KEY,
    "tagId" varchar(27),
    "postId" varchar(27),
    "deleted" bool DEFAULT false,
    "userId" varchar(27),
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "voteCount" real DEFAULT 0,
    "baseScore" real DEFAULT 0,
    "extendedScore" jsonb,
    "score" real DEFAULT 0,
    "inactive" bool,
    "afBaseScore" real,
    "afExtendedScore" jsonb,
    "afVoteCount" real)

-- Schema for "Tags", hash: f541ac3f23bdfb2583830989004f3971
CREATE TABLE "Tags" (
    _id varchar(27) PRIMARY KEY,
    "name" text,
    "slug" text,
    "oldSlugs" text[],
    "core" bool DEFAULT false,
    "suggestedAsFilter" bool DEFAULT false,
    "defaultOrder" real DEFAULT 0,
    "descriptionTruncationCount" real DEFAULT 0,
    "postCount" real DEFAULT 0,
    "userId" varchar(27),
    "adminOnly" bool DEFAULT false,
    "canEditUserIds" varchar(27)[],
    "charsAdded" real,
    "charsRemoved" real,
    "deleted" bool DEFAULT false,
    "lastCommentedAt" timestamptz,
    "lastSubforumCommentAt" timestamptz,
    "needsReview" bool DEFAULT true,
    "reviewedByUserId" varchar(27),
    "wikiGrade" integer DEFAULT 2,
    "wikiOnly" bool DEFAULT false,
    "bannerImageId" text,
    "tagFlagsIds" varchar(27)[],
    "lesswrongWikiImportRevision" text,
    "lesswrongWikiImportSlug" text,
    "lesswrongWikiImportCompleted" bool,
    "htmlWithContributorAnnotations" text,
    "contributionStats" jsonb,
    "introSequenceId" varchar(27),
    "postsDefaultSortOrder" text,
    "canVoteOnRels" text[],
    "isSubforum" bool DEFAULT false,
    "subforumModeratorIds" varchar(27)[],
    "parentTagId" varchar(27),
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "description_latest" text,
    "subforumWelcomeText_latest" text)

-- Schema for "UserTagRels", hash: e4f9bb0ef9bc34f63c6ffacbcaf79fce
CREATE TABLE "UserTagRels" (
    _id varchar(27) PRIMARY KEY,
    "tagId" varchar(27),
    "userId" varchar(27),
    "subforumLastVisitedAt" timestamptz,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

-- Schema for "Users", hash: dd0e0a33d17dd480d34e0785fcfe60b8
CREATE TABLE "Users" (
    _id varchar(27) PRIMARY KEY,
    "username" text,
    "emails" jsonb[],
    "isAdmin" bool,
    "isNotAdmin" bool,
    "profile" jsonb,
    "services" jsonb,
    "displayName" text,
    "previousDisplayName" text,
    "email" text,
    "slug" text,
    "noindex" bool DEFAULT false,
    "groups" text[],
    "lwWikiImport" bool,
    "theme" text,
    "lastUsedTimezone" text,
    "whenConfirmationEmailSent" timestamptz,
    "legacy" bool DEFAULT false,
    "commentSorting" text,
    "sortDraftsBy" text,
    "showHideKarmaOption" bool,
    "showPostAuthorCard" bool,
    "hideIntercom" bool DEFAULT false,
    "markDownPostEditor" bool DEFAULT false,
    "hideElicitPredictions" bool DEFAULT false,
    "hideAFNonMemberInitialWarning" bool DEFAULT false,
    "noSingleLineComments" bool DEFAULT false,
    "noCollapseCommentsPosts" bool DEFAULT false,
    "noCollapseCommentsFrontpage" bool DEFAULT false,
    "petrovOptOut" bool DEFAULT false,
    "hideNavigationSidebar" bool,
    "currentFrontpageFilter" text,
    "frontpageFilterSettings" jsonb,
    "allPostsTimeframe" text,
    "allPostsFilter" text,
    "allPostsSorting" text,
    "allPostsShowLowKarma" bool,
    "allPostsIncludeEvents" bool,
    "allPostsOpenSettings" bool,
    "draftsListSorting" text,
    "draftsListShowArchived" bool,
    "draftsListShowShared" bool,
    "lastNotificationsCheck" timestamptz,
    "karma" real,
    "goodHeartTokens" real,
    "moderationStyle" text,
    "moderatorAssistance" bool,
    "collapseModerationGuidelines" bool,
    "bannedUserIds" varchar(27)[],
    "bannedPersonalUserIds" varchar(27)[],
    "bookmarkedPostsMetadata" jsonb[],
    "hiddenPostsMetadata" jsonb[],
    "legacyId" text,
    "deleted" bool DEFAULT false,
    "voteBanned" bool,
    "nullifyVotes" bool,
    "deleteContent" bool,
    "banned" timestamptz,
    "auto_subscribe_to_my_posts" bool DEFAULT true,
    "auto_subscribe_to_my_comments" bool DEFAULT true,
    "autoSubscribeAsOrganizer" bool DEFAULT true,
    "notificationCommentsOnSubscribedPost" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationShortformContent" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationRepliesToMyComments" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationRepliesToSubscribedComments" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationSubscribedUserPost" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationPostsInGroups" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationSubscribedTagPost" jsonb DEFAULT '{"channel": ' onsite ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationPrivateMessage" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationSharedWithMe" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationAlignmentSubmissionApproved" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationEventInRadius" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationRSVPs" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationGroupAdministration" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationCommentsOnDraft" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "notificationPostsNominatedReview" jsonb DEFAULT '{"channel": ' both ',"batchingFrequency": ' realtime ',"timeOfDayGMT": 12,"dayOfWeekGMT": ' Monday '}',
    "karmaChangeNotifierSettings" jsonb DEFAULT '{"updateFrequency": ' daily ',"timeOfDayGMT": 11,"dayOfWeekGMT": ' Saturday ',"showNegativeKarma": false}',
    "karmaChangeLastOpened" timestamptz,
    "karmaChangeBatchStart" timestamptz,
    "emailSubscribedToCurated" bool,
    "subscribedToDigest" bool DEFAULT false,
    "unsubscribeFromAll" bool,
    "hideSubscribePoke" bool DEFAULT false,
    "hideMeetupsPoke" bool DEFAULT false,
    "frontpagePostCount" real DEFAULT 0,
    "sequenceCount" real DEFAULT 0,
    "sequenceDraftCount" real DEFAULT 0,
    "mongoLocation" jsonb,
    "googleLocation" jsonb,
    "location" text,
    "mapLocation" jsonb,
    "mapLocationSet" bool,
    "mapMarkerText" text,
    "htmlMapMarkerText" text,
    "nearbyEventsNotifications" bool DEFAULT false,
    "nearbyEventsNotificationsLocation" jsonb,
    "nearbyEventsNotificationsMongoLocation" jsonb,
    "nearbyEventsNotificationsRadius" real,
    "nearbyPeopleNotificationThreshold" real,
    "hideFrontpageMap" bool,
    "hideTaggingProgressBar" bool,
    "hideFrontpageBookAd" bool,
    "hideFrontpageBook2019Ad" bool,
    "sunshineNotes" text DEFAULT '',
    "sunshineFlagged" bool DEFAULT false,
    "needsReview" bool DEFAULT false,
    "sunshineSnoozed" bool DEFAULT false,
    "snoozedUntilContentCount" real,
    "reviewedByUserId" varchar(27),
    "reviewedAt" timestamptz,
    "afKarma" real DEFAULT false,
    "voteCount" real,
    "smallUpvoteCount" real,
    "smallDownvoteCount" real,
    "bigUpvoteCount" real,
    "bigDownvoteCount" real,
    "fullName" text,
    "shortformFeedId" varchar(27),
    "viewUnreviewedComments" bool,
    "partiallyReadSequences" jsonb[],
    "beta" bool,
    "reviewVotesQuadratic" bool,
    "reviewVotesQuadratic2019" bool,
    "reviewVotesQuadratic2020" bool,
    "petrovPressedButtonDate" timestamptz,
    "petrovLaunchCodeDate" timestamptz,
    "defaultToCKEditor" bool,
    "signUpReCaptchaRating" real,
    "oldSlugs" text[],
    "noExpandUnreadCommentsReview" bool DEFAULT false,
    "postCount" real DEFAULT 0,
    "maxPostCount" real DEFAULT 0,
    "commentCount" real DEFAULT 0,
    "maxCommentCount" real DEFAULT 0,
    "tagRevisionCount" real DEFAULT 0,
    "abTestKey" text,
    "abTestOverrides" jsonb,
    "reenableDraftJs" bool,
    "walledGardenInvite" bool,
    "hideWalledGardenUI" bool,
    "walledGardenPortalOnboarded" bool,
    "taggingDashboardCollapsed" bool,
    "usernameUnset" bool DEFAULT false,
    "paymentEmail" text,
    "paymentInfo" text,
    "profileImageId" text,
    "jobTitle" text,
    "organization" text,
    "careerStage" text[],
    "website" text,
    "fmCrosspostUserId" text,
    "linkedinProfileURL" text,
    "facebookProfileURL" text,
    "twitterProfileURL" text,
    "githubProfileURL" text,
    "profileTagIds" varchar(27)[],
    "organizerOfGroupIds" varchar(27)[],
    "programParticipation" text[],
    "postingDisabled" bool,
    "allCommentingDisabled" bool,
    "commentingOnOtherUsersDisabled" bool,
    "conversationsDisabled" bool,
    "acknowledgedNewUserGuidelines" bool,
    "afPostCount" real DEFAULT 0,
    "afCommentCount" real DEFAULT 0,
    "afSequenceCount" real DEFAULT 0,
    "afSequenceDraftCount" real DEFAULT 0,
    "reviewForAlignmentForumUserId" text,
    "afApplicationText" text,
    "afSubmittedApplication" bool,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz,
    "moderationGuidelines" jsonb,
    "moderationGuidelines_latest" text,
    "howOthersCanHelpMe_latest" text,
    "howICanHelpOthers_latest" text,
    "biography_latest" text,
    "recommendationSettings" jsonb)

-- Schema for "Votes", hash: 24debedd70935759e8bfd1b3db4e6d29
CREATE TABLE "Votes" (
    _id varchar(27) PRIMARY KEY,
    "documentId" text,
    "collectionName" text,
    "userId" varchar(27),
    "authorIds" varchar(27)[],
    "voteType" text,
    "extendedVoteType" jsonb,
    "power" real,
    "afPower" real,
    "cancelled" bool DEFAULT false,
    "isUnvote" bool DEFAULT false,
    "votedAt" timestamptz,
    "documentIsAf" bool DEFAULT false,
    "schemaVersion" real DEFAULT 1,
    "createdAt" timestamptz)

