import { registerMigration } from './migrationUtils';
import Users from '../../lib/collections/users/collection';
import { createMutator, Utils } from '../vulcan-lib';
import { Posts } from '../../lib/collections/posts';
import { mapsAPIKeySetting } from '../../components/form-components/LocationFormComponent';
import fetch from 'node-fetch';
import { getLocalTime } from '../mapsUtils';
import { userFindByEmail } from '../../lib/vulcan-users/helpers';

async function coordinatesToGoogleLocation({ lat, lng }: { lat: string, lng: string }) {
  const requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };
  
  const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${mapsAPIKeySetting.get()}`, requestOptions)
  const responseText = await response.text()
  const responseData = JSON.parse(responseText)
  return responseData.results[0]
}

registerMigration({
  name: "importACXMeetups2022",
  dateWritten: "2022-08-22",
  idempotent: true,
  action: async () => {
    // eslint-disable-next-line no-console
    console.log(`Beginning to import ${Object.keys(acxData).length}`)
    for (const row of acxData) {
      let eventOrganizer
      // Figure out whether user with emailAddress already exists
      const existingUser = row.emailAddress ? await userFindByEmail(row.emailAddress) : undefined
      // If not, create them (and send them an email, maybe?)
      if (existingUser) {
        eventOrganizer = existingUser
      } else {
        const { data: newUser } = await createMutator({
          collection: Users,
          document: {
            username: await Utils.getUnusedSlugByCollectionName("Users", row.nameInitialsHandle.toLowerCase()),
            displayName: row.nameInitialsHandle,
            email: row.emailAddress,
            reviewedByUserId: "XtphY3uYHwruKqDyG",
            reviewedAt: new Date()
          },
          validate: false,
          currentUser: null
        })
        eventOrganizer = newUser
      }
      
      let googleLocation
      if (row["lat"] && row['lng']) {
        googleLocation = await coordinatesToGoogleLocation({lat: row["lat"], lng: row["lng"]})
      }
      const eventTimePretendingItsUTC = new Date(`${row["dateMMDDYYYY"]} ${row["Time"]} UTC`)
      const localtime = eventTimePretendingItsUTC.getTime() ? await getLocalTime(eventTimePretendingItsUTC, googleLocation) : new Date();
      const actualTime = new Date(eventTimePretendingItsUTC.getTime() + (eventTimePretendingItsUTC.getTime() - (localtime?.getTime() || eventTimePretendingItsUTC.getTime())))
      // Then create event post with that user as owner, if it doesn't exist yet
      const title = `${row["City"]} – ACX Meetups Everywhere 2022`
      
      const existingPost = await Posts.findOne({ title });
      if (!existingPost) {
        const newPostData = {
          title,
          postedAt: new Date(),
          userId: eventOrganizer._id,
          submitToFrontpage: true,
          activateRSVPs: true,
          draft: false,
          meta: false,
          isEvent: true,
          frontpageDate: new Date(),
          reviewedByUserId: "r38pkCm7wF4M44MDQ",
          authorIsUnreviewed: false,
          contactInfo: row.emailAddress,
          location: `${row.City}`,
          startTime: eventTimePretendingItsUTC.getTime() ? actualTime : undefined,
          meetupLink: row.Meetup,
          facebookLink: row.FB,
          googleLocation,
          contents: {
            originalContents: {
              type: 'ckEditorMarkup',
              data: `<p>This year's ACX Meetup everywhere in ${row.City}.</p>
                <p>Location: ${row.locationDescription} – <a href="https://plus.codes/${row.Pluscodes}">${row.Pluscodes}</a></p>
                ${row["Notes"] ? `<p>${row["Notes"]}</p>` : ""}
                <p>Contact: ${row["emailAddress"]} ${row.additionalContactInfo ? `– ${row.additionalContactInfo}` : ""}</p>
                ${row.GroupInfo && 
                  `<h3>Group Info</h3>
                  <p>${row.GroupInfo}</p>
                  `
                }`
            },
            updateType: 'minor',
            commitMessage: ''
          },
          moderationStyle: 'easy-going',
          af: false,
          types: [
            'SSC'
          ],
        };
        const { data: newPost } = await createMutator({
          collection: Posts,
          document: newPostData,
          currentUser: eventOrganizer,
          validate: false
        })
        // eslint-disable-next-line no-console
        console.log("Created new ACX Meetup: ", newPost.title)
      } else {
        // eslint-disable-next-line no-console
        console.log("Meetup with this name already existed: ", title)
      }
    }
  }
})


const acxData = [{'City': 'Bryan/College Station, TX',
'nameInitialsHandle': 'Kenny',
'emailAddress': 'easwaran@gmail.com',
'dateMMDDYYYY': '9/9/2022',
'Time': '5:00 PM',
'lat': undefined,
'lng': undefined,
'locationDescription': "Back patio of Torchy's Tacos at Texas and New Main",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8625JMFC+5M',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Zurich, Switzerland',
'nameInitialsHandle': 'MB',
'emailAddress': 'acxzurich@proton.me',
'dateMMDDYYYY': '9/24/2022',
'Time': '3:00 PM',
'lat': undefined,
'lng': undefined,
'locationDescription': 'TBD',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': undefined,
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Lakewood, NJ',
'nameInitialsHandle': 'Ben L',
'emailAddress': 'mywebdev3@gmail.com',
'dateMMDDYYYY': '10/29/2022',
'Time': '8:30 PM',
'lat': undefined,
'lng': undefined,
'locationDescription': 'TBD',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': undefined,
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Cape Town, South Africa',
'nameInitialsHandle': 'Mark Chimes',
'emailAddress': 'chimes.mark@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '11:00 AM',
'lat': '-33.9273125',
'lng': '18.4241875',
'locationDescription': "Truth Coffee Roasting, 36 Buitenkant St, Cape Town City Centre - we'll put a sign on the table",
'Notes': "We're planning on having another meetup on the 8th October if you can't make the first.",
'additionalContactInfo': 'WhatsApp 0826568573',
'Pluscodes': '4FRW3CFF+3M',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We met up pre-Covid and pre-ACX as an SSC group. Now we're getting back in the swing of things. We eat lunch and chat about philosophy, politics, and sometimes SSC/ACX blog posts. "},
{'City': 'Dar es Salaam, Tanzania',
'nameInitialsHandle': 'Arno',
'emailAddress': 'arnorohwedder@gmail.com',
'dateMMDDYYYY': '9/29/2022',
'Time': '7:30 PM',
'lat': '-6.7375625',
'lng': '39.2805625',
'locationDescription': 'The Deck, Masaki',
'Notes': 'Seeing if there are any interested people in Dar, look forward to meeting, if you are coming please send me a whatsapp.',
'additionalContactInfo': '+255763998637',
'Pluscodes': '6G5X776J+X6',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Calgary, AB',
'nameInitialsHandle': 'David Piepgrass',
'emailAddress': 'qwertie256@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '51.0560375',
'lng': '-113.978515625',
'locationDescription': 'Marlborough Mall food court',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9538324C+CH9',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "It's small!"},
{'City': 'Vancouver, BC',
'nameInitialsHandle': 'Tom Ash and Dirk Haupt',
'emailAddress': 'events@philosofiles.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '1:00 PM',
'lat': '49.2643125',
'lng': '-123.0961875',
'locationDescription': "Dude Chilling (aka Guelph) Park, near the intersection of Main, Broadway & Kingsway. We'll be just west of the garden - look for Tom in a neon yellow shirt.",
'Notes': "🍣  We'll have a sushi lunch for everyone who comes (fish or vegan). This is not at all necessary, but posting on the Facebook event to say you will or won't want this will help estimate numbers. RSVPing there will help boost attendance too.",
'additionalContactInfo': undefined,
'Pluscodes': '84XR7W73+PG',
'FB': 'https://www.facebook.com/events/593192119179410/',
'Meetup': undefined,
'GroupInfo': 'For future events, join the following: For rationalism, [this Facebook group](https://www.facebook.com/groups/vanrationality), for effective altruism, [this Facebook group](https://www.facebook.com/groups/vancouvereffectivealtruists) for both, [Meetup.com](https://www.meetup.com/effective-altruism/)'},
{'City': 'Victoria, BC',
'nameInitialsHandle': 'Sarah McManus',
'emailAddress': 'sarahmcmanusbc@gmail.com',
'dateMMDDYYYY': '9/23/2022',
'Time': '7:00 PM',
'lat': '48.4764375',
'lng': '-123.3323125',
'locationDescription': "Snowy Village, 4071 Shelbourne St #2a, Victoria, BC V8N 5Y1 - It's a small cafe, I'll be at a table with an ACX MEETUP sign on it",
'Notes': undefined,
'additionalContactInfo': 'Twitter @SarahAMcManus',
'Pluscodes': '84WRFMG9+H3',
'FB': 'https://www.facebook.com/events/5708264749193151/',
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Halifax, NS',
'nameInitialsHandle': 'Conor Barnes (ideopunk)',
'emailAddress': 'conorbarnes93@gmail.com',
'dateMMDDYYYY': '9/25/2022',
'Time': '1:00 PM',
'lat': '44.6509375',
'lng': '-63.5814375',
'locationDescription': 'Seven Bays Cafe (2017 Gottingen Street)',
'Notes': 'Join us at Seven Bayes',
'additionalContactInfo': undefined,
'Pluscodes': '87PRMC29+9C',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Ottawa, ON',
'nameInitialsHandle': 'Tess Walsh',
'emailAddress': 'rationalottawa@gmail.com',
'dateMMDDYYYY': '9/16/2022',
'Time': '6:00 PM',
'lat': '45.4067625',
'lng': '-75.675796875',
'locationDescription': "We are meeting at the Atelier d'innovation sociale, located at 95 Clegg St, K1S1C5. Specifically in the Lounge area, there will be numerous signs for ACX MEETUP where needed.",
'Notes': "I always appreciate RSVP's in any form! It helps me set expectations/plan the best meetup I can! You can also contact me, Tess Walsh, with any questions whatsoever at rationalottawa@gmail.com",
'additionalContactInfo': undefined,
'Pluscodes': '87Q6C84F+PM4',
'FB': 'https://www.facebook.com/events/375274231447988',
'Meetup': undefined,
'GroupInfo': 'We meet weekly on Friday evenings, and that allows us enough opportunity to try out a huge variety of different types of events — probably some that you, yes you, would enjoy! Here are our [Facebook](https://www.facebook.com/groups/rationalottawa), [LessWrong](https://www.lesswrong.com/groups/PB4YL2K54CzmQDtC4), and [Discord](https://discord.gg/zk7aAFt6FZ) (where the action really is)'},
{'City': 'Huntsville, AL',
'nameInitialsHandle': 'Mike',
'emailAddress': 'mjhouse@protonmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '3:00 PM',
'lat': '34.7154375',
'lng': '-86.6723125',
'locationDescription': "Barnes & Noble – 300 The Bridge St #100, Huntsville, AL 35806. I'll be in the cafe with a sign that says ACX MEETUP on it.",
'Notes': "Barnes & Noble has an area for little kids. If you want to bring a service animal, that's probably fine, but I doubt they allow pets.",
'additionalContactInfo': undefined,
'Pluscodes': '866MP88H+53',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Phoenix, AZ',
'nameInitialsHandle': 'Ben Morin',
'emailAddress': 'benjamin.j.morin@gmail.com',
'dateMMDDYYYY': '10/15/2022',
'Time': '1:00 PM',
'lat': '33.4930625',
'lng': '-112.1114375',
'locationDescription': 'Thirsty Lion Pub in Tempe. I will have a table with an ACX sign.',
'Notes': "Please email if interested to be added to the email list, even if you can't make this event",
'additionalContactInfo': undefined,
'Pluscodes': '8559FVVQ+6C',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'This will be our 5th meetup (started during the meetups everywhere last year). '},
{'City': 'Belmont, CA',
'nameInitialsHandle': 'Moshe Z.',
'emailAddress': 'belmont-acx@devskillup.com',
'dateMMDDYYYY': '9/4/2022',
'Time': '2:00 PM',
'lat': '37.5170625',
'lng': '-122.277921875',
'locationDescription': "Twin Pines Park, Picnic Tables. The table will have some sign saying 'ACX Meetup' on it.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '849VGP8C+RRG',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "You can join the mailing list [here](https://buttondown.email/belmont-acx). There's also a [Discord server](https://discord.gg/2HEZfsqPCQ) for the whole Bay Area."},
{'City': 'Berkeley, CA',
'nameInitialsHandle': 'Scott',
'emailAddress': undefined,
'dateMMDDYYYY': '9/17/2022',
'Time': '1:00 PM',
'lat': '37.8599875',
'lng': '-122.259328125',
'locationDescription': 'Rose Garden Inn, a rationalist event space at 2740 Telegraph Ave. Come in through the front gate on Telegraph.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '849VVP5R+X7V',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'The Bay rationality community has a [mailing list](https://groups.google.com/g/bayarealesswrong), a [Discord server](https://discord.gg/Yqus2bFhww), and a [Facebook group](https://www.facebook.com/groups/566160007909175/). There are dinner meetups every Thursday at 7 PM in the East Bay, and occasional meetups in SF and South Bay.'},
{'City': 'Fillmore, CA',
'nameInitialsHandle': 'Ryan',
'emailAddress': 'wiserd@gmail.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '6:00 PM',
'lat': '34.3946875',
'lng': '-118.9005625',
'locationDescription': "It's my house. There are a bunch of plants on the porch and garbage bins in the driveway. ",
'Notes': 'Please RSVP to my email or Discord. Kids and dogs are welcome in the back yard. Full vaccinations (on the honor system) and masks required. ',
'additionalContactInfo': 'Discord: Wiserd#0906',
'Pluscodes': '856393VX+VQ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Grass Valley, CA',
'nameInitialsHandle': 'Max Harms',
'emailAddress': 'raelifin@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '39.2160625',
'lng': '-121.0720625',
'locationDescription': "Condon Park by the prospector statue. In the case of rain we'll change the location to a residence, so RSVP to get updated! ",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '84FW6W8H+C5',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Irvine, CA',
'nameInitialsHandle': 'Nick C',
'emailAddress': 'cohenskijanuary1@mail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '2:00 PM',
'lat': '33.6506875',
'lng': '-117.8385625',
'locationDescription': 'University Town Center',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8554M526+7H',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet once a month at the same location.'},
{'City': 'Newport Beach, CA',
'nameInitialsHandle': 'Michael M',
'emailAddress': 'michaelmichalchik@gmail.com',
'dateMMDDYYYY': '8/27/2022',
'Time': '2:00 PM',
'lat': '33.6173625',
'lng': '-117.858890625',
'locationDescription': 'Picnic tables next to 1900 Port Carlow community clubhouse. The park is verdant and pleasant and easy to access. Free street parking nearby. In case of bad weather, we have a couple of near by places to relocate to.',
'Notes': "Its a public park with tables and BBQ's so you can bring food and well behaved pets. We may regularly go on casual walks in the surrounding area. ",
'additionalContactInfo': undefined,
'Pluscodes': '8554J48R+WCX',
'FB': 'https://www.facebook.com/groups/883959279640466',
'Meetup': undefined,
'GroupInfo': 'We will meet most Saturdays at 2pm until whenever. There will be short suggested readings and question most weeks to spur conversation, but they are optional. Each week we will ask if people have had something happen recently that surprised them or changed the way they looked at the world. Something that should or did update their priors. Participation is optional. '},
{'City': 'San Diego, CA',
'nameInitialsHandle': 'Julius',
'emailAddress': 'julius.simonelli@gmail.com',
'dateMMDDYYYY': '10/9/2022',
'Time': '3:00 PM',
'lat': '32.7394375',
'lng': '-117.1343125',
'locationDescription': 'We will meet up in Bird Park. I will be wearing a red shirt.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8544PVQ8+Q7',
'FB': undefined,
'Meetup': 'https://www.meetup.com/san-diego-rationalists/events/287922342/',
'GroupInfo': 'Join our [Discord server](https://discord.gg/QcVx7kjj33)'},
{'City': 'San Francisco, CA',
'nameInitialsHandle': 'Derek Pankaew',
'emailAddress': 'derekpankaew@gmail.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '11:00 AM',
'lat': '37.7721875',
'lng': '-122.4466875',
'locationDescription': "We'll between in the Panhandle, between Ashbury and Masonic, with a 'ACX' sign.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '849VQHC3+V8',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'San Jose, CA',
'nameInitialsHandle': 'David Friedman',
'emailAddress': 'ddfr@daviddfriedman.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '2:00 PM',
'lat': '37.3080625',
'lng': '-121.9681875',
'locationDescription': '3806 Williams Rd, San Jose, CA 95117',
'Notes': 'Kids are welcome. Please RSVP to my email so I will have a rough count of how many we are feeding.',
'additionalContactInfo': undefined,
'Pluscodes': '849W825J+6P',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Before Covid we hosted every month or two. No structure, just conversation and food. We feed everyone who is still there at dinner time. We have done it once or twice since Covid. I have an email list of interested people.'},
{'City': 'San Marcos, CA',
'nameInitialsHandle': 'Eric F.',
'emailAddress': 'EricF14159@gmail.com',
'dateMMDDYYYY': '9/25/2022',
'Time': '3:00 PM',
'lat': '33.1470625',
'lng': '-117.1428125',
'locationDescription': 'Hollandia Park Soccer Field. At the tables near the top parking lot.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '85544VW4+RV',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Carbondale, CO',
'nameInitialsHandle': 'Nick',
'emailAddress': 'naj@njarboe.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '1:00 PM',
'lat': '39.3994375',
'lng': '-107.213328125',
'locationDescription': 'Sopris Park - Center covered picnic tables - blue shirt with ACX sign on table',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '85FJ9QXP+QMF',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Lakewood, CO',
'nameInitialsHandle': 'Steven Zuber',
'emailAddress': 'stevenjzuber@gmail.com',
'dateMMDDYYYY': '10/5/2022',
'Time': '7:00 PM',
'lat': '39.6616875',
'lng': '-105.0926875',
'locationDescription': 'We meet in the clubhouse located in this townhome community: 8769 W Cornell Ave Lakewood, CO  80227',
'Notes': 'Check the [Meetup page](https://www.meetup.com/colorado-rationality/events/287917731/) or [Facebook group](https://www.facebook.com/groups/969594296461197/) for updates.',
'additionalContactInfo': undefined,
'Pluscodes': '85FPMW64+MW',
'FB': undefined,
'Meetup': 'https://www.meetup.com/colorado-rationality/events/287917731/',
'GroupInfo': 'We meet the first Wednesday of every month. Informal, casual atmosphere with occasional presentations by people. '},
{'City': 'Fairfield, CT',
'nameInitialsHandle': 'Justin Barclay',
'emailAddress': 'barclay.justin@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '10:00 AM',
'lat': '41.1210625',
'lng': '-73.2708125',
'locationDescription': "South Pine Creek Beach. I'll set up near the lifeguard stand.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87H84PCH+CM',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Manchester, CT',
'nameInitialsHandle': 'Mike',
'emailAddress': 'park-mike@outlook.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '5:00 PM',
'lat': '41.7740625',
'lng': '-72.5218125',
'locationDescription': 'Near flagpole on top of hill',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87H9QFFH+J7',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'New Haven, CT',
'nameInitialsHandle': 'RM',
'emailAddress': 'acx.meetup.nhv@gmail.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '12:30 PM',
'lat': '41.3108125',
'lng': '-72.927796875',
'locationDescription': "Cross Campus (Yale University), New Haven, CT 06511. We'll be on the grass on the northern half of Cross Campus, closest to Sterling Memorial Library. I'll be wearing an orange shirt.",
'Notes': "Feel free to bring friends! The vibe will be welcoming and relaxed, and you can stay for any amount of time. Please email me if you're thinking about coming so I can get the right number of Insomnia cookies!",
'additionalContactInfo': undefined,
'Pluscodes': '87H9836C+8VG',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Cape Coral / Fort Myers, FL',
'nameInitialsHandle': 'Shawn Spilman',
'emailAddress': 'shawn.spilman@outlook.com',
'dateMMDDYYYY': '10/2/2022',
'Time': '1:00 PM',
'lat': '26.5503125',
'lng': '-81.9946875',
'locationDescription': '929 SW 54th Ln, Cape Coral, FL 33914',
'Notes': 'RSVP via email. I can be flexible about the date.',
'additionalContactInfo': '508 655 8123',
'Pluscodes': '76RWH224+44',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Gulf Breeze / Pensacola, FL',
'nameInitialsHandle': 'Christian',
'emailAddress': 'christian.h.williams@gmail.com',
'dateMMDDYYYY': '10/12/2022',
'Time': '7:30 PM',
'lat': '30.3713125',
'lng': '-87.1769375',
'locationDescription': 'The Bridge Bar - 33 Gulf Breeze Pkwy A, Gulf Breeze, FL 32561',
'Notes': "Please RSVP by emailing me. Thanks! If I don't hear from anyone, I won't be there. I work for Metaculus, but promise not to talk your ear off about forecasting. (Unless you want it talked off.) ",
'additionalContactInfo': undefined,
'Pluscodes': '862J9RCF+G6',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Tallahassee, FL',
'nameInitialsHandle': 'JF',
'emailAddress': 'jf19o@fsu.edu',
'dateMMDDYYYY': '8/29/2022',
'Time': '2:00 PM',
'lat': '30.4418125',
'lng': '-84.2950625',
'locationDescription': 'Landis, FSU. I will be wearing a black shirt',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '862QCPR3+PX',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Athens, GA',
'nameInitialsHandle': 'Dallon',
'emailAddress': 'knox.dallon.a@gmail.com',
'dateMMDDYYYY': '10/15/2022',
'Time': '3:00 PM',
'lat': '33.9600625',
'lng': '-83.3826875',
'locationDescription': 'Hendershots on Prince Avenue',
'Notes': 'I might bring some board games',
'additionalContactInfo': 'Discord: leonard#4208',
'Pluscodes': '865RXJ68+2W',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Atlanta, GA',
'nameInitialsHandle': 'Steve French',
'emailAddress': 'steve@digitaltoolfactory.net',
'dateMMDDYYYY': '9/17/2022',
'Time': '2:00 PM',
'lat': '33.8021875',
'lng': '-84.4266875',
'locationDescription': 'Bold Monk Brewing - 1737 Ellsworth Industrial Blvd NW suite d-1 · Atlanta, GA (upstairs – look for\xa0the ACX Atlanta sign)',
'Notes': 'Please RSVP on LessWrong or [Meetup.com](https://www.meetup.com/acx-atlanta/events/287993740/)',
'additionalContactInfo': undefined,
'Pluscodes': '865QRH2F+V8',
'FB': undefined,
'Meetup': 'https://www.meetup.com/acx-atlanta/events/287993740/',
'GroupInfo': "We've been in existence for four years – we have a dedicated crew and a very active Slack group"},
{'City': 'Honolulu, HI',
'nameInitialsHandle': 'Matt Popovich',
'emailAddress': 'mattpopovich@outlook.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '4:00 PM',
'lat': '21.2840625',
'lng': '-157.8456875',
'locationDescription': "We'll meet at Magic Island at Ala Moana Beach Park, 1201 Ala Moana Blvd, Honolulu, HI 96814. From the parking lot, walk along the left side of the peninsula out toward Magic Island Lagoon. We're usually near the end of the peninsula, somewhere around the bathroom building. Look for the large 'ACX' sign.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '73H475M3+JP',
'FB': undefined,
'Meetup': 'https://www.meetup.com/honolulurationality/events/287808458/',
'GroupInfo': 'Honolulu Rationality hosts discussion meetups about twice a month in Ala Moana Beach Park. Check us out at https://honolulurationality.com'},
{'City': 'Boise, ID',
'nameInitialsHandle': 'Julia and John',
'emailAddress': 'jae.miomu@gmail.com',
'dateMMDDYYYY': '10/7/2022',
'Time': '6:00 PM',
'lat': '43.6109375',
'lng': '-116.2144375',
'locationDescription': "Old Timer's Shelter in Ann Morrison Park. I will have an ACX sign.",
'Notes': 'Please RSVP and feel free to bring kids.',
'additionalContactInfo': undefined,
'Pluscodes': '85M5JQ6P+96',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Chicago, IL',
'nameInitialsHandle': 'Todd',
'emailAddress': 'info@chicagorationality.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '1:00 PM',
'lat': '41.8733125',
'lng': '-87.6221875',
'locationDescription': 'Grant Park - North side of Balbo between the tracks and Columbus',
'Notes': 'Sign up for our [email list](https://chicagorationality.com) to be notified of future meetups',
'additionalContactInfo': 'https://chicagorationality.com',
'Pluscodes': '86HJV9FH+84',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': '[Chicago Rationality](https://chicagorationality.com) does a monthly discussion meetup (typically the first Saturday of the month) and a monthly social meetup (typically the third weekend of the month)'},
{'City': 'Evanston, IL',
'nameInitialsHandle': 'Uzair',
'emailAddress': 'uzairq93@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '7:00 PM',
'lat': '42.0479625',
'lng': '-87.680140625',
'locationDescription': '626 Church Street, Evanston IL 60201',
'Notes': "The venue is a pub but it's really more of a restaurant, big long tables available so space should be fine and non drinkers shouldn't feel too out of place. ",
'additionalContactInfo': undefined,
'Pluscodes': '86JJ28X9+5WQ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Bloomington, IN',
'nameInitialsHandle': 'Avery',
'emailAddress': 'acxbloomington@fastmail.com',
'dateMMDDYYYY': '10/16/2022',
'Time': '2:00 PM',
'lat': '39.1478125',
'lng': '-86.5380625',
'locationDescription': 'Switchyard Park. Will be at one of the tables near the Rogers Street parking lot. I will bring a cardboard sign that says “ACX”.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86FM4FX6+4Q',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We met last year for Meetups Everywhere and it was fun! Here's a link to [our Discord](https://discord.com/invite/jvN2p3HB)."},
{'City': 'West Lafayette, IN',
'nameInitialsHandle': 'NR',
'emailAddress': 'mapreader4@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '1:00 PM',
'lat': '40.4256625',
'lng': '-86.924921875',
'locationDescription': "1275 1st Street, West Lafayette, IN 47906. We'll be in the south of the Earhart Hall lobby (not the dining court) near the piano, and I will be wearing a green shirt and carrying a sign with ACX MEETUP on it.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86GMC3GG+728',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Lexington, KY',
'nameInitialsHandle': 'Nathan',
'emailAddress': 'nwculley@gmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '7:00 PM',
'lat': '38.0571875',
'lng': '-84.5013125',
'locationDescription': 'Blue Stallion Brewing. 610 W. 3rd St., Lexington, KY 40508. We will have a sign indicating we are the ACX meetup.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86CQ3F4X+VF',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet 1-2 times a month to talk about ACX, books, memes, etc., often over drinks and board games.'},
{'City': 'New Orleans, LA',
'nameInitialsHandle': 'Blake',
'emailAddress': 'blake@philosophers.group',
'dateMMDDYYYY': '9/4/2022',
'Time': '11:11 AM',
'lat': '29.9633125',
'lng': '-90.0454375',
'locationDescription': 'Petite Clouet Cafe. Look for the group with an iPad that has a People’s Pint sticker. ',
'Notes': 'Hybrid in-person and online, video link sent weekly. Email for the link. ',
'additionalContactInfo': undefined,
'Pluscodes': '76XFXX73+8R',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': '[Website](https://bbertucc.notion.site/Sunday-Open-Hangs-at-11-11-f5ce807c86c3470b870d9f679a9ee72d)'},
{'City': 'Boston, MA',
'nameInitialsHandle': 'Robi Rahman',
'emailAddress': 'robirahman94@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '5:00 PM',
'lat': '42.3543125',
'lng': '-71.0654375',
'locationDescription': 'Boston Common, at the Parkman Bandstand gazebo',
'Notes': "We'll be providing food at the meetup, and giving out free books related to ACX, rationality, and effective altruism. Email the hosts if you'd like a particular book or you have any dietary restrictions.",
'additionalContactInfo': '7039818526',
'Pluscodes': '87JC9W3M+PR',
'FB': 'https://www.facebook.com/events/3267233143606936',
'Meetup': undefined,
'GroupInfo': '[Mailing list](https://groups.google.com/g/ssc-boston)\n[Facebook group](https://www.facebook.com/groups/1023018131571906/)\n[Meetup.com](https://www.meetup.com/boston-astral-codex-meetup/)'},
{'City': 'Baltimore, MD',
'nameInitialsHandle': 'Rivka',
'emailAddress': 'rivka@adrusi.com',
'dateMMDDYYYY': '9/11/2022',
'Time': '7:00 PM',
'lat': '39.2554375',
'lng': '-76.7148125',
'locationDescription': 'UMBC outside of the Performing Arts and Humanities Building. I will have a sign that says ACX meetup. Parking is free on the weekends. ',
'Notes': 'There will be pizza and drinks',
'additionalContactInfo': undefined,
'Pluscodes': '87F5774P+53',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet Sundays at 7pm — half are in person and half are virtual. '},
{'City': 'Kansas City, MO',
'nameInitialsHandle': 'Alex',
'emailAddress': 'alex.hedtke@gmail.com',
'dateMMDDYYYY': '9/16/2022',
'Time': '6:30 PM',
'lat': '39.0345625',
'lng': '-94.5829375',
'locationDescription': 'We will be in the courtyard above Whole Foods (which is also an apartment complex). You can enter through the apartment lobby, located on Oak Street. We will have runners shepherding people from the entrance up to the courtyard. ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86F72CM8+RR',
'FB': undefined,
'Meetup': 'https://meetu.ps/e/LnmZ4/BSLmD/i',
'GroupInfo': undefined},
{'City': 'Saint Louis, MO',
'nameInitialsHandle': 'JohnBuridan',
'emailAddress': 'littlejohnburidan@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '1:00 PM',
'lat': '38.6074375',
'lng': '-90.2578125',
'locationDescription': 'Lily Pond Shelter, Tower Grove Park, St. Louis',
'Notes': 'BYOB',
'additionalContactInfo': undefined,
'Pluscodes': '86CFJP4R+XV',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'West Plains, MO',
'nameInitialsHandle': 'Liam',
'emailAddress': 'liamhession@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '12:00 PM',
'lat': '36.7285625',
'lng': '-91.8528125',
'locationDescription': '10/40 Coffee, 24 Court Square, West Plains, MO',
'Notes': 'Hoping to get anyone from around the Ozark region',
'additionalContactInfo': undefined,
'Pluscodes': '868CP4HW+CV',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Princeton, NJ',
'nameInitialsHandle': 'Danny K',
'emailAddress': 'dskumpf@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '3:00 PM',
'lat': '40.3500875',
'lng': '-74.661421875',
'locationDescription': "Palmer Square, Princeton, NJ 08540. On the green right outside The Bent Spoon and Rojo's Roastary, near the big tree. I'll have some sort of ACX Meetup sign!",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87G7982Q+2CP',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Las Vegas, NV',
'nameInitialsHandle': 'Jonathan Ray',
'emailAddress': 'ray.jonathan.w@gmail.com',
'dateMMDDYYYY': '9/11/2022',
'Time': '11:45 AM',
'lat': '36.1276875',
'lng': '-115.1685625',
'locationDescription': 'At El Segundo Sol restaurant with giant ACX MEETUP signs',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '85864RHJ+3H',
'FB': 'https://www.facebook.com/events/318842413736336/',
'Meetup': undefined,
'GroupInfo': 'We meet regularly and mostly just socialize. We have a new [Discord server](https://discord.gg/bNem2CsQ?event=1009257520294010960).'},
{'City': 'Long Island, NY',
'nameInitialsHandle': 'Gabe',
'emailAddress': 'gabeaweil@gmail.com',
'dateMMDDYYYY': '10/21/2022',
'Time': '7:00 PM',
'lat': '40.8909375',
'lng': '-73.3540625',
'locationDescription': 'Whales Tale in Northport',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87G8VJRW+99',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'New York City, NY',
'nameInitialsHandle': 'Jasmine',
'emailAddress': 'jasminermj@gmail.com',
'dateMMDDYYYY': '9/11/2022',
'Time': '4:00 PM',
'lat': '40.7177625',
'lng': '-74.015953125',
'locationDescription': 'Pavillion @ Rockefeller Park, Warren St / River Terrace',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87G7PX9M+4J3',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Newburgh, NY',
'nameInitialsHandle': 'Pedro David Bonilla',
'emailAddress': 'proportionatetoevidence@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '10:00 AM',
'lat': '41.5213125',
'lng': '-74.0713125',
'locationDescription': '[Perkins Restaurant & Bakery](https://maps.app.goo.gl/G2FZ4QeiDWH6JZiM9), 1421 NY-300, Newburgh, NY 12550',
'Notes': undefined,
'additionalContactInfo': 'Cell 8452001681',
'Pluscodes': '87H7GWCH+GF',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Rochester, NY',
'nameInitialsHandle': 'Skivverus',
'emailAddress': 'skivverus@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '1:00 PM',
'lat': '43.2344625',
'lng': '-77.539546875',
'locationDescription': '4870 Culver Road; will be wearing a polo shirt, jeans, and glasses, and may or may not have figured out a sign due to just getting back from honeymoon. Look for a pair of parrots, one white, one green with a yellow/orange head.',
'Notes': 'Venue very near amusement park; non-bathroom, non-parking amenities are therefore available but not free. Plan accordingly. Not particularly attached to specific location named, just happen to live reasonably close to there; alternative suggestions acceptable. Canadian visitors also welcome should your logistics permit; airport transportation available.\nRSVP via Discord preferred, but email will also work. ',
'additionalContactInfo': 'Discord: Skivverus#5915',
'Pluscodes': '87M46FM6+Q5P',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Cleveland, OH',
'nameInitialsHandle': 'Jack Zhang',
'emailAddress': 'LukeZhao9@protonmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '1:00 PM',
'lat': '41.5112625',
'lng': '-81.611390625',
'locationDescription': 'Picnic tables at Wade Oval (university circle)',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86HWG96Q+GC5',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Columbus, OH',
'nameInitialsHandle': 'Daniel',
'emailAddress': 'daniel.m.adamiak@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '3:00 PM',
'lat': '39.9719375',
'lng': '-82.9463125',
'locationDescription': 'Jeffrey Park - [Clinton Shelter](https://w3w.co/appeal.august.post). I will be wearing a red shirt.',
'Notes': 'Email me if you want to be added to the mailing list to receive any updates or future invites. RSVPing is appreciated. ',
'additionalContactInfo': undefined,
'Pluscodes': '86FVX3C3+QF',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet once a month. We discuss EA, AI and other two letter initialisms. Occasionally we go for walks in local grottos and nature trails.'},
{'City': 'Toledo, OH',
'nameInitialsHandle': 'Scout',
'emailAddress': 'scout.sivar@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '12:00 PM',
'lat': '41.6709375',
'lng': '-83.5554375',
'locationDescription': 'Black Kite Coffee',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86HRMCCV+9R',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Oklahoma City, OK',
'nameInitialsHandle': 'bean',
'emailAddress': 'battleshipbean@gmail.com',
'dateMMDDYYYY': '10/9/2022',
'Time': '1:00 PM',
'lat': '35.6541875',
'lng': '-97.4776875',
'locationDescription': 'Edmond Public Library/Shannon Miller Park.  I will be wearing a hat that says USS Iowa on it.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8674MG3C+MW',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Had four people last year and a good time, moved to Edmond because a lot of us are up here.'},
{'City': 'Albany, OR',
'nameInitialsHandle': 'Keundefined (he/him)',
'emailAddress': 'kbitikofer@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '2:00 PM',
'lat': '44.6424125',
'lng': '-123.086484375',
'locationDescription': 'Bowman Park, Albany, Oregon. In or near the shelter. I will wear a bright red shirt and carry a sign with ACX MEETUP on it.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '84PRJWR7+XC6',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Corvallis, OR',
'nameInitialsHandle': 'Ethan Ashkie',
'emailAddress': 'ethanashkie@gmail.com',
'dateMMDDYYYY': '9/7/2022',
'Time': '6:00 PM',
'lat': '44.5596875',
'lng': '-123.2630625',
'locationDescription': 'Common Fields, in the reserved outdoor seating near the entrance',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '84PRHP5P+VQ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Portland, OR',
'nameInitialsHandle': 'Sam F Celarek',
'emailAddress': 'support@pearcommunity.com',
'dateMMDDYYYY': '9/9/2022',
'Time': '5:00 PM',
'lat': '45.5246875',
'lng': '-122.6746875',
'locationDescription': '205 NW 4th Ave',
'Notes': 'We would prefer you RSVP on Meetup.com a week beforehand so that we can get the right amount of food! ',
'additionalContactInfo': '513-432-3310, Discord: Sam Celarek#2845',
'Pluscodes': '84QVG8FG+V4',
'FB': undefined,
'Meetup': 'https://www.meetup.com/portland-effective-altruists-and-rationalists/events/287917611/',
'GroupInfo': 'Portland Effective Altruism and Rationality is very active. We have book clubs, bi-weekly AI safety meet-ups, bi-weekly topical meet-ups, bi-weekly socials, and have an active Discord. '},
{'City': 'Indiana, PA',
'nameInitialsHandle': 'Eric',
'emailAddress': 'ericindianapa@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '11:00 AM',
'lat': '40.6228125',
'lng': '-79.1516875',
'locationDescription': "Caffè Amadeus in downtown Indiana, PA. I will have a sign with 'ACX Meetup' on one of the tables. ",
'Notes': 'Please RSVP via email or text message so I know how many to expect.',
'additionalContactInfo': '717-256-2717',
'Pluscodes': '87G2JRFX+48',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Philadelphia, PA',
'nameInitialsHandle': 'Wes and Diana',
'emailAddress': 'rationalphilly@gmail.com',
'dateMMDDYYYY': '9/22/2022',
'Time': '6:30 PM',
'lat': '39.9486875',
'lng': '-75.1730625',
'locationDescription': 'The Philadelphia Ethical Society, 1906 Rittenhouse Square ',
'Notes': "We'll be ordering food from a local restaurant, so no need to eat first. BYOB",
'additionalContactInfo': undefined,
'Pluscodes': '87F6WRXG+FQ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We tend to meet in downtown Philly on the last Thursday of the month. We're aiming to make the Ethical Society our new steady location. We have many links: [Discord](https://discord.gg/46zb6hRVGB), [Google Calendar](https://calendar.google.com/calendar/u/0?cid=cmF0aW9uYWxwaGlsbHlAZ21haWwuY29t), [Facebook](https://www.facebook.com/groups/rationalphilly), [Meetup](https://www.meetup.com/philadelphia-rationalists/), [Google Group](https://groups.google.com/g/ACXPhiladelphia)"},
{'City': 'Pittsburgh, PA',
'nameInitialsHandle': 'Justin',
'emailAddress': 'pghacx@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '2:00 PM',
'lat': '40.4381375',
'lng': '-79.944328125',
'locationDescription': "Westinghouse Shelter @ Schenley Park (W Circuit Rd near Schenley Dr). We have the outdoor shelter reserved, so light rain shouldn't be a problem, but in the event of extreme weather, we may relocate indoors (our default 'contingency indoor location' is Crazy Mocha Coffee on 2100 Murray Ave in Squirrel Hill).",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87G2C3Q4+773',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We meet monthly-ish for general discussion and chit-chat, email me if you'd like to be notified of future meetups."},
{'City': 'State College, PA',
'nameInitialsHandle': 'John Slow',
'emailAddress': 'auk480@psu.edu',
'dateMMDDYYYY': '9/8/2022',
'Time': '5:00 PM',
'lat': '40.7964375',
'lng': '-77.8628125',
'locationDescription': 'Old Main. I will be carrying an ACX meetup sign.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87G4Q4WP+HV',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Providence, RI',
'nameInitialsHandle': 'James Bailey',
'emailAddress': 'feanor1600@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '4:00 PM',
'lat': '41.8300625',
'lng': '-71.4071875',
'locationDescription': 'Prospect Terrace park, to the right of the Roger Williams statue',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87HCRHJV+24',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Sioux Falls, SD',
'nameInitialsHandle': 'S. C.',
'emailAddress': 'villainsplus@protonmail.com',
'dateMMDDYYYY': '10/2/2022',
'Time': '5:00 PM',
'lat': '43.5322875',
'lng': '-96.722078125',
'locationDescription': "410 E 26th St, Sioux Falls, SD 57105 - the pavillion on the west side of McKenundefined Park, or the tables just south of it if I can't book it. I'll be the guy with the grill.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86M5G7JH+W57',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Memphis, TN',
'nameInitialsHandle': 'Michael',
'emailAddress': 'michael@postlibertarian.com',
'dateMMDDYYYY': '9/5/2022',
'Time': '1:00 PM',
'lat': '35.1519375',
'lng': '-90.013609375',
'locationDescription': 'French Truck Coffee at Crosstown Concourse, Central Atrium 1350 Concourse Ave, Memphis, TN 38104. We will be at one of the many tables near French Truck Coffee and I will have a sign that says ACX MEETUP.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '867F5X2P+QHC',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We meet about every month or so. We've been around since 2019 but only regularly since mid 2021 due to the pandemic. We have a [Discord server](https://discord.gg/Pv2W7rjHG3)."},
{'City': 'Nashville, TN',
'nameInitialsHandle': 'Ellen',
'emailAddress': 'enwiegand@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '11:00 AM',
'lat': '36.1524375',
'lng': '-86.8201875',
'locationDescription': "OneCity Nashville (8 City Blvd, Nashville, TN 37209), next to the volleyball courts. I'll have a pink ballcap that says SPINSTER on it.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '868M552H+XW',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Austin, TX',
'nameInitialsHandle': 'Silas Barta',
'emailAddress': 'sbarta@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '12:00 PM',
'lat': '30.3058125',
'lng': '-97.7389375',
'locationDescription': '4001 N Lamar, Austin Texas, park by Central Market near stone tables and tents',
'Notes': 'Location may change as we are talking to other venues',
'additionalContactInfo': undefined,
'Pluscodes': '86248746+8C',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': '[Austin LessWrong](http://austinlesswrong.com) has a weekly focused discussion, a weekly social mixer, a weekly online book club, and a monthly movie night. Been around since 2011.'},
{'City': 'Waco, TX',
'nameInitialsHandle': 'Mike',
'emailAddress': 'BaylorACX@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '1:00 PM',
'lat': '31.5771875',
'lng': '-97.1490625',
'locationDescription': "Cameron Park, picnic tables next to Jacob's Ladder",
'Notes': "Please email me if you're thinking about attending! Would love to start an ACX community here :)",
'additionalContactInfo': undefined,
'Pluscodes': '8634HVG2+V9',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Salt Lake City, UT',
'nameInitialsHandle': 'Ross Richey (aka Jeremiah)',
'emailAddress': 'wearenotsaved@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '3:00 PM',
'lat': '40.7471875',
'lng': '-111.8759375',
'locationDescription': 'Liberty Park near the ChargePoint stations',
'Notes': 'Will be outdoors. If the weather looks bad, email event organizer to check on location.',
'additionalContactInfo': undefined,
'Pluscodes': '85GCP4WF+VJ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet every other month, we do book clubs and movie nights as well.'},
{'City': 'Charlottesville, VA',
'nameInitialsHandle': 'RL',
'emailAddress': 'effectivealtruismatuva@gmail.com',
'dateMMDDYYYY': '9/4/2022',
'Time': '5:00 PM',
'lat': '38.0351375',
'lng': '-78.501046875',
'locationDescription': '12 Rotunda Drive Charlottesville, VA 22903 - We’ll meet at the picnic tables across the street from The Virginian. There will be an ACX sign.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '87C32FPX+3H4',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Reston, VA',
'nameInitialsHandle': 'James',
'emailAddress': 'jrbalch333@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '1:30 PM',
'lat': '38.9484375',
'lng': '-77.3375625',
'locationDescription': "The matchbox at 1900 Reston Station Blvd, Reston, VA 20190 on the 1st floor of the giant Google building. I'll be holding a copy of _Sapiens._",
'Notes': 'Email me to be added to the WhatsApp group',
'additionalContactInfo': undefined,
'Pluscodes': '87C4WMX6+9X',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Bellingham, WA',
'nameInitialsHandle': 'Alex',
'emailAddress': 'bellinghamrationalish@gmail.com',
'dateMMDDYYYY': '9/29/2022',
'Time': '5:30 PM',
'lat': '48.6988125',
'lng': '-122.4458125',
'locationDescription': 'Lake Padden Park, at one of the tables near the lake by the dog park',
'Notes': 'Please [RSVP on Meetup](https://www.meetup.com/bellingham-rationalish-community/events/287869950/) so I have an idea how many people to expect. Kids, animals, food, beverages, etc. are all welcome.',
'additionalContactInfo': undefined,
'Pluscodes': '84WVMHX3+GM',
'FB': undefined,
'Meetup': 'https://www.meetup.com/bellingham-rationalish-community/events/287869950/',
'GroupInfo': 'Bellingham Rationalish discusses (in good faith!) topics in and around rationality. We usually meet the evening of the last Wednesday of each month. Our first meeting was a 2021 ACX Everywhere meetup.'},
{'City': 'Madison, WI',
'nameInitialsHandle': 'Mary Wang',
'emailAddress': 'mmwang@wisc.edu',
'dateMMDDYYYY': '9/10/2022',
'Time': '1:00 PM',
'lat': '43.0549375',
'lng': '-89.4001875',
'locationDescription': "1022 High St. Blue house with red porches. If weather permits, we'll be in my large backyard, which has more seating now than last year. If rain, come in the side door. There will be air purifiers and open windows. Masks optional. Look for a sign at the end of the driveway that says ACX/SSC Meetup.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '86MG3H3X+XW',
'FB': 'https://fb.me/e/1YlydMulh',
'Meetup': undefined,
'GroupInfo': 'We have met fortnightly in the past, but quit last year when it got too cold to meet outside. We typically have shared a meal, sat around my kitchen table and talked. Have held a Solstice celebration. '},
{'City': 'San Juan, Puerto Rico',
'nameInitialsHandle': 'Dan Gelfarb',
'emailAddress': 'danielgelfarb@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '1:00 PM',
'lat': '18.4447625',
'lng': '-66.067359375',
'locationDescription': 'Lote 23, back corner under the tents. I will be wearing a blue shirt with a sign that says ACX meetup on it. ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '77CMCWVM+W32',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Wollongong, Australia',
'nameInitialsHandle': 'Jason ',
'emailAddress': 'jason.bowkettblogs@gmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '12:00 PM',
'lat': '-34.4069375',
'lng': '150.8784375',
'locationDescription': 'UOW Library ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '4RQGHVVH+69',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Gold Coast (South), Australia',
'nameInitialsHandle': 'Lerancan',
'emailAddress': 'lerancan@gmail.com',
'dateMMDDYYYY': '9/11/2022',
'Time': '2:00 PM',
'lat': '-28.1421125',
'lng': '153.495484375',
'locationDescription': 'A picnic table, Wyberba Street Reserve, Tugun',
'Notes': "Email me in case of bad weather/you can't find me/you can't make that time etc.",
'additionalContactInfo': undefined,
'Pluscodes': '5R3MVF5W+555',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Brisbane, Australia',
'nameInitialsHandle': 'Jarred Filmer',
'emailAddress': 'jarred.filmer@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '7:00 PM',
'lat': '-27.5006875',
'lng': '152.9883125',
'locationDescription': '52 McCaul Street Taringa (house)',
'Notes': 'Snacks will be provided but dinner will not be, would recommend eating before you come',
'additionalContactInfo': undefined,
'Pluscodes': '5R4JFXXQ+P8',
'FB': 'https://fb.me/e/4GTPFvq9X',
'Meetup': undefined,
'GroupInfo': "We used to meet once a month years ago, but now just meet whenever there's a Meetups Everywhere :)"},
{'City': 'Canberra, Australia',
'nameInitialsHandle': 'Andy Bachler',
'emailAddress': 'Andy.Bachler@gmail.com',
'dateMMDDYYYY': '8/31/2022',
'Time': '5:30 PM',
'lat': '-35.2773125',
'lng': '149.1203125',
'locationDescription': 'Badger & Co pub at ANU. Central location, parking free after 5pm, might be loud, sorry!',
'Notes': 'Parking area just to the north of the pub, over the river, is free after 5pm!',
'additionalContactInfo': undefined,
'Pluscodes': '4RPFP4FC+34',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Melbourne, Australia',
'nameInitialsHandle': 'Ryan',
'emailAddress': 'xgravityx@hotmail.com',
'dateMMDDYYYY': '9/2/2022',
'Time': '6:00 PM',
'lat': '-37.8173125',
'lng': '144.9694375',
'locationDescription': 'Beer Deluxe Federation Square ',
'Notes': 'Please RSVP to the meeting invite on the [Facebook group](https://www.facebook.com/groups/lesswrongmelbourne) so that I can make an appropriate booking.',
'additionalContactInfo': undefined,
'Pluscodes': '4RJ65XM9+3Q',
'FB': 'https://www.facebook.com/groups/lesswrongmelbourne',
'Meetup': undefined,
'GroupInfo': "We're officially the Less Wrong Melbourne social meetup group, though our members include the broader rationalist community. We meet once a month for casual discussion (and beers for those so inclined). Please join [our Facebook group](https://www.facebook.com/groups/lesswrongmelbourne) to see the meeting invite; there you will see a WhatsApp group link - please join that group too to ensure timely updates in case of changes (Facebook notifications don't work reliably for this)."},
{'City': 'Sydney, Australia ',
'nameInitialsHandle': 'Eliot',
'emailAddress': 'Redeliot@gmail.com ',
'dateMMDDYYYY': '9/15/2022',
'Time': '6:00 PM',
'lat': '-33.8766125',
'lng': '151.205796875',
'locationDescription': 'City of Sydney rsl, lvl 2 in the fishbowl',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '4RRH46F4+983',
'FB': undefined,
'Meetup': 'https://meetu.ps/e/LlSlG/sqK6x/i',
'GroupInfo': 'We meet monthly '},
{'City': 'Chengdu, China',
'nameInitialsHandle': 'Alex',
'emailAddress': 'acx.chengdu@gmail.com',
'dateMMDDYYYY': '9/15/2022',
'Time': '7:00 PM',
'lat': '30.6202625',
'lng': '104.058015625',
'locationDescription': 'Chef Wenwu Hot & Spicy Jianghu Food (Yulin store)/文武大厨·热辣江湖菜(玉林店). I (a foreigner) will be wearing a green shirt. ',
'Notes': "Please RSVP at the above emailAddress, I will give you my Wechat contact if you're interested in attending. Open to time/date/location changes, so let me know if the proposed event doesn't work for you! Can be a bilingual event; all welcome. 有双语交流的可能性。如果想来的话，请提前发给我个电子邮件。",
'additionalContactInfo': undefined,
'Pluscodes': '8P26J3C5+462',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Hong Kong',
'nameInitialsHandle': 'Nathan',
'emailAddress': 'nathan@xevarion.org',
'dateMMDDYYYY': '9/10/2022',
'Time': '1:00 PM',
'lat': '30.2855875',
'lng': '-86.852546875',
'locationDescription': 'The Catalyst, 2 Po Yan Street, Sheung Wan. Big wooden door.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '862M74PW+6XP',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Hyderabad, India',
'nameInitialsHandle': 'Vatsal',
'emailAddress': 'vmehra@pm.me',
'dateMMDDYYYY': '9/11/2022',
'Time': '5:00 PM',
'lat': '17.4554375',
'lng': '78.4993125',
'locationDescription': "The Weekend Cafe, Plot No D, 3, Vikrampuri Colony, beside vac's bakery, Vikrampuri Colony, Lane, Secunderabad, Telangana, 500015, India",
'Notes': undefined,
'additionalContactInfo': 'Whatsapp: +919944430856 (username: Vim)',
'Pluscodes': '7J9WFF4X+5P',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Our rationality meetup group has been around for about 3 months and we discuss articles and exercises (eg. CFAR handbook) that can help us improve epistemic and instrumental rationality. '},
{'City': 'Ubud, Bali, Indonesia',
'nameInitialsHandle': 'William Ubud',
'emailAddress': 'Napaproject@gmail.com',
'dateMMDDYYYY': '8/30/2022',
'Time': '6:00 PM',
'lat': '-8.5050625',
'lng': '115.2656875',
'locationDescription': 'PARQ Ubud',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '6P3QF7V8+X7',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Tokyo, Japan',
'nameInitialsHandle': 'Harold Godsoe',
'emailAddress': 'hgodsoe@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '10:00 AM',
'lat': '35.6444625',
'lng': '139.701203125',
'locationDescription': 'Near Nakameguro station - RSVP for details',
'Notes': "ACX Tokyo meets monthly since Sept 2021. Our meetups are in English, so far. To join in, feel free to get in touch in any of the many ways to do so (email, [Meetup.com](https://www.meetup.com/acx-tokyo/)). It's useful to be in contact before coming to an event, to help with that first leap of faith.",
'additionalContactInfo': undefined,
'Pluscodes': '8Q7XJPV2+QFP',
'FB': undefined,
'Meetup': 'https://www.meetup.com/acx-tokyo/events/287853319/',
'GroupInfo': undefined},
{'City': 'Dunedin, New Zealand',
'nameInitialsHandle': 'Gavin',
'emailAddress': 'bisga673@student.otago.ac.nz',
'dateMMDDYYYY': '9/3/2022',
'Time': '3:00 PM',
'lat': '-45.8637375',
'lng': '170.514234375',
'locationDescription': "Picnic tables outside of St. David's lecture theatre on Otago University campus. I'll make a sign with ACX meetup.",
'Notes': "There is no Dunedin group as far as I'm aware of, but I'd be keen to meet other likeminded people and organise group hangouts occasionally. ",
'additionalContactInfo': undefined,
'Pluscodes': '4V6G4GP7+GM5',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Wellington, New Zealand',
'nameInitialsHandle': 'Ben W',
'emailAddress': 'benwve@gmail.com',
'dateMMDDYYYY': '9/27/2022',
'Time': '5:30 PM',
'lat': '-41.2788125',
'lng': '174.778765625',
'locationDescription': 'Rutherford House, Bunny Street, Wellington. Room MZ05, which is on the mezzanine floor ',
'Notes': "We're running the event this time in partnership with Effective Altruism Wellington",
'additionalContactInfo': undefined,
'Pluscodes': '4VCPPQCH+FGC',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Auckland, New Zealand',
'nameInitialsHandle': 'Jonathan De Wet',
'emailAddress': 'jonpdw@gmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '6:30 PM',
'lat': '-36.7716875',
'lng': '174.7555625',
'locationDescription': '32 Stanley Ave Milford, Auckland',
'Notes': 'It’s a dinner party! Please [RSVP on FB](https://fb.me/e/2a4Po9eKl) so I know how much food to make ',
'additionalContactInfo': undefined,
'Pluscodes': '4VMP6QH4+86',
'FB': 'https://fb.me/e/2a4Po9eKl',
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Lapu Lapu, Cebu, Philippines',
'nameInitialsHandle': 'Dave',
'emailAddress': ' tokkolizard@tutanota.com',
'dateMMDDYYYY': '9/4/2022',
'Time': '2:00 PM',
'lat': '10.3078125',
'lng': '124.0136875',
'locationDescription': 'Starbucks in Mactan Newtown,  there will be a sign with ACX MEETUP on it.',
'Notes': 'Please RSVP by mail so I know if I need to set up a bigger meeting place',
'additionalContactInfo': undefined,
'Pluscodes': '7Q268257+4F',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Vienna, Austria',
'nameInitialsHandle': 'Manuel',
'emailAddress': 'manuel.turonian@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '48.2037625',
'lng': '16.379265625',
'locationDescription': 'Wiener Stadtpark at the Strauss Monument; will have an ACX Meetup sign.',
'Notes': 'We may want to shift to an indoor location depending on weather and the local Covid numbers. ',
'additionalContactInfo': undefined,
'Pluscodes': '8FWR693H+GP2',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Rationality Vienna is a group of about 30 people who meet once a month in person or via Zoom. You can join our [Facebook group](https://facebook.com/groups/579192105439508).'},
{'City': 'Zagreb, Croatia',
'nameInitialsHandle': 'DJStern',
'emailAddress': 'dorian.sternvukotic@gmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '6:00 PM',
'lat': '45.8047375',
'lng': '15.965578125',
'locationDescription': 'Krivi Put',
'Notes': 'Send me an Email and I will add you to a Telegram group where everything (active) LessWrong Croatia/Zagreb happens',
'additionalContactInfo': undefined,
'Pluscodes': '8FQQRX38+V6W',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Croatian LessWrong active group communicates mainly through a Telegram group, we meetup semi regularly, approx once a month. The group is mostly social, and the meetups are not structured (sometimes we all just meet at a random party)'},
{'City': 'Limassol, Cyprus',
'nameInitialsHandle': 'Arseniy',
'emailAddress': 'runescape@list.ru',
'dateMMDDYYYY': '9/2/2022',
'Time': '12:00 PM',
'lat': '34.6844375',
'lng': '33.0530625',
'locationDescription': 'By the Municipal Zoo',
'Notes': "Please hit me up on Mail, Telegram, or Instagram if you're actually going",
'additionalContactInfo': '@anchorheld (Telegram / Instagram)',
'Pluscodes': '8G6MM3M3+Q6',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Tallinn, Estonia',
'nameInitialsHandle': 'Andrew W',
'emailAddress': 'andrew_n_west@yahoo.co.uk',
'dateMMDDYYYY': '9/26/2022',
'Time': '7:00 PM',
'lat': '59.4458125',
'lng': '24.7389375',
'locationDescription': "Tops, Tallinn. I don't know if anyone will turn up, but I'll be wearing a suit, a beard, and a book.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9GF6CPWQ+8H',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Paris, France',
'nameInitialsHandle': 'Olivier',
'emailAddress': 'w20l2qtf@mailer.me',
'dateMMDDYYYY': '9/23/2022',
'Time': '6:00 PM',
'lat': '48.8613125',
'lng': '2.3314375',
'locationDescription': 'In the jardin du carrousel, next to jardin des Tuileries',
'Notes': "We have a mailing list if you are interested in future meetups. Please don't hesitate to send me an email to RSVP that you're coming to help gauge the interest.",
'additionalContactInfo': 'We have a [Discord](https://discord.gg/aGqGP98g) and a [matrix server](https://matrix.to/#/#ssc-paris-meetups:matrix.org)  (both servers are bridged together)',
'Pluscodes': '8FW4V86J+GH',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Regular meetups organized via discord or the newsletter every 3 months with around 20 people.'},
{'City': 'Toulouse, France',
'nameInitialsHandle': 'Alfonso',
'emailAddress': 'barsom.maelwys@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '7:00 PM',
'lat': '43.5884375',
'lng': '1.4464375',
'locationDescription': "Bar 'Le Biergarten' (60 Gd Rue Saint-Michel, 31400 Toulouse). We'll be sitting at a table with an ACX MEETUP sign on it.",
'Notes': 'Please RSVP by email',
'additionalContactInfo': undefined,
'Pluscodes': '8FM3HCQW+9H',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Fontainebleau, France',
'nameInitialsHandle': 'Ebrahim Akbari',
'emailAddress': 'ea.akbari@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '6:00 PM',
'lat': '48.4040625',
'lng': '2.7008125',
'locationDescription': 'Glasgow bar, Fontainebleau ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8FW4CP32+J8',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Tbilisi, Georgia',
'nameInitialsHandle': 'Evgenia Karunus',
'emailAddress': 'lakesare@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '7:00 PM',
'lat': '41.6898125',
'lng': '44.8014375',
'locationDescription': 'Coffee Place',
'Notes': undefined,
'additionalContactInfo': 'https://twitter.com/lakesare',
'Pluscodes': '8HH6MRQ2+WH',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Berlin, Germany',
'nameInitialsHandle': 'Ruben Arslan',
'emailAddress': 'ssc@alphabattle.xyz',
'dateMMDDYYYY': '10/2/2022',
'Time': '2:00 PM',
'lat': '52.5278125',
'lng': '13.3574375',
'locationDescription': 'Südplateau Fritz-Schloss-Park',
'Notes': "Please RSVP on LessWrong. I'll bring some beverages.",
'additionalContactInfo': undefined,
'Pluscodes': '9F4MG9H4+4X',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Karlsruhe, Germany',
'nameInitialsHandle': 'Marcus Wilhelm',
'emailAddress': 'mail@marcuswilhelm.de',
'dateMMDDYYYY': '9/24/2022',
'Time': '3:00 PM',
'lat': '49.0133625',
'lng': '8.400484375',
'locationDescription': 'Botanischer Garten Karlsruhe',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8FXC2C72+85X',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet weekly, alternating offline and online, see [our LessWrong page](https://www.lesswrong.com/groups/kw7Zb8DLmZtsK8g3R)'},
{'City': 'Kassel, Hessen, Germany',
'nameInitialsHandle': 'Tobias',
'emailAddress': 'Sphinxfire@outlook.de',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '51.3120625',
'lng': '9.4980625',
'locationDescription': 'Friedrichsplatz, to the left of the DocumentaHall',
'Notes': "Please join the [Telegram group](https://t.me/+pmOE79F5Y7UzNDM6) if you are interested in coming. It will be helpful for coordinating something beyond 'let's just see who shows up and take it from there', plus, it will also make me feel a lot better on a purely subjective level if I know beforehand that at least one other person is interested. If you prefer the surprise factor of 'knowing as little as possible about who you're going to meet', you can also just write me via E-mail, of course.",
'additionalContactInfo': undefined,
'Pluscodes': '9F3F8F6X+R6',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': '[Telegram group](https://t.me/+pmOE79F5Y7UzNDM6)'},
{'City': 'Tübingen, Germany',
'nameInitialsHandle': 'Emma',
'emailAddress': 'emma.tuebingen@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '6:00 PM',
'lat': '48.5253125',
'lng': '9.0619375',
'locationDescription': 'Meet at the main university library, in the ground floor hall with the tables. We can stay there or grab some snacks and walk to my dorm (5 minutes away) and hang out in the party room there.',
'Notes': "Please email me to get my phone number. If a lot of people are out of town for the holidays and can't come we could meet on, say, October 1st. I would like to know how many people to expect.",
'additionalContactInfo': undefined,
'Pluscodes': '8FWFG3G6+4Q',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Aachen, Germany',
'nameInitialsHandle': 'Jörn',
'emailAddress': 'acx@j.stoehler.eu',
'dateMMDDYYYY': '9/27/2022',
'Time': '7:00 PM',
'lat': '50.7784375',
'lng': '6.0819375',
'locationDescription': 'Chico Mendes',
'Notes': 'Please RSVP [here](https://terminplaner6.dfn.de/en/p/ddb19843a9a35fa506906ffb14f4f8a6-24950) so I can reserve the right number of tables. ',
'additionalContactInfo': undefined,
'Pluscodes': '9F28Q3HJ+9Q',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Leipzig, Germany',
'nameInitialsHandle': 'Gunther Forderung',
'emailAddress': 'notavailable@riseup.net',
'dateMMDDYYYY': '10/4/2022',
'Time': '6:00 PM',
'lat': '51.3343125',
'lng': '12.4011875',
'locationDescription': 'In the Lene-Voigt-Park, in the secluded area opposite of the swings ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9F3J8CM2+PF',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Athens, Greece',
'nameInitialsHandle': 'Spyros',
'emailAddress': 'spyros.dovas@gmail.com',
'dateMMDDYYYY': '9/5/2022',
'Time': '7:00 PM',
'lat': '37.9398375',
'lng': '23.692078125',
'locationDescription': 'On the plaza in front of the National Library',
'Notes': 'Please RSVP on LessWrong or [Meetup.com](https://www.meetup.com/astral-codex-ten-athens-meetup/)',
'additionalContactInfo': undefined,
'Pluscodes': '8G95WMQR+WRP',
'FB': undefined,
'Meetup': 'https://www.meetup.com/astral-codex-ten-athens-meetup/',
'GroupInfo': "We have organized 2 events so far, fall and spring, we just sit around and discuss. We have a Whatsapp group that hasn't picked up momentum yet."},
{'City': 'Cork, Ireland',
'nameInitialsHandle': 'Mikey',
'emailAddress': 'Godojhana@gmail.com',
'dateMMDDYYYY': '9/29/2022',
'Time': '6:00 PM',
'lat': '51.8890625',
'lng': '-8.4855625',
'locationDescription': 'If sunny: The Lough. If not, then the game arcade on the parade',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C3HVGQ7+JQ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Foligno, Italy',
'nameInitialsHandle': 'Mauro',
'emailAddress': 'orfino@yandex.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '5:00 PM',
'lat': '42.9514375',
'lng': '12.7010625',
'locationDescription': 'Parco dei Canapé, at the open air cafe, ask the barista',
'Notes': 'Please RSVP on LessWrong so I know how much food to get. No kids please.',
'additionalContactInfo': '[LW profile](https://www.lesswrong.com/users/orfino-dottorsi), [Telegram](https://www.telegram.me/dottorsi)',
'Pluscodes': '8FJJXP22+HC',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Milano, Italy',
'nameInitialsHandle': 'Raffaele',
'emailAddress': 'raffa.mauro@gmail.com',
'dateMMDDYYYY': '9/16/2022',
'Time': '6:30 PM',
'lat': '45.4709375',
'lng': '9.2060625',
'locationDescription': 'Viale Luigi Majno, 18, 20129 Milano MI - Primo Ventures / T8P, IInd floor. ',
'Notes': 'Please RSVP by email by the 1st of September',
'additionalContactInfo': undefined,
'Pluscodes': '8FQFF6C4+9C',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet once per month. The group started in May 2022.'},
{'City': 'Padova, Italy',
'nameInitialsHandle': 'Carlo',
'emailAddress': 'carlo.martinucci@gmail.com',
'dateMMDDYYYY': '10/1/2022',
'Time': '3:30 PM',
'lat': '45.3984375',
'lng': '11.8765625',
'locationDescription': "Prato della Valle, fountain in the middle. I'll be carrying a sign with ACX MEETUP on it :)",
'Notes': "We'll probably find a bar to have a hot chocolate or tea or something :)",
'additionalContactInfo': undefined,
'Pluscodes': '8FQH9VXG+9J',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Roma, Italy',
'nameInitialsHandle': 'Grigorio',
'emailAddress': 'greghero12@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '6:00 PM',
'lat': '41.8858125',
'lng': '12.5686875',
'locationDescription': "We'll be around Gardenie metro station, at the benches, and I will be wearing a red shirt and sitting on top of the station to be seen",
'Notes': "If you are into ACX enough to see this post, I believe we have enough common ground to be worth meeting each other. Aren't you curious who else is within this niche community in Rome? Come on, take a leap of faith.\nP.S. Would be nice if you sent me a message in WhatsApp with your name and probability of attendance, but I love walk-ins just fine. No space limit after all ;-)",
'additionalContactInfo': '[Facebook](https://www.facebook.com/GregorDeVillain), +393920366026',
'Pluscodes': '8FHJVHP9+8F',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'We meet around 20-25 times a year but it is asymmetrical, focused in summer, Christmas and Easter. We discuss opinions, engage in circling, play games where we spot logical fallacies and biases by attacking our members ideological weakpoints and formalize some debating stances. Occasionally we find the willpower to devote meetups in steelmaning and understanding the outgroup (roughly 4-5 times a year)'},
{'City': 'Delft, Netherlands',
'nameInitialsHandle': 'Pierre Bongrand',
'emailAddress': 'bongrand.pierre@gmail.com',
'dateMMDDYYYY': '9/22/2022',
'Time': '6:30 PM',
'lat': '52.0230625',
'lng': '4.3755625',
'locationDescription': 'Delftse Hout Beach, on the grass, in the center of the beach, I will be wearing a red T-shirt and carrying a sign with ACX MEETUP on it.',
'Notes': undefined,
'additionalContactInfo': '0033620644013 (Whatsapp/Telegram/Signal)',
'Pluscodes': '9F4629FG+66',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Hattem, Netherlands',
'nameInitialsHandle': 'Shoshannah',
'emailAddress': 'shos.rationality@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '2:00 PM',
'lat': '52.4643125',
'lng': '6.0670625',
'locationDescription': 'Lijsterbeslaan 6, Hattem',
'Notes': "Feel free to bring kids. Ours will be there :) Also, please park 't Heem if you are coming by car. It's a 2 minute walk to our house.",
'additionalContactInfo': 'Discord: Dark#0849',
'Pluscodes': '9F48F378+PR',
'FB': 'https://fb.me/e/2br6ppSN3',
'Meetup': undefined,
'GroupInfo': 'We support and coordinate groups across the country, including everything from social meetups to structured events and applied rationality. The intention is to connect all Dutch rationalists and rationalists in the Netherlands. We also discuss rationality topics online and coordinate events on our [Discord server](https://discord.gg/nAp9FQ26W4).'},
{'City': 'Helmond, Netherlands',
'nameInitialsHandle': 'Rutger',
'emailAddress': 'silvery.swift@protonmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '3:00 PM',
'lat': '51.4721875',
'lng': '5.6595625',
'locationDescription': 'De Motte (On top of the hill). Nearest road is Palladio.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9F37FMC5+VR',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'The Hague, Netherlands',
'nameInitialsHandle': 'Kristof Redei',
'emailAddress': 'acxmeetup@kristof.me',
'dateMMDDYYYY': '9/14/2022',
'Time': '6:00 PM',
'lat': '52.0813125',
'lng': '4.3043125',
'locationDescription': "Paleistuin, Prinsessewal, 2513 EE Den Haag, Netherlands. We'll have a picnic blanket with an ACX sign on the large central field, somewhere near the playground.",
'Notes': "Please RSVP [on Facebook](https://www.facebook.com/events/728757288220162) if possible! All ages/species welcome. If it's not outdoor weather, we'll go to The Bookstor Cafe next door as a backup.",
'additionalContactInfo': undefined,
'Pluscodes': '9F4638J3+GP',
'FB': 'https://www.facebook.com/events/728757288220162',
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Oslo, Norway',
'nameInitialsHandle': 'Hans Andreas & Jonas',
'emailAddress': 'acxoslomeetup@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '1:00 PM',
'lat': '59.9294375',
'lng': '10.7143125',
'locationDescription': 'Look for the sign of Moloch at Café Billabong - Bogstadveien 53B 0366 Oslo',
'Notes': "The cafe has historically been accepting of guests' not ordering--please don't let fiundefinedcial reasons keep you away!",
'additionalContactInfo': undefined,
'Pluscodes': '9FFGWPH7+QP',
'FB': undefined,
'Meetup': 'https://www.meetup.com/acx-oslo/events/287948206/',
'GroupInfo': "We're hoping to do at least a quarterly meetup, but we'll base it on the turnout and enthusiasm of this event."},
{'City': 'Gdańsk, Poland',
'nameInitialsHandle': 'Frank',
'emailAddress': 'frankastralcodexten@gmail.com',
'dateMMDDYYYY': '8/27/2022',
'Time': '3:00 PM',
'lat': '54.3815625',
'lng': '18.6073125',
'locationDescription': 'Next to Park Kuźniczki, opposite the train station, on the circular benches around the water pump; I will be wearing a red armband',
'Notes': undefined,
'additionalContactInfo': 'Discord: frhrpr#1663',
'Pluscodes': '9F6W9JJ4+JW',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Kraków, Poland',
'nameInitialsHandle': 'Mateusz Bagiński',
'emailAddress': 'bagginsmatthew@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '2:30 PM',
'lat': '50.0446875',
'lng': '19.9475625',
'locationDescription': 'Celna 6/9',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9F2X2WVX+V2',
'FB': 'https://fb.me/e/2k7IwUrfV',
'Meetup': undefined,
'GroupInfo': 'We meet every month, here is [our Facebook group](https://www.facebook.com/groups/LWKrakow).'},
{'City': 'Lublin, Poland',
'nameInitialsHandle': 'Piotr',
'emailAddress': 'piotrekzlublina@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '5:00 PM',
'lat': '51.2486875',
'lng': '22.5674375',
'locationDescription': 'Między Słowami cafe, Rybna 4, Lublin',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9G346HX8+FX',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Poznań, Poland',
'nameInitialsHandle': 'Ofelia Kerr',
'emailAddress': 'ofel.kerr@gmail.com',
'dateMMDDYYYY': '10/8/2022',
'Time': '6:00 PM',
'lat': '52.4099375',
'lng': '16.935171875',
'locationDescription': "Van Gogh Pub, Żydowska 12, 61-761. I'll most likely be on the ground floor and I'll have an ACX sign.",
'Notes': undefined,
'additionalContactInfo': 'Discord: ofelia#0001',
'Pluscodes': '9F4RCW5P+X3F',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Warsaw, Poland',
'nameInitialsHandle': 'Michał',
'emailAddress': 'rationalwarsaw@gmail.com',
'dateMMDDYYYY': '9/4/2022',
'Time': '6:00 PM',
'lat': '52.2250625',
'lng': '21.0171875',
'locationDescription': 'Południk Zero, Wilcza 25',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9G4362G8+2V',
'FB': undefined,
'Meetup': 'https://www.meetup.com/lesswrongwarsaw/events/287979030/',
'GroupInfo': "The community of Warsaw LessWrong/SSC/ACX/etc. readers is active for over 8 years now. We're trying to organise regular monthly meetups. You can join our [Facebook group](https://www.facebook.com/groups/lwwarsaw) or [Meetup.com](https://www.meetup.com/lesswrongwarsaw/)."},
{'City': 'Bucharest, Romania',
'nameInitialsHandle': 'Tony',
'emailAddress': 'skyrimtracer@gmail.com',
'dateMMDDYYYY': '10/16/2022',
'Time': '3:00 PM',
'lat': '44.4284375',
'lng': '26.0349375',
'locationDescription': 'Plaza România Mall, Bd. Timișoara 26 - food court',
'Notes': 'Please RSVP by email',
'additionalContactInfo': undefined,
'Pluscodes': '8GP8C2HM+9X',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Cluj-Napoca, Romania',
'nameInitialsHandle': 'Marius Pop',
'emailAddress': 'pop.marius@gmail.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '11:00 AM',
'lat': '46.7666875',
'lng': '23.5748125',
'locationDescription': 'Deva Host, Strada Deva 1-7',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8GR5QH8F+MW',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Belgrade, Serbia',
'nameInitialsHandle': 'Ivica Bogosavljevic',
'emailAddress': 'ibogosavljevic@gmail.com',
'dateMMDDYYYY': '9/12/2022',
'Time': '6:00 PM',
'lat': '44.8363125',
'lng': '20.4131875',
'locationDescription': 'Pool Cafe on Prve pruge',
'Notes': 'Please RSVP on my Viber number, so I know how big the room we need. ',
'additionalContactInfo': 'Viber +381 65 3473 433',
'Pluscodes': '8GP2RCP7+G7',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Bratislava, Slovakia',
'nameInitialsHandle': 'Viliam',
'emailAddress': 'viliam@bur.sk',
'dateMMDDYYYY': '9/10/2022',
'Time': '3:00 PM',
'lat': '48.1499125',
'lng': '17.119828125',
'locationDescription': 'Medická záhrada, by the fountain',
'Notes': 'I will post an announcement on LessWrong later. In case of rain, a new meeting place nearby will be announced there.',
'additionalContactInfo': undefined,
'Pluscodes': '8FWV44X9+XW8',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Barcelona, Spain',
'nameInitialsHandle': 'Alfonso',
'emailAddress': 'alfonso.martinez@upf.edu',
'dateMMDDYYYY': '10/2/2022',
'Time': '5:30 PM',
'lat': '41.3884375',
'lng': '2.1855625',
'locationDescription': "Parc de la Ciutadella, by the Lion Catcher statue; I'll have an ACX sign",
'Notes': "The idea is to sit on the grass; bring a foulard along for your comfort, or a foldable chair if preferred. Don't worry about the language: English, Spanish, Catalan, we'll find a way.",
'additionalContactInfo': 'WhatsApp +34693846738',
'Pluscodes': '8FH495QP+96',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Sevilla, Spain',
'nameInitialsHandle': 'Edu',
'emailAddress': 'edur.acx@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '8:00 PM',
'lat': '37.3726875',
'lng': '-5.987921875',
'locationDescription': "Parque de María Luisa. I'll be on the grass behind the Museum of Popular Arts and Traditions. I'll be the guy next to an ACX sign, a white wooden chair, and a cardboard ukulele with a tiny cardboard hat on it.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8C9P92F6+3RG',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Gothenburg, Sweden',
'nameInitialsHandle': 'Joacim',
'emailAddress': 'joacimj@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '3:00 PM',
'lat': '57.7051875',
'lng': '11.970953125',
'locationDescription': "Condeco Fredsgatan. I'll have a stack of three books on my table.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9F9HPX4C+39G',
'FB': 'https://facebook.com/events/s/acx-meetup-gothenburg/2231181767045942/',
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Bern, Switzerland',
'nameInitialsHandle': 'Daniel',
'emailAddress': 'dd14214+acx@gmail.com',
'dateMMDDYYYY': '10/2/2022',
'Time': '4:00 PM',
'lat': '46.9503125',
'lng': '7.4388125',
'locationDescription': "Grosse Schanze, at the statue in front of the main uni building, heading to the Pittaria if it's cold or raining",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '8FR9XC2Q+4G',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Istanbul, Turkey',
'nameInitialsHandle': 'J',
'emailAddress': 'jinai.jyap@gmail.com',
'dateMMDDYYYY': '9/25/2022',
'Time': '4:00 PM',
'lat': '41.0475875',
'lng': '29.025203125',
'locationDescription': "The House Cafe in Ortaköy. I am a young Asian woman and imagine I'll be easy to spot, but will also try to bring a sign with ACX MEETUP on it.",
'Notes': 'Please RSVP via the Partiful link (you can RSVP as a Maybe)!',
'additionalContactInfo': undefined,
'Pluscodes': '8GHF22XG+23P',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "I do not live here; I am just digital nomading for an indefinite amount of time and would like to meet anyone who's here!"},
{'City': 'Cardiff, Wales',
'nameInitialsHandle': 'AF',
'emailAddress': 'strmnova@gmail.com',
'dateMMDDYYYY': '9/16/2022',
'Time': '5:00 PM',
'lat': '51.4815625',
'lng': '-3.1759375',
'locationDescription': 'Big Moose Coffee Company',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C3RFRJF+JJ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Brighton, UK',
'nameInitialsHandle': 'Alan Enright',
'emailAddress': 'alanenright@protonmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '11:00 AM',
'lat': '50.8326875',
'lng': '-0.1375625',
'locationDescription': "We'll be at the Alcampo Lounge on London Road—we will try and get a table on the raised area in front of you and to the left as you come in but will also have a little ACX sign.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C2XRVM6+3X',
'FB': undefined,
'Meetup': 'https://www.meetup.com/brighton-rationalish/',
'GroupInfo': undefined},
{'City': 'Bristol, UK',
'nameInitialsHandle': 'Nick Lowry',
'emailAddress': 'bristoleffectivealtruism@gmail.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '2:00 PM',
'lat': '51.4570875',
'lng': '-2.590953125',
'locationDescription': 'We’ll be meeting at entrance closet to Tesco Express in the Galleries, Bristol City Centre',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C3VFC45+RJM',
'FB': 'https://fb.me/e/2nvLdyGVz',
'Meetup': 'https://www.meetup.com/bristol-effective-altruism/events/286472111/',
'GroupInfo': "Meet twice monthly for socials, more regular 'productive' meetups. Been active for 3+ years, please message for WhatsApp group"},
{'City': 'Cambridge, UK',
'nameInitialsHandle': 'Hamish Todd',
'emailAddress': 'hamish.todd1@gmail.com',
'dateMMDDYYYY': '9/17/2022',
'Time': '2:00 PM',
'lat': '52.2040625',
'lng': '0.1184375',
'locationDescription': "Bath House Pub, UPSTAIRS!! I will have a copy of Peter Singer's _The Most Good You Can Do_",
'Notes': "My phone/WhatsApp number is +44 0730 *** 3550, where the *** are replaced by the serial number of the Boeing plane whose first flight was on September 2, 1998. Email me to get on the mailing list for future events if you'd like that :)",
'additionalContactInfo': undefined,
'Pluscodes': '9F426439+J9',
'FB': 'https://www.facebook.com/Rationalish-Cambridge-Astral-Codex-TenSlatestarcodex-meetups-107072022120997',
'Meetup': undefined,
'GroupInfo': 'We meet on the third Saturday of every month. The group has been around almost a year and is well-attended!'},
{'City': 'Lincoln, UK',
'nameInitialsHandle': 'Tobias',
'emailAddress': 'tobias.showan@yahoo.co.uk',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '53.2199375',
'lng': '-0.5584375',
'locationDescription': "Nosey Parker pub, I'll bring a little paper ACX sign.",
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C5X6C9R+XJ',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Manchester, UK',
'nameInitialsHandle': 'Matthew Gibson',
'emailAddress': 'melkartmtg@hotmail.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '11:00 AM',
'lat': '53.4766875',
'lng': '-2.2360625',
'locationDescription': 'Sackville Gardens, Alan Turing Memorial',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C5VFQG7+MH',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Newcastle upon Tyne, UK',
'nameInitialsHandle': 'Joshua William ',
'emailAddress': 'iamjoshwilliam@icloud.com',
'dateMMDDYYYY': '9/3/2022',
'Time': '12:30 PM',
'lat': '55.0054375',
'lng': '-1.6203125',
'locationDescription': "Trinity Square, High Street Gosforth. You can get the bus to Gosforth from the city center just outside the famous 'Tyneside Cinema' (bus number: 30, 31, or 35 at [Monument Pilgrim Street bus stop](https://plus.codes/9C6WX9FQ+G8)), or you can take a walk if you want to get your 'steps' in (if you'd like to do the latter, send me an email and I'll send you the directions), which takes ~60-min. ",
'Notes': "We have a deli, '1901 cafe', on the square, which we can grab an immediate bite to eat at [so save some hunger if you'd like to do that]. There's a safe [and lovely] park with some benches just by the way, which, if the weather is nice, we can sit at after a bite to eat, or, otherwise, we can remain in the cafe. ",
'additionalContactInfo': '[Telegram](t.me/dokkodian)',
'Pluscodes': '9C7W294H+5V',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "To my knowledge, there isn't an ACX meet up in this city, or region of the UK, though if there is a demand for a reoccurrence, I'd be happy to keep facilitating such. I'd also happily formulate a WhatsApp group if theres interest, after the meet up."},
{'City': 'Penryn, Cornwall, UK',
'nameInitialsHandle': 'mini t',
'emailAddress': 'tminns@btinternet.com',
'dateMMDDYYYY': '8/27/2022',
'Time': '12:00 PM',
'lat': '50.1406875',
'lng': '-5.0763125',
'locationDescription': 'swanpool beach',
'Notes': "I don't mind rescheduling, or organizing another event, not many people are likely to turn up this far out of the way.",
'additionalContactInfo': undefined,
'Pluscodes': '9C2P4WRF+7F',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Lancaster, UK',
'nameInitialsHandle': 'Gruffydd Gozali',
'emailAddress': 'gruffyddgozali@gmail.com',
'dateMMDDYYYY': '10/15/2022',
'Time': '3:00 PM',
'lat': '54.0098625',
'lng': '-2.785984375',
'locationDescription': 'Lancaster University Library, will be on the ground floor by the tree wearing an EA shirt.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '9C6V2657+WJR',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'São Paulo, Brazil',
'nameInitialsHandle': 'Simon',
'emailAddress': 'sjclawrence@gmail.com',
'dateMMDDYYYY': '9/10/2022',
'Time': '2:00 PM',
'lat': '-23.5919375',
'lng': '-46.6600625',
'locationDescription': 'Ibirapuera Park in Praca do Porquinho. I will be wearing a white t-shirt, be very tall and have a sign.',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '588MC85Q+6X',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Medellín, Colombia',
'nameInitialsHandle': 'HP',
'emailAddress': 'hp-med-acx@proton.me',
'dateMMDDYYYY': '9/18/2022',
'Time': '5:00 PM',
'lat': '6.2133125',
'lng': '-75.5728125',
'locationDescription': 'Hija Mia Nomada',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '67R66C7G+8V',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Bogotá, Colombia',
'nameInitialsHandle': 'Dan P',
'emailAddress': 'shorty.george.productions@gmail.com',
'dateMMDDYYYY': '9/18/2022',
'Time': '4:00 PM',
'lat': '4.6726625',
'lng': '-74.053828125',
'locationDescription': 'Illy Cafe, Kr 15 with Park Virrey.  Sign will say ACX',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '67P7MWFW+3F7',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Mérida, Mexico',
'nameInitialsHandle': 'Mati Roy',
'emailAddress': 'mathieu.roy.37@gmail.com',
'dateMMDDYYYY': '8/28/2022',
'Time': '5:00 PM',
'lat': '21.0133125',
'lng': '-89.5513125',
'locationDescription': 'Parque Gardenia, C. 65-A, Residencial Floresta, 97309 Mérida, Yuc.',
'Notes': "Please let me know if you'll be coming.",
'additionalContactInfo': '[Facebook](https://www.facebook.com/mati.roy.09/)',
'Pluscodes': '76HG2C7X+8F',
'FB': 'https://www.facebook.com/events/5369782209776018',
'Meetup': undefined,
'GroupInfo': '[Facebook group](https://www.facebook.com/groups/lesswrongmerida)'},
{'City': 'Punta del Este, Uruguay',
'nameInitialsHandle': 'Manuel',
'emailAddress': 'acx@maraoz.com',
'dateMMDDYYYY': '9/24/2022',
'Time': '5:00 PM',
'lat': '-34.9145625',
'lng': '-54.8616875',
'locationDescription': 'Borneo Coffee, patio del fondo. Ruta 10, 20001 La Barra, Departamento de Maldonado, Uruguay ',
'Notes': undefined,
'additionalContactInfo': undefined,
'Pluscodes': '48Q734PQ+58',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Baghdad, Iraq',
'nameInitialsHandle': 'MA',
'emailAddress': 'tofiahmed117@gmail.com',
'dateMMDDYYYY': '9/2/2022',
'Time': '11:00 AM',
'lat': '33.3256875',
'lng': '44.4601875',
'locationDescription': 'Grinders Coffeeshop',
'Notes': undefined,
'additionalContactInfo': 'Discord: WolframSigma#1532, [Telegram](https://t.me/Wolfram_Sigma)',
'Pluscodes': '8H568FG6+73',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Jerusalem, Israel',
'nameInitialsHandle': 'Zvi Schreiber',
'emailAddress': 'zvi@zvi.net',
'dateMMDDYYYY': '10/19/2022',
'Time': '6:00 PM',
'lat': '31.7493125',
'lng': '35.1868125',
'locationDescription': 'Malcha technology park garden',
'Notes': undefined,
'additionalContactInfo': 'WhatsApp +972 54 569 1100 ',
'Pluscodes': '8G3QP5XP+PP',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Rehovot, Israel',
'nameInitialsHandle': 'David Manheim',
'emailAddress': 'David@alter.org.il',
'dateMMDDYYYY': '9/11/2022',
'Time': '8:00 PM',
'lat': '31.9016875',
'lng': '34.8093125',
'locationDescription': 'Outside porch of Aroma Coffee, הרצל 218, רחובות',
'Notes': 'Please RSVP [on Facebook](https://www.facebook.com/events/737808667280605/) so we can give updates if needed',
'additionalContactInfo': undefined,
'Pluscodes': '8G3PWR25+MP',
'FB': 'https://www.facebook.com/events/737808667280605/',
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Tel Aviv, Israel',
'nameInitialsHandle': 'Adam & inbar M',
'emailAddress': 'projectscentrum@gmail.com, inbar192@gmail.com',
'dateMMDDYYYY': '9/4/2022',
'Time': '7:00 PM',
'lat': '32.0658125',
'lng': '34.7879375',
'locationDescription': 'Hamenia industrial loft at Beit Alfa 7 (רחוב בית אלפא 7). Look for a door with ACX sign. Two floors up. ',
'Notes': 'For questions contact Adam on email or WhatsApp. Feel free to bring a snack or a bottle of white wine.',
'additionalContactInfo': 'Whatsapp +46762791415 (Adam)',
'Pluscodes': '8G4P3Q8Q+85',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': "We've just made a [Facebook group](https://www.facebook.com/groups/5389163051129361) and are planning to organize monthly meetings going forward"},
{'City': 'Amman, Jordan',
'nameInitialsHandle': 'Daniel',
'emailAddress': 'dnledvs@gmail.com',
'dateMMDDYYYY': '9/20/2022',
'Time': '6:30 PM',
'lat': '31.9573125',
'lng': '35.9188125',
'locationDescription': 'Rustic, Jabal al Weibdeh',
'Notes': "We're hoping to grow the group, so feel free to come even if you've only read a few posts! +1s are also welcome.",
'additionalContactInfo': undefined,
'Pluscodes': '8G3QXW49+WG',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': undefined},
{'City': 'Dubai, UAE',
'nameInitialsHandle': 'RS',
'emailAddress': 'xyxyxz@gmail.com',
'dateMMDDYYYY': '9/30/2022',
'Time': '7:30 PM',
'lat': '25.2434375',
'lng': '55.3403125',
'locationDescription': 'Starbucks, Garhoud',
'Notes': 'Please RSVP on LessWrong, or message me on WhatsApp',
'additionalContactInfo': '+971552726281 (Whatsapp)',
'Pluscodes': '7HQQ68VR+94',
'FB': undefined,
'Meetup': undefined,
'GroupInfo': 'Met once before'}] as const
