import {addField, dropField} from '@/server/migrations/meta/utils'
import Tags from '@/lib/collections/tags/collection'

/**
 * Generated on 2024-06-10T02:33:24.187Z by `yarn makemigrations`
 * The following schema changes were detected:
 * -------------------------------------------
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 1/3 --- Text (46 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * Renamed from /Users/vlad/coding/dance/fm/ForumMagnum/schema/accepted_schema.sql to /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql
 *  2 -- Do not edit this file directly. I 2 -- Do not edit this file directly. I
 *  . nstead, start a server and run "yarn . nstead, start a server and run "yarn
 *  .  makemigrations"                     .  makemigrations"
 *  3 -- as described in the README. This  3 -- as described in the README. This 
 *  . file should nevertheless be checked  . file should nevertheless be checked 
 *  . in to version control.               . in to version control.
 *  4 --                                   4 --
 *  5 -- Overall schema hash: 369a319cca4b 5 -- Overall schema hash: a40d21a9f1a5
 *  . 365db2c976b7f74f49c2                 . 8c39ef6f10d674e7c6d6
 *  6                                      6 
 *  7 -- Accepted on 2024-06-10T01:46:26.0 . 
 *  . 00Z by 20240610T014626.rebase_noop.t . 
 *  . s                                    . 
 *  8                                      . 
 *  9 -- Extension "btree_gin", hash 7b207 7 -- Extension "btree_gin", hash 7b207
 *  . eefbb36f8109cca31911e6ab886          . eefbb36f8109cca31911e6ab886
 * 10 CREATE EXTENSION IF NOT EXISTS "btre 8 CREATE EXTENSION IF NOT EXISTS "btre
 * .. e_gin" CASCADE;                      . e_gin" CASCADE;
 * 11                                      9 
 * 
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 2/3 --- Text (46 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * 2625 -- Index "idx_TagRels_tagId", hash 2623 -- Index "idx_TagRels_tagId", hash
 * ....  d726549e45ae78cf8864716b449c0ab7  ....  d726549e45ae78cf8864716b449c0ab7
 * 2626 CREATE INDEX IF NOT EXISTS "idx_Ta 2624 CREATE INDEX IF NOT EXISTS "idx_Ta
 * .... gRels_tagId" ON "TagRels" USING bt .... gRels_tagId" ON "TagRels" USING bt
 * .... ree ("tagId");                     .... ree ("tagId");
 * 2627                                    2625 
 * 2628 -- Table "Tags", hash c8fd5b7d21da 2626 -- Table "Tags", hash 6b9453bfa012
 * .... 5d0da9355c7d023f258d               .... 33459e8a6f9a3634bb95
 * 2629 CREATE TABLE "Tags" (              2627 CREATE TABLE "Tags" (
 * 2630   _id VARCHAR(27) PRIMARY KEY,     2628   _id VARCHAR(27) PRIMARY KEY,
 * 2631   "name" TEXT NOT NULL,            2629   "name" TEXT NOT NULL,
 * 
 * /Users/vlad/coding/dance/fm/ForumMagnum/schema/schema_to_accept.sql --- 3/3 --- Text (46 SQL parse errors, exceeded DFT_PARSE_ERROR_LIMIT)
 * 2675 2673   "legacyData" JSONB,
 * 2676 2674   "description" JSONB,
 * 2677 2675   "description_latest" TEXT,
 * .... 2676   "pingbacks" JSONB,
 * 2678 2677   "subforumWelcomeText" JSONB,
 * 2679 2678   "subforumWelcomeText_latest" TEXT,
 * 2680 2679   "moderationGuidelines" JSONB,
 * 
 * 
 * -------------------------------------------
 * (run `git diff --no-index schema/accepted_schema.sql schema/schema_to_accept.sql` to see this more clearly)
 *
 * - [ ] Write a migration to represent these changes
 * - [ ] Rename this file to something more readable
 * - [ ] Uncomment `acceptsSchemaHash` below
 * - [ ] Run `yarn acceptmigrations` to update the accepted schema hash (running makemigrations again will also do this)
 */
export const acceptsSchemaHash = "a40d21a9f1a58c39ef6f10d674e7c6d6";

export const up = async ({db}: MigrationContext) => {
  await addField(db, Tags, "pingbacks");
}

export const down = async ({db}: MigrationContext) => {
  await dropField(db, Tags, "pingbacks");
}
