import { importComponent } from '../../../lib/vulcan-lib';

importComponent("PostsPage", () => require('./PostsPage'));
importComponent("PostsPageDate", () => require('./PostsPageDate'));
importComponent("PostsPagePostFooter", () => require('./PostsPagePostFooter'));
importComponent("PostsPagePostHeader", () => require('./PostsPagePostHeader'));
importComponent("PostsPodcastPlayer", () => require('./PostsPodcastPlayer'));
importComponent("PostCoauthorRequest", () => require('./PostCoauthorRequest'));
importComponent("PostsPageWrapper", () => require('./PostsPageWrapper'));
importComponent("PostsPageCrosspostWrapper", () => require('./PostsPageCrosspostWrapper'));
importComponent("PostsPageCrosspostComments", () => require('./PostsPageCrosspostComments'));
importComponent("PostBody", () => require('./PostBody'));
importComponent("PostBodyPrefix", () => require('./PostBodyPrefix'));
importComponent("PostsAuthors", () => require('./PostsAuthors'));
importComponent("PostsPageTitle", () => require('./PostsPageTitle'));
importComponent("PostsTopSequencesNav", () => require('./PostsTopSequencesNav'));
importComponent("PostsPageEventData", () => require('./PostsPageEventData'));
importComponent("PostActions", () => require('./PostActions'));
importComponent("PostAuthorCard", () => require('./PostAuthorCard'));
importComponent("ContentType", () => require('./ContentType'));
importComponent("PostsRevisionSelector", () => require('./PostsRevisionSelector'));
importComponent("PostsRevisionsList", () => require('./PostsRevisionsList'));
importComponent("PostsRevisionMessage", () => require('./PostsRevisionMessage'));
importComponent("RSVPs", () => require('./RSVPs'));
importComponent("RSVPForm", () => require('./RSVPForm'));
importComponent("WelcomeBox", () => require('./WelcomeBox'));
importComponent("CrosspostHeaderIcon", () => require('./CrosspostHeaderIcon'));
importComponent("CollapsedFootnotes", () => require('./CollapsedFootnotes'));
