import { registerMigration } from './migrationUtils';
import Users from '../../lib/collections/users/collection';
import { createMutator } from '../vulcan-lib/mutators';
import { Posts } from '../../lib/collections/posts/collection';
import { mapsAPIKeySetting } from '../../components/form-components/LocationFormComponent';
import { getLocalTime } from '../mapsUtils';
import {userFindOneByEmail} from "../commonQueries";
import { getUnusedSlugByCollectionName } from '../utils/slugUtil';

const what3WordsAPIKey = "FM5HBWEL"

async function what3WordsToCoordinates(words: string) {
  const requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };

  const response = await fetch(`https://api.what3words.com/v3/convert-to-coordinates?words=${words}&key=${what3WordsAPIKey}`, requestOptions)
  const responseText = await response.text()
  const responseData = JSON.parse(responseText)
  return responseData.coordinates
}

async function coordinatesToGoogleLocation({ lat, lng }: { lat: string, lng: string }) {
  const requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };

  const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${mapsAPIKeySetting.get()}`, requestOptions)
  const responseText = await response.text()
  const responseData = JSON.parse(responseText)
  return responseData.results[0]
}

registerMigration({
  name: "importACXMeetups",
  dateWritten: "2021-08-22",
  idempotent: true,
  action: async () => {
    for (const row of acxData) {
      let eventOrganizer
      // Figure out whether user with email address already exists
      const existingUser = await userFindOneByEmail(row["Email address"])
      // If not, create them (and send them an email, maybe?)
      if (existingUser) {
        eventOrganizer = existingUser
      } else {
        const { data: newUser } = await createMutator({
          collection: Users,
          document: {
            username: await getUnusedSlugByCollectionName("Users", row["Name/initials/handle"].toLowerCase()),
            displayName: row["Name/initials/handle"],
            email: row["Email address"],
            reviewedByUserId: "XtphY3uYHwruKqDyG",
            reviewedAt: new Date()
          },
          validate: false,
          currentUser: null
        })
        eventOrganizer = newUser
      }
      // Call the what3words API to get the location
      const coordinates = await what3WordsToCoordinates(row["Coordinates"])
      const googleLocation = await coordinatesToGoogleLocation(coordinates)
      const eventTimePretendingItsUTC = new Date(`${row["Date (mm/dd/yyyy)"]} ${row["Time"]} UTC`)
      const localtime = eventTimePretendingItsUTC.getTime() ? await getLocalTime(eventTimePretendingItsUTC, googleLocation) : new Date();
      const actualTime = new Date(eventTimePretendingItsUTC.getTime() + (eventTimePretendingItsUTC.getTime() - (localtime?.getTime() || eventTimePretendingItsUTC.getTime())))
      // Then create event post with that user as owner, if it doesn't exist yet
      const title = `${row["City"]} – ACX Meetups Everywhere 2021 `
      const existingPost = await Posts.findOne({ title });
      if (!existingPost) {
        const newPostData = {
          title,
          postedAt: new Date(),
          userId: eventOrganizer._id,
          submitToFrontpage: true,
          activateRSVPs: true,
          draft: false,
          meta: false,
          isEvent: true,
          contactInfo: row["Email address"],
          location: `${row["City"]}`,
          startTime: eventTimePretendingItsUTC.getTime() ? actualTime : undefined,
          googleLocation,
          contents: {
            originalContents: {
              type: 'ckEditorMarkup',
              data: `<p>This year's ACX Meetup everywhere in ${row["City"]}.</p>
                <p>Location: ${row["Location description"]} – <a href="https://what3words.com/${row["Coordinates"]}">${row["Coordinates"]}</a></p>
                ${row["Notes"] ? `<p>${row["Notes"]}</p>` : ""}
                <p>Contact: ${row["Email address"]} ${row["Additional contact info"] ? `– ${row["Additional contact info"]}` : ""}</p>`
            },
            updateType: 'minor',
            commitMessage: ''
          },
          moderationStyle: 'easy-going',
          af: false,
          authorIsUnreviewed: false,
          types: [
            'SSC'
          ],
        };
        const { data: newPost } = await createMutator({
          collection: Posts,
          document: newPostData,
          currentUser: eventOrganizer,
          validate: false
        })
        // eslint-disable-next-line no-console
        console.log("Created new ACX Meetup: ", newPost.title)
      } else {
        // eslint-disable-next-line no-console
        console.log("Meetup with this name already existed: ", title)
      }
    }
  }
})

const acxData = [
  {
    "City": "Calgary, AB",
    "Name/initials/handle": "David Piepgrass",
    "Email address": "qwertie256@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "1:00 PM",
    "Coordinates": "///readily.rosette.pools",
    "Location description": "Pearce Estate Park: parking on 17a St SE, one of the 10 picnic tables northeast of the parking area, unless full. Look for a red-shirt guy and \"ACX\".",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Edmonton, AB",
    "Name/initials/handle": "JS",
    "Email address": "ta1hynp09@relay.firefox.com",
    "Date (mm/dd/yyyy)": "9/3/2021",
    "Time": "6:00 PM",
    "Coordinates": "///interval.solid.globe",
    "Location description": "Hawrelak Park - 9330 Groat Rd NW, Edmonton, AB T6G 2A8.  We will be at one of the tables near the north parking lot with a (small) ACX sign for at least the first 30 minutes.  I am a long-haired, bearded man with a black/navy baseball cap.  If you arrive later or cannot find us, please email - I will keep my phone handy all evening.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Vancouver, BC",
    "Name/initials/handle": "Tom Ash",
    "Email address": "acxmeetup2021@philosofiles.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "2:30 PM",
    "Coordinates": "///wardrobe.admires.gourmet",
    "Location description": "We'll be at the covered area of Trout Lake, near Nanaimo skytrain station. We'll have a sign saying 'ACX Meetup', or put one up pointing elsewhere if another group has claimed it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Winnipeg, MB",
    "Name/initials/handle": "Rory",
    "Email address": "rorykaufmann@gmail.com",
    "Date (mm/dd/yyyy)": "9/9/2021",
    "Time": "6:00 PM",
    "Coordinates": "///drank.gained.respect",
    "Location description": "The Forks, outside on the patio (or in the main building if the weather is bad). Look for the tall guy with a yellow sweater.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Fredericton, NB",
    "Name/initials/handle": "Liam Nolan",
    "Email address": "liamfnolan@gmail.com",
    "Date (mm/dd/yyyy)": "",
    "Time": "",
    "Coordinates": "///polling.homerun.bossy",
    "Location description": "",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Kitchener-Waterloo, ON",
    "Name/initials/handle": "JC",
    "Email address": "blxxia@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "3:00 PM",
    "Coordinates": "///flopped.uses.cherub",
    "Location description": "Waterloo Park, under the Wonders of Winter sign (it's an archway over a trail near the LRT station). I will be in scuffed white doc martens",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Ottawa, ON",
    "Name/initials/handle": "Tess",
    "Email address": "rationalottawa@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "3:00 PM",
    "Coordinates": "///trees.library.along",
    "Location description": "Lansdowne Park, on the curved benches/bleachers near the tall geometric statue/fountain. We will have a prominent sign that says ACX.",
    "Notes": "",
    "Additional contact info": "Facebook group; LessWrong group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Toronto, ON",
    "Name/initials/handle": "Sean Aubin",
    "Email address": "seanaubin@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "1:00 PM",
    "Coordinates": "///barman.squares.knee",
    "Location description": "Little Norway Park, northeast corner",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Montreal, QC",
    "Name/initials/handle": "DS",
    "Email address": "sdaria375@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "3:00 PM",
    "Coordinates": "///apples.fevered.gasping",
    "Location description": "Jeanne-Mance park on the corner of Duluth and Esplanade",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Vienna, Austria",
    "Name/initials/handle": "Alexej Gerstmaier",
    "Email address": "alexej.gerstmaier@gmail.com",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "6:30 PM",
    "Coordinates": "///informal.courage.courage",
    "Location description": "Wiener Stadtpark at the Strauss Monument; will have an ACX Meetup sign",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Brussels, Belgium",
    "Name/initials/handle": "Bruno D.",
    "Email address": "bruno.astral.codex@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "4:00 PM",
    "Coordinates": "///badly.deliver.ducks",
    "Location description": "Parc du Cinquantenaire at Guinguette Maurice, I'll be wearing a watermelon shirt",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Sofia, Bulgaria",
    "Name/initials/handle": "Anastasia",
    "Email address": "sofia.acx.meetup@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "7:00 PM",
    "Coordinates": "///noise.bridges.outpost",
    "Location description": "NDK park, the benches behind (south of) the Pillars / Пилоните; I'll be wearing a blue shirt and carrying a sheet of paper with ACX MEETUP on it.",
    "Notes": "I am not certain that there's even one other ACX person in the city/country, so if potential attendees could signal it somehow, that would be grand.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Prague, Czech Republic",
    "Name/initials/handle": "Jiri Nadvornik",
    "Email address": "jiri.nadvornik@efektivni-altruismus.cz",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "6:30 PM",
    "Coordinates": "///magnets.hurry.charm",
    "Location description": "Garden of Dharmasala teahouse",
    "Notes": "There is CFAR rEUnion on 24-27 September. I hope some people will attend both events.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Aarhus, Denmark",
    "Name/initials/handle": "Jonas",
    "Email address": "proz@c.dk",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "10:00 AM",
    "Coordinates": "///bicker.rise.parts",
    "Location description": "Outside entrance of the Greenhouses in Aarhus Botanical Garden. I will be wearing a red shirt and carrying a sign with ACX MEETUP on it. Nearby parking lot: Poppelpladsen 2, 8000 Aarhus.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Copenhagen, Denmark",
    "Name/initials/handle": "Søren Elverlin",
    "Email address": "soeren.elverlin@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "3:00 PM",
    "Coordinates": "///halvdel.kviste.synger",
    "Location description": "Rundholtsvej 10, 2300 København S. My roof terrace can accommodate us unless we are twice as many as last time. In that case, we will move to the green area in front of the house",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Helsinki, Finland",
    "Name/initials/handle": "Joe Nash",
    "Email address": "joenash499@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "4:00 PM",
    "Coordinates": "///earliest.adopt.verse",
    "Location description": "Restaurant Töölönranta, Helsinginkatu 56; we'll put out a notepad that says \"ACX",
    "Notes": "I've ended up as the organizer of an existing meetup group but I'm not gung-ho about it. If someone else wants the job they should get it, but we have to coordinate the transfer.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bordeaux, France",
    "Name/initials/handle": "Tom R",
    "Email address": "trth@fastmail.fm",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "3:00 PM",
    "Coordinates": "///prelude.rails.glades",
    "Location description": "Jardin Public, under the large trees next to the main entrance (Cours de Verdun). There will be an ACX sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Nantes, France",
    "Name/initials/handle": "Carado",
    "Email address": "carado@carado.moe",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "3:00 PM",
    "Coordinates": "///consumed.pass.scans",
    "Location description": "Parc de Procé, southwest entrance (Place Paul Doumer)",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Paris, France",
    "Name/initials/handle": "Victor",
    "Email address": "victorforissier@gmail.com",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "3:00 PM",
    "Coordinates": "///edicts.required.lightly",
    "Location description": "Parc Monceau near the weird pyramid. Will be wearing only red and white (including a red shirt), and (maybe) holding an ACX sign!",
    "Notes": "French/English bilingual",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Toulouse, France",
    "Name/initials/handle": "Loïc",
    "Email address": "acx.tls@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "3:00 PM",
    "Coordinates": "///promises.sentences.lance",
    "Location description": "Jardin des Plantes, northwest part",
    "Notes": "I can change the time, date, and/or location if needed.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Berlin, Germany",
    "Name/initials/handle": "Ruben",
    "Email address": "ssc@alphabattle.xyz",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "3:00 PM",
    "Coordinates": "///directly.packing.pardon",
    "Location description": "Südplateau Fritz-Schloss-Park",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bonn, Germany",
    "Name/initials/handle": "Anton",
    "Email address": "acx-bonn@posteo.de",
    "Date (mm/dd/yyyy)": "10/2/2021",
    "Time": "7:00 PM",
    "Coordinates": "///snooty.sings.both",
    "Location description": "Hofgartenwiese an der Statue von August Macke. Look out for this statue and a small sign saying 'ACX'. If you are late or bad weather is forecast please email me.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Cologne (Köln), Germany",
    "Name/initials/handle": "Elias",
    "Email address": "minus42cgn@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "5:00 PM",
    "Coordinates": "///album.disputes.snored",
    "Location description": "Hiroshima-Nagasaki-Park, Hill towards Aachener Weiher. I will put up a sign with \"ACX MEETUP\" on it",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Erlangen, Bavaria, Germany",
    "Name/initials/handle": "AA",
    "Email address": "burn_adi@yahoo.de",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "2:00 PM",
    "Coordinates": "///laufer.lindwurm.anderem",
    "Location description": "Röthelheimpark (Martin-Luther-King-Weg), at the big stone head",
    "Notes": "This date is after the school summer holidays (13.9.), but before university semester starts (18.10.). If a lot of students sign up, I am amenable to organizing another meetup at a later date.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Hamburg, Germany",
    "Name/initials/handle": "Gunnar Zarncke",
    "Email address": "g.zarncke@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "3:00 PM",
    "Coordinates": "///cove.wider.solves",
    "Location description": "Kleine Wallanlagen on the lawn near Memorial Holstenglacis. Look for pink blankets; I will also have an ACX sign. Here is an Open Street Map Link which also shows the short-cut tunnel from the subway station.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Frankfurt, Germany",
    "Name/initials/handle": "Jan",
    "Email address": "kirchner.jan@icloud.com",
    "Date (mm/dd/yyyy)": "8/25/2021",
    "Time": "7:00 PM",
    "Coordinates": "///staple.buzzer.lance",
    "Location description": "Grüneburgpark (4MF6+R4 Frankfurt), southwest part",
    "Notes": "This will overlap with the first iteration of a EA Frankfurt meetup, so lots of potentially positive synergies!",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Freiberg, Sachsen, Germany",
    "Name/initials/handle": "Alexander",
    "Email address": "act.meets.freiberg@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "4:00 PM",
    "Coordinates": "///salt.diamonds.huddle",
    "Location description": "At the central fountain in the city park just west of the city wall. I'll wear a bright shirt and will put up a sign.",
    "Notes": "German/English bilingual",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Göttingen, Germany",
    "Name/initials/handle": "Nikos",
    "Email address": "nikosbosse@gmail.com",
    "Date (mm/dd/yyyy)": "9/15/2021",
    "Time": "4:30 PM",
    "Coordinates": "///smoothly.magma.wicket",
    "Location description": "Schillerwiese, near Jérôme Pavillon",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Karlsruhe, Germany",
    "Name/initials/handle": "Markus Toran",
    "Email address": "acxmeetup@toranm.me",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "3:00 PM",
    "Coordinates": "///canines.dame.sounding",
    "Location description": "Schlossgarten, we will meet where the blue tiles cross with the train tracks",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Munich, Germany",
    "Name/initials/handle": "Sable",
    "Email address": "sablegm@protonmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "1:00 PM",
    "Coordinates": "///same.exacted.hears",
    "Location description": "English Garden, within 50 meters of the given coordinates, wherever is shade and not many people. I will be wearing a \"Just buy a clock\" white T-shirt.",
    "Notes": "Anyone who wants to contact me without sacrificing their privacy can use a service like guerrillamail.com or temp-mail.org to send me an email from a temporary address. I promise to check my inbox several times from 20:00 to 21:00 German time every day, so you should have ample time to send me an email, get a reply, and read it before your temp email removes the reply. If you want to do that multiple times over a span of time larger than your address remains alive, just generate a random alphanumeric string (look up password generators online), put it somewhere in the first email, and include it in subsequent ones, that way I could figure out same person is talking to me from multiple addresses.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Tübingen, Germany",
    "Name/initials/handle": "Laurenz Hemmen",
    "Email address": "laurenz.hemmen@gmail.com",
    "Date (mm/dd/yyyy)": "9/3/2021",
    "Time": "6:00 PM",
    "Coordinates": "///crust.polished.informed",
    "Location description": "We will meet at the stairs of the Neckarbrücke to the Neckarinsel. I will carry an \"ACX meetup” sign. If its' raining we will go to a nearby cafe/restaurant from there.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Athens, Greece",
    "Name/initials/handle": "Spyros Dovas",
    "Email address": "acx.meetup.athens.greece@gmail.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "7:00 PM",
    "Coordinates": "///sued.scouts.slows",
    "Location description": "Stavros Niarchos Foundation Cultural Center, at the tables by the main entrance to the Library (360 view), I will have a red balloon marking the exact table(s). If it rains we will move under the big \"roof\" upstairs.",
    "Notes": "It will be really great if we manage to establish a small community of people that enjoy and get inspired reading ACX in Athens.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Budapest, Hungary",
    "Name/initials/handle": "Timothy Underwood",
    "Email address": "timunderwood9@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "2:00 PM",
    "Coordinates": "///sticking.flipping.solid",
    "Location description": "We'll meet on Margit Island at Gulliver Park, which is a grassy area behind the bars that are past the fountain. I'll bring a green blanket like thing to sit on and have a purple hard cover copy of one of Richard Dawkins' books. We'll also have an open blue umbrella to mark who we are. If it is raining we'll go to champs sziget bar which is the first big bar on the right past the fountain.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Dublin, Ireland",
    "Name/initials/handle": "Laplace",
    "Email address": "bayesianconspirator@protonmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "2:00 PM",
    "Coordinates": "///steep.beside.veal",
    "Location description": "Stephen's Green playground",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Foligno, Italy",
    "Name/initials/handle": "Orfino Dottorsi",
    "Email address": "orfino@yandex.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "4:30 PM",
    "Coordinates": "///dads.onwards.mailing",
    "Location description": "Parco dei Canapé, at the open air cafe, ask the barista",
    "Notes": "This is a long shot: I am not aware of such a meeting in central Italy. Foligno is the middle point of the entire area and it is very well connected, the goal is to attract ACX fans throughout  the nearby regions. The park is only 800 meters from the train station so that public transport would be an excellent choice. Estimated chances of having more than 2 people is at 10%.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Padova, Italy",
    "Name/initials/handle": "Carlo (CM)",
    "Email address": "04doqkba@ciarlibraun.anonaddy.me",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "3:00 PM",
    "Coordinates": "///capacity.saucepan.servers",
    "Location description": "Obelisco in Prato della Valle. I will have a sign with ACX MEETUP on it.",
    "Notes": "Padova can be a good meeting city for most people living in the north/north-east of Italy, but I'm more than happy to move to another (close) city if it is a better alternative for 1+ other people. Ask people if they'd prefer Udine.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Roma, Italy",
    "Name/initials/handle": "Christian",
    "Email address": "lambiguo@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "4:00 PM",
    "Coordinates": "///lizards.free.crunch",
    "Location description": "Città Universitaria Sapienza in front of the Philosophy building.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Rīga, Latvia",
    "Name/initials/handle": "Valts K",
    "Email address": "valtskr@inbox.lv",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "4:00 PM",
    "Coordinates": "///number.presume.gurgled",
    "Location description": "Bastejkalns (on top of the hill)",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Luxembourg, Luxembourg",
    "Name/initials/handle": "Mathieu Putz",
    "Email address": "mathieuputz (at) gmail (dot) com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "4:30 PM",
    "Coordinates": "///pockets.serve.annoys",
    "Location description": "Parc Kinnekswiss near Glacis, on the big open lawn in the North-East. (The park is near Glacis, which is where the \"Schueberfouer\" will be held at the time of the meetup.) I'll be wearing a burgundy shirt and carrying a sign with \"ACX Meetup\" on it. I'm 1.93m tall, 22 years old and male, with blonde-brownish short hair. If you email me in advance, I'm happy to send you my phone number. That way, in case you don't find us, you can just call me. I'll also check my email regularly during the meetup.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Skopje, Macedonia",
    "Name/initials/handle": "Qantarot",
    "Email address": "info@kantarot.mk",
    "Date (mm/dd/yyyy)": "12/22/2021",
    "Time": "5:00 PM",
    "Coordinates": "///libraries.describe.fresh",
    "Location description": "Rooftop of the Intertec building in Skopje (outdoor but heated and covered in case of rain). Since you'll need to be let in, RSVPing is encouraged. You can also contact me the day of the meetup at +389 71 890 497.",
    "Notes": "My name is Nikola Stikov, I run a blog (qantarot.blogspot.com) that recently spun off a foundation (qantarot.substack.com). I am a professor at Montreal Polytechnique and split my time between Montreal and Skopje. I imagine Montreal already has an organizer (if necessary I can jump in, will be there August 13 - December 15). In Skopje we have a small but passionate rationality community that gravitates around my blog/foundation and we would love to grow the community and raise awareness about EA / ACX.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Amsterdam, Netherlands",
    "Name/initials/handle": "Pierre",
    "Email address": "pierreavdb@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "3:00 PM",
    "Coordinates": "///count.laptops.factor",
    "Location description": "Westerpark, in front of ijscuypje",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Eindhoven, Netherlands",
    "Name/initials/handle": "RH",
    "Email address": "silvery.swift@protonmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "3:00 PM",
    "Coordinates": "///level.dreams.partner",
    "Location description": "Outside \"Het Ketelhuis\" (Ketelhuisplein 1 in Eindhoven), I'll be wearing a red shirt and reading a book.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Maastricht, Netherlands",
    "Name/initials/handle": "Laurens",
    "Email address": "laurensk90@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "2:00 PM",
    "Coordinates": "///paraded.progress.score",
    "Location description": "2e Carabinierslaan 128, in the backyard.",
    "Notes": "I'm fully vaccinated and stats indicate the majority of Dutch adults are too. My address is technically in Belgium but it's practically touching the border, and quickly and easily reachable through all conventional modes of transport.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Rotterdam, Netherlands",
    "Name/initials/handle": "Lydia Krifka-Dobes",
    "Email address": "lydiakrifka@gmail.com",
    "Date (mm/dd/yyyy)": "9/3/2021",
    "Time": "5:00 PM",
    "Coordinates": "///vague.saunas.residual",
    "Location description": "We will meet up by the Water Taxi station very close to Holland Amerikaplein",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "I am volunteering altruistically but would prefer not to host; don't choose me if there are actively excited people available",
    "__5": "No, never"
  },
  {
    "City": "Warsaw, Poland",
    "Name/initials/handle": "MK",
    "Email address": "lesswrongpoland@freelists.org",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "6:00 PM",
    "Coordinates": "///scouts.bowls.clipped",
    "Location description": "Bar Studio, Plac Defilad 1, outdoor tables",
    "Notes": "",
    "Additional contact info": "Meetup.com event",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Gdańsk, Poland",
    "Name/initials/handle": "Frank",
    "Email address": "frankastralcodexten@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "1:00 PM",
    "Coordinates": "///flood.gangway.scans",
    "Location description": "Park Akademicki opposite the Opera Bałtycka",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lisbon, Portugal",
    "Name/initials/handle": "Thor",
    "Email address": "thorck@protonmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "5:00 PM",
    "Coordinates": "///guitars.record.caps",
    "Location description": "Parque da Pedra at Monsanto Park, spot the tall white guy in pink pants. There's an adjacent road with street parking, and a clearing at that point that opens onto a trail that leads to the park.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bucharest, Romania",
    "Name/initials/handle": "Alen",
    "Email address": "alen3000@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "7:00 PM",
    "Coordinates": "///cool.bells.balanced",
    "Location description": "Cișmigiu Park, center of Rotonda Scriitorilor",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Rostov-on-Don, Russia",
    "Name/initials/handle": "Nadia",
    "Email address": "nadia.s.1024@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "2:00 PM",
    "Coordinates": "///chew.message.green",
    "Location description": "Food court \"Leto\" near Don State Public Library (Pushkinskaya, 175). We'll have an ACX sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Saint Petersburg, Russia",
    "Name/initials/handle": "Vit",
    "Email address": "imbarus@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "2:00 PM",
    "Coordinates": "///logged.kitchens.lined",
    "Location description": "Aleksandrovskiy Park near Gorkovskaya if the weather allows it, near \"Bolshe coffee\" coffeshop. Huge guy with moustache and a hat i guess?",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Stockholm, Sweden",
    "Name/initials/handle": "Sal",
    "Email address": "sallat@protonmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "3:30 PM",
    "Coordinates": "///glow.fracture.retire",
    "Location description": "Humlegården, Karlavägen. We will meet near blue gazebo, I will have \"ACX meetup\" sign.",
    "Notes": "We have an existing group that has been organizing regular SSC meetups for a while. I only recently took over as organizer, but the group exists for several years",
    "Additional contact info": "Facebook group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Basel, Switzerland",
    "Name/initials/handle": "Julian",
    "Email address": "julian.sscmeetup@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "5:30 AM",
    "Coordinates": "///wharfs.addicted.bubbles",
    "Location description": "At Wettepark, near the patio.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bern, Switzerland",
    "Name/initials/handle": "Daniel",
    "Email address": "dd14214@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "4:00 PM",
    "Coordinates": "///softest.eagle.gangway",
    "Location description": "Marzili, at the main entrance vis-a-vis the Gelateria di Berna",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Geneva, Switzerland",
    "Name/initials/handle": "Konrad Seifert",
    "Email address": "seifert.konrad@gmail.com",
    "Date (mm/dd/yyyy)": "9/17/2021",
    "Time": "6:30 PM",
    "Coordinates": "///soucieux.preparer.appeler",
    "Location description": "We will meet in Parc de la Grange, near the entrance to the Orangerie, next to the Monkey Puzzle tree (Araucaria araucana). I will be wearing a green t-shirt/sweater and carrying a sign with ACX Meetup on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Zurich, Switzerland",
    "Name/initials/handle": "SSC_Zurich",
    "Email address": "ssczurich@gmx.ch",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "3:00 PM",
    "Coordinates": "///paints.shows.dressy",
    "Location description": "Blatterwiese, across from the Chinese Garden",
    "Notes": "People can email the address given to be added to the mailing list.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Birmingham, UK",
    "Name/initials/handle": "Tom A",
    "Email address": "askew.thomas@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "1:00 PM",
    "Coordinates": "///oldest.preoccupied.kind",
    "Location description": "Cathedral Square, AKA Pigeon Park. Benches to the rear (east) of the Cathedral. There will be an A3 sign showing \"ACX Meetup\". The site is ~400 yards from New Street Station, making it accessible for anyone in the greater West Midlands area.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bristol, UK",
    "Name/initials/handle": "Nick Lowry",
    "Email address": "bristoleffectivealtruism@gmail.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "11:30 AM",
    "Coordinates": "///excuse.intro.soft",
    "Location description": "Brandon Hill, near Cabot Tower",
    "Notes": "Plans are still being decided; join the FB page or the WhatsApp group for updates.",
    "Additional contact info": "Facebook group; WhatsApp group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Cambridge, UK",
    "Name/initials/handle": "Theodore Ehrenborg",
    "Email address": "jtae2@cam.ac.uk",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "4:00 PM",
    "Coordinates": "///proper.event.wiring",
    "Location description": "I'll be near the Jesus Green Skatepark, wearing a blue shirt and holding an ACX MEETUP sign",
    "Notes": "If you want to attend but can't because of the time/date, email me",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Edinburgh, UK",
    "Name/initials/handle": "Sam",
    "Email address": "s.enright@sms.ed.ac.uk",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "2:00 PM",
    "Coordinates": "///boxing.branch.appeal",
    "Location description": "The Meadows, picnic tables next to the playground. I will be wearing a navy jumper",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Falmouth, UK",
    "Name/initials/handle": "mini t",
    "Email address": "tminns@btinternet.com",
    "Date (mm/dd/yyyy)": "TBD",
    "Time": "12:00 PM",
    "Coordinates": "///seats.reef.manual",
    "Location description": "Gyllyngvase Beach",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lincoln, UK",
    "Name/initials/handle": "Tobias",
    "Email address": "tobias.showan@yahoo.co.uk",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "2:00 PM",
    "Coordinates": "///vanish.burn.copy",
    "Location description": "Beer garden of the Horse and Groom, Carholme Rd, Lincoln LN1 1RH",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "London, UK",
    "Name/initials/handle": "Edward Saperia",
    "Email address": "edsaperia@gmail.com",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "1:00 PM",
    "Coordinates": "///crab.gossip.winter",
    "Location description": "Terrace of Newspeak House, 133 Bethnal Green Road, E2 7DG",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Manchester, UK",
    "Name/initials/handle": "OK",
    "Email address": "osnatkatz@protonmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "2:00 PM",
    "Coordinates": "///tigers.wasp.union",
    "Location description": "Whitworth Park, Oxford Road, Manchester, M14 4PW. We'll be gathered by the picnic tables on Oxford Road side.",
    "Notes": "Transport information: The 15/18/42/43/111/142/143/147 buses all stop right outside Whitworth Park, and all take cash or contactless. If you're not in Greater Manchester, you can get to Manchester Piccadilly train station pretty easily (most trains stop here) and walk up from there to the Piccadilly Gardens bus station, where buses to South Manchester depart at least once every 10 minutes. The closest parking place is the Q-Park Wilmslow Park on Hathersage Road, about 10 minutes' walk away. Free parking is somewhere between difficult and impossible to find.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Newcastle, UK",
    "Name/initials/handle": "Chris G",
    "Email address": "wardle@live.fr",
    "Date (mm/dd/yyyy)": "TBD",
    "Time": "11:00 AM",
    "Coordinates": "///arena.steps.burst",
    "Location description": "Old Eldon Square (Hippie Green), northwest quadrant. I'll be wearing a suit jacket and Hawaiian shirt.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Oxford, UK",
    "Name/initials/handle": "Sam",
    "Email address": "ssc@sambrown.eu",
    "Date (mm/dd/yyyy)": "TBD - see post",
    "Time": "7:00 PM",
    "Coordinates": "///nobody.joined.friend",
    "Location description": "South Park, near the Divinity Road entrance",
    "Notes": "I wouldn't say I'm a /crap/ organiser, exactly, but I don't schedule meetings very often and I've not been very responsive to people who've offered to help. I'm a bit of a bottleneck, and I'm open to be joined/replaced by someone more diligent.",
    "Additional contact info": "Facebook group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Dnipro, Ukraine",
    "Name/initials/handle": "Vlad Sitalo",
    "Email address": "root@stvad.org",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "5:00 PM",
    "Coordinates": "///things.walls.proofs",
    "Location description": "Shevchenko Park, near entrance to the bridge crossing to the Monastyrsky island",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Perth, Western Australia",
    "Name/initials/handle": "Madge",
    "Email address": "madgech@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "2:00 PM",
    "Coordinates": "///kept.locate.dose",
    "Location description": "Russell Square, Northbridge, corner of Shenton and Aberdeen St. There will be some sort of ACX meetup sign. If it is raining, we will go to San Churro Northbridge instead.",
    "Notes": "If there is an indoor mask mandate in place, consider that a proxy for the COVID situation being bad enough to cancel the meetup.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Hong Kong",
    "Name/initials/handle": "Aldrin",
    "Email address": "aldrin.cheung@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "12:30 PM",
    "Coordinates": "///director.crossings.outs",
    "Location description": "TusPark Workhub Causeway Bay, 23/F, Island Beverley, 1 Great George Street, Causeway Bay, Hong Kong",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Mumbai, India",
    "Name/initials/handle": "Nitin Nair",
    "Email address": "nairnitin2424@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "5:30 PM",
    "Coordinates": "///simulator.works.freedom",
    "Location description": "Marine Drive, opposite the NCPA",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "New Delhi, India",
    "Name/initials/handle": "SK",
    "Email address": "nevakanezzar@gmail.com",
    "Date (mm/dd/yyyy)": "9/9/2021",
    "Time": "6:00 PM",
    "Coordinates": "///change.value.intruders",
    "Location description": "Regional Park near NFC market. Straight up the path towards the back where the little hill is.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Jakarta, Indonesia",
    "Name/initials/handle": "Jaticarta",
    "Email address": "goomilar.setya@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "3:00 PM",
    "Coordinates": "///uptake.harmony.conclude",
    "Location description": "Arborea Café, Senayan, DKI Jakarta",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Auckland, New Zealand",
    "Name/initials/handle": "Mako Yass",
    "Email address": "marcus.yass@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "4:00 PM",
    "Coordinates": "///jump.trial.films",
    "Location description": "If the current covid alert level allows indoor meetings, and the temperature listed here is at or below 18°C at 4pm, we will gather in Lim Chhour food court and asian supermarket on Karangahape Road. Otherwise (if either of those conditions are false), if the lockdown level permits small outdoor gatherings, we will try to meet in Albert Park, in the Gazebo here; or if someone else is using the gazebo we will meet beside it somewhere around here. You will be able to recognise us by the reflective silvery orb about the size of a rockmelon positioned in the center of the gathering.",
    "Notes": "Date is September 12th OR whichever Sunday first comes after the alert level once again permits gatherings",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Wellington, New Zealand",
    "Name/initials/handle": "Ben W",
    "Email address": "benwve@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "1:00 PM",
    "Coordinates": "///jets.drank.fits",
    "Location description": "Waitangi Park. Main grassy area, west-most corner.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Singapore",
    "Name/initials/handle": "DG",
    "Email address": "druidgetafix91@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "5:00 PM",
    "Coordinates": "///units.jelly.chain",
    "Location description": "BQ Bar, 39 Boat Quay. Outdoor Seating area, with a ACX Meetup sign.",
    "Notes": "Currently in Singapore there is a group size restriction of 5 fully vaccinated (2nd dose +14 days) people. To get into the bar you must show proof of full vaccination, a negative PET result that's valid for the dine-in duration, or proof of recovery from COVID-19.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Taipei, Taiwan",
    "Name/initials/handle": "KZ",
    "Email address": "kz.acx@co.sent.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "12:00 PM",
    "Coordinates": "///notice.chills.perform",
    "Location description": "Inside the Nanmen Park Museum's cafe, look for the \"ACX\" sign. Coordinates point to the entrance.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Buenos Aires, Argentina",
    "Name/initials/handle": "Juan",
    "Email address": "juan.acxmeetup@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "4:00 PM",
    "Coordinates": "///meanest.erupted.generals",
    "Location description": "The location will be Parque Centenario, which is located in the geographic center of the City of Buenos Aires. I will be seating at one of the benches by the central lake of the park, carrying a sign with ACX MEETUP on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "São Paulo, São Paulo, Brazil",
    "Name/initials/handle": "Fernando",
    "Email address": "fdesmello@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "2:00 PM",
    "Coordinates": "///refrain.hacking.workforce",
    "Location description": "Ibirapuera Park, in front of the entrance to the Planetarium. I will be carrying a sign with 'ACX MEETUP' on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bogotá, Colombia",
    "Name/initials/handle": "Dan",
    "Email address": "shorty.george.productions+acx@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "2:00 PM",
    "Coordinates": "///dull.biked.debate",
    "Location description": "We'll meet at Cafe Illy Kr 15, #87-94 (by Parque Virrey).  I'll wear a green T-shirt saying \"I went to theodicy-con 2017...\" and have a sign with \"ACX MEETUP",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Mexico City, Mexico",
    "Name/initials/handle": "Fornicad Cigarros",
    "Email address": "fagarrido@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "4:00 AM",
    "Coordinates": "///spoiled.given.waving",
    "Location description": "Bosque de Chapultepec by the Canadian Totem",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Be'er Sheva, Israel",
    "Name/initials/handle": "Oren",
    "Email address": "oren-acxmeetup@opayq.com",
    "Date (mm/dd/yyyy)": "9/9/2021",
    "Time": "7:00 PM",
    "Coordinates": "///couple.answers.herb",
    "Location description": "רגע, מקום בפארק\nפארק הסופרים שכונה ב'",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Tel Aviv, Israel",
    "Name/initials/handle": "Inbar",
    "Email address": "inbar192@gmail.com",
    "Date (mm/dd/yyyy)": "10/7/2021",
    "Time": "7:00 PM",
    "Coordinates": "///market.coherent.muddle",
    "Location description": "Sarona market park, between the Magnum bar and Sarona beer garden. I'll have an ACX sign and some red balloons.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lagos, Nigeria",
    "Name/initials/handle": "Damola",
    "Email address": "social@damolamorenikeji.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "3:35 PM",
    "Coordinates": "///brittle.fondest.zips",
    "Location description": "The Joy Hub, Lagos",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Johannesburg, South Africa",
    "Name/initials/handle": "DS",
    "Email address": "87robertjames@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "3:00 PM",
    "Coordinates": "///holiday.crashing.custom",
    "Location description": "Delta Park, within 100m of the parking area on the west. I will be wearing a red shirt or jacket, carrying a sign that says ACX MEETUP.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Dubai, UAE",
    "Name/initials/handle": "RS",
    "Email address": "xyxyxz@gmail.com",
    "Date (mm/dd/yyyy)": "10/1/2021",
    "Time": "6:00 PM",
    "Coordinates": "///themes.seasonal.salsa",
    "Location description": "Starbucks behind Jumeirah Creekside Hotel",
    "Notes": "This is probably going to be a tiny group, so I'm open to change time or location to accommodate anyone if they get in touch.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Phoenix, AZ",
    "Name/initials/handle": "Ben Morin & aK",
    "Email address": "benjamin.j.morin@gmail.com, sareenyoga@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "5:00 PM",
    "Coordinates": "///wages.putty.ground",
    "Location description": "Cactus Park, 7202 E Cactus Rd, Scottsdale, AZ 85260. We will meet under the east ramada closest to the parking lot. aK will be wearing a red t-shirt.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Belmont, CA",
    "Name/initials/handle": "SS",
    "Email address": "ss4417@columbia.edu",
    "Date (mm/dd/yyyy)": "8/27/2021",
    "Time": "4:00 PM",
    "Coordinates": "///prices.shut.basket",
    "Location description": "Twin Pines Park, near Buckeye Picnic Area (see park map)",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Berkeley, CA",
    "Name/initials/handle": "Habryka",
    "Email address": "oliver.habryka@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "1:00 PM",
    "Coordinates": "///powers.rating.final",
    "Location description": "TBD, either UC Berkeley campus or Event Horizon backyard",
    "Notes": "Time, date, and location subject to change",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Grass Valley, CA",
    "Name/initials/handle": "Max Harms",
    "Email address": "raelifin@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "2:00 PM",
    "Coordinates": "///payer.apply.filer",
    "Location description": "Condon Park near Dogs Run Free",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Harbor City, CA",
    "Name/initials/handle": "Eric",
    "Email address": "eric.l.fire@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "7:00 PM",
    "Coordinates": "///test.obliges.paces",
    "Location description": "Ken Malloy Harbor Regional Park, on the lakeside, on the same latitude as the fork in the road where Vermont splits into Normandie.",
    "Notes": "I am doing this primarily because I am bringing my chess set and want to go a few rounds. If there is also ACC themed discussions going on around us, icing on the cake.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Irvine, CA",
    "Name/initials/handle": "Nick",
    "Email address": "cohenskijanuary1@mail.com",
    "Date (mm/dd/yyyy)": "10/2/2021",
    "Time": "3:00 PM",
    "Coordinates": "///peanut.shuts.elevate",
    "Location description": "William R Mason Regional. Look for ACX Meetup sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Monterey, CA",
    "Name/initials/handle": "Andrew",
    "Email address": "ajsmitha7@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "2:00 PM",
    "Coordinates": "///retail.poetic.gets",
    "Location description": "Veterans Memorial Park, on the grass, I'll have an orange frisbee",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Oakland, CA",
    "Name/initials/handle": "Max",
    "Email address": "paxperplexus@gmail.com",
    "Date (mm/dd/yyyy)": "9/9/2021",
    "Time": "7:00 PM",
    "Coordinates": "///softly.finishing.risks",
    "Location description": "Marina Lawn, Jack London Square, we’ll be on the grass (you can bring blankets or chairs if you want) at the northwest corner. I’ll be wearing a blue and white stovepipe hat. For food there is pizza, Thai, burgers and salads very nearby.",
    "Notes": "I hope someone uses this chance to start a public weekend meetup in the east bay — but if not I hope my weeknight meetup can suffice.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Pasadena, CA",
    "Name/initials/handle": "SG",
    "Email address": "sgord512@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "3:00 PM",
    "Coordinates": "///piper.calculating.harp",
    "Location description": "Central Park in Pasadena; We'll be in the southeast corner and there will be a sign that says ACX on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Sacramento, CA",
    "Name/initials/handle": "Andrew",
    "Email address": "justsomerandomguy@protonmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "3:00 PM",
    "Coordinates": "///transfers.easy.anyway",
    "Location description": "Backyard of private home, near the intersection of Garfield and Marconi — address will be provided by email",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "San Diego, CA",
    "Name/initials/handle": "Julius",
    "Email address": "julius.simonelli@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "11:00 AM",
    "Coordinates": "///deed.rift.people",
    "Location description": "Bird Park; I'll be wear a red shirt and a baseball cap",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "San Francisco, CA",
    "Name/initials/handle": "Derek Pankaew",
    "Email address": "derekpankaew@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "2:00 PM",
    "Coordinates": "///skips.turned.action",
    "Location description": "Dolores Park, San Francisco | On the grass, near the tennis courts, I'll hold up an ACX sign",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "San Rafael, CA",
    "Name/initials/handle": "Sridhar Prasad",
    "Email address": "sridhar_90033@yahoo.com",
    "Date (mm/dd/yyyy)": "9/24/2021",
    "Time": "4:00 PM",
    "Coordinates": "///code.salads.issue",
    "Location description": "Freitas Water Park. I will be wearing scrubs and I’ll bring a sign. I’ll have a cooler with some sparkling water as well.",
    "Notes": "Kids play in the park and I don’t want to displace them. Still, it should be quite possible for us to have space to hang out and chat, etc",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Santa Cruz, CA",
    "Name/initials/handle": "Maxwell",
    "Email address": "maxwelljoslyn@gmail.com",
    "Date (mm/dd/yyyy)": "10/2/2021",
    "Time": "11:00 AM",
    "Coordinates": "///foster.fantastic.spared",
    "Location description": "Ocean View Park by the big rocks. I will wear a magenta shirt and carry a balloon.",
    "Notes": "I am open to hosting a regular meetup if there is sufficient interest.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Sunnyvale, CA",
    "Name/initials/handle": "IS",
    "Email address": "svmeetup@protonmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "3:00 PM",
    "Coordinates": "///island.economies.coach",
    "Location description": "On the roundish grassy area in the northeast corner of Washington Park, 840 W Washington Ave. We'll have a dark blue picnic blanket and a ACX Meetup sign attached to a red camping chair.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Thousand Oaks, CA",
    "Name/initials/handle": "Mike",
    "Email address": "martoca@live.com",
    "Date (mm/dd/yyyy)": "10/17/2021",
    "Time": "12:01 PM",
    "Coordinates": "///massing.comfort.pace",
    "Location description": "Picnic tables at Lynn Oaks Park, 359 Capitan St, Thousand Oaks, CA 91360",
    "Notes": "",
    "Additional contact info": "Meetup.com group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "West Los Angeles, CA",
    "Name/initials/handle": "Robert",
    "Email address": "bobert.mushky@gmail.com",
    "Date (mm/dd/yyyy)": "10/6/2021",
    "Time": "7:00 PM",
    "Coordinates": "///labs.motion.cherry",
    "Location description": "3266 Inglewood Blvd, Los Angeles, CA 90066",
    "Notes": "Location is subject to change; join the Google Group for updates. Meetups are every Wednesday at 7 pm.",
    "Additional contact info": "Google group; LessWrong group; Discord server",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Boulder, CO",
    "Name/initials/handle": "Josh Sacks",
    "Email address": "josh.sacks+acx@gmail.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "4:00 PM",
    "Coordinates": "///complex.politicians.appointing",
    "Location description": "9191 Tahoe Ln, Boulder, CO 80301",
    "Notes": "We have a large landscaped outdoor area near the house + 55 acres in case folks *really* want to social distance. Also happy to cater with pizza/BBQ if that will bring more peeps.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Denver, CO",
    "Name/initials/handle": "Matt Lowerre",
    "Email address": "mattlowerre@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "1:00 PM",
    "Coordinates": "///serves.spends.minds",
    "Location description": "Washington Park Northwest Corner",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lakewood, CO",
    "Name/initials/handle": "Eneasz Brodski",
    "Email address": "embrodski@gmail.com",
    "Date (mm/dd/yyyy)": "9/1/2021",
    "Time": "7:00 PM",
    "Coordinates": "///chances.envisaged.ruffle",
    "Location description": "2800 S Estes St, Lakewood, CO 80227. It's a park, walk just a bit into it from the parking lot and you'll find a few picnic tables under a roof. We're meeting there.",
    "Notes": "We have a regular crew of 8-10 people that come to most of these meetups, and we'd love to meet other rationalist-adjacent people in the Denver area. We meet the first Wednesday of every month.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Fairfield, CT",
    "Name/initials/handle": "Justin Barclay",
    "Email address": "barclay.justin@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "10:00 AM",
    "Coordinates": "///spotlights.notify.colleague",
    "Location description": "South Pine Creek Beach",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Storrs, CT",
    "Name/initials/handle": "Isadore J",
    "Email address": "isadore.johnson@uconn.edu",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "2:00 PM",
    "Coordinates": "///songbird.practically.laundry",
    "Location description": "We'll meet outside Mirror Lake",
    "Notes": "",
    "Additional contact info": "202-495-1332",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Washington, DC",
    "Name/initials/handle": "John Bennett",
    "Email address": "johnofcharleston@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "5:00 PM",
    "Coordinates": "///decent.search.hurls",
    "Location description": "Patio next to private residence at 1002 N St. NW, Washington DC, 20001. Follow the sign for \"Free Utility\".",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Fort Lauderdale, FL",
    "Name/initials/handle": "Vlad",
    "Email address": "vovaplombir@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "4:00 PM",
    "Coordinates": "///training.today.surreal",
    "Location description": "Starbucks at 2519 E Sunrise Blvd, outdoor seating area",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Gainesville, FL",
    "Name/initials/handle": "ZachH",
    "Email address": "zachary.hamaker@gmail.com",
    "Date (mm/dd/yyyy)": "9/7/2021",
    "Time": "7:30 PM",
    "Coordinates": "///briefer.releases.loyal",
    "Location description": "4th Ave Food Park, I’ll be wearing a maroon shirt",
    "Notes": "Will consider delaying if the COVID situation in FL doesn’t improve",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Gulf Breeze, FL",
    "Name/initials/handle": "Christian",
    "Email address": "christian.h.williams@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "5:30 PM",
    "Coordinates": "///legroom.trustees.feather",
    "Location description": "The outdoor deck at The Grey Taproom. I'll be wearing a blue t-shirt with a crudely drawn wizard on it that says Pavement Ist Rad. It's a band shirt fyi.",
    "Notes": "If no one emails me saying they'll be there, I won't be there.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Miami, FL",
    "Name/initials/handle": "Eric",
    "Email address": "eric135033 at gmail",
    "Date (mm/dd/yyyy)": "10/9/2021",
    "Time": "5:00 PM",
    "Coordinates": "///delivers.trading.season",
    "Location description": "Books & Books, 265 Aragon Ave, Coral Gables, FL 33134 --- We'll be seated in the outdoor patio area with an ACX MEETUP sign on the table.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Orlando, FL",
    "Name/initials/handle": "Noah Topper",
    "Email address": "noah.topper@gmail.com",
    "Date (mm/dd/yyyy)": "10/8/2021",
    "Time": "6:30 PM",
    "Coordinates": "///trading.undergraduate.verbs",
    "Location description": "University of Central Florida, 4000 Central Florida Blvd, Orlando, FL 32816. We'll meet at a small pavilion on campus. Here's a UCF map: https://map.ucf.edu/. If you start from Garage A or I and walk toward the center of campus, you'll walk by a small gazebo-looking place; that's where we'll meet. Other nearby landmarks include the campus library, the reflection pond, and the Foxtail Cafe. I'll try to have something identifying.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Tampa, FL",
    "Name/initials/handle": "A.D.",
    "Email address": "aka.eden@gmail.com",
    "Date (mm/dd/yyyy)": "10/2/2021",
    "Time": "4:30 PM",
    "Coordinates": "///smarter.slice.chef",
    "Location description": "Water Works Park, in front of Ulele",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Athens, GA",
    "Name/initials/handle": "TW",
    "Email address": "ttaskward@gmail.com",
    "Date (mm/dd/yyyy)": "9/26/2021",
    "Time": "6:00 PM",
    "Coordinates": "///pouts.succeeds.quilting",
    "Location description": "State Botanical Garden, outside the Garden Club of Georgia. I will be in a red shirt at the front fountain closest to the green house.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Atlanta, GA",
    "Name/initials/handle": "Steve French",
    "Email address": "steve@digitaltoolfactory.net",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "2:00 PM",
    "Coordinates": "///readily.sank.struck",
    "Location description": "The Beltline on Memorial Drive, near Muchacho Coffeehouse -  I will have  large sign that says \"ACX Meetup",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Honolulu, HI",
    "Name/initials/handle": "James L",
    "Email address": "jglamine@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "4:00 PM",
    "Coordinates": "///tingled.steer.tricky",
    "Location description": "Magic island, on the grass under a tree by this drop pin: https://goo.gl/maps/PJ7dJjgZusNsjVd7A",
    "Notes": "Look for the ACX sign. We will be sitting on the grass so you may want to bring a blanket, towel, or beach chair to sit on. Consider bringing water and sunscreen. It would be helpful if you RSVP in the google group: https://groups.google.com/g/acx-meetup-honolulu",
    "Additional contact info": "Google group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Champaign-Urbana, IL",
    "Name/initials/handle": "nk",
    "Email address": "nmkiahrne@outlook.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "6:00 PM",
    "Coordinates": "///saying.music.rust",
    "Location description": "UIUC main quad, south end. I will wear a red t-shirt and have an ACX meetup sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Chicago, IL",
    "Name/initials/handle": "Todd",
    "Email address": "todd@southloopsc.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "2:00 PM",
    "Coordinates": "///pink.longer.diary",
    "Location description": "Ping Tom Park. The Cermak Red Line stop is reasonably close, and there's usually free parking at the main Ping Tom complex here: https://goo.gl/maps/a346wrwukm7KRQgc7",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bloomington, IN",
    "Name/initials/handle": "Avery",
    "Email address": "acxbloomington@fastmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "2:00 PM",
    "Coordinates": "///taking.miles.making",
    "Location description": "Switchyard Park. Will be at one of the tables near the Rogers Street parking lot. I will bring a sign that says “ACX”",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Louisville, KY",
    "Name/initials/handle": "KWT",
    "Email address": "kris@ipocandy.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "3:00 PM",
    "Coordinates": "///natural.louder.underground",
    "Location description": "Tom Sawyer State Park - Shelter #3",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "New Orleans, LA",
    "Name/initials/handle": "Noah",
    "Email address": "snugstarling@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "6:30 PM",
    "Coordinates": "///rattler.mediate.promote",
    "Location description": "Audubon Riverview Park (AKA \"the Fly\") at the Butterfly Pavilion",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Ann Arbor, MI",
    "Name/initials/handle": "Sam",
    "Email address": "samrossini9@gmail.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "3:00 PM",
    "Coordinates": "///slices.zealous.launch",
    "Location description": "Island Park Shelter A, Ann Arbor, MI We will be at Island Park Shelter A. It is the first shelter when you enter the park, closest to the foot bridge to the island.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Boston/Cambridge, MA",
    "Name/initials/handle": "Dan Elton, Robi Rahman",
    "Email address": "bostonacx@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "5:00 PM",
    "Coordinates": "///area.bricks.tribune",
    "Location description": "John F Kennedy Park in Cambridge, near the picnic tables.",
    "Notes": "",
    "Additional contact info": "Facebook event; Google group; Facebook group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Baltimore, MD",
    "Name/initials/handle": "Rivka",
    "Email address": "rivka@adrusi.com",
    "Date (mm/dd/yyyy)": "9/19/2021",
    "Time": "7:00 PM",
    "Coordinates": "///lasted.slide.skip",
    "Location description": "UMBC campus, outside the Performing Arts and Humanities Building. We'll be by the arches, and I will have a sign that says ACX. If you're having trouble finding us, you can email me.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Detroit, MI",
    "Name/initials/handle": "Matt Arnold",
    "Email address": "matt.mattarn@gmail.com",
    "Date (mm/dd/yyyy)": "TBD",
    "Time": "8:00 PM",
    "Coordinates": "///helps.volunteered.ankle",
    "Location description": "Outdoor seating area, Tenacity Craft, 8517 2nd Ave, Detroit, MI 48202.",
    "Notes": "I might be the only potential attendee here. I will cancel if there is not at least 1 RSVP.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Rochester, MN",
    "Name/initials/handle": "Brandon",
    "Email address": "brandoninrochester@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "4:00 PM",
    "Coordinates": "///basic.sings.wisely",
    "Location description": "Essex Park @ the picnic tables. We'll have a sign with \"ACX MEETUP\" on it!",
    "Notes": "Kids are welcome! There are spooky woods nearby that are well worth exploring, for kids who like that sort of thing.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Kansas City, MO",
    "Name/initials/handle": "Maryana Pinchuk",
    "Email address": "justdandy@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "3:00 PM",
    "Coordinates": "///baker.twilight.methodical",
    "Location description": "Swope Park Shelter #7",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "St. Louis, MO",
    "Name/initials/handle": "JohnBuridan",
    "Email address": "littlejohnburidan@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "3:00 PM",
    "Coordinates": "///fields.flank.feed",
    "Location description": "Tower Grove Park. Chinese Pavilion.",
    "Notes": "All vaguely connected rationalsphere types welcome. I'm not connected to Wash U or SLU. If anyone in the ACX world is, they should do us a favor by promoting the event on campus.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Durham, NC",
    "Name/initials/handle": "Will Jarvis",
    "Email address": "willdjarvis@gmail.com",
    "Date (mm/dd/yyyy)": "8/26/2021",
    "Time": "6:30 PM",
    "Coordinates": "///verbs.clock.finest",
    "Location description": "Ponysaurus Brewing, 219 Hood St, Durham, NC 27701, outdoor seating area. I will have a sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Wilmington, NC",
    "Name/initials/handle": "Todd",
    "Email address": "twoc@hardboot.org",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "1:00 PM",
    "Coordinates": "///parks.hands.provider",
    "Location description": "Long Leaf Park, south of splash pad",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Omaha, NE",
    "Name/initials/handle": "TracingWoodgrains",
    "Email address": "tracingwoodgrains@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "5:00 PM",
    "Coordinates": "///ashes.salt.green",
    "Location description": "Memorial Park - We will be near the white stone monument at the center of the park. I'll be wearing jeans and a black polo, carrying a sign with ACX meetup on it.",
    "Notes": "I've arranged a meetup before, but never in Omaha, and to be frank I don't know if there are more than one or two other ACX readers there, so this meetup is an experimental roll of the dice to see if anyone will show. I encourage interested parties to email me so I can get a sense of how many people to expect.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Concord, NH",
    "Name/initials/handle": "Lincoln",
    "Email address": "lincoln@techhouse.org",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "11:00 AM",
    "Coordinates": "///scenic.bowls.unfounded",
    "Location description": "Marjory Swope Park, specifically the bench and vista point overlooking Penacook Lake. Accessible via a 15 minute hike (some uphill) from the Marjory Swope Park trailhead on Long Pond Road (///spurring.declare.towards). You can see the trail on this map: https://www.concordnh.gov/DocumentCenter/View/9159/Map-25-Swope-Park-Trails. Bring a lunch!",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lakewood, NJ",
    "Name/initials/handle": "Ben L",
    "Email address": "mywebdev3@gmail.com",
    "Date (mm/dd/yyyy)": "8/29/2021",
    "Time": "11:00 AM",
    "Coordinates": "///novel.stick.meals",
    "Location description": "Ocean County Park. East end of the first big parking lot. I'll be the tall guy in gym clothing wearing a yarmulke.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Las Vegas, NV",
    "Name/initials/handle": "JWR",
    "Email address": "ray.jonathan.w@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "10:00 AM",
    "Coordinates": "///compiles.graduating.logged",
    "Location description": "Silverado Ranch Park at one of the south pavillions with a big ACX sign",
    "Notes": "The last time I tried to organize a meetup.com event a few RSVPed but none of them showed up.  I would appreciate it if people RSVP and pinky swear that they'll actually show up if they do RSVP.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Reno, NV",
    "Name/initials/handle": "Steven Lee",
    "Email address": "stevenbrycelee@gmail.com",
    "Date (mm/dd/yyyy)": "9/17/2021",
    "Time": "6:00 PM",
    "Coordinates": "///island.normal.agents",
    "Location description": "Idlewild Park, by the workout station near the western entrance of the park. I'll be the tall person in a pink shirt.",
    "Notes": "This is an outdoor park by a river, but there have been smoke problems recently. I might cancel if the air quality is too bad and reschedule later, but let me know if you’d be interested in coming and I’ll let you know the new date .",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Buffalo, NY",
    "Name/initials/handle": "George Herold",
    "Email address": "ggherold@gmail.com",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "1:00 PM",
    "Coordinates": "///witnessing.balanced.stand",
    "Location description": "Private home at 932 Welch Rd., Java Center (half-hour drive from Buffalo)",
    "Notes": "I live in the country, woods, trails, a stream with waterfalls.  Walking the creek is a great way to cool off it it's hot, so bring 'creek shoes' if you might be so inclined.  I also have two or three dogs if that would be a problem.  I'll cook up some hamburgers, hot dogs along with local sweet corn... Yum!",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Ithaca, NY",
    "Name/initials/handle": "Russ Nelson",
    "Email address": "russnelson@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "12:00 PM",
    "Coordinates": "///slices.bonus.deflection",
    "Location description": "Ithaca Commons \"Child of Ithaca\" statue",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "New York City, NY",
    "Name/initials/handle": "Jasmine, Shaked & Tristan",
    "Email address": "jasminermj@gmail.com; shaked.koplewitz@gmail.com; trishume@gmail.com",
    "Date (mm/dd/yyyy)": "9/6/2021",
    "Time": "5:00 PM",
    "Coordinates": "///swung.shape.shows",
    "Location description": "Teardrop Park",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Columbus, OH",
    "Name/initials/handle": "Jim Hays",
    "Email address": "james.thomas.hays@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "3:00 PM",
    "Coordinates": "///appeal.august.post",
    "Location description": "Clifton Park Shelterhouse (this is in the SW corner of Jeffrey Park). We will have a sign that says ACX Meetup.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Toledo, OH",
    "Name/initials/handle": "Luke Zhao",
    "Email address": "lukezhao9@protonmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "2:00 PM",
    "Coordinates": "///citizenship.walnuts.preserves",
    "Location description": "Toledo Botanical Garden. We will meet at the cluster of picnic tables near the north parking lot, a bathroom, and a water fountain. We will likely have a sign or a red balloon.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Oklahoma City, OK",
    "Name/initials/handle": "bean",
    "Email address": "battleshipbean@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "1:00 PM",
    "Coordinates": "///direct.angle.flank",
    "Location description": "45th Infantry Division Museum. The picnic shelter next to the planes. I will be wearing a hat that says USS Iowa on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Portland, OR",
    "Name/initials/handle": "Rachel Shu, Sam Celarek, Jeff Freyley",
    "Email address": "hello@rachelshu.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "5:00 PM",
    "Coordinates": "///mining.skills.mess",
    "Location description": "Oregon Park, outdoors at southeast picnic tables, will have large banner",
    "Notes": "Location is highly dependent on whether Delta variant or wildfire smoke is the limiting factor at the time.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Ashland, OR",
    "Name/initials/handle": "David",
    "Email address": "ashland.acx.meetup@gmail.com",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "10:00 AM",
    "Coordinates": "///chances.shelter.group",
    "Location description": "Lithia Park, in the meadow at the main (north) entrance, across the street from Skout Taphouse. I'll have a sign with ACX MEETUP on it.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Harrisburg, PA",
    "Name/initials/handle": "Eric",
    "Email address": "harrisburgeric@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "1:00 PM",
    "Coordinates": "///refrigerate.boomers.riverbank",
    "Location description": "Fort Hunter Park, northwest corner, on the grass",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Philadelphia, PA",
    "Name/initials/handle": "Majuscule",
    "Email address": "dmcbriggs@gmail.com",
    "Date (mm/dd/yyyy)": "9/30/2021",
    "Time": "8:00 PM",
    "Coordinates": "///heap.tracks.fantastic",
    "Location description": "210 Ardmore Avenue, Ardmore PA. We’ll be meeting on the spacious covered front porch.",
    "Notes": "",
    "Additional contact info": "Google group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Pittsburgh, PA",
    "Name/initials/handle": "Matthew Marks",
    "Email address": "matthewfmarks@gmail.com",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "12:00 PM",
    "Coordinates": "///pulse.cubes.admiral",
    "Location description": "Location may be updated, so (1) email to confirm, (2) thanks in advance for any suggestions and (3) consider outside the Frick Park gate: https://goo.gl/maps/q3T7iMmp6HGQnoTv9",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "State College, PA",
    "Name/initials/handle": "John Slow",
    "Email address": "auk480@psu.edu",
    "Date (mm/dd/yyyy)": "9/5/2021",
    "Time": "4:00 PM",
    "Coordinates": "///highs.cooks.later",
    "Location description": "Sunset Park. I will be wearing a blue hat.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Providence, RI",
    "Name/initials/handle": "James Bailey",
    "Email address": "feanor1600@gmail.com",
    "Date (mm/dd/yyyy)": "9/21/2021",
    "Time": "12:00 PM",
    "Coordinates": "///serve.free.mostly",
    "Location description": "Prospect Terrace Park. I'll be near the 2nd bench to the right of the Roger Williams statue.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Greenville, SC",
    "Name/initials/handle": "Steve S",
    "Email address": "gvilleacxmeetup@gmail.com",
    "Date (mm/dd/yyyy)": "10/3/2021",
    "Time": "12:00 PM",
    "Coordinates": "///hotel.knee.copper",
    "Location description": "McPherson Park, 120 E. Park Avenue, Greenville, SC 29601 at the shelter nearest the putt-putt course.",
    "Notes": "I have created my own form about the event which is here: https://forms.gle/9cy659xzSfvzi7Mx5.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Sioux Falls, SD",
    "Name/initials/handle": "S. C.",
    "Email address": "villainsplus@protonmail.com",
    "Date (mm/dd/yyyy)": "9/27/2021",
    "Time": "6:00 PM",
    "Coordinates": "///aura.escape.buddy",
    "Location description": "McKennan Park, near the stone circle in the center of the park",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Chattanooga, TN",
    "Name/initials/handle": "JBS",
    "Email address": "smijer@gmail.com",
    "Date (mm/dd/yyyy)": "9/4/2021",
    "Time": "3:00 PM",
    "Coordinates": "///traded.looked.overnight",
    "Location description": "Miller Park, M.L. King Blvd and Market St, near fountains. I'll have a sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Memphis, TN",
    "Name/initials/handle": "Michael",
    "Email address": "michael19571202@outlook.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "1:00 PM",
    "Coordinates": "///smiled.limbs.oiled",
    "Location description": "French Truck Coffee at Crosstown Concourse, Central Atrium, 1350 Concourse Ave, Memphis, TN 38104. Will have a sign that says \"SSC Meetup\".",
    "Notes": "We're an existing meetup, we use Google groups to send emails.",
    "Additional contact info": "Google group",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Austin, TX",
    "Name/initials/handle": "Silas Barta",
    "Email address": "sbarta@gmail.com",
    "Date (mm/dd/yyyy)": "10/2/2021",
    "Time": "1:30 PM",
    "Coordinates": "///loosed.balloons.elastic",
    "Location description": "Tables in the park area by pond beyind Central Market 4001 N. Lamar",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Dallas, TX",
    "Name/initials/handle": "Ethan Morse",
    "Email address": "ethan.morse97@gmail.com",
    "Date (mm/dd/yyyy)": "9/12/2021",
    "Time": "2:00 PM",
    "Coordinates": "///rent.award.forms",
    "Location description": "We'll be at the Reverchon Park picnic tables next to the playground with a sign that says \"ACX Meetup\" on it. Free parking is available at the Reverchon Park Baseball Field. There are no public bathrooms available.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Houston, TX",
    "Name/initials/handle": "Tripp",
    "Email address": "trippsapientae@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "5:00 PM",
    "Coordinates": "///stray.planet.gold",
    "Location description": "Hermann Park Conservancy",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "San Antonio, TX",
    "Name/initials/handle": "Derek Sky",
    "Email address": "intothestarrynightsky@gmail.com",
    "Date (mm/dd/yyyy)": "10/9/2021",
    "Time": "12:30 PM",
    "Coordinates": "///enter.flap.novel",
    "Location description": "The Friendly Spot Ice House, 943 S Alamo St, San Antonio, TX 78206",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bryan/College Station, TX",
    "Name/initials/handle": "Kenny",
    "Email address": "easwaran@gmail.com",
    "Date (mm/dd/yyyy)": "9/10/2021",
    "Time": "5:00 PM",
    "Coordinates": "///musical.airship.viewers",
    "Location description": "Patio behind Torchy's Tacos on Texas Ave. I'll have a yellow umbrella (even if it's not raining) and purple hair.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Salt Lake City, UT",
    "Name/initials/handle": "Ross Richey",
    "Email address": "wearenotsaved@gmail.com",
    "Date (mm/dd/yyyy)": "8/28/2021",
    "Time": "3:00 PM",
    "Coordinates": "///origin.reader.decks",
    "Location description": "Liberty Park, open area NE of Chargepoint Station",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Richmond, VA",
    "Name/initials/handle": "Cal",
    "Email address": "cbilenkin@gmail.com",
    "Date (mm/dd/yyyy)": "9/25/2021",
    "Time": "3:00 PM",
    "Coordinates": "///panels.above.cases",
    "Location description": "Monroe Park: Near the fountain in the middle of the park, and I'll bring an \"ACX Meetup\" sign. (Don't worry, it's not that big of a park anyway.)",
    "Notes": "I know Richmond isn't that big of a city (I think it's barely one of the 100 biggest cities in the US) but if there are even just a handful of interested people, I would still be happy to organize it to meet up and talk",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Burlington, VT",
    "Name/initials/handle": "Jaspar",
    "Email address": "fjabujaber@icloud.com",
    "Date (mm/dd/yyyy)": "9/7/2021",
    "Time": "6:00 PM",
    "Coordinates": "///nurse.slim.shade",
    "Location description": "Battery park, near the cannons. I’ll be wearing a bright yellow floral button up shirt.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Bellingham, WA",
    "Name/initials/handle": "Alex Ellis",
    "Email address": "bellinghamacx@gmail.com",
    "Date (mm/dd/yyyy)": "9/8/2021",
    "Time": "5:00 PM",
    "Coordinates": "///refine.tissue.daily",
    "Location description": "Lake Padden Park, in the field just east of the southeast corner of the lake. Space permitting, we'll try to be close to the water. Look for a sign that says \"ACX MEETUP\". Alternate location in case of rain: the picnic shelter in Fairhaven Park (https://w3w.co/vibes.spent.drag).",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Seattle, WA",
    "Name/initials/handle": "Spencer",
    "Email address": "speeze.pearson+acx@gmail.com",
    "Date (mm/dd/yyyy)": "9/15/2021",
    "Time": "6:00 PM",
    "Coordinates": "///value.shapes.tracks",
    "Location description": "Volunteer Park, near the amphitheater just north of the reservoir. I'll have an \"ACX MEETUP\" sign.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Madison, WI",
    "Name/initials/handle": "Mary",
    "Email address": "mmwang@wisc.edu",
    "Date (mm/dd/yyyy)": "9/11/2021",
    "Time": "3:00 PM",
    "Coordinates": "///volume.eagles.tiles",
    "Location description": "Backyard of private home at 1022 High St, Madison. If it's raining we'll just go into the garage.",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Milwaukee, WI",
    "Name/initials/handle": "Bernie Brewer",
    "Email address": "acxmke@mailbox.org",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "3:00 PM",
    "Coordinates": "///dining.harp.hero",
    "Location description": "Cathedral Square Park",
    "Notes": "Time and date are very flexible.",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  },
  {
    "City": "Lusk, WY",
    "Name/initials/handle": "Michael Hendricks",
    "Email address": "m.acx@ndrix.org",
    "Date (mm/dd/yyyy)": "9/18/2021",
    "Time": "1:00 PM",
    "Coordinates": "///keys.besides.sprinkle",
    "Location description": "Washington Park, 325 S Barrett Blvd, Lusk, WY 82225 (covered picnic benches in the center of the park)",
    "Notes": "",
    "Additional contact info": "",
    "": "",
    "__1": "",
    "__2": "",
    "__3": "",
    "__4": "",
    "__5": ""
  }
]
