import { registerMigration } from './migrationUtils';
import Users from '../../lib/collections/users/collection';
import { createMutator, Utils } from '../vulcan-lib';
import { Posts } from '../../lib/collections/posts';
import { mapsAPIKeySetting } from '../../components/form-components/LocationFormComponent';
import { getLocalTime } from '../mapsUtils';
import {userFindOneByEmail} from "../commonQueries";
import { writeFile } from 'fs/promises';

async function coordinatesToGoogleLocation({ lat, lng }: { lat: string, lng: string }) {
  const requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };
  
  const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${mapsAPIKeySetting.get()}`, requestOptions)
  const responseText = await response.text()
  const responseData = JSON.parse(responseText)
  return responseData.results[0]
}

registerMigration({
  name: "importACXMeetupsFall24",
  dateWritten: "2024-08-19",
  idempotent: true,
  action: async () => {
    const eventCacheContents: { _id: string, lat: number, lng: number }[] = [];

    // eslint-disable-next-line no-console
    console.log("Begin importing ACX Meetups");
    for (const row of acxData) {
      let eventOrganizer
      // Check there's a user by that username
      const userName = row["Username"];
      // Figure out whether user with email address already exists
      // This used to be userFindByEmail from /lib/vulcan-users/helpers. That seems to have become userFindOneByEmail from /lib/collections/users/commonQueries, but you should check that those actually behaved the same.
      const email = row["Email address"] as string|undefined;
      const lookupEmail = email === 'ed@newspeak.house' ? 'edsaperia@gmail.com' : email;
      const existingUser = lookupEmail ? await userFindOneByEmail(lookupEmail) : undefined;
      // If not, create them (and send them an email, maybe?)
      if (existingUser) {
        eventOrganizer = existingUser
      } else {
        const username = await Utils.getUnusedSlugByCollectionName("Users", row["Name"].toLowerCase());
        try {
          const { data: newUser } = await createMutator({
            collection: Users,
            document: {
              username,
              displayName: row["Name"],
              email: email,
              reviewedByUserId: "XtphY3uYHwruKqDyG", //This looks like a hardcoded user who supposedly reviewed something. Who is that user?
              reviewedAt: new Date()
            },
            validate: false,
            currentUser: null
          })
          eventOrganizer = newUser
        } catch (err) {
          // eslint-disable-next-line no-console
          console.log({ err, email, row }, 'Error when creating a new user, using a different username');

          const { data: newUser } = await createMutator({
            collection: Users,
            document: {
              username: `${username}-fall-acx-24`,
              displayName: row["Name"],
              email: email,
              reviewedByUserId: "XtphY3uYHwruKqDyG", //This looks like a hardcoded user who supposedly reviewed something. Who is that user?
              reviewedAt: new Date()
            },
            validate: false,
            currentUser: null
          })

          eventOrganizer = newUser
        }
      }
      
      //Use the coordinates to get the location
      const [latitude, longitude] = row["GPS Coordinates"].split(",");
      const title = `${row["City"]} ${row["Country"]} – ACX Meetups Everywhere Fall 2024`

      // Check for existing event links
      const eventUrl = row["Event Link"];
      const premadePost = eventUrl?.includes("lesswrong.com");
      const eventId = eventUrl && premadePost ? new URL(eventUrl).pathname.split('/')[2] : undefined;

      const [googleLocation, existingPost, premadePostObject] = await Promise.all([
        coordinatesToGoogleLocation({lat: latitude, lng: longitude}),
        // TODO: THIS ISN'T INDEXED, SO THIS RUNS PRETTY SLOWLY IN PROD SINCE IT'S DOING ~FULL TABLE SCANS
        Posts.findOne({ title }),
        eventId ? Posts.findOne(eventId) : Promise.resolve(undefined)
      ]);

      const eventTimePretendingItsUTC = new Date(`${row["Date"]} ${row["Time"]} UTC`)
      const localtime = eventTimePretendingItsUTC.getTime() ? await getLocalTime(eventTimePretendingItsUTC, googleLocation) : new Date();
      const actualTime = new Date(eventTimePretendingItsUTC.getTime() + (eventTimePretendingItsUTC.getTime() - (localtime?.getTime() || eventTimePretendingItsUTC.getTime())))
      
      const fbUrlExists = eventUrl?.includes("facebook.com");
      const meetupUrlExists = eventUrl?.includes("meetup.com");

      let usedPost: DbPost | undefined;
      
      //Then create event post with that user as owner, if there's none by that title and the local organizer didn't already make one.
      if (!existingPost && !premadePostObject) {
        const newPostData = {
          title,
          postedAt: new Date(),
          userId: eventOrganizer._id,
          submitToFrontpage: true,
          activateRSVPs: true,
          draft: false,
          meta: false,
          isEvent: true,
          contactInfo: row["Email address"],
          location: `${row["City"]}`,
          startTime: eventTimePretendingItsUTC.getTime() ? actualTime : undefined,
          meetupLink: meetupUrlExists ? eventUrl : undefined,
          facebookLink: fbUrlExists ? eventUrl : undefined,
          googleLocation,
          contents: {
            originalContents: {
              type: 'ckEditorMarkup',
              data: `<p>This year's Fall ACX Meetup everywhere in ${row["City"]}.</p>
                <p>Location: ${row["Location description"]} – <a href="https://plus.codes/${row["Plus.Code Coordinates"]}">${row["Plus.Code Coordinates"]}</a></p>
                ${row["Group Link"] ? `<p>Group Link: ${row["Group Link"]}</p>` : ""}
                ${row["Notes"] ? `<p>${row["Notes"]}</p>` : ""}
                <p>Contact: ${row["Email address"]} ${row["Additional contact info"] ? `– ${row["Additional contact info"]}` : ""}</p>`
            },
            updateType: 'minor',
            commitMessage: ''
          },
          moderationStyle: 'easy-going',
          af: false,
          authorIsUnreviewed: false,
          types: [
            'SSC'
          ],
        };
        const { data: newPost } = await createMutator({
          collection: Posts,
          document: newPostData,
          currentUser: eventOrganizer,
          validate: false
        })
        // eslint-disable-next-line no-console
        console.log("Created new ACX Meetup: ", newPost.title);
        const googleLocationInfo = newPost.googleLocation?.geometry?.location;
        eventCacheContents.push({ _id: newPost._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });

        usedPost = newPost;
      } else {
        // eslint-disable-next-line no-console
        console.log("Meetup already had a LW event. Check ", eventUrl, "or", title);
        if (existingPost) {
          const googleLocationInfo = existingPost.googleLocation?.geometry?.location;
          eventCacheContents.push({ _id: existingPost._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });
          usedPost = existingPost;
        } else if (premadePostObject) {
          const googleLocationInfo = premadePostObject.googleLocation?.geometry?.location;
          eventCacheContents.push({ _id: premadePostObject._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });
          usedPost = premadePostObject;
        }
      }
      const usedPostStartTime = usedPost?.startTime?.getTime();
      const appliedTime = actualTime.getTime();

      if (usedPostStartTime !== appliedTime) {
        // eslint-disable-next-line no-console
        console.log({ usedPostStartTime, appliedTime, row }, 'Created event might have the wrong time');
      }
    }
    // eslint-disable-next-line no-console
    console.log("End importing ACX meetups.");

    await writeFile('eventCache.json', JSON.stringify(eventCacheContents, null, 2))
  }
})

interface ACXMeetup {
  "Region": string
  "Name": string
  "Username": string
  "Email address": string
  "City": string
  "Country": string
  "Location description": string
  "Plus.Code Coordinates": string
  "Date": string
  "Time": string
  "GPS Coordinates": string
  "Event Link"?: string
  "Group Link"?: string
  Notes?: string
  "Additional contact info"?: string
}

//Updated 4-03-29 14:25 Eastern Time
const acxData: ACXMeetup[] = [
  {
    "Region": "Africa & Middle East",
    "Country": "Iraq",
    "City": "Baghdad",
    "Name": "Mustafa",
    "Username": "",
    "Email address": "wolframsigma2.7@gmail.com",
    "Location description": "In the Grinders, Zayona. I will sit with a brown ",
    "GPS Coordinates": "33.3257875,44.4602344",
    "Plus.Code Coordinates": "https://plus.codes/8H568FG6+839",
    "Date": "9/5/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "please join the group or notify me in any way, I hosted 3 meet ups so far and no attended, so I would not go if no other person at least notified me. If you can't attend, but you're still likeminded and in the area, please reach out! I'd love to meet you sometime."
  },
  {
    "Region": "Africa & Middle East",
    "Country": "Israel",
    "City": "Haifa",
    "Name": "shai zilberman",
    "Username": "",
    "Email address": "dizinteria@walla.com",
    "Location description": "The Goldmund book store located at the talpiot market on ekron 6 street",
    "GPS Coordinates": "32.8101875,35.0009375",
    "Plus.Code Coordinates": "https://plus.codes/8G4QR262+39",
    "Date": "9/16/2024",
    "Time": "05:00 PM",
    "Event Link": "",
    "Group Link": "https://chat.whatsapp.com/FSclSIRSpdSJ6T5VJT2QAD",
    "Notes": "Looking forward to seeing ya'll at our meetup! Feel free to bring along anyone/anything if you'd like—everyone is welcome. To help us plan better, please RSVP via email or whatsapp (detailed here) so we can ensure we have enough space and refreshments for everyone. See you there!"
  },
  {
    "Region": "Africa & Middle East",
    "Country": "Israel",
    "City": "Tel Aviv",
    "Name": "Inbar",
    "Username": "",
    "Email address": "inbar192@gmail.com",
    "Location description": "Sarona park, grass area next to Benedict restaurant. I'll have an ACX MEETUP sign and some balloons.",
    "GPS Coordinates": "32.0716875,34.7868594",
    "Plus.Code Coordinates": "https://plus.codes/8G4P3QCP+MPH",
    "Date": "10/20/2024",
    "Time": "05:00 PM",
    "Event Link": "",
    "Group Link": "https://www.facebook.com/groups/5389163051129361",
    "Notes": "There is a secure location (מרחב מוגן) very close to where we'll be sitting in case of a missile alert - an underground staircase. "
  },
  {
    "Region": "Africa & Middle East",
    "Country": "Nigeria",
    "City": "Kaduna State",
    "Name": "Abdul Malik ",
    "Username": "",
    "Email address": "maleekcherry510@gmail.com",
    "Location description": "Cafe one, Uptown Mall, Zaire Rd",
    "GPS Coordinates": "10.4708125,7.4324375",
    "Plus.Code Coordinates": "https://plus.codes/7F29FCCJ+8X",
    "Date": "9/21/2024",
    "Time": "03:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Africa & Middle East",
    "Country": "Turkey",
    "City": "Antalya",
    "Name": "Annalise",
    "Username": "",
    "Email address": "annalisetarhan@gmail.com",
    "Location description": "We'll be meeting at the Shakespeare in Beach Park, on the patio. Look for a propped up notebook with ACX in big letters.",
    "GPS Coordinates": "36.8828625,30.6721406",
    "Plus.Code Coordinates": "https://plus.codes/8G8GVMMC+4VR",
    "Date": "9/28/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Africa & Middle East",
    "Country": "Turkey",
    "City": "Istanbul",
    "Name": "Ozge",
    "Username": "ozge",
    "Email address": "ozgeco@yahoo.com",
    "Location description": "Kadikoy, Rıhtım, Yeni Iskele Upstairs, Istanbul Kitapcisi Kahve Dunyasi",
    "GPS Coordinates": "40.9928125,29.02368749999999",
    "Plus.Code Coordinates": "https://plus.codes/8GGFX2VF+4F",
    "Date": "10/5/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "This time we organize this meeting together with AI Safety Istanbul Group. Everybody warmly welcomed."
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Australia",
    "City": "Brisbane",
    "Name": "Laura",
    "Username": "",
    "Email address": "laura.leighton94@gmail.com",
    "Location description": "The Fourth Monkey, West End. We will probably be in the courtyard out the back, where it's quieter. I will have a sign that says ACX Meetup.",
    "GPS Coordinates": "-27.4769875,153.0123281",
    "Plus.Code Coordinates": "https://plus.codes/5R4MG2F6+6W4",
    "Date": "9/18/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Australia",
    "City": "Canberra",
    "Name": "Declan",
    "Username": "",
    "Email address": "declan_t@hotmail.com",
    "Location description": "Grease Monkey Braddon",
    "GPS Coordinates": "-35.2729375,149.1326875",
    "Plus.Code Coordinates": "https://plus.codes/4RPFP4GM+R3",
    "Date": "10/7/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP by previous Friday for table booking."
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Australia",
    "City": "Melbourne",
    "Name": "Allan",
    "Username": "",
    "Email address": "winnings_gesture485@simplelogin.com",
    "Location description": "Wolf Cafe and Eatery, 21 Lobelia Dr, Altona North VIC 3025. We will have a sign saying \"AXC Meetup\" written on it",
    "GPS Coordinates": "-37.8448125,144.8421875",
    "Plus.Code Coordinates": "https://plus.codes/4RJ65R4R+3V",
    "Date": "9/14/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://www.facebook.com/groups/lesswrongmelbourne/",
    "Notes": ""
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Australia",
    "City": "Perth",
    "Name": "Bianca Peterek",
    "Username": "",
    "Email address": "bianca.czatyrko@gmail.com",
    "Location description": "Dôme Café Bassendean (Located in Hawaiian's) West Rd, Bassendean WA 6054",
    "GPS Coordinates": "-31.9040625,115.9538125",
    "Plus.Code Coordinates": "https://plus.codes/4PWQ3XW3+9G",
    "Date": "10/12/2024",
    "Time": "01:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please find the table with the \"ACX meet-up\" sign. I'm totally blind, so you'll have to find me and be verbal!"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Australia",
    "City": "Sydney",
    "Name": "Eliot",
    "Username": "Elo",
    "Email address": "Redeliot@gmail.com ",
    "Location description": "Lvl 2, 565 George St, Sydney NSW ",
    "GPS Coordinates": "-33.8765625,151.2058125",
    "Plus.Code Coordinates": "https://plus.codes/4RRH46F4+98",
    "Date": "9/19/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://meetu.ps/e/.qqqqlrygcmbzb/sqK6x/i",
    "Notes": "Bring a friend! Everyone welcome! "
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Hong Kong",
    "City": "Hong Kong",
    "Name": "Max Bolingbroke",
    "Username": "batterseapower",
    "Email address": "acx@alpha.engineering",
    "Location description": "Private flat in The Oakhill, 28 Wood Road, Wan Chai",
    "GPS Coordinates": "22.2764375,114.1768125",
    "Plus.Code Coordinates": "https://plus.codes/7PJP75GG+HP",
    "Date": "9/7/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Email me to RSVP and I will let you know which flat number to come to & give you an invite link to the ACX Hong Kong WhatsApp group. For those who couldn't RSVP in time I will also put an \"ACX Meetup\" sign outside the entrance of the building with the number of my flat on it."
  },
  {
    "Region": "Asia-Pacific",
    "Country": "India",
    "City": "Bengaluru",
    "Name": "Nihal M",
    "Username": "nihal-m",
    "Email address": "propwash@duck.com",
    "Location description": "Matteo coffea, church street",
    "GPS Coordinates": "12.9743125,77.6070625",
    "Plus.Code Coordinates": "https://plus.codes/7J4VXJF4+PR",
    "Date": "10/27/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/i5vLw9xnG9iwXNQZZ",
    "Notes": "RSVP on the event for october"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "India",
    "City": "Chennai",
    "Name": "Sathish",
    "Username": "",
    "Email address": "sathish9289@gmail.com",
    "Location description": "Besant Nagar Beach",
    "GPS Coordinates": "12.9988125,80.2718125",
    "Plus.Code Coordinates": "https://plus.codes/7M42X7XC+GP",
    "Date": "9/5/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Indonesia",
    "City": "Jakarta",
    "Name": "Aud",
    "Username": "",
    "Email address": "helloaud2000@gmail.com",
    "Location description": "First Crack Coffee Jl. Bumi https://maps.app.goo.gl/1VBV9GmM51HxLEnL7",
    "GPS Coordinates": "-6.2371875,106.7900625",
    "Plus.Code Coordinates": "https://plus.codes/6P58QQ7R+42",
    "Date": "9/22/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP to my email so I know how many people to expect. Thanks!"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Indonesia",
    "City": "Ubud",
    "Name": "River",
    "Username": "",
    "Email address": "acx.k55uc@passinbox.com",
    "Location description": "Kafe Upstairs",
    "GPS Coordinates": "-8.513937499999999,115.2641875",
    "Plus.Code Coordinates": "https://plus.codes/6P3QF7P7+CM",
    "Date": "9/12/2024",
    "Time": "11:00 AM",
    "Event Link": "",
    "Group Link": "https://chat.whatsapp.com/HydwIF3u7Ve0nfpbc9EtnS",
    "Notes": ""
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Japan",
    "City": "Tokyo",
    "Name": "Harold",
    "Username": "harold-1",
    "Email address": "rationalitysalon@gmail.com",
    "Location description": "Get in touch for the details!",
    "GPS Coordinates": "Invalid URL",
    "Plus.Code Coordinates": "Get in touch for the details!",
    "Date": "10/12/2024",
    "Time": "10:00 AM",
    "Event Link": "",
    "Group Link": "https://www.meetup.com/acx-tokyo/",
    "Notes": "Get in touch for the details!"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "New Zealand",
    "City": "Auckland",
    "Name": "Mark",
    "Username": "mark-gilmour",
    "Email address": "markgilmour@gmail.com",
    "Location description": "Cornwall Park Band Rotunda ",
    "GPS Coordinates": "-36.8954375,174.7895625",
    "Plus.Code Coordinates": "https://plus.codes/4VMP4Q3Q+RR",
    "Date": "9/21/2024",
    "Time": "10:00 AM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Bring kids if relevant, feel free to bring some nibbles."
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Singapore",
    "City": "Singapore",
    "Name": "Andrew",
    "Username": "",
    "Email address": "mindupgrade[at]protonmail[dot]com",
    "Location description": "Maxwell (will send more details in email)",
    "GPS Coordinates": "1.2804375,103.8448125",
    "Plus.Code Coordinates": "https://plus.codes/6PH57RJV+5W",
    "Date": "9/29/2024",
    "Time": "04:30 PM",
    "Event Link": "",
    "Group Link": "https://rentry.co/AC6PH57RJV5W",
    "Notes": "Please send your RSVP email as early as you can because it would be immensely helpful. Feel free to send an email about topic sentences that you are interested in or want to have a conversation with others about. Topic sentences will be collated and privately shared with the other attendees. We have at least one ACX Meetup every month. The Aug/Sep/Oct/Nov/Dec dates will be on https://rentry.co/AC6PH57RJV5W."
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Taiwan",
    "City": "Taipei",
    "Name": "Jake & Brandon",
    "Username": "",
    "Email address": "jakessolo+acxmeetup@gmail.com",
    "Location description": "Daan Park - northeast field next to the basketball courts (backup: Learn Bar if it's raining)",
    "GPS Coordinates": "25.0317625,121.5362969",
    "Plus.Code Coordinates": "https://plus.codes/7QQ32GJP+PG3",
    "Date": "9/8/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Backup location coordinates of Learn Bar: https://plus.codes/7QQ32GMJ+GHR"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Thailand",
    "City": "Bankok",
    "Name": "Steven",
    "Username": "steven_shonts",
    "Email address": "steven.shonts@gmail.com",
    "Location description": "Too Fast To Sleep (Siam) สยาม - 222,222/1-7,224 ซอย Siam Square Soi 1, Pathum Wan, Bangkok 10330",
    "GPS Coordinates": "13.7449375,100.5315625",
    "Plus.Code Coordinates": "https://plus.codes/7P52PGVJ+XJ",
    "Date": "9/1/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Vietnam",
    "City": "Da Nang",
    "Name": "Egor",
    "Username": "",
    "Email address": "zmaznevegor@gmail.com",
    "Location description": "Me Coffee Roastery, 2nd floor. 91 Chương D., Bắc Mỹ Phú, Ngũ Hành Sơn, Đà Nẵng 550000, Vietnam",
    "GPS Coordinates": "16.0469125,108.2350469",
    "Plus.Code Coordinates": "https://plus.codes/7P8C26WP+Q27",
    "Date": "9/15/2024",
    "Time": "02:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "If you are planning to come, please contact me on Telegram @Zmaznevegor. https://t.me/Zmaznevegor"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Vietnam",
    "City": "Hanoi",
    "Name": "Jord",
    "Username": "jordine",
    "Email address": "jordnguyen43@gmail.com",
    "Location description": "Ciao Bella Coffee, Alley 132 Vo Chi Cong, Xuan La, Tay Ho, Hanoi",
    "GPS Coordinates": "21.0532625,105.8052344",
    "Plus.Code Coordinates": "https://plus.codes/7PH73R34+835",
    "Date": "9/7/2024",
    "Time": "09:00 AM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP on Lesswrong / email me in case of any changes"
  },
  {
    "Region": "Asia-Pacific",
    "Country": "Vietnam",
    "City": "Ho Chi Minh City",
    "Name": "Hiep",
    "Username": "cygnus",
    "Email address": "hiepbq14408@gmail.com",
    "Location description": "Trung Nguyen Legend Coffee at 603 Tran Hung Dao St.",
    "GPS Coordinates": "10.7564375,106.6854375",
    "Plus.Code Coordinates": "https://plus.codes/7P28QM4P+H5",
    "Date": "9/15/2024",
    "Time": "09:30 AM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/nSoF5ntooah7f4qzj",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Bulgaria",
    "City": "Sofia",
    "Name": "Daniel",
    "Username": "Daniel Bensen",
    "Email address": "bensen.daniel@gmail.com",
    "Location description": "Borisova Gradina, Sofia, Bulgaria",
    "GPS Coordinates": "42.6768125,23.3453125",
    "Plus.Code Coordinates": "https://plus.codes/8GJ5M8GW+P4",
    "Date": "9/29/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/HGaSdqwqG4SogWfTi",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Croatia",
    "City": "Zagreb",
    "Name": "Dominik",
    "Username": "dominicq",
    "Email address": "dominik.tujmer@gmail.com",
    "Location description": "A Most Unusual Garden (Hendrick's Gin Garden), Horvaćanska cesta 3, Zagreb",
    "GPS Coordinates": "45.7872625,15.9529844",
    "Plus.Code Coordinates": "https://plus.codes/8FQQQXP3+W55",
    "Date": "9/28/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "https://t.me/+A8_-NHQnSkhmY2Fk",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Czech Republic",
    "City": "Brno",
    "Name": "Michal",
    "Username": "adekcz",
    "Email address": "adekcz@gmail.com",
    "Location description": "Skautský institut Brno, 2nd floor, shared office (not ground level main hall)",
    "GPS Coordinates": "49.1995625,16.6058125",
    "Plus.Code Coordinates": "https://plus.codes/8FXR5JX4+R8",
    "Date": "9/26/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "https://www.efektivni-altruismus.cz/kalendar-akci/",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Denmark",
    "City": "Copenhagen",
    "Name": "Søren Elverlin",
    "Username": "Søren Elverlin",
    "Email address": "soeren.elverlin@gmail.com",
    "Location description": "Rundholtsvej 10, 2300 Copenhagen S",
    "GPS Coordinates": "55.65383749999999,12.5661406",
    "Plus.Code Coordinates": "https://plus.codes/9F7JMH38+GFJ",
    "Date": "9/7/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/events/xsAqbxvT8PD8kCgcr/astralcodexten-lesswrong-meetup-5jau",
    "Notes": "RSVP on LessWrong"
  },
  {
    "Region": "Europe",
    "Country": "Finland",
    "City": "Helsinki",
    "Name": "Joe Nash",
    "Username": "jn2",
    "Email address": "sschelsinkimeetup@gmail.com",
    "Location description": "Oluthuone Kaisla, Vilhonkatu 4, 00100 Helsinki. I will have a notebook that says \"ACX\" on the table.",
    "GPS Coordinates": "60.1718125,24.9473125",
    "Plus.Code Coordinates": "https://plus.codes/9GG65WCW+PW",
    "Date": "9/17/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://www.meetup.com/helsinki-slate-star-codex-readers-meetup/",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "France",
    "City": "Bordeaux",
    "Name": "Tom",
    "Username": "",
    "Email address": "tom@rethaller.net",
    "Location description": "Under the trees, on the waterfront, opposite Quinconces",
    "GPS Coordinates": "44.8455625,-0.5701875",
    "Plus.Code Coordinates": "https://plus.codes/8CPXRCWH+6W",
    "Date": "9/21/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/2NBRvz5JbC",
    "Notes": "Please join the Discord server before attending, the exact location might change depending on the weather"
  },
  {
    "Region": "Europe",
    "Country": "France",
    "City": "Genoble",
    "Name": "Fantin",
    "Username": "Vafin",
    "Email address": "fantin.seguin@live.fr",
    "Location description": "We'll be in the Jardin de Ville, on the lawn near the cable car, with a small ACX Meetup sign. ",
    "GPS Coordinates": "45.1926875,5.726437499999999",
    "Plus.Code Coordinates": "https://plus.codes/8FQ75PVG+3H",
    "Date": "9/7/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP on LessWrong so I know how many we are. We can go to a bar or somewhere else afterwards."
  },
  {
    "Region": "Europe",
    "Country": "France",
    "City": "Paris",
    "Name": "Augustin",
    "Username": "TeaTieAndHat",
    "Email address": "augustin.portier@proton.me",
    "Location description": "In the Carrousel Garden (next to the Tuileries Gardens). We’ll be sitting on the grass near the Museum of Decorative Arts, which is located at the end of the north wing of the Louvre building complex. I’ll bring an ACX sign, and I’ll be wearing a bowtie.",
    "GPS Coordinates": "48.8629375,2.3319375",
    "Plus.Code Coordinates": "https://plus.codes/8FW4V87J+5Q",
    "Date": "9/28/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/VMQq8r83GS",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "France",
    "City": "Toulouse",
    "Name": "Alfonso",
    "Username": "",
    "Email address": "barsom.maelwys@gmail.com",
    "Location description": "Pizzeria La Pastasciutta (35Bis Rue Gabriel Péri, 31000 Toulouse). We'll meet at the door.",
    "GPS Coordinates": "43.6063125,1.4548125",
    "Plus.Code Coordinates": "https://plus.codes/8FM3JF43+GW",
    "Date": "9/10/2024",
    "Time": "08:00 PM",
    "Event Link": "",
    "Group Link": "https://www.meetup.com/the-friendly-debate/",
    "Notes": "Please, RSVP by email"
  },
  {
    "Region": "Europe",
    "Country": "Georgia",
    "City": "Tbilisi",
    "Name": "Dmitrii",
    "Username": "",
    "Email address": "overfull_jailbird656@simplelogin.com",
    "Location description": "BNKR coffee (https://maps.app.goo.gl/VjMviRv9yymSpA1p7)",
    "GPS Coordinates": "41.7056875,44.7814375",
    "Plus.Code Coordinates": "https://plus.codes/8HH6PQ4J+7H",
    "Date": "9/1/2024",
    "Time": "10:00 AM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Berlin",
    "Name": "Milli and Dominik",
    "Username": "Milli | Martin",
    "Email address": "acx-meetups@martinmilbradt.de",
    "Location description": "Big lawn at the center of Humboldthain",
    "GPS Coordinates": "52.5451875,13.3855625",
    "Plus.Code Coordinates": "https://plus.codes/9F4MG9WP+36",
    "Date": "9/7/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://t.me/+_50JIXMIFYc1NTRi",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Cologne",
    "Name": "Marcel Müller",
    "Username": "egi",
    "Email address": "marcel_mueller@mail.de",
    "Location description": "Marienweg 43, 50858 Köln",
    "GPS Coordinates": "50.9334375,6.8481875",
    "Plus.Code Coordinates": "https://plus.codes/9F28WRMX+97",
    "Date": "10/12/2024",
    "Time": "05:00 AM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/2QwpKyXvwiZ53G4HP",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Hamburg",
    "Name": "Gunnar ",
    "Username": "Gunnar_Zarncke",
    "Email address": "g.zarncke+acx@gmail.com",
    "Location description": "Eppendorfer Park at the pond, we will have a sign reading \"ACX Meetup\".",
    "GPS Coordinates": "53.58918749999999,9.9786875",
    "Plus.Code Coordinates": "https://plus.codes/9F5FHXQH+MF",
    "Date": "9/28/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "lesswrong-hamburg@googlegroups.com",
    "Notes": "Feel free to bring friends and family. Please RSVP on to me for planning."
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Mannheim",
    "Name": "Simon",
    "Username": "",
    "Email address": "acxmannheim@mailbox.org",
    "Location description": "Murphy's Law (Irish Pub)",
    "GPS Coordinates": "49.4804375,8.4713125",
    "Plus.Code Coordinates": "https://plus.codes/8FXCFFJC+5G",
    "Date": "9/15/2024",
    "Time": "08:00 PM",
    "Event Link": "",
    "Group Link": "https://signal.group/#CjQKIFmicB23eRhkDDjxjT94PWsbTYPdux-uoZJH2bH2M7OqEhBzfNMhsDNayw_ETHxhsGG6",
    "Notes": "Look for the table with the ACX sign on it!"
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Nürnberg",
    "Name": "Dimi",
    "Username": "",
    "Email address": "dimi.zharkov@gmail.com",
    "Location description": "Biergarten 'Gutmann am Dutzendteich', outside if the weather allows. I will put a sign on the table saying ACX",
    "GPS Coordinates": "49.4354375,11.1169375",
    "Plus.Code Coordinates": "https://plus.codes/8FXHC4P8+5Q",
    "Date": "9/15/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "We can start at Gutmann's and then go for a walk around Dutzendteich. German, English, and Russian/Ukrainian speakers very welcome! (As well as any other language)"
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Saarbrücken",
    "Name": "Jan Wehner",
    "Username": "jan-wehner",
    "Email address": "janwehner1@t-online.de",
    "Location description": "Am Staden 16a, 66121 Saarbrücken (Ulanen-Pavillon Beer garden). I'll have a laptop saying ACX MEETUP",
    "GPS Coordinates": "49.2258125,7.006328099999999",
    "Plus.Code Coordinates": "https://plus.codes/8FX962G4+8GG",
    "Date": "9/18/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "RSVPs are required. Please use this form: https://forms.gle/QwvuVeL4sTQbuQub7."
  },
  {
    "Region": "Europe",
    "Country": "Germany",
    "City": "Stuttgart",
    "Name": "Steve",
    "Username": "Khafra",
    "Email address": "Steve.Bachelor@gmail.com ",
    "Location description": "Café am See Nil in the Mittlerer Schlossgarten Park: Am Schlossgarten 26, 70173 Stuttgart, Germany. I’ll be in the outdoor seating area wearing the “Shrimp love me, Unaligned AIs fear me” hat",
    "GPS Coordinates": "48.7874375,9.1879375",
    "Plus.Code Coordinates": "https://plus.codes/8FWFQ5PQ+X5",
    "Date": "9/8/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "I don’t actually speak any German; I just got here."
  },
  {
    "Region": "Europe",
    "Country": "Hungary",
    "City": "Budapest",
    "Name": "Tim",
    "Username": "Timothy Underwood",
    "Email address": "timunderwood9@gmail.com",
    "Location description": "Muzeumkert, with Sirius Teahaz as backup in case of bad weather",
    "GPS Coordinates": "47.4919375,19.0633125",
    "Plus.Code Coordinates": "https://plus.codes/8FVXF3R7+Q8",
    "Date": "10/6/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://groups.google.com/g/rationality-budapest",
    "Notes": "We'll have a sign, feel free to bring kids, and it'll be great to see you all."
  },
  {
    "Region": "Europe",
    "Country": "Ireland",
    "City": "Dublin",
    "Name": "David O.",
    "Username": "",
    "Email address": "inlets_spinal_0a@icloud.com",
    "Location description": "Motel One, 111-114 Middle Abbey St, North City, Dublin, D01 H220",
    "GPS Coordinates": "53.3480625,-6.2635625",
    "Plus.Code Coordinates": "https://plus.codes/9C5M8PXP+6H",
    "Date": "9/28/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://urldefense.com/v3/__https://chat.whatsapp.com/FzNygSigEbhLgH3QO7X3jt__;!!CXc2QsB7-X90!4nFELKz3w07KYYnBDVLX0VyPNes-fYIQ7xv_ZzwqCd6IDOgXB1LKujopocsB0ONiXD8kf9wNShWTkrvd7m_aBQ$",
    "Notes": "No RSVP required"
  },
  {
    "Region": "Europe",
    "Country": "Italy",
    "City": "Milano",
    "Name": "Raffaele ",
    "Username": "",
    "Email address": "raffa.mauro@gmail.com",
    "Location description": "Viale Majno 18, 20127, Milano (MI) - Primo Ventures, second floor",
    "GPS Coordinates": "45.4709375,9.2060625",
    "Plus.Code Coordinates": "https://plus.codes/8FQFF6C4+9C",
    "Date": "9/6/2024",
    "Time": "06:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP to raffa.mauro@gmail.com"
  },
  {
    "Region": "Europe",
    "Country": "Italy",
    "City": "Rome",
    "Name": "Giulio Starace",
    "Username": "thesofakillers",
    "Email address": "giulio.starace@gmail.com",
    "Location description": "Roma Termini, Via Marsala entrance",
    "GPS Coordinates": "41.90183750000001,12.5027969",
    "Plus.Code Coordinates": "https://plus.codes/8FHJWG23+P4M",
    "Date": "10/19/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://chat.whatsapp.com/IqVk1B8RwgxHnm1u6fgeQA",
    "Notes": "Please feel free to come even if you feel awkward about it, even if you’re not ‘the typical ACX reader’, even if you’re worried people won’t like you, etc.! We are a very casual and laid back group."
  },
  {
    "Region": "Europe",
    "Country": "Netherlands",
    "City": "Amsterdam",
    "Name": "Tom",
    "Username": "",
    "Email address": "hello@tomrijntjes.nl",
    "Location description": "Ijscuypje Westerpark",
    "GPS Coordinates": "52.3863125,4.8724375",
    "Plus.Code Coordinates": "https://plus.codes/9F469VPC+GX",
    "Date": "9/2/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "Whatsapp: https://chat.whatsapp.com/InPyklCnyYs9PQi5NXevV2, Discord: https://discord.gg/6YKnURhHWZ",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Netherlands",
    "City": "Nijmegen",
    "Name": "Stian",
    "Username": "meraxion",
    "Email address": "stian.sgronlund@outlook.com",
    "Location description": "Sport Cafe \"The Yard\", Elinor Ostromgebouw, Heyendaalseweg 141, 6525 AJ Nijmegen. I will bring some sort of sign that says \"ACX/Rationality Meetup Nijmegen\"",
    "GPS Coordinates": "51.8185625,5.867437499999999",
    "Plus.Code Coordinates": "https://plus.codes/9F37RV98+CX",
    "Date": "9/8/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "RSVPs appreciated but not required"
  },
  {
    "Region": "Europe",
    "Country": "Poland",
    "City": "Warsaw",
    "Name": "ntoxeg",
    "Username": "ntoxeg",
    "Email address": "ntoxeg@proton.me",
    "Location description": "Wilcza 25, walk down and look for a big white room.",
    "GPS Coordinates": "52.22508750000001,21.0171406",
    "Plus.Code Coordinates": "https://plus.codes/9G4362G8+2VJ",
    "Date": "10/6/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/ZXL54LioSRqtK5yZY, https://www.facebook.com/groups/lwwarsaw",
    "Notes": "RSVP on LessWrong or Facebook is recommended."
  },
  {
    "Region": "Europe",
    "Country": "Portugal",
    "City": "Funchal",
    "Name": "Marko",
    "Username": "Marko",
    "Email address": "thiel.marko@cantab.net",
    "Location description": "Santa Catarina Park, northeast corner",
    "GPS Coordinates": "32.6461875,-16.9136875",
    "Plus.Code Coordinates": "https://plus.codes/8C45J3WP+FG",
    "Date": "9/2/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "I'll wear a grey hat with a ship's wheel on it"
  },
  {
    "Region": "Europe",
    "Country": "Portugal",
    "City": "Lisbon",
    "Name": "Luís Campos",
    "Username": "luis-campos",
    "Email address": "luis.filipe.lcampos@gmail.com",
    "Location description": "We meet on top of a small hill East of the Linha d'Água café in Jardim Amália Rodrigues. For comfort, bring sunglasses and a blanket to sit on. There is some natural shade. Also, it can get quite windy, so bring a jacket. Look for the big orange blanket.",
    "GPS Coordinates": "38.73218749999999,-9.154187499999999",
    "Plus.Code Coordinates": "https://plus.codes/8CCGPRJW+V8",
    "Date": "9/21/2024",
    "Time": "03:00 PM",
    "Event Link": "https://www.lesswrong.com/events/iKtM6JkLWfW7FxPes/acx-ea-lisbon-september-2024-meetup-acx-meetups-everywhere",
    "Group Link": "https://chat.whatsapp.com/EaWFPJNfKZeJiHECesblMS",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Scotland",
    "City": "Edinburgh",
    "Name": "Satya Benson",
    "Username": "satchlj",
    "Email address": "acx.meetup@satchlj.com",
    "Location description": "George Square Gardens Labyrinth",
    "GPS Coordinates": "55.9438125,-3.1895625",
    "Plus.Code Coordinates": "https://plus.codes/9C7RWRV6+G5",
    "Date": "10/12/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "If it rains, the backup location is Söderberg The Meadows (https://plus.codes/9C7RWRV5+C7) "
  },
  {
    "Region": "Europe",
    "Country": "Serbia",
    "City": "Belgrade",
    "Name": "Tanya Trninic",
    "Username": "",
    "Email address": "tanja.trninic@efektivnialtruizam.com",
    "Location description": "Restaurant Rai Urban Vege; Address: Visokog Stevana 5, Belgrade, Serbia",
    "GPS Coordinates": "44.8265625,20.4569375",
    "Plus.Code Coordinates": "https://plus.codes/8GP2RFG4+JQ",
    "Date": "9/15/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "EA Serbia Telegram group invite: https://t.me/+wu3itsO2ZjoxNmY0",
    "Notes": "Please RSVP to tanja.trninic@efektivnialtruizam.com so I can reserve a suitable table."
  },
  {
    "Region": "Europe",
    "Country": "Spain",
    "City": "Cambrils",
    "Name": "Alexander",
    "Username": "",
    "Email address": "alexander.oleshko@gmail.com",
    "Location description": "North entrance to Park del Pescador, I'll hold an \"ACX meetup\" poster.",
    "GPS Coordinates": "41.0667625,1.0564531",
    "Plus.Code Coordinates": "https://plus.codes/8FH33384+PH4",
    "Date": "9/13/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP if you're planning to come. If I get no replies, I'll still show up there and stand with the poster for 20 minutes. I expect that we will communicate in English, however, if Spanish is a more preferable choice for you, you'll find conversation partners."
  },
  {
    "Region": "Europe",
    "Country": "Spain",
    "City": "Madrid",
    "Name": "Pablo",
    "Username": "pvs",
    "Email address": "pvillalobos@proton.me",
    "Location description": "El Retiro Park, puppet theatre. I will be carrying an ACX sign",
    "GPS Coordinates": "40.4187125,-3.686703099999999",
    "Plus.Code Coordinates": "https://plus.codes/8CGRC897+F8M",
    "Date": "9/21/2024",
    "Time": "11:00 AM",
    "Event Link": "https://www.lesswrong.com/events/Gn4gqpseg6GinauWD/madrid-acx-meetups-everywhere-fall-2024",
    "Group Link": "https://www.meetup.com/Effective-Altruism-Madrid/",
    "Notes": "RSVPs appreciated but not required"
  },
  {
    "Region": "Europe",
    "Country": "Sweden",
    "City": "Gothenburg",
    "Name": "Stefan",
    "Username": "stefan-1",
    "Email address": "acx_gbg@posteo.se",
    "Location description": "Condeco Fredsgatan, second floor, look for some books on the table",
    "GPS Coordinates": "57.70518749999999,11.9709219",
    "Plus.Code Coordinates": "https://plus.codes/9F9HPX4C+39F",
    "Date": "9/25/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "Sweden",
    "City": "Stockholm",
    "Name": "Jonatan Westholm",
    "Username": "",
    "Email address": "jonatanwestholm@hotmail.com",
    "Location description": "Radisson Blu Viking, Stockholm City",
    "GPS Coordinates": "59.3315625,18.0580625",
    "Plus.Code Coordinates": "https://plus.codes/9FFW83J5+J6",
    "Date": "9/15/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://www.facebook.com/share/g/84RznjYeqCefurUh/",
    "Notes": "Yes, please RSVP! Depending on how many sign up, I may have to phone the hotel ahead of time. Also note: I have learned from previous meetups that the afternoon sun blinds half the group at Scandic Continental, which is why I decided to give Radisson Blu Viking a try (it's literally 100m from the old place). "
  },
  {
    "Region": "Europe",
    "Country": "Switzerland",
    "City": "Zurich",
    "Name": "MB",
    "Username": "",
    "Email address": "acxzurich@proton.me",
    "Location description": "Blatterwiese in front of the chinese garden. If it rains we will go under the roof inside the garden (free entry).",
    "GPS Coordinates": "47.3546875,8.551187500000001",
    "Plus.Code Coordinates": "https://plus.codes/8FVC9H32+VF",
    "Date": "9/28/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Snacks and picnic blankets are optional, but appreciated. Drop me a line at the email above to be added to the mailing list (future meetups will be announced there, we meet monthly)."
  },
  {
    "Region": "Europe",
    "Country": "UK",
    "City": "Sheffield",
    "Name": "Colin Z. Robertson",
    "Username": "czrobertson",
    "Email address": "czr@rtnl.org.uk",
    "Location description": "200 Degrees, 25 Division St, Sheffield S1 4GE. I'll have a piece of paper on the table with ACX written on it.",
    "GPS Coordinates": "53.3800625,-1.4733125",
    "Plus.Code Coordinates": "https://plus.codes/9C5W9GJG+2M",
    "Date": "9/7/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/8RMx8BvZbz",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "United Kingdom",
    "City": "Cambridge",
    "Name": "Hamish Todd",
    "Username": "hamishtodd1",
    "Email address": "hamish.todd1@gmail.com",
    "Location description": "**Upstairs** at The Bath House",
    "GPS Coordinates": "52.2040625,0.1184375",
    "Plus.Code Coordinates": "https://plus.codes/9F426439+J9",
    "Date": "9/21/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/SodAF4T4T2dw8X6Jj",
    "Notes": "3 years and still going strong! Always happy to see new faces too :)"
  },
  {
    "Region": "Europe",
    "Country": "United Kingdom",
    "City": "London",
    "Name": "Aubrey Niederhoffer",
    "Username": "",
    "Email address": "aubreyniederhoffer@berkeley.edu",
    "Location description": "Diana Memorial Fountain, Hyde Park",
    "GPS Coordinates": "51.5049375,-0.1716875",
    "Plus.Code Coordinates": "https://plus.codes/9C3XGR3H+X8",
    "Date": "9/13/2024",
    "Time": "05:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/gxTSBtUGqs",
    "Notes": "Please join the Discord server or email me if you're attending, so I can get a headcount! I will provide vegan-friendly food. "
  },
  {
    "Region": "Europe",
    "Country": "United Kingdom",
    "City": "Oxford",
    "Name": "Stan",
    "Username": "fenmund",
    "Email address": "stanislawmalinowski09@gmail.com",
    "Location description": "The Star Pub",
    "GPS Coordinates": "51.74931249999999,-1.2383125",
    "Plus.Code Coordinates": "https://plus.codes/9C3WPQX6+PM",
    "Date": "10/16/2024",
    "Time": "06:30 AM",
    "Event Link": "",
    "Group Link": "https://www.facebook.com/groups/oxfordrationalish",
    "Notes": ""
  },
  {
    "Region": "Europe",
    "Country": "United Kingdom",
    "City": "Reading",
    "Name": "Ben Wōden",
    "Username": "Ben Wōden",
    "Email address": "cascadestyler@gmail.com",
    "Location description": "Siren RG1 Craft Brew: 1 Friars Walk, Reading RG1 1DA",
    "GPS Coordinates": "51.4568125,-0.9741874999999999",
    "Plus.Code Coordinates": "https://plus.codes/9C3XF24G+P8",
    "Date": "9/21/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Siren RG1 is not a pub in the traditional sense and does not have pub vibes. It has an almost cafe-like atmosphere that's friendly to non-drinkers. If you are put off by the atmosphere of the traditional british pub, please don't let that be a reason to give this one a miss. I'm planning on staying around until maybe about 6, so don't worry about turning up significantly later than the start time. RSVPs would be helpful but are not a requirement. Feel free to email me with any questions."
  },
  {
    "Region": "North America",
    "Country": "Canada",
    "City": "Calgary",
    "Name": "David P",
    "Username": "dpiepgrass",
    "Email address": "qwertie256@gmail.com",
    "Location description": "First Street Market, 1327 1st Street SW, Calgary. Look for a red ACX sign.",
    "GPS Coordinates": "51.0400625,-114.0663125",
    "Plus.Code Coordinates": "https://plus.codes/95372WRM+2F",
    "Date": "9/7/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/LZQ6HBAd8afoqPP27",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "Canada",
    "City": "Edmonton",
    "Name": "Joseph Shapkin",
    "Username": "monumental",
    "Email address": "ta1hynp09@relay.firefox.com",
    "Location description": "Irrational Brewing Company. 10643 124 St #109. Edmonton, AB T5N 1S5. We will have an ACX sign so you can easily find our table.",
    "GPS Coordinates": "53.5506875,-113.5355625",
    "Plus.Code Coordinates": "https://plus.codes/9558HF27+7Q",
    "Date": "9/19/2024",
    "Time": "07:00 PM",
    "Event Link": "https://www.lesswrong.com/events/kBCpoouwrn4GoAZyr/acx-meetups-everywhere-5",
    "Group Link": "https://www.lesswrong.com/groups/hNzrLboTGkRFraHWG",
    "Notes": "Event Link: https://www.lesswrong.com/events/kBCpoouwrn4GoAZyr/acx-meetups-everywhere-5"
  },
  {
    "Region": "North America",
    "Country": "Canada",
    "City": "Saint John",
    "Name": "Sergey",
    "Username": "",
    "Email address": "spam04321@gmail.com",
    "Location description": "McAllister Place food court, I'll have some kind of a small ACX MEETUP sign on the table.",
    "GPS Coordinates": "45.3074625,-66.0159219",
    "Plus.Code Coordinates": "https://plus.codes/87QM8X4M+XJP",
    "Date": "9/14/2024",
    "Time": "11:30 AM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP if you have any intention of coming as the event will only proceed if there's at least someone interested in coming."
  },
  {
    "Region": "North America",
    "Country": "Canada",
    "City": "Toronto",
    "Name": "Andrew",
    "Username": "Wuje",
    "Email address": "partyatmyplace2024@gmail.com",
    "Location description": "FourFifty The Well (450 Front Street), ask the concierge to send you to the rec room for the ACX Meetup ",
    "GPS Coordinates": "43.6428125,-79.3954375",
    "Plus.Code Coordinates": "https://plus.codes/87M2JJV3+4R",
    "Date": "9/14/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/8ktnBi4AjxtCmGeXA",
    "Notes": "RSVP over email for planning around snacks and venue capacity, or to let me know any dietary requirements. Please leave your pets at home :)"
  },
  {
    "Region": "North America",
    "Country": "Canada",
    "City": "Vancouver",
    "Name": "Jordan",
    "Username": "https://www.lesswrong.com/users/jordan-2",
    "Email address": "j.verasamy@gmail.com",
    "Location description": "Dude Chilling Park, NW corner, with a big sign",
    "GPS Coordinates": "49.2643125,-123.0964375",
    "Plus.Code Coordinates": "https://plus.codes/84XR7W73+PC",
    "Date": "9/21/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "https://www.meetup.com/vancouver-rationality and https://www.lesswrong.com/groups/foFedJFgad2qDd3vp",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "Germany",
    "City": "Aachen",
    "Name": "Martin Schmidt",
    "Username": "caffemacchiavelli",
    "Email address": "acx@enc0.com",
    "Location description": "Cafe Papillon, probably near the entrance, will bring ACX sign",
    "GPS Coordinates": "50.7808125,6.078812500000001",
    "Plus.Code Coordinates": "https://plus.codes/9F28Q3JH+8G",
    "Date": "9/28/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "https://t.me/+IiFfbpWDWm1kOGQ6",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "Mexico",
    "City": "Mérida",
    "Name": "Silvia ",
    "Username": "Silvia Fernández ",
    "Email address": "silviafidelina@hotmail.com",
    "Location description": "Centro de Estudios e Investigaciones Sociales y Culturales (CEISC) \"Efraín Calderón Lara\"",
    "GPS Coordinates": "20.9823125,-89.6069375",
    "Plus.Code Coordinates": "https://plus.codes/76GGX9JV+W6",
    "Date": "10/19/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://m.facebook.com/groups/lesswrongmerida",
    "Notes": "Please RSVPs by email"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Huntsville",
    "Name": "Michael House",
    "Username": "",
    "Email address": "mjhouse@protonmail.com",
    "Location description": "300 The Bridge St, Huntsville, AL 35806. I'll be in the Starbucks which is located inside of the Barnes and Noble. I'll have a whiteboard with \"ACX MEETUP\" on it.",
    "GPS Coordinates": "34.7154375,-86.6724375",
    "Plus.Code Coordinates": "https://plus.codes/866MP88H+52",
    "Date": "9/19/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Anchorage",
    "Name": "Mark",
    "Username": "",
    "Email address": "FLWAB@protonmail.com",
    "Location description": "Kaladi Brothers Coffee, 6861 Jewel Lake Rd, Anchorage, AK, 99502. We’ll be in the community room and I’ll have a sign.",
    "GPS Coordinates": "61.1581875,-149.9509375",
    "Plus.Code Coordinates": "https://plus.codes/93HG525X+7J",
    "Date": "9/21/2024",
    "Time": "01:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Feel free to bring kids."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Phoenix",
    "Name": "Nathan",
    "Username": "Psmith",
    "Email address": "natoboo2000@gmail.com",
    "Location description": "20 W 6th St, Tempe, AZ 85281, USA",
    "GPS Coordinates": "33.4244375,-111.9409375",
    "Plus.Code Coordinates": "https://plus.codes/855CC3F5+QJ",
    "Date": "9/14/2024",
    "Time": "03:00 AM",
    "Event Link": "https://www.lesswrong.com/events/Eq2PYKCMBM9cGsFQP/acx-phoenix-september-meetup",
    "Group Link": "https://discord.com/invite/ANSywQABEF",
    "Notes": "Please RSVP on Lesswrong so that I can get a general gauge of how many people are coming: https://www.lesswrong.com/events/Eq2PYKCMBM9cGsFQP/acx-phoenix-september-meetup"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Los Angeles",
    "Name": "Vishal",
    "Username": "koreindian",
    "Email address": "Contact me on discord",
    "Location description": "11841 Wagner Street, Culver City, Los Angeles",
    "GPS Coordinates": "33.9963125,-118.4156875",
    "Plus.Code Coordinates": "https://plus.codes/8553XHWM+GP",
    "Date": "9/11/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "losangelesrationality.com ",
    "Notes": "Join our discord, where we do all our communication (invite link on losangelesrationality.com)."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Newport Beach",
    "Name": "Michael Michalchik",
    "Username": "Michael Michalchik",
    "Email address": "michaelmichalchik+acxlw@gmail.com",
    "Location description": "1970 Port Laurent Place, Newport Beach, Ca, 92660. I will be sitting on my front porch wearing a black shirt,",
    "GPS Coordinates": "33.6144375,-117.8591875",
    "Plus.Code Coordinates": "https://plus.codes/8554J47R+Q8",
    "Date": "9/7/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/ytkHvpQrvLHFcyDhx",
    "Notes": "We have met most Saturdays for that last 2 years. We have had more than 70 meetings, Send me a email to get on our announcements re-mailer or check the less wrong community website for the orange county meetups. "
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Rancho Cucamonga",
    "Name": "Nelson",
    "Username": "",
    "Email address": "nelson.horsley@gmail.com",
    "Location description": "Punchbowl Social in Victoria Gardens on the second floor",
    "GPS Coordinates": "34.1119375,-117.5296875",
    "Plus.Code Coordinates": "https://plus.codes/85644F6C+Q4",
    "Date": "9/20/2024",
    "Time": "06:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Let me know if you’re coming in advance so I know if I need to officially book a reservation."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "San Diego",
    "Name": "Julius",
    "Username": "Julius",
    "Email address": "julius.simonelli@gmail.com",
    "Location description": "Bird Park",
    "GPS Coordinates": "32.7392625,-117.1339844",
    "Plus.Code Coordinates": "https://plus.codes/8544PVQ8+PC2",
    "Date": "9/21/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "https://meetup.com/san-diego-rationalists/",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "San Francisco",
    "Name": "Andrew Gaul",
    "Username": "",
    "Email address": "gaul@gaul.org",
    "Location description": "Dolores Park near the tennis courts",
    "GPS Coordinates": "37.76043749999999,-122.4270625",
    "Plus.Code Coordinates": "https://plus.codes/849VQH6F+55",
    "Date": "10/20/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://groups.google.com/g/bayarealesswrong",
    "Notes": "Please RSVP via email so I can coordinate tarps, drinks, and other picnic gear"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Boulder",
    "Name": "Josh Sacks",
    "Username": "josh-sacks",
    "Email address": "josh.sacks+acx@gmail.com",
    "Location description": "9191 Tahoe Ln, Boulder, CO 80301",
    "GPS Coordinates": "40.0190625,-105.1379375",
    "Plus.Code Coordinates": "https://plus.codes/85GP2V96+JR",
    "Date": "9/22/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "Pending a Discord channel for Boulder meetups...",
    "Notes": "Please RSVP on LessWrong so we know how much cheese to buy"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Denver",
    "Name": "Eneasz Brodski",
    "Username": "Eneasz",
    "Email address": "embrodski@gmail.com",
    "Location description": "Sloan's Lake, North Shore, at the pier BBQs. Park in the Sloan's Lake North Parking Lot (very close to 4701 W Byron Pl), walk just past the stone structure that's right there, and we'll be on the other side of it. Should have a shade structure up, and a white board that says ACX MEETUP on it.",
    "GPS Coordinates": "39.7520625,-105.0483125",
    "Plus.Code Coordinates": "https://plus.codes/85FPQX22+RM",
    "Date": "9/15/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://www.meetup.com/colorado-rationality/",
    "Notes": "Kids are welcome! We'll be BBQing some burgers and hot dogs, and sodas and other snacks also available. Some vegan dogs on offer, but if that's your jam it would help if you could bring something vegan."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Washington DC",
    "Name": "Kayla",
    "Username": "",
    "Email address": "kjgamin@gmail.com",
    "Location description": "Froggy Bottom Pub, 2021 K St NW, Washington, DC 20006 (near Farragut North metro)",
    "GPS Coordinates": "38.9029375,-77.0458125",
    "Plus.Code Coordinates": "https://plus.codes/87C4WX33+5M",
    "Date": "9/21/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://www.facebook.com/groups/605023464809227",
    "Notes": "Food will be provided; drinks available for purchase. You do not need to buy anything to come!"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Washington DC",
    "Name": "Annie Normal",
    "Username": "I truly cannot remember my user name on there. I made my account when I was around 23. ",
    "Email address": "normalannie@gmail.com",
    "Location description": "A bar in central DC. 1240 9th St. NW, Washington DC, 20001",
    "GPS Coordinates": "38.9068125,-77.0241875",
    "Plus.Code Coordinates": "https://plus.codes/87C4WX4G+P8",
    "Date": "9/21/2024",
    "Time": "05:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Cape Coral",
    "Name": "Shawn",
    "Username": "",
    "Email address": "Shawn.Spilman@gmail.com",
    "Location description": "929 SW 54th Ln, Cape Coral, FL 33914",
    "GPS Coordinates": "26.5503125,-81.9946875",
    "Plus.Code Coordinates": "https://plus.codes/76RWH224+44",
    "Date": "9/29/2024",
    "Time": "12:01 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "RSVP optional but appreciated."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Miami",
    "Name": "Campbell Nilsen",
    "Username": "",
    "Email address": "campbell.nilsen@gmail.com",
    "Location description": "Lagniappe, large table in the back right-hand corner as you walk out from the interior onto the patio. I will be wearing a short-sleeved linen shirt and glasses with a sign that says ACX MEETUP on it.",
    "GPS Coordinates": "25.8093125,-80.19093749999999",
    "Plus.Code Coordinates": "https://plus.codes/76QXRR55+PJ",
    "Date": "10/12/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "Email me for an invite link to the Discord server.",
    "Notes": "There are charcuterie/bread/cheese boards and we'll get a few of those (expect some Venmo tag afterwards); there are also some more personal-sized snack options. Lagniappe is primarily a wine bar, but there are plentiful non-alcoholic options as well as beer. No RSVP needed."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Orlando",
    "Name": "Ethan",
    "Username": "Judot",
    "Email address": "ethanhuyck@gmail.com",
    "Location description": "We will meet at the pavilion at UCF by the Breezeway, I will have a sign",
    "GPS Coordinates": "28.6007375,-81.2024844",
    "Plus.Code Coordinates": "https://plus.codes/76WWJQ2X+72R",
    "Date": "9/12/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.com/invite/yKP4v4hC",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Tallahassee",
    "Name": "James",
    "Username": "",
    "Email address": "Jamesmzech@gmail.com",
    "Location description": "Oyster City brewery (603 W Gaines St #7, Tallahassee, FL 32304). I’ll be wearing nondescript clothing and carrying a sign with ACX MEETUP on it.",
    "GPS Coordinates": "30.4353125,-84.29068749999999",
    "Plus.Code Coordinates": "https://plus.codes/862QCPP5+4P",
    "Date": "9/13/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "West Palm Beach",
    "Name": "Charlie",
    "Username": "Auspicious",
    "Email address": "chuckwilson477@yahoo.com",
    "Location description": "Grandview Public Market. 1401 Clare Ave, West Palm Beach, FL 33401. We'll be at the northeast outside area, sitting at a table with an ACX MEETUP sign on it. Parking is free at an adjacent lot, and there should also be a free valet service.",
    "GPS Coordinates": "26.6988125,-80.0635625",
    "Plus.Code Coordinates": "https://plus.codes/76RXMWXP+GH",
    "Date": "9/7/2024",
    "Time": "12:00 AM",
    "Event Link": "",
    "Group Link": "https://discord.gg/tDf8fYPRRP",
    "Notes": "Hosted by the south Florida ACX group that also does meetups in Palm Beach and Broward communities such as Boca Raton, Boynton Beach, Delray Beach and many others. Come join our Discord, we're always welcoming!"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Boise",
    "Name": "Tim",
    "Username": "",
    "Email address": "tim.r.burr@gmail.com",
    "Location description": "Let's meet on the north side of Ann Morrison park, between the road and the greenbelt. I will bring my small, black dog and a lawn game. ",
    "GPS Coordinates": "43.6144375,-116.2225625",
    "Plus.Code Coordinates": "https://plus.codes/85M5JQ7G+QX",
    "Date": "10/5/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Chicago",
    "Name": "Todd",
    "Username": "chicagorationality",
    "Email address": "info@chicagorationality.com",
    "Location description": "Ping Tom Park",
    "GPS Coordinates": "41.8563125,-87.63506249999999",
    "Plus.Code Coordinates": "https://plus.codes/86HJV947+GX",
    "Date": "9/7/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://chicagorationality.com",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Indianapolis",
    "Name": "Tyler",
    "Username": "",
    "Email address": "tylerbraly@gmail.com",
    "Location description": "Tap Indianapolis, 306 N Delaware St, Indianapolis, IN 46204, outside of the weather is nice, otherwise look for the sign saying ACX",
    "GPS Coordinates": "39.7715625,-86.1545625",
    "Plus.Code Coordinates": "https://plus.codes/86FMQRCW+J5",
    "Date": "9/28/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "New Orleans",
    "Name": "Blake Bertuccelli-Booth",
    "Username": "blake-1",
    "Email address": "1111@philosophers.group",
    "Location description": "Petite Clouet Cafe",
    "GPS Coordinates": "29.9633125,-90.04543749999999",
    "Plus.Code Coordinates": "https://plus.codes/76XFXX73+8R",
    "Date": "10/14/2024",
    "Time": "11:11 AM",
    "Event Link": "",
    "Group Link": "http://philosophers.group",
    "Notes": "We're hosting an ACX Lunch and Learn part of NOAI 2024, https://noai.philosophers.group."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Acton",
    "Name": "Paul",
    "Username": "",
    "Email address": "saturndoesmars+acx@gmail.com",
    "Location description": "We'll be hosted by an awesome event venue with a 4-season timber frame \"barn\" w/ recreation/games/patio/fires and lodging for 12 available in 2 cottages. Dinner for purchase. Full bar inside. rain/shine. We are 45min from both Portland, ME and Portsmouth, NH.",
    "GPS Coordinates": "43.5281875,-70.9170625",
    "Plus.Code Coordinates": "https://plus.codes/87MFG3HM+75",
    "Date": "9/26/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP and I'll send a simple Square $0 ticket link. Meeting up and hanging out is free. Buying a dinner is optional. Max capacity 150 people inside."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Baltimore",
    "Name": "Rivka",
    "Username": "",
    "Email address": "rivka@adrusi.com",
    "Location description": "First floor of the Performing Arts and Humanities Building at UMBC. The address is 1000 Hilltop Cir, Baltimore, MD 21250. There will be a sign that says \"ACX Meetup\".",
    "GPS Coordinates": "39.2554375,-76.7148125",
    "Plus.Code Coordinates": "https://plus.codes/87F5774P+53",
    "Date": "9/22/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/h4z5UgeYVK. If you would like to be added to the mailing list (which is primarily for weekly meetup reminders) please email me.",
    "Notes": "Parking is free on the weekend. There will be food and drinks (likely pizza). RSVPs are useful so I know how much food to get, but are not required. We meet weekly, Sundays at 7 PM, half the meetups are virtual and half are in person"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Fort Meade",
    "Name": "Ferret",
    "Username": "",
    "Email address": "meetup2024.exposure178@passinbox.com",
    "Location description": "Fort Meade",
    "GPS Coordinates": "Invalid URL",
    "Plus.Code Coordinates": "(ask organizer)",
    "Date": "10/12/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "(ask organizer)",
    "Notes": "Meetup is on a controlled-access government campus. Organizer will not sponsor guests onto base; attendees must be able to enter on their own. "
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Cambridge",
    "Name": "Skyler",
    "Username": "screwtape",
    "Email address": "skyler@rationalitymeetups.org",
    "Location description": "JFK Memorial Park. I'll be wearing a tall blue and green hat.",
    "GPS Coordinates": "42.3708125,-71.1226875",
    "Plus.Code Coordinates": "https://plus.codes/87JC9VCG+8W",
    "Date": "9/15/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "https://groups.google.com/g/ssc-boston",
    "Notes": "Children and pets welcome- we're in a park with a decent amount of grass and open space.  We'll have food and a shelter in case of rain."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Newton",
    "Name": "duck_master",
    "Username": "duck_master",
    "Email address": "duckmaster0@protonmail.com",
    "Location description": "Newton Centre Green (Centre St & Beacon St)",
    "GPS Coordinates": "42.3306875,-71.19443749999999",
    "Plus.Code Coordinates": "https://plus.codes/87JC8RJ4+76",
    "Date": "9/7/2024",
    "Time": "12:00 PM",
    "Event Link": "",
    "Group Link": "https://www.lesswrong.com/groups/HnrqwPvpX7TFtMwR9",
    "Notes": "Anyone in the area is free to come! The format will be general miscellaneous talk as with earlier meetups. I will ask everyone to say their names though (and I might bring nametags too).  I plan on sticking around for ~3 hours, but if attendees plan on leaving an hour earlier or later I'm ok with that as well."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Detroit",
    "Name": "Victor",
    "Username": "",
    "Email address": "wooddellv@yahoo.com",
    "Location description": "The Panera Bread at the corner of 13 mile and Woodward Ave, in Royal Oak, MI. There will be a sign indicating the section of the restaurant reserved for us. ",
    "GPS Coordinates": "42.5174375,-83.18731249999999",
    "Plus.Code Coordinates": "https://plus.codes/86JRGR87+X3",
    "Date": "9/27/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "RSVP Required (so that I can reserve enough space) Contact me at wooddellv@yahoo.com"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "St. Paul",
    "Name": "Aaron",
    "Username": "25Hour",
    "Email address": "ironlordbyron@gmail.com",
    "Location description": "Davanni's Pizza: 41 Cleveland Ave S, St Paul, MN 55105",
    "GPS Coordinates": "44.9399375,-93.1875625",
    "Plus.Code Coordinates": "https://plus.codes/86P8WRQ6+XX",
    "Date": "10/13/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "Discord link for the MSP ACX meetup group: https://discord.gg/m2xJcuC937",
    "Notes": "I'll be providing pizza!  Vegans are free to bring their own food (Davanni's selection here isn't great); I'll be getting a vegetarian and gluten-free pizza along with other kinds of pizza.  RSVPs on lesswrong would be great."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Reno",
    "Name": "Daniel Gold",
    "Username": "",
    "Email address": "daniel.ian.gold@gmail.com",
    "Location description": "Double R Apartments pool, 9200 Double R Blvd.",
    "GPS Coordinates": "39.4526875,-119.7573125",
    "Plus.Code Coordinates": "https://plus.codes/85F2F63V+33",
    "Date": "9/21/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Morristown",
    "Name": "Matt",
    "Username": "mbrooks",
    "Email address": "matthewrbrooks94@gmail.com",
    "Location description": "10 N Park Pl, Morristown, NJ 07960 (Center of the Morristown Green)",
    "GPS Coordinates": "40.7970625,-74.4809844",
    "Plus.Code Coordinates": "https://plus.codes/87G7QGW9+RJC",
    "Date": "9/21/2024",
    "Time": "03:00 PM",
    "Event Link": "https://www.lesswrong.com/events/LW9Qz6B3rEzdGBuzk/morristown-acx-meetup",
    "Group Link": "https://www.meetup.com/morristown-nj-friendly-ambitious-nerds/",
    "Notes": "If the weather is good we can bring blankets and snacks and picnic on the green. If the weather is poor we can meet at Hops or elsewhere inside."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Albany",
    "Name": "Jake S",
    "Username": "",
    "Email address": "jacob.scheiber@gmail.com",
    "Location description": "Professor Java's Coffee Sanctuary145 Wolf Rd Albany, NY 12205",
    "GPS Coordinates": "42.7181625,-73.8034219",
    "Plus.Code Coordinates": "https://plus.codes/87J8P59W+7J8",
    "Date": "9/14/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "We will probably be sitting outside (unless the weather is bad)."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Brooklyn",
    "Name": "Stefan",
    "Username": "",
    "Email address": "stefanlenoach@gmail.com",
    "Location description": "81 McGuinness Blvd. apt 6A",
    "GPS Coordinates": "40.7250625,-73.9485625",
    "Plus.Code Coordinates": "https://plus.codes/87G8P3G2+2H",
    "Date": "9/14/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "If it rains, we will move to same time the next day, September 15th."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Manhattan",
    "Name": "Robi Rahman",
    "Username": "robirahman",
    "Email address": "robirahman94@gmail.com",
    "Location description": "Pumphouse Park",
    "GPS Coordinates": "40.71206249999999,-74.0161875",
    "Plus.Code Coordinates": "https://plus.codes/87G7PX6M+RG",
    "Date": "9/8/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://groups.google.com/g/overcomingbiasnyc",
    "Notes": "We will meet in Pumphouse Park if the weather is clear, or Brookfield Place if it is raining."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Massapequa",
    "Name": "Gabe ",
    "Username": "gabriel-weil",
    "Email address": "gabeaweil@gmail.com",
    "Location description": "47 Clinton Pl., Massapequa, NY 11758 - backyard if weather permits",
    "GPS Coordinates": "40.6618125,-73.46256249999999",
    "Plus.Code Coordinates": "https://plus.codes/87G8MG6P+PX",
    "Date": "10/5/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP to gabe.a.weil@gmail.com. Also, my wife is pregnant and trying to be Covid cautious. Please don't come if you experiencing any relevant symptoms. "
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Asheville",
    "Name": "Vicki Williams",
    "Username": "Vicki Williams",
    "Email address": "vickirwilliams@gmail.com",
    "Location description": "Biltmore Lake (aka Enka Lake) Fire Pit. Park near 88 Lake Dr. in Candler. Follow the path by the lake to the fire pit behind the tennis courts.",
    "GPS Coordinates": "35.5334375,-82.65368749999999",
    "Plus.Code Coordinates": "https://plus.codes/867VG8MW+9G",
    "Date": "9/27/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP for details, meal planning, and rain location."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Cleveland",
    "Name": "Amber",
    "Username": "AmbiBambi",
    "Email address": "act114@case.edu",
    "Location description": "Floor 2, Think[Box], Case Western Reserve University, Cleveland, Ohio, 44106, USA \n(Tentative location, to be confirmed closer to the time)\n",
    "GPS Coordinates": "41.5005625,-81.6056875",
    "Plus.Code Coordinates": "https://plus.codes/86HWG92V+6P",
    "Date": "10/19/2024",
    "Time": "12:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP on LessWrong by the 16th of October. You can bring guests, but please indicate the number on RSVP"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Corvallis",
    "Name": "Kenan",
    "Username": "kenakofer",
    "Email address": "kbitikofer@gmail.com",
    "Location description": "At a table in Laughing Planet, 127 NW 2nd St, Corvallis, OR 97330, or just outside if the weather is nice. I will have a paper with \"ACX Meetup\" written on it. Car parking is sometimes hard to find.",
    "GPS Coordinates": "44.56458749999999,-123.2594219",
    "Plus.Code Coordinates": "https://plus.codes/84PRHP7R+R6P",
    "Date": "9/27/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.com/invite/ks3KxB3TCM",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Pittsburgh",
    "Name": "Justin",
    "Username": "",
    "Email address": "pghacx@gmail.com",
    "Location description": "City Kitchen @ Bakery Square in East Liberty. If the weather is nice, we can meet at the outdoor tables by the South-East entrance. In case of bad weather, look for us in the atrium between City Kitchen and the Alta Via Pizza/Jeni's Ice Cream. Look for a table with a small stand saying \"ACX\" on it. I will also send out an email ~5 minutes before the scheduled start time with the table number.",
    "GPS Coordinates": "40.4564875,-79.9157031",
    "Plus.Code Coordinates": "https://plus.codes/87G2F34M+HPV",
    "Date": "9/14/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "We have ACX meetups ~monthly.  If you'd like to be added to the email list to be notified of future meetups, contact Justin at pghacx@gmail.com"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Nashville",
    "Name": "Felix",
    "Username": "felixp",
    "Email address": "ACXMeetupNashville@gmail.com",
    "Location description": "Sevier Park Picnic Shelter",
    "GPS Coordinates": "36.1191875,-86.7891875",
    "Plus.Code Coordinates": "https://plus.codes/868M4696+M8",
    "Date": "9/22/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Austin",
    "Name": "Silas Barta",
    "Username": "SilasBarta",
    "Email address": "sbarta@gmail.com",
    "Location description": "The park by Central Market, 4001 North Lamar, Austin, Texas. We will be by the stone tables. We will have a LessWrong and ACX sign and have some tents set up. You can also park in the parking lot at 3900 Guadalupe St (outside the fenced hospital area).",
    "GPS Coordinates": "30.3059375,-97.7389375",
    "Plus.Code Coordinates": "https://plus.codes/86248746+9C",
    "Date": "10/5/2024",
    "Time": "12:00 PM",
    "Event Link": "",
    "Group Link": "https://groups.google.com/g/austin-less-wrong",
    "Notes": "Feel free to bring kids/dogs. We will provide lunch (soft tacos including vegan) and snacks and drinks."
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "College Station",
    "Name": "Michael Frost",
    "Username": "Frost",
    "Email address": "mikefrosttx@gmail.com",
    "Location description": "On the porch of Torchies on Texas Ave. I’ll have a small sign that says “ACX”",
    "GPS Coordinates": "30.6228875,-96.3284219",
    "Plus.Code Coordinates": "https://plus.codes/8625JMFC+5J4",
    "Date": "10/12/2024",
    "Time": "07:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Please RSVP on LessWrong if you are coming, even if it’s last minute"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Dallas",
    "Name": "Ethan",
    "Username": "ethanmorse",
    "Email address": "ethan.morse97@gmail.com",
    "Location description": "11700 Preston Rd Suite 714, Dallas, TX 75230. We'll be in the Whole Foods' upstairs seating area closest to the windows.",
    "GPS Coordinates": "32.9075625,-96.8034375",
    "Plus.Code Coordinates": "https://plus.codes/8645W55W+2J",
    "Date": "10/13/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Houston",
    "Name": "H. B.",
    "Username": "",
    "Email address": "Valerolactone@gmail.com",
    "Location description": "Hermann Park",
    "GPS Coordinates": "29.7201875,-95.3893125",
    "Plus.Code Coordinates": "https://plus.codes/76X6PJC6+37",
    "Date": "10/13/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/DzmEPAscpS",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "San Antonio",
    "Name": "James P",
    "Username": "JonBenetTleilax",
    "Email address": "jonbenettleilax@gmail.com",
    "Location description": "Commonwealth Coffee and Bakery (Jones St), 203 E Jones Ave Ste 101, San Antonio, TX 78215. Meet in the outdoor enclave abutting the cafe. I should have a sign setup, and I will have nametags.",
    "GPS Coordinates": "29.4359375,-98.4800625",
    "Plus.Code Coordinates": "https://plus.codes/76X3CGP9+9X",
    "Date": "10/20/2024",
    "Time": "12:00 PM",
    "Event Link": "",
    "Group Link": "https://lesswrongsa.dry.ai/",
    "Notes": "All are welcome!"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Salt Lake City",
    "Name": "Adam",
    "Username": "",
    "Email address": "adam.r.isom@gmail.com",
    "Location description": "We'll be on the west side of Liberty Park, near the ChargePoint station, in a circle of chairs on the lawn",
    "GPS Coordinates": "40.7471875,-111.8759375",
    "Plus.Code Coordinates": "https://plus.codes/85GCP4WF+VJ",
    "Date": "10/12/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "There's a mailing list and a Discord server, I can get you on both at the meetup",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Richmond",
    "Name": "Brandon Quintin",
    "Username": "",
    "Email address": "brandonmquintin@gmail.com",
    "Location description": "Hardywood Pizza Kitchen and Taproom",
    "GPS Coordinates": "37.5649375,-77.4575625",
    "Plus.Code Coordinates": "https://plus.codes/8794HG7R+XX",
    "Date": "9/26/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "RSVPs encouraged"
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Bellevue-Redmond",
    "Name": "Cedar",
    "Username": "cedar",
    "Email address": "cedar.ren@gmail.com",
    "Location description": "TBD: I want to reserve a library room but room reservations have to be made one month in advance max",
    "GPS Coordinates": "47.62206250000001,-122.1319375",
    "Plus.Code Coordinates": "https://plus.codes/84VVJVC9+R6",
    "Date": "9/14/2024",
    "Time": "02:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Seattle",
    "Name": "Spencer",
    "Username": "Optimization Process",
    "Email address": "speeze.pearson+acx@gmail.com",
    "Location description": "Volunteer Park, by the amphitheater",
    "GPS Coordinates": "47.6315625,-122.3153125",
    "Plus.Code Coordinates": "https://plus.codes/84VVJMJM+JV",
    "Date": "9/29/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "https://facebook.com/groups/seattlerationality/",
    "Notes": ""
  },
  {
    "Region": "North America",
    "Country": "USA",
    "City": "Stone Lake",
    "Name": "Ethan",
    "Username": "",
    "Email address": "eleventhrootofseven@gmail.com",
    "Location description": "Stone Lake Lions Hall @ 16831 W. Main Street Stone Lake, WI. Look for a yellow building on the corner of Main Street and Frost Avenue. Park anywhere close and walk up the ramp from Frost Avenue to enter. We'll be in the café.",
    "GPS Coordinates": "45.8456875,-91.53831249999999",
    "Plus.Code Coordinates": "https://plus.codes/86QCRFW6+7M",
    "Date": "9/14/2024",
    "Time": "06:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "There is a barn dance at the hall afterward (beginner's lesson start at 6:45p, main dance at 7:00p, goes until 9:00p). Some of us will stay to dance. You can to."
  },
  {
    "Region": "Saint Louis",
    "Country": "USA",
    "City": "Saint Louis",
    "Name": "Alex Freeman",
    "Username": "",
    "Email address": "alexrfreeman@proton.me",
    "Location description": "Gurney Pavilion in Tower Grove Park",
    "GPS Coordinates": "38.6060625,-90.26306249999999",
    "Plus.Code Coordinates": "https://plus.codes/86CFJP4P+CQ",
    "Date": "9/21/2024",
    "Time": "01:00 PM",
    "Event Link": "",
    "Group Link": "https://discord.gg/kJvvy6HQ",
    "Notes": ""
  },
  {
    "Region": "South America",
    "Country": "Argentina",
    "City": "Buenos Aires",
    "Name": "Matt",
    "Username": "",
    "Email address": "mw.coop.r@gmail.com",
    "Location description": "Meet at Facultad de Derecho, right outside of the Ache Grill and Starbucks.  We will have some kind of sign that says ACX Meetup",
    "GPS Coordinates": "-34.5830625,-58.39064059999999",
    "Plus.Code Coordinates": "https://plus.codes/48Q3CJ85+QPH",
    "Date": "9/14/2024",
    "Time": "03:00 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": ""
  },
  {
    "Region": "South America",
    "Country": "Brazil",
    "City": "Florianópolis",
    "Name": "Adiel",
    "Username": "",
    "Email address": "adiel@airpost.net",
    "Location description": "Angeloni Beira Mar, at the food court. I’ll be wearing a yellow hat.",
    "GPS Coordinates": "-27.5748375,-48.5274844",
    "Plus.Code Coordinates": "https://plus.codes/584HCFGF+326",
    "Date": "10/19/2024",
    "Time": "04:00 PM",
    "Event Link": "",
    "Group Link": "https://chat.whatsapp.com/C2WFfuFX07W0UBMnTeooN6",
    "Notes": "Everyone is welcome!  There will be cookies."
  },
  {
    "Region": "South America",
    "Country": "Chile",
    "City": "Santiago",
    "Name": "Iñaki",
    "Username": "",
    "Email address": "inaki.escarate@gmail.com",
    "Location description": "Parque Bicentenario, next to the Vitacura municipality, next to the stairs and fountain. We'll have a sign that says \"ACX\"",
    "GPS Coordinates": "-33.3984375,-70.6016875",
    "Plus.Code Coordinates": "https://plus.codes/47RFJ92X+J8",
    "Date": "9/28/2024",
    "Time": "11:30 AM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "English and Spanish speakers welcome!"
  },
  {
    "Region": "South America",
    "Country": "Costa Rica",
    "City": "Tamarindo",
    "Name": "timeless",
    "Username": "",
    "Email address": "pvspam-timeless-acx@hacklab.net",
    "Location description": "El Mercadito, near Asian Fusion Sushi",
    "GPS Coordinates": "10.2994375,-85.8407969",
    "Plus.Code Coordinates": "https://plus.codes/762P75X5+QMG",
    "Date": "9/15/2024",
    "Time": "01:30 PM",
    "Event Link": "",
    "Group Link": "",
    "Notes": "Wear a nerdy tshirt. I will wear a nerdy tshirt. This is a surfer town, so anyone with math or philosophy on their tshirt is probably one of us. Mercadito is a small food court, but I'll get as close to Asian Fusion sushi as possible, and may order some before we begin."
  }
]
