import { registerMigration } from './migrationUtils';
import Users from '../../server/collections/users/collection';
import { createMutator } from '../vulcan-lib/mutators';
import { Posts } from '../../server/collections/posts/collection';
import { mapsAPIKeySetting } from '../../components/form-components/LocationFormComponent';
import { getLocalTime } from '../mapsUtils';
import {userFindOneByEmail, userFindOneByUsernameOrEmail} from "../commonQueries";
import { writeFile } from 'fs/promises';
import { getUnusedSlugByCollectionName } from '../utils/slugUtil';

async function coordinatesToGoogleLocation({ lat, lng }: { lat: string, lng: string }) {
  const requestOptions: any = {
    method: 'GET',
    redirect: 'follow'
  };
  
  const response = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${mapsAPIKeySetting.get()}`, requestOptions)
  const responseText = await response.text()
  const responseData = JSON.parse(responseText)
  return responseData.results[0]
}

export default registerMigration({
  name: "importACXMeetupsSpring25",
  dateWritten: "2025-03-19",
  idempotent: true,
  action: async () => {
    const eventCacheContents: { _id: string, lat: number, lng: number }[] = [];

    // eslint-disable-next-line no-console
    console.log("Begin importing ACX Meetups");
    for (const row of acxData) {
      let eventOrganizer
      // Figure out whether user with email address already exists
      // This used to be userFindByEmail from /lib/vulcan-users/helpers. That seems to have become userFindOneByEmail from /lib/collections/users/commonQueries, but you should check that those actually behaved the same.
      const email = row["Email address"] as string|undefined;
      const lookupUsername = row["Username"] as string|undefined
      const lookupEmail = email === 'ed@newspeak.house' ? 'edsaperia@gmail.com' : email;
      const existingUser = lookupUsername
      ? await userFindOneByUsernameOrEmail(lookupUsername)
      : lookupEmail
        ? await userFindOneByEmail(lookupEmail)
        : undefined;
        
      if (existingUser) {
        eventOrganizer = existingUser
      } else {
        const username = await getUnusedSlugByCollectionName("Users", row["Name"].toLowerCase());
        try {
          const { data: newUser } = await createMutator({
            collection: Users,
            document: {
              username,
              displayName: row["Name"],
              email: email,
              reviewedByUserId: "XtphY3uYHwruKqDyG", //This looks like a hardcoded user who supposedly reviewed something. Who is that user?
              reviewedAt: new Date()
            },
            validate: false,
            currentUser: null
          })
          eventOrganizer = newUser
        } catch (err) {
          // eslint-disable-next-line no-console
          console.log({ err, email, row }, 'Error when creating a new user, using a different username');

          const { data: newUser } = await createMutator({
            collection: Users,
            document: {
              username: `${username}-spring-acx-25`,
              displayName: row["Name"],
              email: email,
              reviewedByUserId: "XtphY3uYHwruKqDyG", //This looks like a hardcoded user who supposedly reviewed something. Who is that user?
              reviewedAt: new Date()
            },
            validate: false,
            currentUser: null
          })

          eventOrganizer = newUser
        }
      }
      
      //Use the coordinates to get the location
      const [latitude, longitude] = row["GPS Coordinates"].split(",");
      const title = `${row["City"]} – ACX Meetups Everywhere Spring 2025`

      // Check for existing event links
      const eventUrl = row["Event Link"];
      const premadePost = eventUrl?.includes("lesswrong.com");
      const eventId = eventUrl && premadePost ? new URL(eventUrl).pathname.split('/')[2] : undefined;

      const [googleLocation, existingPost, premadePostObject] = await Promise.all([
        coordinatesToGoogleLocation({lat: latitude, lng: longitude}),
        // TODO: THIS ISN'T INDEXED, SO THIS RUNS PRETTY SLOWLY IN PROD SINCE IT'S DOING ~FULL TABLE SCANS
        Posts.findOne({ title }),
        eventId ? Posts.findOne(eventId) : Promise.resolve(undefined)
      ]);

      const eventTimePretendingItsUTC = new Date(`${row["Date"]} ${row["Time"]} UTC`)
      const localtime = eventTimePretendingItsUTC.getTime() ? await getLocalTime(eventTimePretendingItsUTC, googleLocation) : new Date();
      const actualTime = new Date(eventTimePretendingItsUTC.getTime() + (eventTimePretendingItsUTC.getTime() - (localtime?.getTime() || eventTimePretendingItsUTC.getTime())))
      
      const fbUrlExists = eventUrl?.includes("facebook.com");
      const meetupUrlExists = eventUrl?.includes("meetup.com");

      let usedPost: DbPost | undefined;
      
      //Then create event post with that user as owner, if there's none by that title and the local organizer didn't already make one.
      if (!existingPost && !premadePostObject) {
        const newPostData = {
          title,
          postedAt: new Date(),
          userId: eventOrganizer._id,
          submitToFrontpage: true,
          activateRSVPs: true,
          draft: false,
          meta: false,
          isEvent: true,
          contactInfo: row["Email address"],
          location: `${row["City"]}`,
          startTime: eventTimePretendingItsUTC.getTime() ? actualTime : undefined,
          meetupLink: meetupUrlExists ? eventUrl : undefined,
          facebookLink: fbUrlExists ? eventUrl : undefined,
          googleLocation,
          contents: {
            originalContents: {
              type: 'ckEditorMarkup',
              data: `<p>This year's Spring ACX Meetup everywhere in ${row["City"]}.</p>
                <p>Location: ${row["Location description"]} – <a href="https://plus.codes/${row["Plus.Code Coordinates"]}">${row["Plus.Code Coordinates"]}</a></p>
                ${row["Group Link"] ? `<p>Group Link: ${row["Group Link"]}</p>` : ""}
                ${row["Notes"] ? `<p>${row["Notes"]}</p>` : ""}
                <p>Contact: ${row["Email address"]} ${row["Additional contact info"] ? `– ${row["Additional contact info"]}` : ""}</p>`
            },
            updateType: 'minor',
            commitMessage: ''
          },
          moderationStyle: 'easy-going',
          af: false,
          authorIsUnreviewed: false,
          types: [
            'SSC'
          ],
        };
        const { data: newPost } = await createMutator({
          collection: Posts,
          document: newPostData,
          currentUser: eventOrganizer,
          validate: false
        })
        // eslint-disable-next-line no-console
        console.log("Created new ACX Meetup: ", newPost.title);
        const googleLocationInfo = newPost.googleLocation?.geometry?.location;
        eventCacheContents.push({ _id: newPost._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });

        usedPost = newPost;
      } else {
        // eslint-disable-next-line no-console
        console.log("Meetup already had a LW event. Check ", eventUrl, "or", title);
        if (existingPost) {
          const googleLocationInfo = existingPost.googleLocation?.geometry?.location;
          eventCacheContents.push({ _id: existingPost._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });
          usedPost = existingPost;
        } else if (premadePostObject) {
          const googleLocationInfo = premadePostObject.googleLocation?.geometry?.location;
          eventCacheContents.push({ _id: premadePostObject._id, lat: googleLocationInfo?.lat, lng: googleLocationInfo?.lng });
          usedPost = premadePostObject;
        }
      }
      const usedPostStartTime = usedPost?.startTime?.getTime();
      const appliedTime = actualTime.getTime();

      if (usedPostStartTime !== appliedTime) {
        // eslint-disable-next-line no-console
        console.log({ usedPostStartTime, appliedTime, row }, 'Created event might have the wrong time');
      }
    }
    // eslint-disable-next-line no-console
    console.log("End importing ACX meetups.");

    await writeFile('eventCache.json', JSON.stringify(eventCacheContents, null, 2))
  }
})

interface ACXMeetup {
  Region: string
  Country: string
  "Name": string
  "Username": string
  "Email address": string
  "City": string
  "Location description": string
  "Plus.Code Coordinates": string
  "Date": string
  "Time": string
  "GPS Coordinates": string
  "Event Link"?: string
  "Group Link"?: string
  Notes?: string
  "Additional contact info"?: string
}

//Updated 4-03-29 14:25 Eastern Time
const acxData: ACXMeetup[] = [
    {
      "Region": "Asia-Pacific",
      "Country": "Australia",
      "City": "Tasmania",
      "Name": "Chris Wintergreen",
      "Username": "Chris Wintergreen",
      "Email address": "cvjones7@gmail.com",
      "Location description": "Parliament lawn",
      "GPS Coordinates": "-42.8857875,147.3312656",
      "Plus.Code Coordinates": "https://plus.codes/4R99487J+MGJ",
      "Date": "4/5/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "If it rains, we'll likely go into Irish Murphy's. You can contact me via email on the day."
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Australia",
      "City": "VIC",
      "Name": "Ryan",
      "Username": "ShardPhoenix",
      "Email address": "xgravityx@hotmail.com",
      "Location description": "Queensberry Hotel Carlton. Will have sign.",
      "GPS Coordinates": "-37.8046875,144.9630625",
      "Plus.Code Coordinates": "https://plus.codes/4RJ65XW7+46",
      "Date": "4/4/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "https://www.facebook.com/groups/lesswrongmelbourne/",
      "Notes": "RSVPs would be helpful for making a booking but not required."
    },
    {
      "Region": "Asia-Pacific",
      "Country": "New Zealand",
      "City": "N/A",
      "Name": "Rachel",
      "Username": "",
      "Email address": "rachelcontact217@gmail.com",
      "Location description": "Band Rotunda, Cornwall Park. I'll have a sign with 'ACX meetup' on it. If the band rotunda is already full of people, I'll be just outside it on the grass.",
      "GPS Coordinates": "-36.8953125,174.7895625",
      "Plus.Code Coordinates": "https://plus.codes/4VMP4Q3Q+VR",
      "Date": "4/6/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "New Zealand",
      "City": "N/A",
      "Name": "Mark",
      "Username": "Mark Gilmour",
      "Email address": "markgilmour@gmail.com",
      "Location description": "Cakes & Ladders, 173 Symonds St, Auckland. I'll have a small sign.",
      "GPS Coordinates": "-36.8626875,174.7610625",
      "Plus.Code Coordinates": "https://plus.codes/4VMP4QP6+WC",
      "Date": "4/6/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "Email me for an invite to the WhatsApp group ",
      "Notes": "We have a small existing meetup group, if you are reading this then you should absolutely come along and check it out. You should RSVP so you feel obligated to follow through :p"
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Australia",
      "City": "ACT",
      "Name": "Declan",
      "Username": "",
      "Email address": "acxcanberra@outlook.com",
      "Location description": "The Snug Room (up the stairs behind the bar), King O'Malley's",
      "GPS Coordinates": "-35.2783125,149.1310625",
      "Plus.Code Coordinates": "https://plus.codes/4RPFP4CJ+MC",
      "Date": "4/7/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "No RSVP needed, but please put 'ACX' in the subject if you email."
    },
    {
      "Region": "South America",
      "Country": "Uruguay ",
      "City": "Maldonado",
      "Name": "Deadpine",
      "Username": "deadpine",
      "Email address": "hey@deadpine.xyz",
      "Location description": "\"La Tranquera\" house, it is located to the right of \"La Olada\" restaurant on La Juanita neighborhood / Casa “La Tranquera” en el barrio La Juanita. Es una casa-container de madera, queda a la derecha del restaurante “La Olada”.",
      "GPS Coordinates": "-34.8357875,-54.6542031",
      "Plus.Code Coordinates": "https://plus.codes/48Q7587W+M8M",
      "Date": "4/29/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP via whatsapp to +598 92 134 064 - I need this to prepare the space and buy food and drinks"
    },
    {
      "Region": "South America",
      "Country": "Argentina",
      "City": "CABA",
      "Name": "Eitan Sprejer",
      "Username": "eitan sprejer",
      "Email address": "eitusprejer@gmail.com",
      "Location description": "Green Eat Billinghurst:\nhttps://maps.app.goo.gl/E4YH12kLxri7jBXLA",
      "GPS Coordinates": "-34.5896875,-58.4091875",
      "Plus.Code Coordinates": "https://plus.codes/48Q3CH6R+48",
      "Date": "4/27/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/BfDp6v3bMwGEfwNGKnhJwV",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Australia",
      "City": "NSW",
      "Name": "Andy B",
      "Username": "",
      "Email address": "Andy.Bachler@gmail.com",
      "Location description": "We'll be in the Common Room in the Wollongong Library. This is a Harry Potter themed room on level 1 (excellent vibes)! I will have a sign on the door saying ACX Meetup.",
      "GPS Coordinates": "-34.4271875,150.8988125",
      "Plus.Code Coordinates": "https://plus.codes/4RQGHVFX+4G",
      "Date": "4/8/2025",
      "Time": "05:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "South Africa",
      "City": "Western Cape",
      "Name": "Leo Hyams",
      "Username": "Leo_9",
      "Email address": "leo@aisafetyct.com",
      "Location description": "Tiger's Milk, Kloof Street",
      "GPS Coordinates": "-33.9293125,18.4116875",
      "Plus.Code Coordinates": "https://plus.codes/4FRW3CC6+7M",
      "Date": "5/7/2025",
      "Time": "05:30 PM",
      "Event Link": "",
      "Group Link": "https://lu.ma/calendar/cal-p3BboQFpGbi3ioe",
      "Notes": "Please register on the Luma event"
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Australia",
      "City": "New South Wales",
      "Name": "Eliot",
      "Username": "elo",
      "Email address": "redeliot@gmail.com",
      "Location description": "Level 2, City of Sydney RSL, 565 George st, Sydney",
      "GPS Coordinates": "-33.8766625,151.2059531",
      "Plus.Code Coordinates": "https://plus.codes/4RRH46F4+89P",
      "Date": "4/17/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/rationalists_of_sydney/",
      "Notes": "Just RSVP on meetup.  Email me with any extra questions"
    },
    {
      "Region": "South America",
      "Country": "Chile",
      "City": "N/A",
      "Name": "Xenofilo",
      "Username": "xenophile",
      "Email address": "xenofiloACX@hotmail.com",
      "Location description": "Parque Bicentenario, al lado de municipalidad de Vitacura. Llevo un cartel con \" ACX meetup \". :)",
      "GPS Coordinates": "-33.3984375,-70.6016875",
      "Plus.Code Coordinates": "https://plus.codes/47RFJ92X+J8",
      "Date": "4/19/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Porfavor siéntanse libres de traer amigos/familia :). También té, café, pan.. Lo que vean mejor. "
    },
    {
      "Region": "South America",
      "Country": "Paraguay",
      "City": "N/A",
      "Name": "Nuño Sempere",
      "Username": "nunosempere",
      "Email address": "nuno.semperelh@protonmail.com",
      "Location description": "Empanadería Sabores de Mi Tierra, 25 De Mayo 3789, Asunción 001229.",
      "GPS Coordinates": "-25.2998125,-57.5990625",
      "Plus.Code Coordinates": "https://plus.codes/5864PC22+39",
      "Date": "4/9/2025",
      "Time": "12:00 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RSVP to my email appreciated, so that I get a sense of how many people are coming, but not required."
    },
    {
      "Region": "South America",
      "Country": "Brazil",
      "City": "Minas Gerais",
      "Name": "David Reis",
      "Username": "",
      "Email address": "davidreis@gmail.com",
      "Location description": "Diamond Mall 1rst Floor Food Court, in front of McDonalds. Address Av. Olegário Maciel, 1600",
      "GPS Coordinates": "-19.9279125,-43.9472344",
      "Plus.Code Coordinates": "https://plus.codes/58GR33C3+R4J",
      "Date": "4/12/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/C0SZe8fdU8O1WgLd4GsST6",
      "Notes": ""
    },
    {
      "Region": "South America",
      "Country": "Brazil",
      "City": "Ceará",
      "Name": "Victor",
      "Username": "",
      "Email address": "victor.a.benevides@gmail.com",
      "Location description": "Parque do Coco",
      "GPS Coordinates": "-3.7451875,-38.4859375",
      "Plus.Code Coordinates": "https://plus.codes/69837G37+WJ",
      "Date": "4/25/2025",
      "Time": "10:00 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Singapore",
      "City": "N/A",
      "Name": "Ben",
      "Username": "",
      "Email address": "79benc@gmail.com",
      "Location description": "Caribbean condominium - the function/leisure room",
      "GPS Coordinates": "1.2671875,103.8164375",
      "Plus.Code Coordinates": "https://plus.codes/6PH57R88+VH",
      "Date": "4/27/2025",
      "Time": "12:30 PM",
      "Event Link": "",
      "Group Link": "https://t.me/LessWrong_Singapore",
      "Notes": "Please RSVP, thanks!"
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "Nigeria",
      "City": "Plateau State",
      "Name": "Jibrin",
      "Username": "https://www.lesswrong.com/users/jibrinx",
      "Email address": "jbnjfr@proton.me",
      "Location description": "Will happen at ICT lab 1, University of Jos, Bauchi-rd campus.",
      "GPS Coordinates": "9.9485625,8.8899375",
      "Plus.Code Coordinates": "https://plus.codes/6FXCWVXQ+CX",
      "Date": "4/18/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://www.facebook.com/groups/Unijos/",
      "Notes": "Access to event is free but requires registration"
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "",
      "City": "KADUNA",
      "Name": "ACX KADUNA",
      "Username": "",
      "Email address": "maleekcherry510@gmail.com",
      "Location description": "NEXUS SPACE",
      "GPS Coordinates": "10.4708125,7.4324375",
      "Plus.Code Coordinates": "https://plus.codes/7F29FCCJ+8X",
      "Date": "3/22/2025",
      "Time": "12:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Vietnam",
      "City": "",
      "Name": "Quang Hiệp",
      "Username": "cygnus",
      "Email address": "hiepbq14408@gmail.com",
      "Location description": "We are going to meet in The Joi Factory Coffee, let me know via email or messages when you arrive and we will take you to our table, the address is: Alley 212/2B, Nguyễn Trãi St., Nguyễn Cư Trinh Ward, Dist. 1",
      "GPS Coordinates": "10.7653125,106.6865625",
      "Plus.Code Coordinates": "https://plus.codes/7P28QM8P+4J",
      "Date": "4/13/2025",
      "Time": "10:00 AM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/nSoF5ntooah7f4qzj",
      "Notes": "If possible, you should response to the following RSVP so that I can estimate the number of guests to expect - https://calendar.app.google/jRCz8McSFGEeCAvm8"
    },
    {
      "Region": "Asia-Pacific",
      "Country": "India",
      "City": "Karnatka",
      "Name": "Chetan",
      "Username": "",
      "Email address": "witnwisdumb@gmail.com",
      "Location description": "I'll be at the gazebo at the centre of Cheluvamba Park on KRS Road in Yadavagiri. I will be wearing a white shirt, and standing next to an A4-sized sign with \"ACX MEETUP\" on it.",
      "GPS Coordinates": "12.3211875,76.63731250000001",
      "Plus.Code Coordinates": "https://plus.codes/7J4R8JCP+FW",
      "Date": "4/19/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP via email."
    },
    {
      "Region": "Asia-Pacific",
      "Country": "India",
      "City": "Telangana",
      "Name": "Ajay",
      "Username": "",
      "Email address": "ajay.bhandari@gmail.com",
      "Location description": "Amro Cafe, Gachibowli",
      "GPS Coordinates": "17.4435625,78.3551875",
      "Plus.Code Coordinates": "https://plus.codes/7J9WC9V4+C3",
      "Date": "5/3/2025",
      "Time": "11:30 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Vietnam",
      "City": "N/A",
      "Name": "Jord",
      "Username": "",
      "Email address": "jordnguyen43@gmail.com",
      "Location description": "Ciao Bella Coffee, ngõ 132 Đ. Võ Chí Công, Xuân La, Cầu Giấy, Hà Nội, Vietnam",
      "GPS Coordinates": "21.0533125,105.8051875",
      "Plus.Code Coordinates": "https://plus.codes/7PH73R34+83",
      "Date": "5/4/2025",
      "Time": "10:00 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Hawaii",
      "Name": "Nancy Hua",
      "Username": "",
      "Email address": "nancythehua@gmail.com",
      "Location description": "Kapiolani park",
      "GPS Coordinates": "21.2654375,-157.8205625",
      "Plus.Code Coordinates": "https://plus.codes/73H4758H+5Q",
      "Date": "4/26/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Feel free to bring kids/dogs. Please RSVP on LessWrong so I know how much food to get."
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "Saudi Arabia",
      "City": "N/A",
      "Name": "A.B.",
      "Username": "",
      "Email address": "AbvACX@proton.me",
      "Location description": "We’ll be at Black Stamp coffee. I’ll have a sign that says “ACX MEETUP” on my table. It should be easy to spot.",
      "GPS Coordinates": "24.7816875,46.6836875",
      "Plus.Code Coordinates": "https://plus.codes/7HP8QMJM+MF",
      "Date": "4/18/2025",
      "Time": "09:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Taiwan",
      "City": "N/A",
      "Name": "Colin",
      "Username": "",
      "Email address": "contact@cosmc.net",
      "Location description": "Wyatt's, 106台北市大安區通化街39巷49弄17號1樓",
      "GPS Coordinates": "25.0310625,121.5556875",
      "Plus.Code Coordinates": "https://plus.codes/7QQ32HJ4+C7",
      "Date": "4/16/2025",
      "Time": "08:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "UAE",
      "City": "N/A",
      "Name": "Mike",
      "Username": "lumenwrites",
      "Email address": "lumenwrites@gmail.com",
      "Location description": "SpartaCUEs Board Game Centre, 2nd floor.",
      "GPS Coordinates": "25.1330625,55.2169375",
      "Plus.Code Coordinates": "https://plus.codes/7HQQ46M8+6Q",
      "Date": "4/13/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/BfIiv6EMJOZIVVhTiNocqj",
      "Notes": "Please message me (+971507349246, or via WhatsApp group) at least a day in advance to let me know that you'll be joining."
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "United Arab Emirates",
      "City": "Dubai",
      "Name": "Nikhil",
      "Username": "",
      "Email address": "nikhilgp@gmail.com",
      "Location description": "Sereni-tea by Tania's Teahouse, 9 Street 29B, Jumeirah",
      "GPS Coordinates": "25.1416875,55.2122031",
      "Plus.Code Coordinates": "https://plus.codes/7HQQ46R6+MVG",
      "Date": "4/5/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Florida",
      "Name": "Zoheb",
      "Username": "",
      "Email address": "zohebanjum@gmail.com",
      "Location description": "1111 Brickell Ave, Miami, FL 33131. We'll be in the lobby, but you can also enter through the Carrot Express.",
      "GPS Coordinates": "25.7621875,-80.1905625",
      "Plus.Code Coordinates": "https://plus.codes/76QXQR65+VQ",
      "Date": "4/12/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/svZeYP83MQ",
      "Notes": "The meetup will go on for several hours so don't worry if you have to arrive later than 2pm. Also, if you need to show up earlier, reach out since we can be flexible about the time. We regularly host local events and also have members across south Florida. If you can't make it to this event, connect with us via Discord or e-mail to stay tuned for future opportunities!"
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "Florida",
      "Name": "Lawrence",
      "Username": "",
      "Email address": "fort.lauderdale.acx@gmail.com",
      "Location description": "Funky Buddha Brewery, parking is free in the lot across the street, I'll be sitting at a table with an \"ACX MEETUP\" sign",
      "GPS Coordinates": "26.1743125,-80.13131249999999",
      "Plus.Code Coordinates": "https://plus.codes/76RX5VF9+PF",
      "Date": "4/27/2025",
      "Time": "01:30 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/svZeYP83MQ",
      "Notes": "Come join our Discord, we're always welcoming"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Florida",
      "Name": "Shawn",
      "Username": "",
      "Email address": "Shawn.Spilman@gmail.com",
      "Location description": "929 SW 54th Ln, Cape Coral, FL 33914",
      "GPS Coordinates": "26.5503125,-81.9946875",
      "Plus.Code Coordinates": "https://plus.codes/76RWH224+44",
      "Date": "5/11/2025",
      "Time": "12:01 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "United States of America",
      "City": "Florida",
      "Name": "Charlie",
      "Username": "Auspicious",
      "Email address": "chuckwilson477@yahoo.com",
      "Location description": "Grandview Public Market. 1401 Clare Ave, West Palm Beach, FL 33401. We'll be at the northeast outside area, sitting at a table with an ACX MEETUP sign on it. Parking is free at an adjacent lot, and there may also be a free valet service.",
      "GPS Coordinates": "26.6988125,-80.0635625",
      "Plus.Code Coordinates": "https://plus.codes/76RXMWXP+GH",
      "Date": "5/3/2025",
      "Time": "11:00 AM",
      "Event Link": "",
      "Group Link": "https://discord.gg/svZeYP83MQ",
      "Notes": "Hosted by the south Florida ACX group that also does meetups in Palm Beach and Broward communities such as Boca Raton, Boynton Beach, Delray and many others. Come join our Discord, we're always welcoming!"
    },
    {
      "Region": "Asia-Pacific",
      "Country": "India",
      "City": "Delhi ",
      "Name": "Suryansh Tyagi ",
      "Username": "",
      "Email address": "suryanshtyagiphone@gmail.com",
      "Location description": "Spaced out Cafe",
      "GPS Coordinates": "28.5494375,77.2118125",
      "Plus.Code Coordinates": "https://plus.codes/7JWVG6X6+QP",
      "Date": "5/10/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/Jph8xQOprnK1mA7DBKkWOS",
      "Notes": "Please RSVP on +919997299972. Feel free to bring friends."
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "Florida",
      "Name": "Ethan",
      "Username": "Judot",
      "Email address": "ethanhuyck@gmail.com",
      "Location description": "The pavilion outside the breezeway at UCF.",
      "GPS Coordinates": "28.6007375,-81.2024844",
      "Plus.Code Coordinates": "https://plus.codes/76WWJQ2X+72R",
      "Date": "4/29/2025",
      "Time": "07:30 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/MJwcEND9wu",
      "Notes": ""
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "Egypt",
      "City": "N/A",
      "Name": "Mostafa Shahat",
      "Username": "",
      "Email address": "ms@mostafashahat.com",
      "Location description": "Consoleya | We'll be in the main coworking space on the ground floor. I'll be wearing a name tag with 'ACX MEETUP' on it, and there will be a small sign on the table.",
      "GPS Coordinates": "30.0493125,31.2403125",
      "Plus.Code Coordinates": "https://plus.codes/8G2H26XR+P4",
      "Date": "4/20/2025",
      "Time": "12:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Texas",
      "Name": "Kevin",
      "Username": "",
      "Email address": "kevinchenftw@gmail.com",
      "Location description": "Radio Coffee and Beer, I will bring a sign saying ACX MEETUP",
      "GPS Coordinates": "30.2316875,-97.7879375",
      "Plus.Code Coordinates": "https://plus.codes/862466J6+MR",
      "Date": "4/18/2025",
      "Time": "08:00 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/austin-less-wrong",
      "Notes": "You can RSVP through the Partiful link (https://partiful.com/e/g5Rc1OQHvZMAB44lmmyu) no account required. RSVP is optional, but would be useful."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Florida",
      "Name": "Metaculus Christian",
      "Username": "ChristianWilliams",
      "Email address": "christian@metaculus.com",
      "Location description": "https://www.oldhickorywhiskeybar.com/ 123 S. Palafox Place, Pensacola, FL 32502 I'll wear a Metaculus hoodie",
      "GPS Coordinates": "30.41056249999999,-87.2150625",
      "Plus.Code Coordinates": "https://plus.codes/862JCQ6M+6X",
      "Date": "4/2/2025",
      "Time": "09:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RSVP. Message if you want to come, because if I don't get any messages, I won't be there. "
    },
    {
      "Region": "Asia-Pacific",
      "Country": "China",
      "City": "N/A",
      "Name": "David",
      "Username": "david-jiang",
      "Email address": "dj@theory-a.com",
      "Location description": "Zhongshan Park, Changning District (Main Entrance)",
      "GPS Coordinates": "31.2200625,121.4209375",
      "Plus.Code Coordinates": "https://plus.codes/8Q336CCC+29",
      "Date": "5/24/2025",
      "Time": "10:00 AM",
      "Event Link": "",
      "Group Link": "https://discord.gg/G6xRGnvD",
      "Notes": "Please RSVP"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "California",
      "Name": "Julius",
      "Username": "Julius",
      "Email address": "julius.simonelli@gmail.com",
      "Location description": "Wisdom Park",
      "GPS Coordinates": "32.8979375,-117.1670625",
      "Plus.Code Coordinates": "https://plus.codes/8544VRXM+55",
      "Date": "5/10/2025",
      "Time": "01:00 PM",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/san-diego-rationalists/",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Texas",
      "Name": "Ethan",
      "Username": "ethanmorse",
      "Email address": "ethan.morse97@gmail.com",
      "Location description": "Whole Foods, 11700 Preston Rd Suite 714, Dallas, TX 75230. We'll be in the upstairs seating area closest to the windows. I will be wearing a name tag that says \"Ethan\" on it.",
      "GPS Coordinates": "32.9075625,-96.80318749999999",
      "Plus.Code Coordinates": "https://plus.codes/8645W55W+2P",
      "Date": "4/27/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/SdwuhENYWpA4BTrZT",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Arizona",
      "Name": "Ryan Sang",
      "Username": "cerwindhunt",
      "Email address": "thedoctor2031@gmail.com",
      "Location description": "The Churchill. Covered, open-air space with misters. Food hall. I'll have a sign saying ACX.",
      "GPS Coordinates": "33.4578125,-112.0721875",
      "Plus.Code Coordinates": "https://plus.codes/8559FW5H+44",
      "Date": "5/16/2025",
      "Time": "05:30 PM",
      "Event Link": "",
      "Group Link": "https://discord.com/invite/ANSywQABEF",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "California",
      "Name": "Michael Michalchik ",
      "Username": "Michael Michalchik ",
      "Email address": "michaelmichalchik@gmail.com",
      "Location description": "1970 port Laurent place. White garage door, brick  entrance into a duplex.",
      "GPS Coordinates": "33.6144375,-117.8591875",
      "Plus.Code Coordinates": "https://plus.codes/8554J47R+Q8",
      "Date": "4/5/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "Email me to be put on our weekly mailing list. Michaelmichalchik. Put keyword in subject line Acxlw",
      "Notes": "RSVP is appreciated but not required"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "North Carolina",
      "Name": "Cam",
      "Username": "",
      "Email address": "camantiodrome@gmail.com",
      "Location description": "4400 Sharon Road, SouthPark Mall, at the entrance atrium between Cheesecake Factory & Maggiano's. I'll be wearing the Kuromi hat (Black with pointed ears)",
      "GPS Coordinates": "35.1519375,-80.83043750000002",
      "Plus.Code Coordinates": "https://plus.codes/867X5529+QR",
      "Date": "4/12/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "US",
      "City": "Oklahoma",
      "Name": "bean",
      "Username": "bean",
      "Email address": "battleshipbean@gmail.com",
      "Location description": "Pavilion by the planes at the 45th infantry division museum.",
      "GPS Coordinates": "35.5083125,-97.4735625",
      "Plus.Code Coordinates": "https://plus.codes/8674GG5G+8H",
      "Date": "4/5/2025",
      "Time": "01:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "I will be wearing a USS Iowa hat."
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "North Carolina",
      "Name": "Vicki Williams",
      "Username": "Vicki Williams",
      "Email address": "vickirwilliams@gmail.com",
      "Location description": "Biltmore (aka Enka) Lake fire pit. Park near 88 Lake Dr., Candler. Walk along the trail by the lake to the fire pit behind the tennis courts.",
      "GPS Coordinates": "35.5334375,-82.65368749999999",
      "Plus.Code Coordinates": "https://plus.codes/867VG8MW+9G",
      "Date": "4/4/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP so you can be notified in case of change in plans. Kid friendly (there's a playground nearby) and pet friendly (leashed please). We'll have a campfire and some fire appropriate food stuffs."
    },
    {
      "Region": "Asia-Pacific",
      "Country": "Japan",
      "City": "N/A",
      "Name": "JT",
      "Username": "Harold",
      "Email address": "rationalitysalon@gmail.com",
      "Location description": "https://g.co/kgs/86R7R1X Just Another Space, 〒153-0051 Tokyo, Meguro City, Kamimeguro, 1 Chome−3−9 Fujiya Bldg., ３F",
      "GPS Coordinates": "35.6444375,139.7011875",
      "Plus.Code Coordinates": "https://plus.codes/8Q7XJPV2+QF",
      "Date": "5/10/2025",
      "Time": "",
      "Event Link": "https://www.lesswrong.com/events/ocwoWy64epCXrkXXQ/tokyo-japan-acx-spring-schelling-meetup-everywhere-2025",
      "Group Link": "https://rationalitysalon.substack.com/s/acx-tokyo",
      "Notes": "Please subscribe to the substack feed for updates to the meetup details and for future events."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Arkansas",
      "Name": "Charles",
      "Username": "cxsmith",
      "Email address": "nwa_rationality.humid012@silomails.com",
      "Location description": "Onyx Coffee Lab, NW 2nd Street",
      "GPS Coordinates": "36.3731875,-94.2093125",
      "Plus.Code Coordinates": "https://plus.codes/86879QFR+77",
      "Date": "4/5/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "PLEASE do not schedule my meetup within three weeks of any other in NW AR. The Fayetteville meetup may have priority. Please email me if my given date is not tenable so I can suggest another date."
    },
    {
      "Region": "Africa & The Middle East",
      "Country": "Turkey",
      "City": "N/A",
      "Name": "Annalise",
      "Username": "",
      "Email address": "annalisetarhan@gmail.com",
      "Location description": "Beach Park, Shakespeare, on the patio - look for a propped up notebook with \"ACX\"",
      "GPS Coordinates": "36.8828625,30.6721406",
      "Plus.Code Coordinates": "https://plus.codes/8G8GVMMC+4VR",
      "Date": "4/19/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Virginia",
      "Name": "Jough",
      "Username": "",
      "Email address": "joughdonakowski@gmail.com",
      "Location description": "The Frothy Moon Brewhouse, 1826 Jamestown Road, Williamsburg, Virginia 23185, United States - I will likely be at an indoor table and try to have some kind of ACX MEETUP signage. I am the 40ish year-old white guy with facial hair, or at least one of them.",
      "GPS Coordinates": "37.2378125,-76.76656249999999",
      "Plus.Code Coordinates": "https://plus.codes/879566QM+49",
      "Date": "5/10/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Kid, spouse, friendly. Venue often has food trucks and allows outside food. RSVPs appreciated but not required."
    },
    {
      "Region": "Asia-Pacific",
      "Country": "South Korea",
      "City": "N/A",
      "Name": "Cyrus C",
      "Username": "",
      "Email address": "Ccheung13@protonmail.com",
      "Location description": "Seoul Brewery in Seongsu, 28-12, Yeonmujang-gil, Seongdong-gu, Seoul, Republic of Korea",
      "GPS Coordinates": "37.5430625,127.0524375",
      "Plus.Code Coordinates": "https://plus.codes/8Q99G3V2+6X",
      "Date": "4/12/2025",
      "Time": "04:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP so i know how many people are joining! The organizer is an English speaker, but Korean-speakers are welcome."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "California",
      "Name": "Austin Chen",
      "Username": "austin-chen",
      "Email address": "austin@manifund.org",
      "Location description": "1680 Mission St (Mox)",
      "GPS Coordinates": "37.7708125,-122.4199375",
      "Plus.Code Coordinates": "https://plus.codes/849VQHCJ+82",
      "Date": "4/5/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Kids welcome!"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "California",
      "Name": "Skyler",
      "Username": "screwtape",
      "Email address": "skyler@rationalitymeetups.org",
      "Location description": "2740 Telegraph Ave, Berkeley",
      "GPS Coordinates": "37.8599375,-122.2595625",
      "Plus.Code Coordinates": "https://plus.codes/849VVP5R+X5",
      "Date": "6/4/2025",
      "Time": "06:30 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/bayarealesswrong",
      "Notes": "Held between Less.Online and Manifest 3, we expect a lot of interesting out-of-town visitors. We’ll provide dinner, kids are welcome, no pets please!"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Kentucky",
      "Name": "Owen",
      "Username": "",
      "Email address": "owencardwellcopenhefer@gmail.com",
      "Location description": "Noble Funk Brewing Company ",
      "GPS Coordinates": "38.2404375,-85.75643749999999",
      "Plus.Code Coordinates": "https://plus.codes/86CP66RV+5C",
      "Date": "4/12/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Location is child friendly. EV slow-charging available."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "CA",
      "Name": "Mike",
      "Username": "",
      "Email address": "semanticprion@gmail.com",
      "Location description": "Brew Coffee House, 555 Healdsburg Avenue, Santa Rosa, CA  95401",
      "GPS Coordinates": "38.4433125,-122.7180625",
      "Plus.Code Coordinates": "https://plus.codes/84CVC7VJ+8Q",
      "Date": "5/12/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Portugal",
      "City": "N/A",
      "Name": "Luis Campos",
      "Username": "No need, I have a script that creates these events automatically :)",
      "Email address": "luis.filipe.lcampos@gmail.com",
      "Location description": "Jardim Amália Rodrigues",
      "GPS Coordinates": "38.73218749999999,-9.154187499999999",
      "Plus.Code Coordinates": "https://plus.codes/8CCGPRJW+V8",
      "Date": "4/12/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/iJzwL2ukGBAGNcwJq",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Missouri",
      "Name": "Ben Scott",
      "Username": "",
      "Email address": "bens9775@gmail.com",
      "Location description": "Cosmo-Bethel Park, 4500 Bethel St, Columbia, MO 65203 We'll be at the shelter by the parking lot. I'll be wearing a red shirt and there will be a sign that says ACX.",
      "GPS Coordinates": "38.9029375,-92.34406249999999",
      "Plus.Code Coordinates": "https://plus.codes/86C9WM34+59",
      "Date": "4/12/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Feel free to bring kids/dogs. Pizza will be provided, bring your own drink. RSVP requested so we know how much food to get-->https://forms.gle/vxeqmN2wBsjZUEaZ7"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "California",
      "Name": "Max and Haven Worsham Harms",
      "Username": "Raelifin",
      "Email address": "raelifin@gmail.com",
      "Location description": "Weather permitting, we'll be at a picnic table near the Prospector Statue in Condon Park. If it rains, we'll probably meet up at our house nearby.",
      "GPS Coordinates": "39.2161875,-121.0721875",
      "Plus.Code Coordinates": "https://plus.codes/84FW6W8H+F4",
      "Date": "5/17/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP on LessWrong so that we can reach out for updates in case details change (such as location)"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Maryland",
      "Name": "Rivka",
      "Username": "Rivka",
      "Email address": "Rivka@adrusi.com",
      "Location description": "First floor of the Performing Arts and Humanities Building at UMBC. The address is 1000 Hilltop Cir, Baltimore, MD 21250. There will be a sign that says \"ACX Meetup\".",
      "GPS Coordinates": "39.2554375,-76.7148125",
      "Plus.Code Coordinates": "https://plus.codes/87F5774P+53",
      "Date": "4/20/2025",
      "Time": "07:00 PM",
      "Event Link": "",
      "Group Link": "We have a mailing list and a discord. The mailing list is more for our weekly meetup reminders and the discord is more of a social environment. Here's a link to the discord: https://discord.gg/h4z5UgeYVK. If you would like to be added to the mailing list, please email me.",
      "Notes": "Parking is free on the weekend. There will be food and drinks. RSVPs are useful so I know how much food to get, but are not required."
    },
    {
      "Region": "Europe",
      "Country": "Spain",
      "City": "Comunidad Valenciana",
      "Name": "Giovanni",
      "Username": "",
      "Email address": "gsstasi@gmail.com",
      "Location description": "Cherry Blossom Valencia, C/ de Moratín, 15, 46002",
      "GPS Coordinates": "39.4706875,-0.3755625",
      "Plus.Code Coordinates": "https://plus.codes/8CFXFJCF+7Q",
      "Date": "4/6/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Indianna",
      "Name": "Tyler",
      "Username": "",
      "Email address": "tylerbraly@gmail.com",
      "Location description": "Upland Brewery Fountain Square 1201 Prospect St, Indianapolis, IN 46203",
      "GPS Coordinates": "39.7546875,-86.1378125",
      "Plus.Code Coordinates": "https://plus.codes/86FMQV36+VV",
      "Date": "4/26/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "CO",
      "Name": "Josh Sacks",
      "Username": "Josh sacks",
      "Email address": "Josh.sacks+acx@gmail.com",
      "Location description": "9191 Tahoe ln, Boulder,CO 80301",
      "GPS Coordinates": "40.0190625,-105.1379375",
      "Plus.Code Coordinates": "https://plus.codes/85GP2V96+JR",
      "Date": "5/4/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP on Less Wrong so we know how much cheese to get. If the weather is nice there’s outdoor seating, otherwise inside. We have 3 very friendly cats."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New Jersey",
      "Name": "Ben L",
      "Username": "",
      "Email address": "mywebdev3@gmail.com",
      "Location description": "Ocean County Park (Please message the coordinator to confirm)",
      "GPS Coordinates": "40.0951875,-74.1841875",
      "Plus.Code Coordinates": "https://plus.codes/87G73RW8+38",
      "Date": "5/4/2025",
      "Time": "10:00 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP and confirm with me beforehand. Time and Place may (often does) change"
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "Indiana",
      "Name": "Grant",
      "Username": "",
      "Email address": "grantfellows18@gmail.com",
      "Location description": "Address: Beering Hall of Liberal Arts (BRNG) Room 1268, 100 N University St, West Lafayette, IN 47907. BRNG 1268 is in the southwest corner of the building, and can be found after turning left at the south entrance. Please email me if you cannot find us. I will also place an ACX Meetup sign at the entrance to the room.",
      "GPS Coordinates": "40.4253125,-86.9164375",
      "Plus.Code Coordinates": "https://plus.codes/86GMC3GM+4C",
      "Date": "4/19/2025",
      "Time": "03:30 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/WpGTW4htZm",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Pennsylvania",
      "Name": "Matan Shtepel",
      "Username": "MrJones",
      "Email address": "matan.shtepel@gmail.com",
      "Location description": "We'll meet on the lawn in front of the tennis courts on CMU's campus. If it rains, we'll go into the the CMU university center (UC) which is open without key-card even on the weekend. We may eventually wander, so email me if you can't find us. ",
      "GPS Coordinates": "40.4425625,-79.9425625",
      "Plus.Code Coordinates": "https://plus.codes/87G2C3V4+2X",
      "Date": "4/6/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Justin",
      "Username": "",
      "Email address": "justin.satriano@gmail.com",
      "Location description": "We can meet at my house at 82 S Centre Ave, Rockville Centre, NY 11570. If it's nice weather we can have it in our large backyard.",
      "GPS Coordinates": "40.65418750000001,-73.6501875",
      "Plus.Code Coordinates": "https://plus.codes/87G8M83X+MW",
      "Date": "5/3/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/overcomingbiasnyc",
      "Notes": "Feel free to bring kids. Please RSVP by April 25th so I know how much food to make."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Gabe",
      "Username": "Gabriel Weil",
      "Email address": "gabeaweil@gmail.com",
      "Location description": "47 Clinton Pl., Massapequa, NY 17758 (backyard)",
      "GPS Coordinates": "40.65531250000001,-73.47506249999999",
      "Plus.Code Coordinates": "https://plus.codes/87G8MG4F+4X",
      "Date": "5/18/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP via email to gabeaweil at gmail"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Shaked and Robi ",
      "Username": "pku",
      "Email address": "shaked.koplewitz@gmail.com, robirahman94@gmail.com",
      "Location description": "Pumphouse Park (I'll be there holding a sign). If the weather is bad, we'll retreat into Brookfield Place mall.",
      "GPS Coordinates": "40.71206249999999,-74.0161875",
      "Plus.Code Coordinates": "https://plus.codes/87G7PX6M+RG",
      "Date": "4/20/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/overcomingbiasnyc",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Stefan",
      "Username": "",
      "Email address": "stefanlenoach@gmail.com",
      "Location description": "81 McGuinness Blvd apt 6A",
      "GPS Coordinates": "40.7253125,-73.9488125",
      "Plus.Code Coordinates": "https://plus.codes/87G8P3G2+4F",
      "Date": "4/26/2025",
      "Time": "08:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP, thank you"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Rishi",
      "Username": "",
      "Email address": "rishiag@umd.edu",
      "Location description": "Washington Square Arch, Washington Square Park, Washington Square N,  New York, NY 10012. At the benches located towards the large fountain at the center, or just standind around. I will be wearing a green polo shirt",
      "GPS Coordinates": "40.7313125,-73.9970625",
      "Plus.Code Coordinates": "https://plus.codes/87G8P2J3+G5",
      "Date": "4/4/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please email me if you have any questions or suggestions. Looking forward to seeing everybody there!"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Utah",
      "Name": "Adam",
      "Username": "",
      "Email address": "adamisom@hey.com",
      "Location description": "We'll be in the usual location at Liberty Park--west side, near the ChargePoint station, in a circle of chairs under a big tree",
      "GPS Coordinates": "40.7466875,-111.8763125",
      "Plus.Code Coordinates": "https://plus.codes/85GCP4WF+MF",
      "Date": "4/12/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "email me for a Discord invite and/or to be added to the email list",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Turkey",
      "City": "N/A",
      "Name": "Ozge",
      "Username": "",
      "Email address": "ozgeco@yahoo.com",
      "Location description": "Espresso Lab at Galataport next to Museum of  Painting and Sculpture",
      "GPS Coordinates": "41.02756249999999,28.9841875",
      "Plus.Code Coordinates": "https://plus.codes/8GHC2XHM+2M",
      "Date": "5/10/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Looking forward to meeting old friends and new ones! It would be nice to let me know that you will be attending by dropping an email or replying on LessWrong. I will be sitting outside of the cafe - weather permitting-  with a ACX Meeting sign on the table. "
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Connecticut",
      "Name": "Evan",
      "Username": "",
      "Email address": "acx.newhaven@gmail.com",
      "Location description": "We will meet in front of the Soldiers and Sailors Monument at the top of East Rock Park. I will be wearing red.",
      "GPS Coordinates": "41.3271875,-72.90481249999999",
      "Plus.Code Coordinates": "https://plus.codes/87H983GW+V3",
      "Date": "4/20/2025",
      "Time": "12:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RSVPs are desired, but not required. Email me. Rain date is Sunday the 21st at noon You can drive to the top of the ridge. Budget a few minutes for this because it's a narrow, windy road with lots of pedestrians. You can also park by the baseball fields on English Drive and take a short, steep hike to the summit."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Connecticut",
      "Name": "Richard B.",
      "Username": "",
      "Email address": "riba@firemail.cc",
      "Location description": "By the flagpole on top of the hill of the Center Memorial Park. ",
      "GPS Coordinates": "41.7735625,-72.5222969",
      "Plus.Code Coordinates": "https://plus.codes/87H9QFFH+C3G",
      "Date": "5/3/2025",
      "Time": "01:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "I expect we'll move somewhere inside for a coffee."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Illinois",
      "Name": "Noah Birnbaum",
      "Username": "https://www.lesswrong.com/users/noah-birnbaum",
      "Email address": "dnbirnbaum@uchicago.edu",
      "Location description": "On the UChicago campus - usually in the Bartlett Dining Commons lounge but this could be subject to change. ",
      "GPS Coordinates": "41.7919375,-87.5984375",
      "Plus.Code Coordinates": "https://plus.codes/86HJQCR2+QJ",
      "Date": "4/15/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "Uchicago: https://forms.gle/LZPSxwd1gtHku2QbA General Chicago: https://chicagorationality.com",
      "Notes": "If you are on the mailing list, please fill out RSVP form that will be sent out so that I know how much food to get. "
    },
    {
      "Region": "Europe",
      "Country": "Italy",
      "City": "N/A",
      "Name": "Giulio Starace",
      "Username": "thesofakillers",
      "Email address": "giulio.starace@gmail.com",
      "Location description": "Caffè Letterario",
      "GPS Coordinates": "41.8710625,12.4803125",
      "Plus.Code Coordinates": "https://plus.codes/8FHJVFCJ+C4",
      "Date": "5/17/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Message me or email me to join the WhatsApp group!"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Iowa",
      "Name": "Samuel",
      "Username": "",
      "Email address": "enemy.jurist@gmail.com",
      "Location description": "Iowa State University 2231 Lincoln Way Ames, IA 50014 ",
      "GPS Coordinates": "42.0243375,-93.64604690000002",
      "Plus.Code Coordinates": "https://plus.codes/86J829F3+PHP",
      "Date": "4/26/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "I will be sitting by the west side of the Fountain of Four Seasons directly north of the Memorial Union on Iowa State University’s campus. I’ll have a bright orange ski jacket on or tied around my waist depending on temperature. I plan on arriving ~15 minutes before the start time of 2:00pm."
    },
    {
      "Region": "North America",
      "Country": "USA ",
      "City": "Iowa",
      "Name": "Sarah",
      "Username": "",
      "Email address": "throwaway3454554@yahoo.com",
      "Location description": "Cafe Diem- 229 Main St, Ames, IA 50010. I will have a sign with ACX meet up on it. Likely sitting near the window towards the front of the store",
      "GPS Coordinates": "42.0251875,-93.61331249999999",
      "Plus.Code Coordinates": "https://plus.codes/86J829GP+3M",
      "Date": "4/6/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RVSP NOT required but useful. First time doing this. "
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Isaac Cohen",
      "Username": "",
      "Email address": "idcohen2000@gmail.com",
      "Location description": "We'll be in the Union Undergrounds on the Binghamton University Campus",
      "GPS Coordinates": "42.0878125,-75.9669375",
      "Plus.Code Coordinates": "https://plus.codes/87J632QM+46",
      "Date": "4/6/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP on LessWrong so I have an idea of how many people to expect"
    },
    {
      "Region": "North America",
      "Country": "United States",
      "City": "Michigan",
      "Name": "Joseph Pryor",
      "Username": "J03MAN",
      "Email address": "jwpryorprojects@gmail.com",
      "Location description": "Friends Meetinghouse 1420 Hill St. Ann Arbor Mi  If the weather is good will meet in the back yard at the picnic tables, if it is raining or too cold the corner room of the meeting house is reserved. ",
      "GPS Coordinates": "42.2716875,-83.73056249999999",
      "Plus.Code Coordinates": "https://plus.codes/86JR77C9+MQ",
      "Date": "5/17/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/ann-arbor-ssc-rationalist-meetup-group",
      "Notes": "Meetup runs from 1pm to 5pm, come any time in that range! All day parking is available in the alley at the rear of the property and on the side streets. Feel free to bring food and drinks if the weather is good. (no food or drinks indoors) Bathrooms are available inside the building. For any questions or for text reminders the day before: 517-945-8084 No rsvp required but check out our monthly meetups at the group link! "
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Massachusetts",
      "Name": "duck_master",
      "Username": "duck_master",
      "Email address": "duckmaster0@protonmail.com",
      "Location description": "Newton Centre Green (Centre St & Beacon St)",
      "GPS Coordinates": "42.3306875,-71.19443749999999",
      "Plus.Code Coordinates": "https://plus.codes/87JC8RJ4+76",
      "Date": "4/5/2025",
      "Time": "12:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Michigan",
      "Name": "Victor",
      "Username": "",
      "Email address": "wooddellv@yahoo.com",
      "Location description": "Panera Bread at the corner of Woodward and 13 Mile road, in Royal Oak. ",
      "GPS Coordinates": "42.5174375,-83.18731249999999",
      "Plus.Code Coordinates": "https://plus.codes/86JRGR87+X3",
      "Date": "4/11/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP to my email address."
    },
    {
      "Region": "Europe",
      "Country": "Bulgaria",
      "City": "N/A",
      "Name": "Daniel",
      "Username": "Daniel Bensen",
      "Email address": "bensen.daniel@gmail.com",
      "Location description": "We'll be in the gazebo in \"Слънчевата градинка\" (picture here https://maps.app.goo.gl/7uBsEdBKGrN2i8F6A). This little garden is part of Borisova Gradina near the tennis courts, roughly between the Television Tower and Levski Stadium. If you think you'll have trouble finding it, email me and I'll arrange for someone to meet you.",
      "GPS Coordinates": "42.6781875,23.3463125",
      "Plus.Code Coordinates": "https://plus.codes/8GJ5M8HW+7G",
      "Date": "4/27/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/HGaSdqwqG4SogWfTi",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Massachusetts",
      "Name": "Satya Benson",
      "Username": "satchlj",
      "Email address": "acx.meetup@satchlj.com",
      "Location description": "Sawyer Library 430 Conference Room",
      "GPS Coordinates": "42.7135625,-73.2020781",
      "Plus.Code Coordinates": "https://plus.codes/87J8PQ7X+C5F",
      "Date": "4/12/2025",
      "Time": "01:30 PM",
      "Event Link": "",
      "Group Link": "https://eph.lol/acx/",
      "Notes": "There will be suggested reading ahead of the meetup"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "New York",
      "Name": "Sarah W. ",
      "Username": "",
      "Email address": "seraphedelweiss@proton.me",
      "Location description": "University at Buffalo South Campus - The quad between the Abbot Library and continuing dental education building. ",
      "GPS Coordinates": "42.9540125,-78.8179531",
      "Plus.Code Coordinates": "https://plus.codes/87J3X53J+JR3",
      "Date": "4/13/2025",
      "Time": "12:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Wisconsin",
      "Name": "Ben",
      "Username": "",
      "Email address": "benjamin.boerigter@gmail.com",
      "Location description": "317 Eugenia Ave 2S - red brick 4-unit apartment building across from Geneva Campus Church. Ring doorbell for unit!",
      "GPS Coordinates": "43.0704375,-89.44506249999999",
      "Plus.Code Coordinates": "https://plus.codes/86MG3HC3+5X",
      "Date": "4/12/2025",
      "Time": "12:00 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/madison-wi-acx",
      "Notes": "Feel free to bring kids. Will have some snacks and drinks."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Maine",
      "Name": "Frost",
      "Username": "",
      "Email address": "argot207",
      "Location description": "Bell Buoy Park on the Waterfront, I've got dyed blue hair you can spot me with, and I'll be near the Bouy.",
      "GPS Coordinates": "43.6575625,-70.2499375",
      "Plus.Code Coordinates": "https://plus.codes/87MFMQ52+22",
      "Date": "4/21/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/portland-effective-altruism-and-rationality",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Ontario",
      "Name": "Sean A",
      "Username": "https://www.lesswrong.com/users/sean-aubin",
      "Email address": "k9i9m9ufh@mozmail.com",
      "Location description": "Enter the Mars Atrium via University Avenue entrance. We'll meet at the food court in the basement. I'll be wearing a bright neon yellow jacket.",
      "GPS Coordinates": "43.6599375,-79.3886875",
      "Plus.Code Coordinates": "https://plus.codes/87M2MJ56+XG",
      "Date": "4/13/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/8ktnBi4AjxtCmGeXA",
      "Notes": "If for some reason the Mars Building is locked, which happens occasionally due to protests and other events, we will still meet outside of the University Avenue entrance for 30 minutes after the start time before relocating to somewhere more accommodating."
    },
    {
      "Region": "Europe",
      "Country": "Italy",
      "City": "N/A",
      "Name": "Joel",
      "Username": "",
      "Email address": "WhatsApp: +393517734452",
      "Location description": "6PM at Giardino pubblico \"La Montagnola\" Via Salvi Cristiani, 50135 Firenze FI, Italy https://maps.app.goo.gl/eX51qGzDcwHhyXuV6",
      "GPS Coordinates": "43.7761875,11.2938125",
      "Plus.Code Coordinates": "https://plus.codes/8FMHQ7GV+FG",
      "Date": "4/2/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RSVP with WhatsApp to +393517734452"
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Oregon",
      "Name": "Michael Bacarella",
      "Username": "",
      "Email address": "michael.bacarella@gmail.com",
      "Location description": "Beergarden.",
      "GPS Coordinates": "44.0535625,-123.1044219",
      "Plus.Code Coordinates": "https://plus.codes/84PR3V3W+C6G",
      "Date": "4/9/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/WmJpAbkR",
      "Notes": "Hosted by the ACX/EAs of Willamette Valley Meetup (see our Discord!)"
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Ontario",
      "Name": "Jeremy",
      "Username": "a_boring_centrist",
      "Email address": "alphabetadelta0@yahoo.com",
      "Location description": "78 Princess St, at Minotaur, they have tables and board games free to use. I'll have some kind of a small ACX MEETUP sign on the table and will wear a red shirt",
      "GPS Coordinates": "44.2311875,-76.48181249999999",
      "Plus.Code Coordinates": "https://plus.codes/87P56GJ9+F7",
      "Date": "4/6/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/zgGw5hpjds",
      "Notes": "RSVPs by emailing me or joining the discord strongly appreciated but not mandatory"
    },
    {
      "Region": "North America",
      "Country": "US",
      "City": "Oregon",
      "Name": "Kenan",
      "Username": "kenakofer",
      "Email address": "kbitikofer@gmail.com",
      "Location description": "Laughing Planet, 127 NW 2nd St, Corvallis, OR 97330. Table outside if it's nice, Table by the windows inside otherwise.",
      "GPS Coordinates": "44.5645125,-123.2594531",
      "Plus.Code Coordinates": "https://plus.codes/84PRHP7R+R63",
      "Date": "4/4/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://discord.gg/y7NFhYKYRP",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "France",
      "City": "Gironde, Nouvelle Aquitaine",
      "Name": "Michael",
      "Username": "vi21maobk9vp",
      "Email address": "acx-meetup-2025-04-12@weboroso.anonaddy.com",
      "Location description": "Initial meeting in the park «Square of Professor Jacques Lasserre», behind 164/166 cours de l'Argonne (Maison Internationale), tram B Bergonié, entries from rue Grateloup and rue Colette, far side from the cours de l'Argonne: https://www.openstreetmap.org/#map=19/44.824715/-0.576945 — I will have an A4 «ACX Meetup» sign. Google Maps / Plus.Codes draw the park weirdly, but within the actual park (which is small anyway).",
      "GPS Coordinates": "44.8246875,-0.5769375",
      "Plus.Code Coordinates": "https://plus.codes/8CPXRCFF+V6",
      "Date": "4/12/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "So that I know if anyone is coming, please mark «Yes» or «Maybe» at LW, or write me an email. I will try to make sure we are within the park / within the line of sight of the specified location for at least 15 minutes after the posted time. Email me your phone number if you want me to text you updates if/when we move from there (e.g. if you are not sure about being able to make it on time but are interested to join a bit later).\n\nI will try to have an option-to-wrap-up moment an hour after the beginning, and I will stay at least two hours if anyone else does (maybe longer too). \n\nIt will almost definitely be a small meetup, so whatever topic you are interested to discuss with other people reading ACX surely can be discussed!"
    },
    {
      "Region": "Europe",
      "Country": "Italy",
      "City": "N/A",
      "Name": "Carlo",
      "Username": "Carlo Martinucci",
      "Email address": "carlo.martinucci@gmail.com",
      "Location description": "Prato della Valle, Isola Memmia, south, then we'll move to a bar or something",
      "GPS Coordinates": "45.3983125,11.8765625",
      "Plus.Code Coordinates": "https://plus.codes/8FQH9VXG+8J",
      "Date": "5/11/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Quebec",
      "Name": "Jeremy",
      "Username": "",
      "Email address": "lordoftydes@gmail.com",
      "Location description": "Jeanne Mance Park, near the beach volley ball courts and Duluth avenue. I will have an ACX MEETUP sign.",
      "GPS Coordinates": "45.5140625,-73.5818125",
      "Plus.Code Coordinates": "https://plus.codes/87Q8GC79+J7",
      "Date": "5/10/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "LessWrong group: https://www.lesswrong.com/groups/3nnqSgGbF8x3mTcia ; Mailing list: http://eepurl.com/io5vZM ; Discord: https://discord.gg/K8gMNzqPVG ; Facebook group: https://www.facebook.com/groups/less.wrong.montreal/",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Switzerland",
      "City": "",
      "Name": "Daniel",
      "Username": "",
      "Email address": "dd14214@gmail.com",
      "Location description": "Grosse Schanze at the Albrecht Haller statue",
      "GPS Coordinates": "46.9502125,7.438828099999999",
      "Plus.Code Coordinates": "https://plus.codes/8FR9XC2Q+3GP",
      "Date": "4/16/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Switzerland",
      "City": "N/A",
      "Name": "Daniel",
      "Username": "",
      "Email address": "danielspottiswood@gmail.com",
      "Location description": "IM Broelberg 11H",
      "GPS Coordinates": "47.3148125,8.5461875",
      "Plus.Code Coordinates": "https://plus.codes/8FVC8G7W+WF",
      "Date": "4/6/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP if possible by sending me an email."
    },
    {
      "Region": "Europe",
      "Country": "Hungary",
      "City": "",
      "Name": "Tim",
      "Username": "Timothy Underwood",
      "Email address": "timunderwood9@gmail.com",
      "Location description": "Muzeum Kert, in the North East corner, ",
      "GPS Coordinates": "47.4919375,19.0633125",
      "Plus.Code Coordinates": "https://plus.codes/8FVXF3R7+Q8",
      "Date": "4/12/2025",
      "Time": "01:00 PM",
      "Event Link": "",
      "Group Link": "https://groups.google.com/g/rationality-budapest",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Washington",
      "Name": "Spencer",
      "Username": "Optimization Process",
      "Email address": "speeze.pearson@gmail.com",
      "Location description": "Armistice Coffee Roosevelt, in the covered outdoor back area. I'll have a sign saying \"Astral Codex Ten meetup.\"",
      "GPS Coordinates": "47.6778375,-122.3176094",
      "Plus.Code Coordinates": "https://plus.codes/84VVMMHJ+4XJ",
      "Date": "5/5/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "EA: https://www.meetup.com/seattle-effective-altruists Rationality: https://www.meetup.com/seattle-rationality/",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "",
      "Name": "Omar",
      "Username": "omark",
      "Email address": "info@rationality-freiburg.de",
      "Location description": "Haus des Engagements, Rehlingstraße 9, 79100 Freiburg",
      "GPS Coordinates": "47.9894125,7.8394844",
      "Plus.Code Coordinates": "https://plus.codes/8FV9XRQQ+QQ9",
      "Date": "4/11/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "https://www.rationality-freiburg.de",
      "Notes": "If possible, check the event on the website for some reading as preparation: https://www.rationality-freiburg.de/ If not, come anyway :-)"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "Bavaria",
      "Name": "M. Stautner",
      "Username": "",
      "Email address": "acx.organizer.munich@gmail.com",
      "Location description": "Müllerstraße 35, 80469 München; TeamWork Konferenzraum; walk past the courtyard to find the actual apartment building we'll be meeting in",
      "GPS Coordinates": "48.13068750000001,11.5693125",
      "Plus.Code Coordinates": "https://plus.codes/8FWH4HJ9+7P",
      "Date": "4/10/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/JekHeDBFokxLlmceXsYhLv",
      "Notes": "Bring snacks if you like"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "N/A",
      "Name": "Ameya Prabhu",
      "Username": "https://www.lesswrong.com/users/bayesian_kitten",
      "Email address": "ameya.pandurang.prabhu@gmail.com",
      "Location description": "Neckawa, Wöhrdstraße 25. I will be carrying a sign with ACX Meetup on it.",
      "GPS Coordinates": "48.5179375,9.0613125",
      "Plus.Code Coordinates": "https://plus.codes/8FWFG396+5G",
      "Date": "4/26/2025",
      "Time": "06:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP on LessWrong so I know how big a table to book"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "",
      "Name": "Simon",
      "Username": "",
      "Email address": "acxmannheim@mailbox.org",
      "Location description": "Good wheather: Rheinpromenade (Flagpole), bad weather: Murphy's Law Pub",
      "GPS Coordinates": "49.4784375,8.4615625",
      "Plus.Code Coordinates": "https://plus.codes/8FXCFFH6+9J",
      "Date": "5/10/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://signal.group/#CjQKIFmicB23eRhkDDjxjT94PWsbTYPdux-uoZJH2bH2M7OqEhBzfNMhsDNayw_ETHxhsGG6",
      "Notes": "Bring a blanket and snacks/drinks! Sign up via email or Signal so you are informed when we switch to the inside location."
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "Bavaria",
      "Name": "Dimi",
      "Username": "",
      "Email address": "dimi.zharkov@gmail.com",
      "Location description": "Spruz Kneipe",
      "GPS Coordinates": "49.5960625,11.0064375",
      "Plus.Code Coordinates": "https://plus.codes/8FXHH2W4+CH",
      "Date": "5/1/2025",
      "Time": "05:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/IQ6whwdbgt35FMKF44s4Y0",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Luxemburg ",
      "City": "",
      "Name": "RO",
      "Username": "lesswrong.com/users/roland-1",
      "Email address": "ACX@nixnuxnox.xyz",
      "Location description": "Café Konrad ",
      "GPS Coordinates": "49.6121875,6.132312499999999",
      "Plus.Code Coordinates": "https://plus.codes/8FX8J46J+VW",
      "Date": "4/5/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/luxembourg-discussions-meetup-group",
      "Notes": "Feel free to contact me before the meetup on the Meetup app or email address "
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Alberta",
      "Name": "Megh",
      "Username": "",
      "Email address": "meghss@proton.me",
      "Location description": "We will meet at the Bono Coffee Roasters, close to Murdoch park in Bridgeland.  I will have ACX meetup sign",
      "GPS Coordinates": "51.0531875,-114.0460625",
      "Plus.Code Coordinates": "https://plus.codes/95373X33+7H",
      "Date": "5/3/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/LZQ6HBAd8afoqPP27",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "N/A",
      "Name": "Dan Jones",
      "Username": "",
      "Email address": "danielrjones [d ot] uk [at] gmail [do t] com",
      "Location description": "Sydney Gardens, on the grass area to the south of the main path directly behind the Holburne Museum.",
      "GPS Coordinates": "51.38606249999999,-2.3495625",
      "Plus.Code Coordinates": "https://plus.codes/9C3V9MP2+C5",
      "Date": "4/12/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": "I'll be sitting on the grass with an ACX sign, unless it's raining in which case I'll shelter under trees nearby. Food/drinks/facilities available at the Holburne Museum, or from Roasted Lemon Cafe on the northwestern corner of the park. Please do email if you have any questions, if you live nearby but can't make it, or if you'd just like to get in touch in advance. Looking forward to meeting you!"
    },
    {
      "Region": "Europe",
      "Country": "UK",
      "City": "N/A",
      "Name": "Ben Woden",
      "Username": "Ben Woden",
      "Email address": "cascadestyler@gmail.com",
      "Location description": "Siren Craft Brew, 1 Friar's Walk, Reading RG1 1HP",
      "GPS Coordinates": "51.4568375,-0.9741719",
      "Plus.Code Coordinates": "https://plus.codes/9C3XF24G+P8P",
      "Date": "5/3/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "If you can RSVP by Apr 19th, that will help me book us a spot of the appropriate size, but please still feel free to come if you don't RSVP. The bar is child and dog friendly, and serves things besides beer if you fancy."
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "N/A",
      "Name": "Stan",
      "Username": "fenmund",
      "Email address": "stanislawmalinowski09@gmail.com",
      "Location description": "the Star Pub on Rectory Road",
      "GPS Coordinates": "51.7494375,-1.2383125",
      "Plus.Code Coordinates": "https://plus.codes/9C3WPQX6+QM",
      "Date": "5/21/2025",
      "Time": "06:30 PM",
      "Event Link": "",
      "Group Link": "https://www.facebook.com/groups/oxfordrationalish",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "The Netherlands",
      "City": "Utrecht",
      "Name": "Lodewijk van der Meer",
      "Username": "",
      "Email address": "lodevandermeer@gmail.com",
      "Location description": "Muntkelder Pannekoekenhuis - Oudegracht aan de Werf 112: I will be wearing a tiger vest jacket or a (if it's not too warm, lol)",
      "GPS Coordinates": "52.09306249999999,5.117062499999999",
      "Plus.Code Coordinates": "https://plus.codes/9F4734V8+6R",
      "Date": "4/27/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": "RSVPs not required, but preferred: please e-mail lodevandermeer@gmail.com"
    },
    {
      "Region": "Europe",
      "Country": "UK",
      "City": "N/A",
      "Name": "Hamish Todd",
      "Username": "https://www.lesswrong.com/users/hamishtodd1",
      "Email address": "hamish.todd1@gmail.com",
      "Location description": "Upstairs at The Bath House ",
      "GPS Coordinates": "52.2040625,0.1185625",
      "Plus.Code Coordinates": "https://plus.codes/9F426439+JC",
      "Date": "4/19/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Poland",
      "City": "N/A",
      "Name": "ntoxeg",
      "Username": "ntoxeg",
      "Email address": "ntoxeg@proton.me",
      "Location description": "Wilcza 25, Warsaw, Poland; Południk Zero, one of the rooms downstairs.",
      "GPS Coordinates": "52.2250625,21.0171875",
      "Plus.Code Coordinates": "https://plus.codes/9G4362G8+2V",
      "Date": "4/27/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/DcCpm5TaBY",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "the Netherlands",
      "City": "Noord-Holland",
      "Name": "Tom",
      "Username": "",
      "Email address": "hello@tomrijntjes.nl",
      "Location description": "Westerpark, across the street from IJscuypje.",
      "GPS Coordinates": "52.3865625,4.8720625",
      "Plus.Code Coordinates": "https://plus.codes/9F469VPC+JR",
      "Date": "5/11/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/JaJTu1HvwJJAVjPXc2vAIj",
      "Notes": "Hang around and eat ice cream. Pets are welcome."
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "N/A",
      "Name": "Askwho",
      "Username": "Askwho",
      "Email address": "askew.thomas@gmail.com",
      "Location description": "Upstairs at Tim Hortons, 112-113 New St, Birmingham B2 4EU. By the windows if possible, I'll have a piece of paper with \"ACX Meetup\" on it.",
      "GPS Coordinates": "52.4791875,-1.8995625",
      "Plus.Code Coordinates": "https://plus.codes/9C4WF4H2+M5",
      "Date": "4/12/2025",
      "Time": "01:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Venue very close to New Street Station "
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "Berlin",
      "Name": "Milli",
      "Username": "Milli | Martin",
      "Email address": "acx@martinmilbradt.de",
      "Location description": "Big lawn at the center of Humboldthain",
      "GPS Coordinates": "52.5451875,13.3855625",
      "Plus.Code Coordinates": "https://plus.codes/9F4MG9WP+36",
      "Date": "5/11/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "https://t.me/+2-6QId-rIOczNWIy",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "N/A",
      "Name": "Alex Patterson",
      "Username": "",
      "Email address": "alex_acx_mtup@proton.me",
      "Location description": "The upstairs mezz bar at Broadway Cinema. I will have a small sign which says \"ACX Meetup\".",
      "GPS Coordinates": "52.9543125,-1.1438125",
      "Plus.Code Coordinates": "https://plus.codes/9C4WXV34+PF",
      "Date": "4/12/2025",
      "Time": "12:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "While not required, please send me an email with the subject line \"ACX Meetup RSVP\" so I know how many people are coming."
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "N/A",
      "Name": "Marta",
      "Username": "https://www.lesswrong.com/users/marta_k",
      "Email address": "marta.krzeminska@gmail.com",
      "Location description": "Cafe Krach, Friesenstraße 16, 28203 Bremen Look for a sign \"ACX meetup\"",
      "GPS Coordinates": "53.0726875,8.8291875",
      "Plus.Code Coordinates": "https://plus.codes/9F5C3RFH+3M ",
      "Date": "4/27/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "This will be a meetup focused on meeting new people and introducing them to the Bremen rationality community. But, if you have a topic or reading you'd like to discuss, feel free to email me and we might get a chance to incorporate it."
    },
    {
      "Region": "Europe",
      "Country": "Netherlands ",
      "City": "Groningen",
      "Name": "Herman",
      "Username": "https://www.lesswrong.com/users/herman-van-der-veer",
      "Email address": "Hvdveer@gmail.com",
      "Location description": "Zondag, Noorderplantsoen, Groningen. ",
      "GPS Coordinates": "53.2246375,6.5555469",
      "Plus.Code Coordinates": "https://plus.codes/9F586HF4+V63",
      "Date": "5/13/2025",
      "Time": "05:30 PM",
      "Event Link": "",
      "Group Link": "https://facebook.com/groups/1078005920756368/",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Ireland",
      "City": "N/A",
      "Name": "David O",
      "Username": "",
      "Email address": "inlets_spinal_0a@icloud.com",
      "Location description": "Motel One, 111-114 Middle Abbey St, North City, Dublin, D01 H220",
      "GPS Coordinates": "53.3480625,-6.2635625",
      "Plus.Code Coordinates": "https://plus.codes/9C5M8PXP+6H",
      "Date": "4/11/2025",
      "Time": "07:00 PM",
      "Event Link": "",
      "Group Link": "hxxps://chat[dot]whatsapp[dot]com/Ecgu6De4a[ignore this]XkDhAk9FELKGr (Note: The link has been obfuscated due to spam.)",
      "Notes": " No RSVP required"
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "England",
      "Name": "BM",
      "Username": "",
      "Email address": "sgbmanso@liverpool.ac.uk",
      "Location description": "The Sphinx bar & grill, 160 Mount Pleasant, Liverpool L3 5TR Near the picnic tables right opposite the entrance. I will be wearing a green shirt and carrying a sign with ACX MEETUP written on it.",
      "GPS Coordinates": "53.4049375,-2.9664844",
      "Plus.Code Coordinates": "https://plus.codes/9C5VC23M+XCC",
      "Date": "5/3/2025",
      "Time": "11:00 AM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Alberta",
      "Name": "Joseph Shapkin",
      "Username": "Please don't make any LessWrong events or accounts.",
      "Email address": "ta1hynp09@relay.firefox.com",
      "Location description": "Irrational Brewing 10643 124 St #109. We will have an ACX sign",
      "GPS Coordinates": "53.5506875,-113.5355625",
      "Plus.Code Coordinates": "https://plus.codes/9558HF27+7Q",
      "Date": "4/17/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/hNzrLboTGkRFraHWG",
      "Notes": "https://www.lesswrong.com/events/XzzfeHmw9fsCbE3Ld/acx-spring-meetups-everywhere-2"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "N/A",
      "Name": "Gunnar Zarncje",
      "Username": "Gunnar_Zarncke",
      "Email address": "g[dot]zarncke[plus]acx[at]gma il[do t]c om",
      "Location description": "Eppendorfer Park at the pond, we will have a sign reading \"ACX Meetup\".",
      "GPS Coordinates": "53.58918749999999,9.9786875",
      "Plus.Code Coordinates": "https://plus.codes/9F5FHXQH+MF",
      "Date": "4/19/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "lesswrong-hamburg@googlegroups.com",
      "Notes": "Feel free to bring friends and family. "
    },
    {
      "Region": "Europe",
      "Country": "Lithuania",
      "City": "N/A",
      "Name": "Tom",
      "Username": "NoUsernameSelected",
      "Email address": "acx.vilnius@gmail.com",
      "Location description": "Lukiškių aikštė (Lukiškės square), Vilnius I'll be somewhere in the center with an ACX sign.",
      "GPS Coordinates": "54.6895625,25.2706875",
      "Plus.Code Coordinates": "https://plus.codes/9G67M7QC+R7",
      "Date": "4/12/2025",
      "Time": "04:00 PM",
      "Event Link": "",
      "Group Link": "https://discord.gg/MrBxnNBKbA",
      "Notes": "Anyone interested is welcome! We'll be gathering at the center of the square, then probably move on to a cafe or something nearby. RSVPs preferred, but not required."
    },
    {
      "Region": "Europe",
      "Country": "Denmark",
      "City": "N/A",
      "Name": "Søren Elverlin",
      "Username": "Søren Elverlin",
      "Email address": "soeren.elverlin@gmail.com",
      "Location description": "Rundholtsvej 10, 2300 Copenhagen S",
      "GPS Coordinates": "55.6538125,12.5660625",
      "Plus.Code Coordinates": "https://plus.codes/9F7JMH38+GC",
      "Date": "5/3/2025",
      "Time": "03:00 PM",
      "Event Link": "",
      "Group Link": "https://www.lesswrong.com/groups/KJeNBZdkHkJEugnWy",
      "Notes": "Please RSVP on LessWrong"
    },
    {
      "Region": "Europe",
      "Country": "United Kingdom",
      "City": "N/A",
      "Name": "Sam",
      "Username": "",
      "Email address": "acxedinburgh@gmail.com",
      "Location description": "Quad room, ground floor, Old College, University of Edinburgh (room G.158)",
      "GPS Coordinates": "55.9474375,-3.1873125",
      "Plus.Code Coordinates": "https://plus.codes/9C7RWRW7+X3",
      "Date": "5/10/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "Email acxedinburgh@gmail.com to join the mailing list and WhatsApp group.",
      "Notes": "After discussing ~3 essays by Scott per month for multiple years, our group has branched out into adjacent topics, and in May we will be discussing 'A Mathematical Theory of Communication' by Claude Shannon. You can see the list of everything we've read here: http://bit.ly/4hpnbhL. I know Scott is sceptical of \"assigning\" readings, but we have a great setup – often with special guests and 'field trips' around the city – and I encourage people to email and join the community. :)"
    },
    {
      "Region": "Europe",
      "Country": "Sweden",
      "City": "",
      "Name": "Stefan",
      "Username": "Stefan",
      "Email address": "acx_gbg@posteo.se",
      "Location description": "Condeco Fredsgatan, second floor, look for some books on the table",
      "GPS Coordinates": "57.70518749999999,11.9709375",
      "Plus.Code Coordinates": "https://plus.codes/9F9HPX4C+39",
      "Date": "4/30/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://www.meetup.com/lw-acx-meetup-gothenburg/events/306691088/",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Norway",
      "City": "N/A",
      "Name": "William",
      "Username": "williawa",
      "Email address": "william.wale@effektivaltruisme.no",
      "Location description": "Kvarteret, Olav Kyrres gate 49, 5015 Bergen",
      "GPS Coordinates": "60.38968749999999,5.3219375",
      "Plus.Code Coordinates": "https://plus.codes/9FG798QC+VQ",
      "Date": "5/5/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "NRW",
      "Name": "AM",
      "Username": "",
      "Email address": "acx-ms@gmx.net",
      "Location description": "A bar close to the main station, contact us for details.",
      "GPS Coordinates": "Invalid Plus Code",
      "Plus.Code Coordinates": "https://plus.codes/XJ4M+QX",
      "Date": "4/3/2025",
      "Time": "07:30 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please send us an email beforehand, because the planning is still somewhat provisional at the moment (and we would like to know what table size we should reserve, so as not to annoy the restaurant/bar owners)."
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Maryland",
      "Name": "Ferret",
      "Username": "",
      "Email address": "meetup2025.unseen534@passmail.net",
      "Location description": "Ask Organizer",
      "GPS Coordinates": "Invalid URL",
      "Plus.Code Coordinates": "Ask Organizer",
      "Date": "4/26/2025",
      "Time": "02:00 PM",
      "Event Link": "",
      "Group Link": "Ask Organizer",
      "Notes": "Event will be held on a government installation. Guests must be able to access the base on their own. Organizer will not sponsor attendees onto base. "
    },
    {
      "Region": "North America",
      "Country": "USA",
      "City": "Virginia",
      "Name": "Brandon Quintin",
      "Username": "",
      "Email address": "brandonmquintin@gmail.com",
      "Location description": "Location TBD. Send me an email and I’ll let you know where we end up! Most likely a local brewery.",
      "GPS Coordinates": "Invalid URL",
      "Plus.Code Coordinates": "N/A",
      "Date": "5/16/2025",
      "Time": "06:00 PM",
      "Event Link": "",
      "Group Link": "",
      "Notes": "We’re a small group (only four of us), but we meet reliably every other month at a local brewery or restaurant to hang out. Anyone else in the area who might be interested, please reach out and we’d be glad to include you!"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "Rhineland-Palatinate",
      "Name": "Lukas",
      "Username": "",
      "Email address": "lf_mail@posteo.de",
      "Location description": "„Baron“ on the Uni Mainz campus",
      "GPS Coordinates": "",
      "Plus.Code Coordinates": "https://plus.codes/8FXCX6VW+Q8",
      "Date": "4/26/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://chat.whatsapp.com/K6h4DsFG6YFECxhlfKXFIR",
      "Notes": "Please RSVP – thanks!"
    },
    {
      "Region": "North America",
      "Country": "usa",
      "City": "mn",
      "Name": "Aaron Kaufman",
      "Username": "ironlordbyron",
      "Email address": "ironlordbyron@gmail.com",
      "Location description": "Davanni's Pizza ; 41 Cleveland Ave S, St Paul, MN 55105",
      "GPS Coordinates": "",
      "Plus.Code Coordinates": "https://plus.codes/86P8WRQ6+XX",
      "Date": "4/13/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": "Please RSVP on lesswrong so i know how much food to get.  Also note that regrettably if you're a vegan davanni's has salad and little else (though i will be getting the salad)."
    },
    {
      "Region": "North America",
      "Country": "Canada",
      "City": "Ontario",
      "Name": "Jeremy",
      "Username": "a_boring_centrist",
      "Email address": "alphabetadelta0@protonmail.com",
      "Location description": "78 Princess St, Kingston, ON K7L 1A5 at Minotaur. They have free board games available to play, I'll be at a table in a red shirt with a small ACX 2025 sign.",
      "GPS Coordinates": "",
      "Plus.Code Coordinates": "https://plus.codes/87P56GJ9+F7",
      "Date": "4/6/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "https://discord.gg/zgGw5hpjds",
      "Notes": "Feel free to email me or join the Discord if you live in Kingston but don't intend to come to the schelling meet up!"
    },
    {
      "Region": "Europe",
      "Country": "Germany",
      "City": "Bavaria",
      "Name": "Nils",
      "Username": "",
      "Email address": "kunze.nils@gmail.com",
      "Location description": "On the Monopteros meadow in the Englischer Garten. When coming from Veterinärsstraße, right after crossing the Schwabinger Bach on the left hand side. I'll be easy to spot with dreadlocks and wearing a red hat. Also we'll have a sign with ACX Meetup on it :)",
      "GPS Coordinates": "",
      "Plus.Code Coordinates": "https://plus.codes/8FWH5H2Q+49",
      "Date": "5/17/2025",
      "Time": "",
      "Event Link": "",
      "Group Link": "",
      "Notes": ""
    }
  ]